### ISSUE TITLE
Your dataset is a tar file. How do I use it?

### ISSUE THREAD

**Issue by sarimmehdi** [waymo-research/waymo-open-dataset#101]
Hello. I downloaded your dataset but it is a tar file. How do I use it? Your tutorial also doesn't explain this.

**Comment by mathild7** [comment]
You should extract and see .tfrecord files.
https://www.tensorflow.org/tutorials/load_data/tfrecord
Follow their tutorial:
https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/v1.0.1/tutorial/tutorial.ipynb#scrollTo=mwZ4xcsHVO1V

**Comment by XiaoyanQian** [comment]
> https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/v1.0.1/tutorial/tutorial.ipynb#scrollTo=mwZ4xcsHVO1V

Hi sir, how to unzip the tar files, does the "ls *.tar.gz | xargs -n1 tar xzvf" work?
