### ISSUE TITLE
Sampling frequency of lidar dataset

### ISSUE THREAD

**Issue by ChaturvediShilpa** [waymo-research/waymo-open-dataset#102]
Hi, 

I want to know how to interpret the sampling frequency of lidar dataset. The paper mentions "Our dataset is organized into sequences, each 20 seconds long with multiple sensors producing data sampled at 10Hz. "

How does this translates to number of points per seconds and duration of data. Please help.

**Comment by peisun1115** [comment]
10 Hz = it takes the LiDAR 0.1 sec to scan 360 degree. All of our data is synchronized which means everything (all LiDARs, cameras) has pretty much the same data collection frequency.
