### ISSUE TITLE
How to download dataset using command line?

### ISSUE THREAD

**Issue by LehengLi** [waymo-research/waymo-open-dataset#109]
Hello, thanks for your great work! It's meaningful to self-driving car and computer vision community. I want to download dataset using our lab's remote computer which don't has graphical interface. And I try to use https://github.com/RalphMao/Waymo-Dataset-Tool . 
However, When it comes 
`gsutil cp gs://waymo_open_dataset_v_1_0_0/validation /validation_0000.tar ./ `
it outputs `ServiceException: 401 Anonymous caller does not have storage.objects.get access to waymo_open_dataset_v_1_0_0/validation/validation_0000.tar. `
It seems like I don't have permission to get data. Could you give me a hand? Thank you.

**Comment by peisun1115** [comment]
@LehengLi 

1. If you have registered in waymo.com/open, you should be able to get access to the buckets within 2 days. 
2. Then you need to install gsutil and login to your google cloud account with the same email you used to register in waymo.com/open.

Then this commandline should work

**Comment by LehengLi** [comment]
> @LehengLi
> 
> 1. If you have registered in waymo.com/open, you should be able to get access to the buckets within 2 days.
> 2. Then you need to install gsutil and login to your google cloud account with the same email you used to register in waymo.com/open.
> 
> Then this commandline should work

It works! Thanks for your quickly reply.

**Comment by peisun1115** [comment]
btw, you need to copy from v_1_2_0 directory. I have sent a PR to update the download code. https://github.com/RalphMao/Waymo-Dataset-Tool/pull/4

**Comment by RyanPham19092002** [comment]
Hi, I have registered in waymo.com/open and get access to the bucket like the image below
![image](https://github.com/user-attachments/assets/3166b89a-8dbb-4e83-9810-ffb52dace75d)
But why I can not download data and get ServiceException: 401 Anonymous caller does not have storage.objects.get access to waymo_open_dataset.
It seems like I don't have permission to get data. Could you give me a hand? Thank you.
