### ISSUE TITLE
Error in loading dataset_pb2

### ISSUE THREAD

**Issue by mahfuz195** [waymo-research/waymo-open-dataset#111]
While running the 'tutorial.ipynb' I got the following error:

---> 24 from waymo_open_dataset import dataset_pb2
     25 from waymo_open_dataset.utils import range_image_utils
     26 from waymo_open_dataset.utils import transform_utils

ImportError: cannot import name 'dataset_pb2'

The file/folder dataset_pb2 does not exist in the waymo_open_dataset folder.

I used git clone to clone the repository.

**Comment by peisun1115** [comment]
You can try the pre-compiled package. See quick start.

**Comment by mahfuz195** [comment]
Hi pensin1115, I am using Colab as the dataset is huge in size. and could not use find the dataset_pb2 file in the repo that I cloned.

**Comment by peisun1115** [comment]
https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md#use-pre-compiled-pippip3-packages

Or follow https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb

Or do something similar as [this](https://github.com/waymo-research/waymo-open-dataset/issues/35) (not officially supported)

**Comment by mahfuz195** [comment]
Using the pre-compiled package worked in solving this issue. However, I had to install tensorflow 2.1.0 in Colab, as Cobal using the default 2.2.0rc1 version currently. Appreciate your help.
