### ISSUE TITLE
Question about bin file generation with waymo competetion

### ISSUE THREAD

**Issue by LehengLi** [waymo-research/waymo-open-dataset#112]
Hello, I am prepare to join waymo competetion. 

However I can't figure out the submission file format. Reference to [this](https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md#submit-to-leaderboard)(Submit to leaderboard), there shoule be bin files generated. And you mention example_code_to_create_a_prediction_file, but I am not familiar with C++, what's the difference bin files and proto files? 

Are there any methods generate bin files using python(my model is written by python)? Finally, I appreciate the effort you've put in this competetion, I think it will contribute to computer vision community like kitti or outperform kitti.

**Comment by peisun1115** [comment]
1. The format are files (it can be multiple if want to shard them) that consist of serialized strings of this submission [proto](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/submission.proto).

2. There are two steps if you follow our process but you can do it on your own.
  s1: generate a file (or multiple) that contains serialized [Objects](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/metrics.proto#L59) proto by filling in fields mentioned in the example_code_to_create_a_prediction_file. It is simply populating fields in a protobuf. I can add a python version for it. I think you can easily figure it out if you read a bit about [proto](https://developers.google.com/protocol-buffers/docs/pythontutorial) here  
  s2: run create_submission

**Comment by LehengLi** [comment]
> 1. The format are files (it can be multiple if want to shard them) that consist of serialized strings of this submission [proto](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/submission.proto).
> 2. There are two steps if you follow our process but you can do it on your own.
>    s1: generate a file (or multiple) that contains serialized [Objects](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/metrics.proto#L59) proto by filling in fields mentioned in the example_code_to_create_a_prediction_file. It is simply populating fields in a protobuf. I can add a python version for it. I think you can easily figure it out if you read a bit about [proto](https://developers.google.com/protocol-buffers/docs/pythontutorial) here
>    s2: run create_submission

Thanks for your reply. However, what's the difference *.bin files and *.proto files? I have seen [fake_predictions.bin](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/fake_predictions.bin). Is this the serialized Objects proto?

**Comment by peisun1115** [comment]
'bin' is just a suffix we picked. it can be anything. We named it that way just because it is a file with binary string. Yes, it is a serialized Objects proto. You can read the file into a string and parse it.

**Comment by peisun1115** [comment]
https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/create_prediction_file_example.py

is a python version

**Comment by LehengLi** [comment]
I have read the python code. Now I understand it. Thanks for your help!
