### ISSUE TITLE
ERROR: Unrecognized option: --auto_output_filter=subpackages

### ISSUE THREAD

**Issue by jiangzhengkai** [waymo-research/waymo-open-dataset#113]
Hi, I meet this error when running `./configure.sh && cat .bazelrc && bazel clean`, any suggestion?

**Comment by peisun1115** [comment]
i've never seen this before. what is your bazel version? 

btw, to get started, you don't really need to build. you can just install the precompiled pip package. folllow our tutorial or quick start.

If you need to build locally (e.g. use camera projection lib or other cc tools), make sure you follow quick start to build.

**Comment by jiangzhengkai** [comment]
@peisun1115 Thanks, I have successfully install precompiled pip package.

**Comment by peisun1115** [comment]
FYI, someone else also encountered this error. The solution is to update your bazel to 0.28.0
