### ISSUE TITLE
How to generate the same kind of .tfrecord file as Waymo

### ISSUE THREAD

**Issue by fyj97** [waymo-research/waymo-open-dataset#114]
Hi, Waymo

I just want to know how to generate .tfrecord file using my own images. I generate images using the simulator,  and I have some code for dealing with the Waymo dataset. So I want to transfer the images to the .tfrecord file that the same as Waymo Dataset.

Thank you very much

**Comment by peisun1115** [comment]
You can follow this [tutorial](https://www.tensorflow.org/tutorials/load_data/tfrecord#writing_a_tfrecord_file_2) to write a tfrecord file.  The tutorial writes a tensorflow.Example proto. but Waymo Dataset writes an open_dataset.Frame proto. You only need to change the type and populate the open_dataset.Frame  instead

**Comment by fyj97** [comment]
Thanks a lot.  I will try to do that.

Pei Sun <notifications@github.com> 于 2020年3月29日周日 上午3:25写道：

**Comment by DocDriven** [comment]
@peisun1115 If I understand this correctly, you populate your Frame proto with the function called Frame.ParseFromString(). Can you provide the implementation of this function? Unfortunately, I am unable to locate it.

Thanks!

**Comment by peisun1115** [comment]
You can read more here. 

https://developers.google.com/protocol-buffers/docs/pythontutorial
