### ISSUE TITLE
num_lidar_points_in_box not populated

### ISSUE THREAD

**Issue by mathild7** [waymo-research/waymo-open-dataset#117]
Hi,
I found all of your 3d detection labels had a zero value for num_lidar_points_in_box. Is there a tool to grab this info? Why is this not populated? 

Thanks!

**Comment by peisun1115** [comment]
Try version 1.2 ? it was not populated in 1.0

**Comment by mathild7** [comment]
> Try version 1.2 ? it was not populated in 1.0

That would make sense. I'm in the middle of downloading and unpacking 1.2.. taking a full day :)

**Comment by peisun1115** [comment]
You can try to download from individual file buckets if you have enough machine. that would be very fast.

waymo_open_dataset_v_1_2_0_individual_files

**Comment by mathild7** [comment]
> You can try to download from individual file buckets if you have enough machine. that would be very fast.
> 
> waymo_open_dataset_v_1_2_0_individual_files

I can't seem to download via linux command util for this? (tried both gsutil and wget) how do you suggest downloading the entire directory?

**Comment by DapengFeng** [comment]
@peisun1115 I found that a few annotated 3d boxes that contain zero points in version 1.2. Should these boxes are added to evaluation?

**Comment by peisun1115** [comment]
No, boxes with zero points are not considered for detection. See our [website](https://waymo.com/open/challenges/3d-detection/) for rules.

**Comment by yinjunbo** [comment]
I'm using waymo-open-dataset-tf-1-15-0  v1.20, but I get `num_lidar_points_in_box=0`? I have also tried v1.0 and v1.3,  `num_lidar_points_in_box` is still 0.

**Comment by peisun1115** [comment]
It is expected to have a small percent of boxes to have zero points because the labels are labeled by looking at the whole sequence. If you found that all boxes have zero points, then it is either a bug in your code or you are using v1.0 data.

**Comment by yinjunbo** [comment]
Thanks a lot! I find the dataset is v1.0 version.
