### ISSUE TITLE
Question on the origin of global frame

### ISSUE THREAD

**Issue by arashk1990** [waymo-research/waymo-open-dataset#119]
Hi, In the description of the Global Frame in the [dataset's website](https://waymo.com/open/data/), it is stated that: 

> The origin of this frame is set to the vehicle position when the vehicle starts.

I was wondering if this implies that the origin of the global frame in each scene is the position of the SDC at the start of that scene, or is it a remote position not necessarily provided in the scenes?
Also, do the coordinates of the SDC represent the coordinates of the LiDar sensor? and if so, what is the distance from the LiDar sensor to the front of the SDC?

**Comment by peisun1115** [comment]
@arashk1990 
1. No, the origin is not the start of that scene. It is remote position that is not necessarily in the scenes. 

2. SDC is a box. I am not clear what you mean by "do the coordinates of the SDC represent the coordinates of the LiDar sensor".  We have defined vehicle frame and LiDAR sensor frame. The origin of vehicle frame is the center of the SDC's rear axle.  You can find out the position of the LiDAR in vehicle frame by looking at the LiDAR's extrinsic provided in the dataset.

**Comment by arashk1990** [comment]
Thanks @peisun1115 for your elaborate answer.
