### ISSUE TITLE
install waymo-open-dataset ?

### ISSUE THREAD

**Issue by yanan550** [waymo-research/waymo-open-dataset#122]
This packages is only for Linux system? I install it, but my computer always show "ERROR: Could not find a version that satisfies the requirement waymo-open-dataset (from versions: none)
ERROR: No matching distribution found for waymo-open-dataset" .  I download the packages to install , it's shown "ERROR: waymo_open_dataset_2_0_0-1.0.1-cp36-cp36m-manylinux2010_x86_64.whl is not a supported wheel on this platform" .  How do I solve it?

**Comment by peisun1115** [comment]
We only support linux.
 For non-linux system, there are 2 solutions

1. Use docker https://github.com/waymo-research/waymo-open-dataset/tree/master/pip_pkg_scripts

2. Just copy the tf scripts from the tutorial to extract data.  The community contributed this. You may find it useful.  https://github.com/gdlg/simple-waymo-open-dataset-reader

After the error you are seeing, looks like you are not following the latest quick starts. check r1.2 branch or the master branch. Make sure you update your pip as well.

**Comment by yanan550** [comment]
Thank you very much! it's very useful.
