### ISSUE TITLE
Is there any validation baseline for 2D object detection challenge?

### ISSUE THREAD

**Issue by huangzehao** [waymo-research/waymo-open-dataset#124]
Is there any validation baseline for 2D object detection challenge? 
I found results in the waymo dataset paper (Scalability in Perception for Autonomous Driving: Waymo Open Dataset):
`The resulting model achieved an AP of 68.4 at LEVEL 1
and 57.6 at LEVEL 2 on vehicles, and an AP of 55.8 at
LEVEL 1 and 52.7 at LEVEL 2 on pedestrians.`
They are validation set results or test set results?

**Comment by peisun1115** [comment]
This is on test set

**Comment by huangzehao** [comment]
Thanks!

**Comment by huangzehao** [comment]
@peisun1115 
Is there any validation baseline for 2D object detection challenge?

**Comment by peisun1115** [comment]
no. we do not provide a public baseline for that.  I think you can use the test set result as a reference.

**Comment by huangzehao** [comment]
Thanks!
