### ISSUE TITLE
How can I generate gt.bin for offline evaluation

### ISSUE THREAD

**Issue by zehuichen123** [waymo-research/waymo-open-dataset#126]
hi, it seems that waymo dataset doesn't provide gt.bin for offline evaluation using `compute_detection_metrics_main` tool. I was wondering what's the format of this gt.bin? I've generated a bin file named **valid_gt.bin** based on given validation dataset and kept the same format with the one in `create_prediction_file_example.py`. The differences are: (1) I didn't fill the field `o.object.id`, `box.center_z`, `box.height`, `box.heading` since I am focusing on 2D detection (2) I added `o.object.detection_difficulty_level` and `o.object.num_lidar_points_in_box` . However, when I run `compute_detection_metrics_main valid_gt.bin valid_gt.bin`, I didn't get a all 1 results (some of them are 0.88 or 0.97, but when i submit this to online leaderboard, I got a all 1 results). Besides, when I use this `valid_gt.bin` to evaluate my prediction, I can not get the same score with the one I submitted to online evaluation. Offline score is a little bit lower than the online(about 5% lower).

**Comment by peisun1115** [comment]
You may check this FAQ first
https://github.com/waymo-research/waymo-open-dataset/issues/121

Let me know if you still have questions.

**Comment by zehuichen123** [comment]
I can get a all 1 score when I submit this file `valid_gt.bin` file to leaderboard :) but can not get all 1 offline:<

**Comment by peisun1115** [comment]
how did you get these num_lidar_points_in_box? for 2d labels, we don't have that.

**Comment by zehuichen123** [comment]
I iterated frame.laser_label and frame.camera_label simultaneously by `zip(frame.laser_labels, frame.camera_labels)` and assigned the laser_labels.num_lidar_points_in_box to all bboxes in one frame. Indeed, it's wrong... So how can I can the right num_lidar_points_in_box for offline validation?

**Comment by peisun1115** [comment]
you don't need that for 2d.  the tool currently does not support 2d image metrics well.
 In order to run it, you need to do the following

1. Set num_lidar_points_in_box to be something larger than 5 for all labels.
2. change [this](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L97) to TYPE_2D_AA.

**Comment by zehuichen123** [comment]
I've aligned the score offline and online after following your steps. Thanks for your prompt reply! :)

**Comment by harish-kamath** [comment]
Could you share your bin? the ground truth in the bucket seem to only be for 3D data.

**Comment by dereyly** [comment]
I cant succefully local test 2D detection
In web I have good result with same submit

I rebuild /compute_detection_metrics_main
1. config.set_box_type(Label::Box::TYPE_AA_2D);
2. bazel build 
--
Input files:
1. metrics_pb2.Objects() 
1.1. session type that i upload in web is not comparable
2. gt.bin
--
gt.bin vs gt.bin is 1
--
maybe I need change gt.bin?

```
o = metrics_pb2.Object()
o.context_name = frame.context.name
o.frame_timestamp_micros = frame.timestamp_micros
o.camera_name = frame.images[z].name 
# Populating box and score.
box = label_pb2.Label.Box()
box.center_x = bb[0] + bb[2]/2
box.center_y = bb[1] + bb[3]/2
box.length=bb[2]
box.width=bb[3]
o.object.box.CopyFrom(box)
o.score = bb[4]
if int(bb[5]) not in map_cls:
        continue
cls=map_cls[int(bb[5])]
o.object.type = cls
o.object.num_lidar_points_in_box=100 #ToDO local eval
objects.objects.append(o)
```
