### ISSUE TITLE
Camera projection of second return

### ISSUE THREAD

**Issue by chreisinger** [waymo-research/waymo-open-dataset#127]
Hi, why does `convert_range_image_to_point_cloud` always return the camera projection points at index 0? 
See: https://github.com/waymo-research/waymo-open-dataset/blob/22700eebe8ee92e912c41fe0aa3f3d863f72e2e1/waymo_open_dataset/utils/frame_utils.py#L153

Wouldn't it make more sense to return the masked camera projection of the corresponding return?
i.e.: `cp = camera_projections[c.name][ri_index]` ?

Another question: What are the six (0-5) channels in `camera_projection_compressed`?
https://github.com/waymo-research/waymo-open-dataset/blob/22700eebe8ee92e912c41fe0aa3f3d863f72e2e1/waymo_open_dataset/dataset.proto#L200

The provided Colab notebook uses only x and y of the first projection. What is the second projection? 

Many thanks in advance!

**Comment by peisun1115** [comment]
yeah, you are right. i think it should be ri_index. 

  //   * channel 0: CameraName.Name of 1st projection. Set to UNKNOWN if no
  //       projection.
  //   * channel 1: x (axis along image width)
  //   * channel 2: y (axis along image height)
  //   * channel 3: CameraName.Name of 2nd projection. Set to UNKNOWN if no
  //       projection.
  //   * channel 4: x (axis along image width)
  //   * channel 5: y (axis along image height)

A point can be projected to multiple camera images as cameras' FOV have overlaps. 

You may also use the lib provided to do such projection on your own. 
https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/ops/py_camera_model_ops.py

**Comment by chreisinger** [comment]
Is there some tutorial or guide available describing how to build and import the third party camera package? 

I have implemented the box projection on my own with the help of your code in other issues and it works mostly as expected. However, the projection on the side cameras are a little bit off. 

An interesting observation: I projected 3d boxes containing at least one lidar point to the image, clipped them to 2d boxes and compared the results with the given projected 2d labels. It turns out that there are projected labels given when they contain at least one point in the image space, not in the 3d space. In my opinion that does not make much sense, because the points within theses labels does not always relate to them.

**Comment by peisun1115** [comment]
This test has an example.

https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/ops/camera_model_ops_test.py

**Comment by chreisinger** [comment]
I know how to use the python code. But how do I insert it in my project. Is there a way to include a specific path or folder. Or do I have to copy the python file and all needed binaries in a separate folder? 

Where do I find all the needed files?

**Comment by peisun1115** [comment]
It is pre-compiled in the pip package. 

from third_party.camera.ops import py_camera_model_ops

**Comment by chreisinger** [comment]
> It is pre-compiled in the pip package.
> 
> from third_party.camera.ops import py_camera_model_ops

Thank you! I didn't expect that...

**Comment by peisun1115** [comment]
Actually, i am not sure now. Let me know if it works. If not, we can update the pip package to add it.

You can also compile on your own to include it.

**Comment by chreisinger** [comment]
It is not included. I added it on my own to the package. What does `world_to_image` exactly expect? When I call it as in 
https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/ops/camera_model_ops_test.py
with the lidar points as an input, I get [0, 0, 0] for each point?!

**Comment by peisun1115** [comment]
They are in world frame (a.k.a. global frame).  See this [comment](https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/camera_model.h#L57-L74) .

So you need to first transform the points to world frame by using [pose](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L295).

Something like: 
vehicle_to_world = tf.reshape(tf.convert_to_tensor(pose.transform.data), [4, 4])
point = [x,y,z,1]
vehicle_point = tf.matmul(vechiel_to_world, point)[0:3]

**Comment by chreisinger** [comment]
Thank you for your help! Everything works out fine for me now. Please add the third_party camera projection to the python package and fix the _ri_index_ in `camera_projection_compressed`.

**Comment by peisun1115** [comment]
FYI, i've added the lib to package waymo-open-dataset-tf-2-2-0 but not for other tf versions yet.

**Comment by chreisinger** [comment]
> FYI, i've added the lib to package waymo-open-dataset-tf-2-2-0 but not for other tf versions yet.

Thank you! However, I made a few changes to meet my requirements. The toolchain for building and packing within the repo works like a charm.
