### ISSUE TITLE
Label is not accuray bounding box?

### ISSUE THREAD

**Issue by jiangzhengkai** [waymo-research/waymo-open-dataset#128]
Hi, I just visualize the predicitons and gt_labels, I found that label is not accurate?

1. some boxes without points?

2. some boxes heading errors?

![Screenshot from 2020-04-09 22-50-03](https://user-images.githubusercontent.com/19780166/78957938-accc6600-7ab4-11ea-9091-36a518c00db2.png)

**Comment by peisun1115** [comment]
I have helped people debugging something like these. Usually it is because of some errors either in parsing data or parsing box or viz the boxes. Maybe try this viz tool before spending too much time debugging it back and forth. https://github.com/erksch/waymo-open-dataset-viewer

**Comment by peisun1115** [comment]
Did it work for you?
