### ISSUE TITLE
how to extract mages from the download data with format ".tfrecord"

### ISSUE THREAD

**Issue by kinginsky** [waymo-research/waymo-open-dataset#13]
I have download the dataset, but the dataset is ".tfrecord", how to extract images? I cannot do it even with the tutorial.

Thanks for your help.

**Comment by Okkband** [comment]
https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/r1.0/tutorial/tutorial.ipynb#scrollTo=ne4-TpYLVCwi
This notebook would be helpful to you problems.

**Comment by kinginsky** [comment]
> https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/r1.0/tutorial/tutorial.ipynb#scrollTo=ne4-TpYLVCwi
> This notebook would be helpful to you problems.

thanks,
but the example used in this tutotutial is "frames", how can I get frames from the ".tfrecord" dataset. I think i can refer to the "dataset.proto" to get the frames data?

**Comment by Okkband** [comment]
> > https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/r1.0/tutorial/tutorial.ipynb#scrollTo=ne4-TpYLVCwi
> > This notebook would be helpful to you problems.
> 
> thanks,
> but the example used in this tutotutial is "frames", how can I get frames from the ".tfrecord" dataset. I think i can refer to the "dataset.proto" to get the frames data?

replace the "frames" with the *.tfrecord.  It is Ok

**Comment by kinginsky** [comment]
> > > https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/r1.0/tutorial/tutorial.ipynb#scrollTo=ne4-TpYLVCwi
> > > This notebook would be helpful to you problems.
> > 
> > 
> > thanks,
> > but the example used in this tutotutial is "frames", how can I get frames from the ".tfrecord" dataset. I think i can refer to the "dataset.proto" to get the frames data?
> 
> replace the "frames" with the *.tfrecord. It is Ok

thanks very much!

**Comment by Guanwh** [comment]
@kinginsky Hi，
I want to know if you had extracted all images from "*.tfrecord"? My work environment is always unsuccessful.

**Comment by peisun1115** [comment]
Guanwh@, what is the problem you are facing?

**Comment by Guanwh** [comment]
@peisun1115 My work environment (cuda8.0) can't match the version (tensorflow1.14), and more important thing is that I can't easily reconfigure the environment. So is there anyone who can provide   the 100 segments that contain 2D labels(the first three files under 'Training' and the first file under 'Validation') directly?

**Comment by peisun1115** [comment]
Ah, i see. You do not really need tensorflow 1.14.0 to read the data. 

All you need to do is to read the protobuf and get the image/labels you need

**Comment by Guanwh** [comment]
@peisun1115 Sorry, I don't quite understand how to read the protobuf and get the image/labels. Can you explain it in detail? Thank you very much.

**Comment by kinfeparty** [comment]
> > > > https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/r1.0/tutorial/tutorial.ipynb#scrollTo=ne4-TpYLVCwi
> > > > This notebook would be helpful to you problems.
> > > 
> > > 
> > > thanks,
> > > but the example used in this tutotutial is "frames", how can I get frames from the ".tfrecord" dataset. I think i can refer to the "dataset.proto" to get the frames data?
> > 
> > 
> > replace the "frames" with the *.tfrecord. It is Ok
> 
> thanks very much!

@lg-code-repo  Hello ,have you extracted all camera images in one tfrecord? I read one tfrecord and learn the tutorial but only get 5 pictures. Could you help me？

**Comment by peisun1115** [comment]
I don't actually understand the problems you encountered. 

You can download the tf records from our website or the google cloud bucket (someone should have sent an email to you after registeration) and read the images from the downloaded files by following the tutorials.  Maybe you can copy paste your code if you still have a problem reading the data.

**Comment by kinfeparty** [comment]
FILENAME = 'segment-1208303279778032257_1360_000_1380_000_with_camera_labels.tfrecord'
dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')
for data in dataset:
    frame = open_dataset.Frame()
    frame.ParseFromString(bytearray(data.numpy()))
    break


def image_show(data, name, layout, cmap=None):
  """Show an image."""
  print(name)
  # plt.subplot(*layout)
  a=tf.image.decode_jpeg(data)
  # cv2.imwrite("%s.jpg"%name,a)
  plt.imshow(a)
  plt.show()
  plt.title(name)
#   plt.grid(False)
#   plt.axis('off')

for index, image in enumerate(frame.images):
  image_show(image.image, open_dataset.CameraName.Name.Name(image.name),
             [3, 3, index+1])




I use the tutorial code and change it,the result is 5 images,is there anything wrong in my code?

**Comment by kinfeparty** [comment]
![2019-10-30 14-21-38屏幕截图](https://user-images.githubusercontent.com/35788879/67833784-99d66280-fb20-11e9-927c-8a4b4c87f311.png)
This is my code. I use and change the toturial code. Is there anything wrong with my code?

**Comment by peisun1115** [comment]
Remove the 'break' in the 'for data in dataset' loop to get all images from all records in the 'FILENAME'. Each file has multiple records.

**Comment by kinfeparty** [comment]
thanks for the fast reply!!

**Comment by Duck-sri** [comment]
> ![2019-10-30 14-21-38屏幕截图](https://user-images.githubusercontent.com/35788879/67833784-99d66280-fb20-11e9-927c-8a4b4c87f311.png)
> This is my code. I use and change the toturial code. Is there anything wrong with my code?

Can you tell me how did u get this segment-{something}-with_camera_labels.tfrecord file.
All i get is a bunch of tfrecord shards. I don't have enought space to hold all of those.

I want to create a bird's eye of the car and it's surrounding, if that matters.

**Comment by mashuk03** [comment]
> https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/r1.0/tutorial/tutorial.ipynb#scrollTo=ne4-TpYLVCwi This notebook would be helpful to you problems.

What is the correct version of Python and TensorFlow for this project? If anyone can suggest the right version of TensorFlow for python 3.6, 3.7, 0r 3.8, that would be a great help.
