### ISSUE TITLE
Dynamic vs Static Objects

### ISSUE THREAD

**Issue by os1a** [waymo-research/waymo-open-dataset#130]
Hi,

I am wondering if there is a possibility to differentiate between static and moving objects (especially for cars). For instance to know which of the cars are moving in the scene and which are parked along the road?

Can we use the metadata of the speed?

**Comment by peisun1115** [comment]
Yes, you can use the speed in metadata to determine whether it is static or not. but you won't have that information in test set. So you need to predict whether it is static.
