### ISSUE TITLE
frame no label zones for lidar

### ISSUE THREAD

**Issue by mathild7** [waymo-research/waymo-open-dataset#132]
Hi,
I have found that no label zones are either not filled, or contain rather large x/y values for each frame. Is this due to the per-frame no label zone being specifically for camera?

Is there a noticable improvement when using the NLZ's for lidar? It seemingly must be extracted from the point cloud/voxel grid instead which seems tedious

**Comment by peisun1115** [comment]
We have masked NLZ in range image. It is much easier to directly use that. 

https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L178 (1 = in a NLZ, -1 = not in a NLZ)

**Comment by mathild7** [comment]
Yeah i've seen that, but that actually seems more difficult to use than cuboids (to match KITTI). Regardless, are you able to share how much of an impact these NLZ's have on the final results?

**Comment by peisun1115** [comment]
Why is that hard to use? it is point masks. 

No, i do not have numbers to show the NLZ impact.  I did not do the ablation study on that.

**Comment by mathild7** [comment]
Because every ground truth box will now need to be matched to the point mask in some voxel grid form to find out if it should be removed or not. A cuboid would be easier, as you would just loop through the cuboid to see if any ground truth, proposal or prediction falls within it, or overlaps with it.

**Comment by mathild7** [comment]
Actually I had a follow up question, the 'num_lidar_points_in_bbox' term, does this also include points contained in the NLZ?

**Comment by peisun1115** [comment]
yes. it also contains points in NLZ. but we are not supposed to release ground truth boxes in NLZ. If you find any, let us know.

**Comment by mathild7** [comment]
Imo it would be easier to release all but add NLZ cuboids per frame, but for now this works.

I'm having trouble repeating your (BEV 0.71mAP L2) results with my net so i'm investigating possible reasons as to why, NLZ/Dont care areas has shown to cause relatively drastic performance differences before.

**Comment by peisun1115** [comment]
I simply masked all points in NLZ.

**Comment by VishalBalaji321** [comment]
Does the mAP results mentioned in "Scalability in Perception for Autonomous Driving: Waymo Open Dataset" paper also include NLZ? Or are the zones being removed during training?
