### ISSUE TITLE
2d labels: Some mis classified images

### ISSUE THREAD

**Issue by mathild7** [waymo-research/waymo-open-dataset#135]
Hi,

There seem to be some inconsistencies with the labels categorized as vehicle, i realize they fall under 'construction' but these should really be under construction SIGNS:
(White boxes are ground truth)
![img-0000145](https://user-images.githubusercontent.com/10726578/79464592-41105e80-7fc8-11ea-9b7f-2471a97d757b.png)
![img-0139165](https://user-images.githubusercontent.com/10726578/79465532-749fb880-7fc9-11ea-81b4-467ea868d27b.png)
(this is only on a subset of the v1.2 data)

There are also a few missing annotations, but that is expected.

**Comment by henrikkretzschmar** [comment]
Thanks for bringing this up!

Our specification defines those wheeled objects as construction vehicles, which is why they belong to the vehicle category.

Hope this helps.

Thanks,
Henrik
