### ISSUE TITLE
Questions about velocities of objects with respect to world frame?

### ISSUE THREAD

**Issue by droneRL2020** [waymo-research/waymo-open-dataset#137]
I calculated an instance's position_w.r.t_world by eq1.
eq1) T_vehicle_to_world.dot(position_w.r.t_vehicle)

And then I calculated the insntance's speed_x by eq2.
eq2) position_w.r.t_world_current_timestamp - position.w.r.t_world_prev_timestamp

And got result of
first_timestamp velocity: 
[[-0.13085334]
 [ 0.73677419]
 [ 0.01428538]
 [ 0.        ]]
second_timestamp velocity: 
[[-0.15538238]
 [ 0.85073076]
 [ 0.01428552]
 [ 0.        ]]

However, it is different from ( speed_x: -1.3777278030209672, speed_y: 7.685341385276843).
Do I have to consider the frequency of the data? 
Is the unit of speed_x the meter/second? 

**[Data I used]**
Time=1557844368322203 
T_vehicle_to_world = [-0.16717355790707938, -0.9859083232235732, -0.006146522201263641, -1565.8830925928753, 0.9858751067922654, -0.16709716892163046, -0.011349446934339912, 14561.819790719877, 0.010162447738004884, -0.00795703065586302, 0.9999167016902528, -7.871, 0.0, 0.0, 0.0, 1.0]
 "AE5mG59C1GJKWSHeZyrOug" position_w.r.t_vehicle =
  center_x: 53.78694672543497
  center_y: -3.643660774025193
  center_z: 0.9277558932018621
"AE5mG59C1GJKWSHeZyrOug" speed_w.r.t_world =
  speed_x: -1.3777278030209672
  speed_y: 7.685341385276843

Time=1557844368422222 
T_vehicle_to_world=[-0.16566021794510555, -0.9861652682052111, -0.005895419927720443, -1565.9691746138212, 0.9861254709568985, -0.16558310457768893, -0.01178095957252181, 14562.314623804834, 0.010641791222129595, -0.007765260083098446, 0.999913222742567, -7.8660000000000005, 0.0, 0.0, 0.0, 1.0]
"AE5mG59C1GJKWSHeZyrOug" position_w.r.t_vehicle =
  center_x: 54.03901332994792
  center_y: -3.5567727069266084
  center_z: 0.9099515520249781
"AE5mG59C1GJKWSHeZyrOug" speed_w.r.t_world =
  speed_x: -1.4323091870295102
  speed_y: 7.969927543193478

Time= 1557844368522243 
T_vehicle_to_world=[-0.16395667470564168, -0.9864579246835236, -0.0043556455944132695, -1566.0504889263248, 0.9864004526302081, -0.16389243192585057, -0.012386194264220354, 14562.806490573857, 0.011504602139534265, -0.006327210009645682, 0.9999138015564666, -7.863, 0.0, 0.0, 0.0, 1.0]
"AE5mG59C1GJKWSHeZyrOug" position_w.r.t_vehicle =
  center_x: 54.41210418704031
  center_y: -3.4477518188442673
  center_z: 0.8761205316188523
"AE5mG59C1GJKWSHeZyrOug" speed_w.r.t_world =
  speed_x: -1.48900298167149
  speed_y: 8.256126532058943

**Comment by peisun1115** [comment]
@droneRL2020 

What you are doing looks correct to me.

To confirm, 

Time := https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L293

T_vehicle_to_world := https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L295

How did you calculate velocity?  It should be something like:

(pos2 - pos1) / (t2 - t1)

**Comment by droneRL2020** [comment]
Oh, timestamp_micros meaning timestamp in microseconds. Yes, that's exactly how I calculated. Thanks for the confirmation.

**Comment by peisun1115** [comment]
nice. btw, if you want it to be more accurate, probably assume something like constant acceleration and fit the positions into the model.
