### ISSUE TITLE
imshow image

### ISSUE THREAD

**Issue by yanan550** [waymo-research/waymo-open-dataset#138]
1. Why is there something wrong with the color of the image?  My System is CPU, I open dataset by using simple-waymo-open-dataset-Reader. Image are as follows:
![image](https://user-images.githubusercontent.com/63165271/79735610-d5483180-82f8-11ea-9c31-35687fca0b61.png)

2. Are the faces of pedestrians all blurred out in the dataset?

**Comment by peisun1115** [comment]
For 1, you can try our colab to see whether the color is expected. I do not know how it is rendered in your machine.

For 2, yes, peds' faces are blurred.

**Comment by yanan550** [comment]
OK, Thank you very much.
