### ISSUE TITLE
Difficulty Level Not Populated (v1.2.0)

### ISSUE THREAD

**Issue by mathild7** [waymo-research/waymo-open-dataset#140]
Hi,
I noticed that for some LiDAR and Image labels, the difficulty level is not populated. For LiDAR this is easy to remedy using the Waymo rules (below 5 pts contained is level 2 and above is level 1 if not populated)

For Image based labels, i'm assuming these rules do not apply, so how should they be sorted?

Thanks!

**Comment by peisun1115** [comment]
The difficulty level is pre-populated **only** for objects labeled as difficult by human labelers. The final difficulty is computed [this way](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L127-L133). This has been documented in our [website](https://waymo.com/open/challenges/3d-detection/) as well.

**Comment by mathild7** [comment]
> The difficulty level is pre-populated **only** for objects labeled as difficult by human labelers. The final difficulty is computed [this way](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L127-L133). This has been documented in our [website](https://waymo.com/open/challenges/3d-detection/) as well.

This solution still doesn't make sense for image 2d labels, as it talks about number of points within the bounding box?

**Comment by peisun1115** [comment]
For image 2D, only human labeled difficulty is used. I will update the code. See https://github.com/waymo-research/waymo-open-dataset/issues/126

**Comment by mathild7** [comment]
Ok so how I understand it, if difficulty is unknown (0) for 2d labels, it
is actually a 1.

**Comment by peisun1115** [comment]
yeah. This leaves us room to modify the difficulty if we want to add anything that is data dependent (e.g. box size). We prefer to populate raw information in the data.

**Comment by mathild7** [comment]
That makes sense, I just had not seen it discussed before. Thanks!
