### ISSUE TITLE
projected_lidar_labels AND camera_labels

### ISSUE THREAD

**Issue by taofuyu** [waymo-research/waymo-open-dataset#141]
How to align object in projected_lidar_labels and camera_labels? The same object has defferent id in projected_lidar_labels and camera_labels, respectively.

**Comment by peisun1115** [comment]
We do not have a way to align them. They are labeled separately. It is an interesting problem to solve to align them by itself.  The easiest way would be to use IoU overlap to align. A more fancy way is to train a net to align them.

**Comment by henrikkretzschmar** [comment]
We experimented with a simple IoU-based association and obtained reasonable results. Note, though, that we didn't conduct a thorough analysis of this approach.

**Comment by mathild7** [comment]
> We experimented with a simple IoU-based association and obtained reasonable results. Note, though, that we didn't conduct a thorough analysis of this approach.

I'm looking at doing detection matching via Hungarian IoU overlap as a part of my research. Are you able to share more information about detection matching? Did you do it in the image plane?

**Comment by henrikkretzschmar** [comment]
@mathild7, in this particular experiment, we associated the projected lidar labels with the camera labels based on IoU in the image plane. As @peisun1115 pointed out, a more fancy way would be to use a neural net to associate the 3D bounding boxes with the 2D bounding boxes. This could be an interesting research challenge.

**Comment by peisun1115** [comment]
@mathild7 One thing that is worth pointing out is that the camera and LiDAR range and FOV are different.  So the objects labeled in these 2 sensors are not necessarily the same.

**Comment by mathild7** [comment]
> @mathild7 One thing that is worth pointing out is that the camera and LiDAR range and FOV are different. So the objects labeled in these 2 sensors are not necessarily the same.

Understood, I think this can be resolved by transforming all GT into the image plane and removing any beyond the acceptable pixel range, no?

**Comment by henrikkretzschmar** [comment]
In addition to that, you would need to take into account that LiDAR has limited range, which means that you may see an object in the camera image that you cannot see in the LiDAR data as it is too far away.

**Comment by taofuyu** [comment]
@henrikkretzschmar  @peisun1115  Thanks for your reply !
