### ISSUE TITLE
How to get detection boxes from detection_3d_vehicle_detection_train.bin?

### ISSUE THREAD

**Issue by droneRL2020** [waymo-research/waymo-open-dataset#142]
Hi, I'm doing 3D tracking and I wanted to get prediction_boxes form this file
 detection_3d_vehicle_detection_train.bin

How can I get position and orientation, size of the boxes from the file?

**Comment by peisun1115** [comment]
It is the same format as our [submission proto](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/submission.proto). 

You can read it with:

f = open("you_file_path")
proto_str = f.read()
submission_proto = waymo_open_dataset.Submission()
CHECK(submission_proto.ParseFromString(proto_str))
# Then find boxes in submission_proto

**Comment by droneRL2020** [comment]
I quickly followed the snippet. It said waymo_open_dataset doesn't have Submission attribute. Do I have to use create_prediction_file_example.py ??? If not, can you please explain bit more?

**Comment by peisun1115** [comment]
it is waymo_open_dataset.protos.Submission.

**Comment by droneRL2020** [comment]
I get the 959522292 output.
submission_proto.ParseFromString(proto_str)
print(submission_proto) 
#959522292

However,  if I print inference_results I get empty list. I didn't understand what the pretrained object detection binary file exactly does. Do I have to import each frame(dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')
) and then run the code you mentioned not to get empty array?

**Comment by peisun1115** [comment]
@droneRL2020 I am sorry. It is actually of proto [waymo_open_dataset.protos.Objects](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/metrics.proto#L59). 

I've just tried it on my own and it worked.

**Comment by Nuri-benbarka** [comment]
> it is waymo_open_dataset.protos.Submission.

@peisun1115 I am also trying to get the detections, and I ran the code you wrote above but in every case, it tells me:
AttributeError: module 'waymo_open_dataset.protos' has no attribute 'Objects'
AttributeError: module 'waymo_open_dataset.protos' has no attribute 'Submission'
what did I do wrong?

**Comment by bilalsattar** [comment]
Here is a code snippet to read boxes and other attributes

```
f = open('detection_3d_vehicle_detection_validation.bin', 'rb')
  objects.ParseFromString(f.read())
  f.close()

  for object in objects.objects:
    type = __type_list[object.object.type]
    height = object.object.box.height
    width = object.object.box.width
    length = object.object.box.length
    score = object.score
    x = object.object.box.center_x
    y = object.object.box.center_y
    z = object.object.box.center_z
    rotation_y = object.object.box.heading
    beta = math.atan2(x, z)
    alpha = (rotation_y + beta - math.pi / 2) % (2 * math.pi)
```

**Comment by Nuri-benbarka** [comment]
> > it is waymo_open_dataset.protos.Submission.
> 
> @peisun1115 I am also trying to get the detections, and I ran the code you wrote above but in every case, it tells me:
> AttributeError: module 'waymo_open_dataset.protos' has no attribute 'Objects'
> AttributeError: module 'waymo_open_dataset.protos' has no attribute 'Submission'
> what did I do wrong?

to solve my problem, I saw issue  [#35](https://github.com/waymo-research/waymo-open-dataset/issues/35) then I ran the following commands:
protoc ./waymo_open_dataset/protos/metrics.proto --python_out=.
protoc ./waymo_open_dataset/protos/breakdown.proto --python_out=.
protoc ./waymo_open_dataset/protos/submission.proto --python_out=.

then I tried the code provided by @bilalsattar and it worked.

**Comment by jiangzhengkai** [comment]
@peisun1115 @bilalsattar I notice that heading you provide is not the yaw which rotate x axis? Why heading is around y axis?

**Comment by jiangzhengkai** [comment]
@bilalsattar What's your meaning for rotation_y?

**Comment by bilalsattar** [comment]
Actually its rotation along z-axis not along the y-axis (I have changed it). This the heading direction of the vehicle or how much the bounding box is rotated along z.

**Comment by bilalsattar** [comment]
@peisun1115 can we call it yaw of the box?

**Comment by peisun1115** [comment]
yes, it is yaw.

**Comment by droneRL2020** [comment]
Thank you all and also the code snippets work well. Another question is, is there any sign labelled detection data?
