### ISSUE TITLE
Metrics (size of 0) and breadown (size of 32) does not match.

### ISSUE THREAD

**Issue by jiangzhengkai** [waymo-research/waymo-open-dataset#147]
Hi, I just download the predictions you provide, and run:

./bazel-bin/waymo_open_dataset/metrics/tools/compute_detection_metrics_main --input_filenames /media/users/zhengkai/code/waymo-challenge/detection_3d_vehicle_detection_validation.bin --out_filenames /media/users/zhengkai/code/waymo-challenge/model --submission_filename="waymo_open_dataset/metrics/tools/submission.txtpb"

There is output:
0 examples found.
Metrics (size of 0) and breadown (size of 32) does not match.

**Comment by peisun1115** [comment]
err, you are using the wrong command. if you want to create submission, use [this](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/create_submission.cc)

**Comment by jiangzhengkai** [comment]
Ok
