### ISSUE TITLE
No information after submitting the results you provide?

### ISSUE THREAD

**Issue by jiangzhengkai** [waymo-research/waymo-open-dataset#148]
Hi, Pei:
I just submit the results you provide, however, no information output? any help?
![image](https://user-images.githubusercontent.com/19780166/80380203-d0274b80-88d1-11ea-82fb-bd7fd76775b5.png)

**Comment by peisun1115** [comment]
Can you make sure you have passed --[submission_filename](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/create_submission.cc#L52) and make sure it exists?

If you pull the latest code, it will fail if you don't pass one.

**Comment by jiangzhengkai** [comment]
@pei I just summit .bin to the server, because there is the error when using create_submit command.
Thanks for your quick response!

**Comment by peisun1115** [comment]
@jiangzhengkai Did you solve the error? I am not sure I understand what you meant in your last response.

**Comment by jiangzhengkai** [comment]
@peisun1115  Solved, Thanks!
