### ISSUE TITLE
Projecting a point/box from Vehicle to Image

### ISSUE THREAD

**Issue by bilalsattar** [waymo-research/waymo-open-dataset#149]
I have seen a lot of filed issues with projecting points/ 3d box labels from vehicle frame to image. None of them had a clear solution for the problems with precise localization from 3d to 2d. 

Can you please publish some official code to make these projections easier?

**Comment by peisun1115** [comment]
see https://github.com/waymo-research/waymo-open-dataset/issues/146#issuecomment-620443276

I think that example is good enough.
