### ISSUE TITLE
AP gap between local evaluation and online server?

### ISSUE THREAD

**Issue by jiangzhengkai** [waymo-research/waymo-open-dataset#151]
Hi, I evaluate vehicle bin file on validation set locally by using python API (sets overlap with nlzs zero), get 52.21%; while the online server gets 60.24%; Why such a big gap? Any suggestion?

**Comment by peisun1115** [comment]
Maybe read https://github.com/waymo-research/waymo-open-dataset/issues/121?

A couple of causes:
1. You did not prepare the ground truth correctly (i.e. did not filter boxes without points).
2. You did not compute the difficulty level correctly

**Comment by jiangzhengkai** [comment]
@peisun1115 Yes, I just forget to filter zeros points box, after filter zeros point boxes, I get 63%. It seems higher than the online server.

**Comment by peisun1115** [comment]
@jiangzhengkai It is likely because of inaccurate difficulty computation. Follow [this](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L121-L136).
