### ISSUE TITLE
Missing data for some timestamps?

### ISSUE THREAD

**Issue by fregu856** [waymo-research/waymo-open-dataset#158]
Hi,

I downloaded both `waymo_open_dataset_v_1_2_0/validation/validation_0000.tar - validation_0007.tar` and `waymo_open_dataset_v_1_2_0_detection_output/detection_3d/vehicle_detection_validation.bin`.

When iterating through all the detections, 
```
from waymo_open_dataset.protos import metrics_pb2

detected_objects = metrics_pb2.Objects()
with open(waymoopen_path + "/baseline_3ddetections/vehicle_detection_validation.bin", "rb") as file:
    detected_objects.ParseFromString(file.read())

for detected_object in detected_objects.objects:
    print (detected_object.frame_timestamp_micros)
```
I discovered that `detected_object.frame_timestamp_micros` can sometimes NOT be found when iterating through the data frames in the .tfrecord file for the corresponding sequence. This is only the case for a handful of the 202 validation sequences.

In fact, when iterating through the data frames for these sequences, there seems to be some missing frames, as the difference in `timestamp_micros` between consecutive frames sometimes is (roughly) equal to 200000 instead of 100000 (as expected for 10Hz sampling). 

For example, I get the following output when iterating through segment-11037651371539287009_77_670_97_670_with_camera_labels.tfrecord:
```
100002
100001
99972
99963
99965
99964
99994
99971
99966
99998
99992
100007
100042
99997
100037
100033
100075
100072
100063
100100
100114
100113
100146
100178
100183
100181
100142
100187
100181
100149
100144
100182
100145
100149
100194
100149
100153
100152
100143
100113
100072
100070
100067
100034
100031
100068
100068
100042
100004
100037
100039
100002
100031
100029
100037
100036
100036
100101
100074
100145
100103
100109
100074
100113
100155
100155
100185
100147
100147
100143
100134
100067
100076
99995
100042
99994
100038
99998
99999
99962
99994
99963
100034
99997
99997
100066
100035
100035
100041
100066
100107
100108
100145
100180
100214
100265
100259
100331
100335
200734 NOTE!
200887 NOTE!
100473
100479
100513
100584
100591
100593
100632
201343 NOTE!
100707
100663
100701
100699
100666
100666
100621
100629
100627
100564
100558
100559
100559
100484
100519
100480
100440
100403
100368
100367
100290
100255
100260
100264
100224
100220
100183
100186
100144
100108
100074
100075
100038
100002
99966
99963
99955
100000
99958
99925
99961
99965
99967
199926 NOTE!
99958
99965
99961
99960
100040
100032
100036
99999
99998
100000
99958
99967
99962
99966
99997
199928 NOTE!
199998 NOTE!
99997
99993
100003
100034
200071 NOTE!
100039
100034
100029
100026
100032
100003
100029
100002
99996
99959
99920
99924
99856
99925
99883
```
The number of frames in this sequence is also just 191.

**Comment by peisun1115** [comment]
1. detected frames are performed on v1.0 data that is unfortunate. There are some minor differences between v1.0 and v1.2. You can just take the intersection of these 2 when consuming the detection outputs. Apologies for the inconvenience. We will fix that in the future versions.

2. There can be missing frames (i.e. became 5 Hz). That should not happen often.  This is expected to happen. It happens because we drop some frames when its data don't meet our bars to release for some reason.

**Comment by fregu856** [comment]
Ok, thanks!
