### ISSUE TITLE
Validation result of all 0's [2D Detection]

### ISSUE THREAD

**Issue by harish-kamath** [waymo-research/waymo-open-dataset#160]
We have finished running our model on validation. However, when submitting to the server, it is giving us a result of all 0's on every metric. We believe this is because we are not pointing to the correct images for our labels (the metadata of the submission).

For the context name of a frame, we are using frame.context.name.
For the timestamp micro, we are using frame.timestamp_micro.
For the camera name, we are using frame.camera_labels[_].name.

We are adding to a big list for each annotation, an Object with the metadata above as well as the bounding box, score, and label. However it seems that the validation server does not determine which frame and which image each annotation is meant for. Any idea?

**Comment by peisun1115** [comment]
@harish-kamath Can you send me a link to your all-zero result so that i can take a look?

**Comment by AmanKishore** [comment]
@peisun1115 Here's the link to the all-zero result: https://waymo.com/open/challenges/entry/?timestamp=1589341847105988&challenge=DETECTION_2D&email=amankishore105@gmail.com&submissionType=VALIDATION

**Comment by AmanKishore** [comment]
@peisun1115 here is the link to the all-zero result: https://waymo.com/open/challenges/entry/?timestamp=1589341847105988&challenge=DETECTION_2D&email=amankishore105@gmail.com&submissionType=VALIDATION

**Comment by peisun1115** [comment]
@AmanKishore 

For the submission you linked, the problem is that you did not populate the box correctly.

An example of your prediction:
`
      object: { # (car.open_dataset.Label) size=94B
        box: {  # (car.open_dataset.Label.Box) size=63B
          center_x: 41.717737197875977
          center_y: 406.08004760742188
          center_z: 0.0
          width   : 15.324283599853516
          length  : 1e-06
          height  : 25.26446533203125
          heading : 0.0
        }       # inference_results.objects[0].object.box
        type    : TYPE_PEDESTRIAN       # integer=2 (enum car.open_dataset.Label.Type)
        id      : "unique object tracking ID"   # size=25
      } # inference_results.objects[0].object
`

We expect a box to be defined with
center_x
center_y
length (along x in image frame)
width  (along y in image frame)

Image frame is defined as (see section 3.2 https://arxiv.org/pdf/1912.04838.pdf)
image width: x
image height: y

**Comment by harish-kamath** [comment]
Thank you for the quick response! We have changed it so that the box populates the length and width fields instead, but are still receiving the same problem. Here is the new submission: https://waymo.com/open/challenges/entry/?timestamp=1589389459938452&challenge=DETECTION_2D&email=harish.k.kamath@gmail.com&submissionType=VALIDATION

**Comment by peisun1115** [comment]
I took a look and it looks correct to me. It shows that it has a lot of false positives.   Probably something is wrong in your predictions? 

      measurements: {   # (car.open_dataset.DetectionMeasurement) 
        num_fps     : 799597    
        num_tps     : 3
        num_fns     : 1539065    
        score_cutoff: 0.01
      } # detection_metrics[0].measurements.measurements[1]

**Comment by harish-kamath** [comment]
Thank you! We will check on this. Do you mind lettig us know how you are reading the submission files and results, so we can do so locally?

**Comment by peisun1115** [comment]
You can read the submission as follows:


`
f = open('untar-ed submission file name')
submission = protos.Submission()
if submission.ParseFromString(f.read()):
    print(submission)
else:
    check fail
`

**Comment by harish-kamath** [comment]
@peisun1115 can you tell us given a frame object in python, the code to get the context name (currently frame.context.name), timestamp micros (currently frame.timestamp_micros), and camera name (currently frame.camera_labels[0].name)? Are these the correct fields to supply when we are creating our predictions.bin file (note: as of right now, we are only predicting for the front camera images hence frame.camera_labels[0].name, but don't think this is the reason for all 0 scores)?

**Comment by peisun1115** [comment]
camera name should be set to frame.images[idx].name instead of frame.camera_labels[0].name? 

Do not assume them to be sorted.

**Comment by harish-kamath** [comment]
Hello! So we found the problem. The bounding boxes we are returning are in relation to only the image frame (a bounding box is the center x,y,w,h pixels in the 1080x720 images given), but observing the ground truth validation, we see that their center x,y,w,h are actually 3d coordinates (based on their magnitude being much smaller and also negative values). How can we convert our 2D pixel coordinates into this format?

**Comment by peisun1115** [comment]
no, our ground truth is in image frame. See this field https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L309

You can visualize your prediction and this ground truth to see whether your predictions make sense. If yes, maybe you can send me an example with ground truth, your prediction, image name, file name, timestamp. i can help you to take another look if your viz looks reasonable but submission still gives 0

**Comment by harish-kamath** [comment]
Just to verify, the validation ground truth we are using is here: https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_2_0/validation/ground_truth_objects/

When we run the submission script on this file with a submission.txtpb specifying the task of 2D Detection, and then observe the resulting files with proto.Submission(), we see the center_x, center_y, length and width fields populated with 3D point data. Is that the correct file we should be using?

**Comment by peisun1115** [comment]
No, that is for 3d. I added that just to illustrate this [issue](https://github.com/waymo-research/waymo-open-dataset/issues/121). You can generate on your own for 2d images. It is simply a collections of all labels in [camera_labels](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L309).

Note that we use the same proto for 2d and 3d.  See my [comment](https://github.com/waymo-research/waymo-open-dataset/issues/160#issuecomment-628113712) above. For 2d, we skip populating some fields.

[LiDAR labels](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L298) and [camera labels](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L309) are populated in different fields.

**Comment by FFrostYY** [comment]
What was the solution to this issue?

**Comment by ly3106** [comment]
> You can read the submission as follows:
> 
> `f = open('untar-ed submission file name') submission = protos.Submission() if submission.ParseFromString(f.read()): print(submission) else: check fail `

This is the completed python code
```python
from waymo_open_dataset.protos import submission_pb2
f = open('/home/bit202/my_model/model0', mode='rb') # You can change the file name from `model0` to `model3`
submission = submission_pb2.Submission()
if submission.ParseFromString(f.read()):
    print(submission)
else:
    print("check fail")
```
If you save this python file as `read_submission_bin.py`, you can also run it and redirect the print information to a `txt` file (for instance [model0.txt](https://github.com/waymo-research/waymo-open-dataset/files/14549526/model0.txt)), which make it easy to read the full information. ps, you better open the `txt` file by the `gedit`, because the `txt` file maybe very large.
```bash
python ~/read_submission_bin.py | tee -a model0.txt
```
