### ISSUE TITLE
center of vehicle frame

### ISSUE THREAD

**Issue by yyuuliang** [waymo-research/waymo-open-dataset#165]
the data here is 001/segment-10750135302241325253_180_000_200_000_with_camera_labels.tfrecord

According to the docs, the box center is in vehicle frame. E.g., in this photo, the center of the box is
(12.425728132752083, -4.773993024558877, 2.878885135010904)
so this box is about 12m forward, 4.7m right and 2.9m upward. 
The y and z might be correct. But this box doesn't look like 12m forward... where is the center of the vehicle frame?

I have also calculated the box center location in the camera frame, the result is 
[[ 4.70110318] [-0.70939735] [10.91130435]]
Looks like the camera center is about 1.5m from the vehicle frame's center, is this correct?

![7_label](https://user-images.githubusercontent.com/21992330/81993867-788c1e00-95fb-11ea-971f-c0995a345f84.jpg)

**Comment by peisun1115** [comment]
the center is in the middle of the SDC's rear axle.  It is better to check the validity of the label in BEV or 3D view?

**Comment by yyuuliang** [comment]
hi @peisun1115 
thanks for your answer. I have checked using a 3D point cloud viewer and I found you are right. It's easier to see from the top.
I have another question, I found that in each data frame, the camera calibration data is the same. There are many photos in one data frame, from my understanding, the extrinsic matrix of the camera may be different in different photos. However, I use this camera calibration data to drawing the bounding box and found the position is correct. How could this happen?

**Comment by peisun1115** [comment]
They are different for different cameras. Check the camera name in this CameraCalibration proto

**Comment by yyuuliang** [comment]
But for one same camera, e.g., the front center camera, does the extrinsic matrix should be different for the different photo?

**Comment by peisun1115** [comment]
extrinsics is fixed for each camera in a scene. it represents the location of the camera in vehicle frame. it does not change

**Comment by yyuuliang** [comment]
@peisun1115 Thanks for the explanation!
