### ISSUE TITLE
Occluded Objects

### ISSUE THREAD

**Issue by os1a** [waymo-research/waymo-open-dataset#17]
Hi,
After exploring the data, I found out that you have also bounding boxes annotation for objects which are occluded by other objects. Do you have any information telling how much the object is occluded?
Can we infer something from the field:
optional DifficultyLevel detection_difficulty_level = 5;

Thanks,

**Comment by kevinsu628** [comment]
Hi @peisun1115 , I don't quite know how to tell if an object is occluded given this helper function 
Suppose I only have a 3D bbox of a car that is occluded by a tree entirely. How can I tell if this car is blocked by calculating the points in that box? 
Would appreciate it if you can give me a hint

**Comment by os1a** [comment]
I still do not understand how to do that?
The function has two arguments: box and points. From where can I get the points?
And how to decide later based on the returned number if the object is occluded or not?

**Comment by peisun1115** [comment]
You can use all points from that frame.

**Comment by Banittos** [comment]
Hello,
I am interested only in the 2D visual data and wanted to use the "optional DifficultyLevel detection_difficulty_level = 5" field to deduce occlusion but it is marked "UNKNOWN" in all 5 segments I have tested. Any idea where can I find samples with this field?
