### ISSUE TITLE
Tracking correspondence

### ISSUE THREAD

**Issue by bilalsattar** [waymo-research/waymo-open-dataset#171]
Following is written on the website:

> We provide 2D bounding box labels in the camera images. The camera labels are tight-fitting, axis-aligned 2D bounding boxes with globally unique tracking IDs. The bounding boxes cover only the visible parts of the objects.
> 
> The following objects have 2D labels: vehicles, pedestrians, cyclists. We do not provide object track correspondences across cameras.

What does this means?

> We do not provide object track correspondences across cameras.

**Comment by peisun1115** [comment]
It means images from different cameras (e.g. FRONT, FRONT_LEFT etc) are labeled independently. If an object appears in FRONT in t0 and appears in FRONT_LEFT in t0+delta, they will have different ID.

**Comment by bilalsattar** [comment]
but for benchmark, in 2d tracking, do you match tracks in individual cameras separately or the track is tracked across all cameras?

**Comment by henrikkretzschmar** [comment]
We evaluate the individual cameras independently in the 2D tracking challenge.
