### ISSUE TITLE
Validation result of all 0's [3D Tracking]

### ISSUE THREAD

**Issue by fuhuan26** [waymo-research/waymo-open-dataset#173]
Hello, @peisun1115 I submitted my validation result and it is all zeros. I tried to use the fake_prediction.bin and still the same.

I verified each indivisual segment performance offline and I can see nonzero MOTA, MOTP values.

My submission is at: https://waymo.com/open/challenges/entry/?timestamp=1589832179772683&challenge=TRACKING_3D&email=fuhuan26@gmail.com&submissionType=VALIDATION

Could you please help me look into it?

Thank you so much for your help!

![image](https://user-images.githubusercontent.com/50088717/82258171-353cf280-990e-11ea-8b82-e0bf93db347b.png)

**Comment by peisun1115** [comment]
Can you take a look at this https://github.com/waymo-research/waymo-open-dataset/issues/163#issuecomment-628419240 to see whether that solves your problem?

**Comment by fuhuan26** [comment]
@peisun1115 Thank you very much for your quick response. Since the validation set is huge, I run 36 out of 202 total segements and I submitted it to first make sure the submission will be successful.
Below is an example of a single segment result.
![image](https://user-images.githubusercontent.com/50088717/82262421-bba90280-9915-11ea-920e-67660c2bde1b.png)

As you can see, there are non zero metrics. I saw your comment in 163 ( zeros when there are too many miss detection, mismatch, etc..) I am wondering if it is the same reason for me, as I have run 36/202, almost 20% of the whole validation dataset. Also, why mismatch and miss score are also 0? Shouldn't they close to 1 if there are many mismatches and misses?

Below is my submission.txtpb and I changed the task to TRACKING_3D
![image](https://user-images.githubusercontent.com/50088717/82262844-8650e480-9916-11ea-86d5-e26b5c94b6cc.png)

I followed the submission instruction and I desperately wondering what is my issue.
Please advice. I appreciate it!

**Comment by fuhuan26** [comment]
Hi @peisun1115 
Just to be clarified, in the create_submission.cc example, one .bin file is the input and one model file is generated. 
![image](https://user-images.githubusercontent.com/50088717/82268773-a8e9fa00-9924-11ea-80b0-03460f98df6d.png)
To be able to run multiple files. I modified the code so that it will read all .bin files in the directory and then generate the single output file. 
Is this the correct thing to do? Or for each segment .bin file, I need to output the corresponding model file, and zip all the model files in the end?

Still could not figure out where is the problem. Thanks.

**Comment by fuhuan26** [comment]
I found an error with my code. Now it is working! Thanks @peisun1115

**Comment by RaymondByc** [comment]
@fuhuan26 Can you tell me what problems you solved? I am facing the same problems and have no idea to figure it out.

**Comment by RaymondByc** [comment]
I got a normal results when I just eval the 20 frames...
