### ISSUE TITLE
What is scene id and frame id?

### ISSUE THREAD

**Issue by droneRL2020** [waymo-research/waymo-open-dataset#175]
From the Waymo thesis, I understood as there are 1000 scenes and each scene is contained with 200 frames because data was gathered at 10FPS in 20 seconds for each scene.
 
1) Is this  "frame.context.name" in the below link scene id?
https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L133

2) Then where is frame id? I only can find timestamp_micros for each frame.

**Comment by henrikkretzschmar** [comment]
1. That's right, you can think of `frame.context.name` as an identifier for an entire segment/sequence.
2. You can use the timestamp `timestamp_micros` as an identifier for the individual frames. The frames do not have frame numbers.

**Comment by droneRL2020** [comment]
thank you for your confirmation.
