### ISSUE TITLE
Sing up for challenges

### ISSUE THREAD

**Issue by RocketFlash** [waymo-research/waymo-open-dataset#176]
Hi! Sorry maybe for stupid question, but how to register on challenges? I didn't find any registration form on site

**Comment by peisun1115** [comment]
Check https://waymo.com/open/challenges/ . If you can upload your results, then you are registered.

**Comment by RocketFlash** [comment]
Thank you, I got it. But what about teams? If I have a team only one of us should submit results?

**Comment by peisun1115** [comment]
Yeah, only one of your should submit. But do list all team members in the authors list.
