### ISSUE TITLE
Psuedo labelling allowed for Object detection challenge?

### ISSUE THREAD

**Issue by GokulEpiphany** [waymo-research/waymo-open-dataset#177]
As per the rules of the challenge, only unlimited prior frames are allowed for object detection as well. It's unclear if we are allowed to pseudo label the confident predictions from the test dataset and use them in training

**Comment by henrikkretzschmar** [comment]
Thanks for your question!

From the rules: "The Training and Validation datasets both have labels that you can use to train your machine learning model (the Test dataset labels will not be made available). You will run your trained machine learning model on the Test dataset to create your own labels for the Test dataset."

Specifically, we do not allow the use of any test data for training the models.

Thanks,
Henrik

**Comment by tugstugi** [comment]
@henrikkretzschmar so pseudo labeling is not allowed?

**Comment by henrikkretzschmar** [comment]
Correct. Using data from the test set for training models is not allowed, which includes pseudo labeling the test set for training models.

**Comment by GokulEpiphany** [comment]
@henrikkretzschmar Makes sense. Thanks!
