### ISSUE TITLE
What is the source of speed_x and speed_y (derived from position or detected directly)?

### ISSUE THREAD

**Issue by Xiangwang-Hu** [waymo-research/waymo-open-dataset#178]
Is speed_x and speed_y: 

- derived from position (center_x,y,z) 

- or detected independently by lidar? 

- or any other source ?
Thanks in advance

**Comment by peisun1115** [comment]
They are derived from (center x y z)

**Comment by Xiangwang-Hu** [comment]
Thanks a lot.
