### ISSUE TITLE
Multiple files while creating submission

### ISSUE THREAD

**Issue by zeenolife** [waymo-research/waymo-open-dataset#179]
Hi,
When I run the command the following command:
`metrics/tools/create_submission  --input_filenames='/tmp/preds.bin' --output_filename='/tmp/my_model/model' --submission_filename='metrics/tools/submission.txtpb'`
I get multiple files as my output. Namely, the output is 4 files:
`model0, model1, model2, model3`
I could not find anything regarding multiple file outputs. Is this an expected behavior? If so, should I put all output files into one *.tar.gz file?

**Comment by peisun1115** [comment]
yes, it is expected. it can be controlled by https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/create_submission.cc#L51

this is to make sure the size of the proto is under control.

**Comment by zeenolife** [comment]
So, I can just set the number of shards to 1, rebuild the `create_sumbission`, and it will output only one file, right?

**Comment by zeenolife** [comment]
Ah, I see that I can pass it as an argument :smile:

**Comment by peisun1115** [comment]
you are supposed to use 4 by default. there is no reason to change it unless your file is too small. 

just tar and zip all of them

**Comment by zeenolife** [comment]
Thanks for your quick response!
