### ISSUE TITLE
Loading data in non-eager mode?

### ISSUE THREAD

**Issue by skaae** [waymo-research/waymo-open-dataset#18]
I'm trying to write a `tf.data` pipeline, but i cannot figure out how to load data when tensorflow is not in eager mode. 

```Python
FILENAME = "/home/skaae/Downloads/waymo/training_0000/segment-13519445614718437933_4060_000_4080_000_with_camera_labels.tfrecord"
dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')

def parse_data(data):
    frame = open_dataset.Frame()
    frame.ParseFromString(bytearray(data.numpy()))  # <--- is Tensor in normal mode? 
    range_images, camera_projections,range_image_top_pose = parse_range_image_and_camera_projection(frame)
    
    range_image_top = range_images[open_dataset.LaserName.TOP][0]
    range_image_top_tensor = tf.reshape(
            tf.convert_to_tensor(range_image_top.data), range_image_top.shape.dims)

    return range_image_top_tensor

parsed_dataset = dataset.map(parse_data)

```

**Comment by skaae** [comment]
Ok, Im still not sure how to do it. Can you give an example on how to extract one of the matrices from a frame? Or do you have it documented somewhere?

**Comment by peisun1115** [comment]
We are thinking of releasing a transformed dataset (in tensorflow.Example) for each challenge we host which might make data loading easier for users.

For now, yes, you need to write your own job to convert the proto to fit your own problem and machine learning framework (e.g. pytorch or tensorflow).

**Comment by SirJuergen** [comment]
hey skaae,

i think i am having the same problem as you. Did you solve it? if yes could you please provide your code? I am new to this and writing my masters thesis about the topic. I would very much appreciate it!! thanks in advance.

**Comment by atyshka** [comment]
@peisun1115 is a transformed dataset still under consideration or no?

**Comment by peisun1115** [comment]
We have released one that is defined by [Lingvo](https://github.com/tensorflow/lingvo/blob/master/lingvo/tasks/car/waymo/tools/waymo_proto_to_tfe.py) in this bucket 

waymo_open_dataset_v_1_0_0_tf_example_lingvo/v.1.2.0

It is not officially supported.

I recommend doing this transformation on your own. In practice, only a subset of the data in the dataset is needed.  Reading a full dataset for your model can limit your training speed by a lot.
