### ISSUE TITLE
3 test submissions per team per month

### ISSUE THREAD

**Issue by tugstugi** [waymo-research/waymo-open-dataset#185]
How is enforced that each team has only 3 test submissions per month in each track?

I.e. The team CyberCore Co.,Ltd. has 3 submissions in the 2D tracking in this month with 2 accounts:
* https://waymo.com/open/challenges/entry/?challenge=TRACKING_2D&email=thuy.ng.ch@gmail.com&timestamp=1590917074923255
* https://waymo.com/open/challenges/entry/?challenge=TRACKING_2D&email=thuy.ng.ch@gmail.com&timestamp=1590545403312354
* https://waymo.com/open/challenges/entry/?challenge=TRACKING_2D&email=holaituan@gmail.com&timestamp=1588922274697785

I am also in a team with another guy who only submits in the 2D detection and I submit only for the 2D tracking not to violate the challenge rules. It shouldn't violate the rules or?

**Comment by peisun1115** [comment]
Each team is supposed to have only 1 email to submit. Having multiple users from the same team submitting the same model is not allowed. 

@onexerxes can comment more on the policy

**Comment by onexerxes** [comment]
It looks like in that case there are two separate teams (with different members), despite having the same affiliation. 

In any case, we will review all entries for eligibility at the close of the challenges.
