### ISSUE TITLE
Results Processing for 30+ minutes

### ISSUE THREAD

**Issue by KishoreMayank** [waymo-research/waymo-open-dataset#187]
My team is attempting to submit our final results for the 2D detection model, but it has been on the processing phase for the past 30 minutes. Is there potentially something wrong with our submission or should we continue to wait?

**Comment by peisun1115** [comment]
There is a high load of submission now. You can wait a bit. As long as it is submitted before the deadline, it is counted in the challenge.

**Comment by peisun1115** [comment]
If you are worried, send me a link to your submission to peis@waymo.com

**Comment by KishoreMayank** [comment]
Great! Just sent the email
