### ISSUE TITLE
Waymo OD Challenge - Need Help Understanding Image Frame

### ISSUE THREAD

**Issue by ARathie** [waymo-research/waymo-open-dataset#188]
https://github.com/waymo-research/waymo-open-dataset/blob/016a54e8a57ffd7c84b4516fe7e335432ffc9212/third_party/camera/ops/camera_model_ops_test.py#L143-L147

https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/ops/camera_model_ops_test.py#L155-L157

In the above lines, `image_points` is converted to `global_points` using the `py_camera_model_ops.image_to_world()` method. I understand that the 3rd elements, the z dim element, in each `global_point` is the height from the ground, following the gravity vector. What does the 3rd element, 20 in this case, in each `image_point` represent? Distance from the camera? Height from the ground? Also, what units are they in?

Thanks in advance

**Comment by peisun1115** [comment]
Distance from the point  to camera frame origin.

comment: https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/camera_model.h#L81

code (for global shutter): https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/camera_model.cc#L447-L448

**Comment by ARathie** [comment]
Got it, thanks for clarifying! 

Another quick question, we are getting some negative Z values after converting to global frame? Does a negative Z value indicate the object is underground? Or is the ground not defined as Z = 0? 
Also, are the global and vehicle frame values in meters?

**Comment by peisun1115** [comment]
Values in global frame cannot be interpreted as is. Negative z's are common there. If you see huge negative z's in vehicle frame, it might be concerning (but can still happen). 

negative z indicates a downward slope which is common in SF. Values are in meters.

**Comment by ARathie** [comment]
Understood, thanks so much Pei Sun!

- Ashwin
