### ISSUE TITLE
Extract object labels?

### ISSUE THREAD

**Issue by cgq5** [waymo-research/waymo-open-dataset#19]
How do you extract object labels from the 2D/3D data? I wonder if there is a demo code for it. Thx.

**Comment by henrikkretzschmar** [comment]
We store the object labels in the frames:
https://github.com/waymo-research/waymo-open-dataset/blob/5f14e0a7390d4673033017d841c5b95a2b77c5d5/waymo_open_dataset/dataset.proto#L270

You can find the laser labels here:
https://github.com/waymo-research/waymo-open-dataset/blob/5f14e0a7390d4673033017d841c5b95a2b77c5d5/waymo_open_dataset/dataset.proto#L284-L290

You can find the camera labels here:
https://github.com/waymo-research/waymo-open-dataset/blob/5f14e0a7390d4673033017d841c5b95a2b77c5d5/waymo_open_dataset/dataset.proto#L291-L295

We're planning on extending the demo code to make this clearer.

**Comment by Okkband** [comment]
> We store the object labels in the frames:
> https://github.com/waymo-research/waymo-open-dataset/blob/5f14e0a7390d4673033017d841c5b95a2b77c5d5/waymo_open_dataset/dataset.proto#L270
> 
> You can find the laser labels here:
> https://github.com/waymo-research/waymo-open-dataset/blob/5f14e0a7390d4673033017d841c5b95a2b77c5d5/waymo_open_dataset/dataset.proto#L284-L290
> 
> You can find the camera labels here:
> https://github.com/waymo-research/waymo-open-dataset/blob/5f14e0a7390d4673033017d841c5b95a2b77c5d5/waymo_open_dataset/dataset.proto#L291-L295
> 
> We're planning on extending the demo code to make this clearer.

I have a question. In the laser information, what does the "first return" and "second return" mean? Does it means that one light delivered from the lidar will return two beam of light ?

**Comment by peisun1115** [comment]
A lidar shot can have multiple returns. I've found this explanation on Google
http://home.iitk.ac.in/~blohani/LiDAR_Tutorial/Multiple%20return%20LiDAR.htm

**Comment by Okkband** [comment]
> http://home.iitk.ac.in/~blohani/LiDAR_Tutorial/Multiple%20return%20LiDAR.htm

Thank you very much.
