### ISSUE TITLE
What does 7-DOF means in this dataset?

### ISSUE THREAD

**Issue by no-Seaweed** [waymo-research/waymo-open-dataset#191]
I have gone through most of content of this dataset and the paper, but, maybe I missed some part of information, I cannot find specific description of what the 7-DOF means. Any help would be appreciated!

**Comment by peisun1115** [comment]
7-DOF = 7 degree of freedom = center_{x,y,z}, l, w, h, heading

**Comment by no-Seaweed** [comment]
Thank you!
