### ISSUE TITLE
Does compute_range_image_polar and compute_range_image_cartesian return vehicle frame?

### ISSUE THREAD

**Issue by skaae** [waymo-research/waymo-open-dataset#20]
Does `compute_range_image_polar` and `compute_range_image_cartesian` return range images in vehicle frame? 

I assume it does because in the tutorial `extract_point_cloud_from_range_image` is called with an extrinsic transform that is from lidar frame to vehicle frame:

https://github.com/waymo-research/waymo-open-dataset/blob/60df55a1a968a7ccce6c13a0b560a4af086561a7/waymo_open_dataset/utils/frame_utils.py#L131-L147

In the docs for `compute_range_image_cartesian` it says that it expect the range image in polar coordinates to be in sensor frame?

**Comment by peisun1115** [comment]
compute_range_image_polar return coordinates in sensor frame.
compute_range_image_cartesian returns coordinates in vehicle frame.
