### ISSUE TITLE
num_points_in_box_3d different from the number read from dataset

### ISSUE THREAD

**Issue by YurongYou** [waymo-research/waymo-open-dataset#200]
Hi,

I tried to calculate the num_points_in_box_3d using the provided code, but it seems the number is smaller than the number recorded in the dataset? Simple way to reproduce: in the colab, after getting the `points` and `points_all_ri2`:
```python
from waymo_open_dataset.utils import box_utils
points_all = np.concatenate((points_all, points_all_ri2))
box = frame.laser_labels[21].box
print(box_utils.compute_num_points_in_box_3d(points_all, tf.constant([[box.center_x, box.center_y, box.center_z, box.length, box.width, box.height, box.heading]])))
print(frame.laser_labels[21].num_lidar_points_in_box)
```

I got:
```
tf.Tensor([847], shape=(1,), dtype=int32)
880
```

I am not sure if I understand the `num_points_in_box_3d` correctly.

P.S. I think the `box_utils.compute_num_points_in_box_3d` should be correct, since I rewrote one by myself and it yields the same results.

Best,
Yurong

**Comment by peisun1115** [comment]
See this [issue](https://github.com/waymo-research/waymo-open-dataset/issues/156). We should make it consistent for future release

**Comment by YurongYou** [comment]
ic, thanks!
