### ISSUE TITLE
Transforming image point to vehicle frame

### ISSUE THREAD

**Issue by bilalsattar** [waymo-research/waymo-open-dataset#204]
I know this method transforms image to world. I have image coordinates and depth in vehicle frame(x-axis)?
py_camera_model_ops.image_to_world([x,y,depth])

===What will be the depth here(in method)? x-axis value from vehicle frame/ world frame?

===Can it be negative? For example for LEFT/RIGHT Camera, objects can be behind camera,

**Comment by peisun1115** [comment]
depth is the distance from camera sensor origin to the point. you can just play with it with some example which can help you figure out.

No, it cannot be out of the image's FOV due to distortion.

**Comment by bilalsattar** [comment]
Thanks
