### ISSUE TITLE
Drawing bounding boxes

### ISSUE THREAD

**Issue by randcode-generator** [waymo-research/waymo-open-dataset#21]
Hi,
I am trying to draw bounding boxes on the images. Is this the right way to convert current data (center_x, center_y, width, length) to rectangular bounding box (left, top, right, bottom)?
```
left = center_x - (length/2)
top = center_y - (width/2)
right = center_x + (length/2)
bottom = center_y + (width/2)
```

**Comment by peisun1115** [comment]
it looks correct to me.
