### ISSUE TITLE
ERROR: pyasn1-modules 0.2.8 has requirement pyasn1<0.5.0,>=0.4.6, but you'll have pyasn1 0.1.9 which is incompatible.

### ISSUE THREAD

**Issue by hughlee815** [waymo-research/waymo-open-dataset#211]
hi
when i run `pip install waymo-open-dataset`, i encounter this error:
`ERROR: pyasn1-modules 0.2.8 has requirement pyasn1<0.5.0,>=0.4.6, but you'll have pyasn1 0.1.9 which is incompatible.`
does anyont have any idea to fix it? please help.
thank in advance.

**Comment by peisun1115** [comment]
follow the quick start. you are not installing the right package
