### ISSUE TITLE
how to tranform 3d points from one frame to another

### ISSUE THREAD

**Issue by hughlee815** [waymo-research/waymo-open-dataset#213]
i know there is a 4x4 row major transform matrix. but it is 4x4. when we have points whose shape is (n, 3), how can we do the transform operation?
this is so confusing.
can any one help me?
thanks so much!

**Comment by hughlee815** [comment]
is it possible that anyone give a help, please...

**Comment by peisun1115** [comment]
A = transform (4x4)

you can do
point = point + [1]
transformed_point = (A * point)[0:3]

**Comment by hughlee815** [comment]
hi,
thanks for your soon reply. i tried your solution immediately, it works very well. but i got another question---after applying the transform matrix with the boxes of the second frame, these new boxes i got didn't coincide with those of the first frame.
i am wondering whether i get any wrong? shouldn't those boxes of the two frames coincide?

**Comment by peisun1115** [comment]
you can try our code https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/utils/box_utils.py#L153

**Comment by hughlee815** [comment]
thanks, your code helps me a lot. Just one thing I am still not so clear --- based on your code, i made some small changes to transform points from the 9th frame (just an example) to the 1st frame as follows:
`trans = np.dot(np.linalg.inv(frame_1_pose), frame_9_pose) # frame_1_pose means the 4*4 transform matrics in frame 1`
`points = np.row_stack((frame_9_points, np.ones(points.shape[0])))`
`points_transformed = np.dot(points, trans)[:,:3]`
then i draw points_transformed and also 3d boxes in frame 9(which are not transforemed) via mayavi in one figure. In theory, point objects should not be in these 3d boxes, since these points have been transformed, while the 3d boxes are not. But according to my experiment, these point objects are still in these boxes, like they have never been transformed.
This result is a little hard for me to understand. If it's not too much trouble, could you please tell me why this happen or did I do anything wrong?
Thanks in advance.

**Comment by hughlee815** [comment]
thans so much. i finlly find my code is wrong, your code are perfect!!!   thanks once again. respect!

**Comment by mc171819** [comment]
> thanks, your code helps me a lot. Just one thing I am still not so clear --- based on your code, i made some small changes to transform points from the 9th frame (just an example) to the 1st frame as follows: `trans = np.dot(np.linalg.inv(frame_1_pose), frame_9_pose) # frame_1_pose means the 4*4 transform matrics in frame 1` `points = np.row_stack((frame_9_points, np.ones(points.shape[0])))` `points_transformed = np.dot(points, trans)[:,:3]` then i draw points_transformed and also 3d boxes in frame 9(which are not transforemed) via mayavi in one figure. In theory, point objects should not be in these 3d boxes, since these points have been transformed, while the 3d boxes are not. But according to my experiment, these point objects are still in these boxes, like they have never been transformed. This result is a little hard for me to understand. If it's not too much trouble, could you please tell me why this happen or did I do anything wrong? Thanks in advance.

Hi, I'm facing the same problem as you. Could you pleace tell me how to solve it?
