### ISSUE TITLE
velocity ground truth?

### ISSUE THREAD

**Issue by AndyYuan96** [waymo-research/waymo-open-dataset#215]
Hi, I just wonder how you guys get the ground truth of obstacle's velocity?

**Comment by peisun1115** [comment]
yes, see https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/label.proto#L52-L55

**Comment by AndyYuan96** [comment]
> yes, see https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/label.proto#L52-L55

I know how to read velocity from your label, I just wonder which method you use to measure the velocity of obstacle.

**Comment by peisun1115** [comment]
They are derivatives of center_(x, y, z) of the labels in global frame

**Comment by AndyYuan96** [comment]
> They are derivatives of center_(x, y, z) of the labels in global frame

how many frames you use to get one obstacle's velocity? Two adjacent frames or more? doe the velocity reliable, it's a little tricky, I thought the velocity label is the true velocity of obstacle.

**Comment by Super-Tree** [comment]
> > They are derivatives of center_(x, y, z) of the labels in global frame
> 
> how many frames you use to get one obstacle's velocity? Two adjacent frames or more? doe the velocity reliable, it's a little tricky, I thought the velocity label is the true velocity of obstacle.

@peisun1115 Could you give some detailed information about how to calculate the velocity of objects？ Like use two adjacent or more frames, or use EKF to fit the real velocity？

**Comment by a954217436** [comment]
I have the same question. Could you please share a clue of how to calculate the velocity? @peisun1115 
And have you guys found the solutions about it? @Super-Tree @AndyYuan96

**Comment by peisun1115** [comment]
I think it just assumes constant velocity between frames given that the interval between frames is small enough. You can come up with better model to calculate the speed if you feel that is necessary (e.g. constant accel, constant derivative of accel etc)
