### ISSUE TITLE
when eval, should I store my prediction results of all of the frames in one bin file, or...

### ISSUE THREAD

**Issue by hughlee815** [waymo-research/waymo-open-dataset#217]
when i evaluate my predictions, should I store my prediction results of all of the frames in one .bin file. Or one frame corresponds to a .bin file, like kitti dataset.

if we store all of the predictions in one bin file, how can the eval tool(`compute_detection_metrics_main`) distinguish the result of one frame from one another?

if we store each frame separately, then we can only evaluate one example at a time by `compute_detection_metrics_main fake_predictions.bin  fake_ground_truths.bin,` which i think could not even be possible.

**Comment by peisun1115** [comment]
one file. each frame is uniquely identified by context.name and frame.timestamp_micros

see https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/create_prediction_file_example.py

**Comment by hughlee815** [comment]
can i only set context.name without frame.timestamp_micros, or only set frame.timestamp_micros without context.name?

**Comment by peisun1115** [comment]
no, we require both.
