### ISSUE TITLE
pip install waymo-open-dataset

### ISSUE THREAD

**Issue by khsrhhh** [waymo-research/waymo-open-dataset#22]
Hi.

Now I am setting my local linux envirionment as same as Colab Waymo Open Dataset Tutorial.
When I type command 'pip install waymo-dataset' , error messages occurs 
![2019-09-02 15;38;36](https://user-images.githubusercontent.com/39553283/64094814-e4916380-cd97-11e9-84e8-3dfd61e451d4.PNG)

Could you help me please?

**Comment by randcode-generator** [comment]
I don't think there's a `waymo-open-dataset` package on pip

You can just run the commands in the [tutorial](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb) to install the necessary packages to get it running locally. Anything that has ! (exclamation mark) is a command.

**Comment by peisun1115** [comment]
The master branch has a waymo-open-dataset on pip. But that is not officially released. We are going to create a 1.0.1 patch release soon.

Your error msg shows that you need to upgrade your pip.

**Comment by khsrhhh** [comment]
> I don't think there's a `waymo-open-dataset` package on pip
> 
> You can just run the commands in the [tutorial](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb) to install the necessary packages to get it running locally. Anything that has ! (exclamation mark) is a command.

![image](https://user-images.githubusercontent.com/39553283/64144114-064d2200-ce4e-11e9-83ea-dea8c300db7f.png)

I found waymo-open-dataset pip package on that website, whether it is official pip-package website.
Just I want to know why I can't install that package on my local PC

**Comment by khsrhhh** [comment]
> The master branch has a waymo-open-dataset on pip. But that is not officially released. We are going to create a 1.0.1 patch release soon.
> 
> Your error msg shows that you need to upgrade your pip.

I will wait the update version.

**Comment by peisun1115** [comment]
You should be able to install before we officially release it. You need to update your pip version as that is required by tensorflow 1.14.0

pip install --upgrade pip

Then 
pip install waymo-open-dataest --user

**Comment by khsrhhh** [comment]
> You should be able to install before we officially release it. You need to update your pip version as that is required by tensorflow 1.14.0
> 
> pip install --upgrade pip
> 
> Then
> pip install waymo-open-dataest --user

Thanks for reply. I will type that command later.
One more question I have.

 'quick start.md' says python3 is required but why waymo-open-dataset pip package is based  python 2.7?

**Comment by peisun1115** [comment]
I will remove that requirement in the coming 1.0.1 release. It is no longer required in the master branch. I realized lots of people are still using python2

**Comment by khsrhhh** [comment]
> I will remove that requirement in the coming 1.0.1 release. It is no longer required in the master branch. I realized lots of people are still using python2

Thanks for reply. I would close the issue.

**Comment by xuanzhangyang** [comment]
https://pypi.org/search/?q=waymo-open-dataset
Find the version corresponding to tensorflow, then click on "Download files" button, check if the version of python in the environment matches "Download files"
