### ISSUE TITLE
Images are the same for all איק items ןn the dataset

### ISSUE THREAD

**Issue by ShaniGam** [waymo-research/waymo-open-dataset#221]
I use the tutorial to extract the images:
```
dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')
for data in dataset:
    frame = open_dataset.Frame()
    frame.ParseFromString(bytearray(data.numpy()))

    for image in frame.images:
        save_images(image)
```
but for some reason, I get the same 5 images for every `data` in `dataset`.
What am I missing?

**Comment by peisun1115** [comment]
How do you tell that they are the same images? The data are stored sequentially. So images from consecutive frames are expected to look similar (but not the same)

**Comment by ShaniGam** [comment]
You're right, thanks!
