### ISSUE TITLE
fatal error: absl/flags/flag.h: No such file or directory

### ISSUE THREAD

**Issue by hughlee815** [waymo-research/waymo-open-dataset#222]
hi,

since i want to submit my bin file to the leadboard, i compile `create_submission.cc` with `g++ create_submission.cc` 
but i got `fatal error: absl/flags/flag.h: No such file or directory` 

is this error normal and i should install absl?
or,is somewhere my operation  wrong?

looking forward to your reply, thanks.

**Comment by hughlee815** [comment]
i think the `create_submission.cc` should have been compiled, since other cpp file are compiiled, but i cannot find `create_submission` anywhere.

**Comment by peisun1115** [comment]
it is under bazel-bin/ if you can compile the repo with bazel (or with the provided docker script)

**Comment by hughlee815** [comment]
i can compile with bazel, but there is only compute_detection_metrics_main under bazel-bin/
