### ISSUE TITLE
World to Image misalignment for dynamic objects

### ISSUE THREAD

**Issue by skanti** [waymo-research/waymo-open-dataset#227]
Is a world3d -> image2d misalignment like this usual?

Note that 

- the red car is moving with a velocity of ~6m/s
- could be that slow lidar spin of 0.1s per spin is causing those ghosting artefacts for dynamic objects

![Figure_1](https://user-images.githubusercontent.com/11197940/96137566-15314f80-0efd-11eb-9fdd-509151c77c46.png)

**Comment by peisun1115** [comment]
This looks like [rolling shutter](https://en.wikipedia.org/wiki/Rolling_shutter) effect. I guess you are looking at the side camera. You can use our projection [lib](https://github.com/waymo-research/waymo-open-dataset/tree/master/third_party/camera) which compensates for this effect.  I forgot whether i have released a new pip lib with this lib compiled if it not in the pre-compiled pip. but you can easily compile on your own by following  [this](https://github.com/waymo-research/waymo-open-dataset/tree/master/pip_pkg_scripts)

**Comment by skanti** [comment]
Oh nice thanks :) 

This projection lib should be more highlighted throughout the repo and tutorials. Would say one of the most important aspects in this dataset.
