### ISSUE TITLE
[Clarification] 3 submission per 30 days 

### ISSUE THREAD

**Issue by tianweiy** [waymo-research/waymo-open-dataset#228]
> You can only submit against the Test Set 3 times every 30 days

How should I interpret this?  

1. Does this mean that I can submit 3 in October, and 3 in early November? 

or 

2. does it mean that I need to wait 30 days after my third submission to resubmit an entry? 

Thanks for the clarification!

**Comment by peisun1115** [comment]
now = t0, number of submissions within (t0 - 30d) <= 3

it is a running sum

**Comment by tianweiy** [comment]
cool, thanks!
