### ISSUE TITLE
what is elongation?

### ISSUE THREAD

**Issue by hughlee815** [waymo-research/waymo-open-dataset#229]
hi,
i am still confused about the function of lidar elongation,
could you please give some details about it?

**Comment by peisun1115** [comment]
I think you can simply view it as another signal we can capture from LiDAR. It is not really something specific to our LiDAR. Intensity measures the signal strength while elongation measures signal duration. 
 
 This [paper](https://www.spiedigitallibrary.org/conference-proceedings-of-spie/11299/112990N/Origins-and-mitigations-of-some-automotive-pulsed-lidar-artifacts/10.1117/12.2546976.short?SSO=1) talks  a little about it.

**Comment by hughlee815** [comment]
that's so kind of you, thanks a lot!
