### ISSUE TITLE
Bazel error when trying to use Metrics Computations

### ISSUE THREAD

**Issue by abahnasy** [waymo-research/waymo-open-dataset#242]
I'm trying to build core metrics library, I followed the steps mentioned in Quick Start but got this error

`bahnasy@TUINI15-VC03:~/waymo-od$ bazel clean
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
bahnasy@TUINI15-VC03:~/waymo-od$ bazel build
WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
ERROR: error loading package '': Unable to load file '//tf:workspace_tf2_3_2.bzl': file doesn't exist
INFO: Elapsed time: 0.052s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @bazel_tools; Restarting.`

**Comment by peisun1115** [comment]
Did you. run ./configure.sh?

**Comment by abahnasy** [comment]
yes

**Comment by abahnasy** [comment]
the problem is related to tensorflow version, there is no `//tf:workspace_tf2_3_2.bzl` file inside tf folder. I changed the name and it builds fine. However, the Tensorflow Op for metrics bazel test failed

`bazel test waymo_open_dataset/metrics/ops/...`

output in log file
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //waymo_open_dataset/metrics/ops:detection_metrics_ops_test
-----------------------------------------------------------------------------
2021-01-21 05:27:39.964486: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/home/bahnasy/.cache/bazel/_bazel_bahnasy/d3a1ab35e435955eb9deaadc9e4dd840/sandbox/linux-sandbox/1162/execroot/__main__/bazel-out/k8-opt/bin/waymo_open_dataset/metrics/ops/detection_metrics_ops_test.runfiles/__main__/waymo_open_dataset/metrics/ops/detection_metrics_ops_test.py", line 24, in <module>
    from waymo_open_dataset.metrics.ops import py_metrics_ops
  File "/home/bahnasy/.cache/bazel/_bazel_bahnasy/d3a1ab35e435955eb9deaadc9e4dd840/sandbox/linux-sandbox/1162/execroot/__main__/bazel-out/k8-opt/bin/waymo_open_dataset/metrics/ops/detection_metrics_ops_test.runfiles/__main__/waymo_open_dataset/metrics/ops/py_metrics_ops.py", line 23, in <module>
    metrics_module = tf.load_op_library(
  File "/home/bahnasy/.local/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/bahnasy/.cache/bazel/_bazel_bahnasy/d3a1ab35e435955eb9deaadc9e4dd840/sandbox/linux-sandbox/1162/execroot/__main__/bazel-out/k8-opt/bin/waymo_open_dataset/metrics/ops/detection_metrics_ops_test.runfiles/__main__/waymo_open_dataset/metrics/ops/metrics_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
```

**Comment by peisun1115** [comment]
did you sync to master? we do have support for tf.2.3

https://github.com/waymo-research/waymo-open-dataset/blob/master/tf/workspace_tf2_3_0.bzl

**Comment by abahnasy** [comment]
Solved, Thank you

**Comment by panda2020-sky** [comment]
> 

hi, how do you solve the problem？I am facing the same error. Thank you!

**Comment by panda2020-sky** [comment]
> the problem is related to tensorflow version, there is no `//tf:workspace_tf2_3_2.bzl` file inside tf folder. I changed the name and it builds fine. However, the Tensorflow Op for metrics bazel test failed
> 
> `bazel test waymo_open_dataset/metrics/ops/...`
> 
> output in log file
> 
> ```
> exec ${PAGER:-/usr/bin/less} "$0" || exit 1
> Executing tests from //waymo_open_dataset/metrics/ops:detection_metrics_ops_test
> -----------------------------------------------------------------------------
> 2021-01-21 05:27:39.964486: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
> Traceback (most recent call last):
>   File "/home/bahnasy/.cache/bazel/_bazel_bahnasy/d3a1ab35e435955eb9deaadc9e4dd840/sandbox/linux-sandbox/1162/execroot/__main__/bazel-out/k8-opt/bin/waymo_open_dataset/metrics/ops/detection_metrics_ops_test.runfiles/__main__/waymo_open_dataset/metrics/ops/detection_metrics_ops_test.py", line 24, in <module>
>     from waymo_open_dataset.metrics.ops import py_metrics_ops
>   File "/home/bahnasy/.cache/bazel/_bazel_bahnasy/d3a1ab35e435955eb9deaadc9e4dd840/sandbox/linux-sandbox/1162/execroot/__main__/bazel-out/k8-opt/bin/waymo_open_dataset/metrics/ops/detection_metrics_ops_test.runfiles/__main__/waymo_open_dataset/metrics/ops/py_metrics_ops.py", line 23, in <module>
>     metrics_module = tf.load_op_library(
>   File "/home/bahnasy/.local/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename)
> tensorflow.python.framework.errors_impl.NotFoundError: /home/bahnasy/.cache/bazel/_bazel_bahnasy/d3a1ab35e435955eb9deaadc9e4dd840/sandbox/linux-sandbox/1162/execroot/__main__/bazel-out/k8-opt/bin/waymo_open_dataset/metrics/ops/detection_metrics_ops_test.runfiles/__main__/waymo_open_dataset/metrics/ops/metrics_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
> ```

hi, how do you solve the problem？I am facing the same error. Thank you!
