### ISSUE TITLE
Google Cloud Bucket: Sorry, the server was not able to fulfil your request.

### ISSUE THREAD

**Issue by ptoews** [waymo-research/waymo-open-dataset#243]
I'm trying to access the data via the Google Cloud Bucket links provided on the website. I have registered with my Google account at least 4-5 days ago and am logged in with the same account while accessing the link, however I cannot access the files, and the following error message is shown.

![image](https://user-images.githubusercontent.com/1062119/105365486-984dfa00-5bfe-11eb-94c9-f10b011ef976.png)

This happens with all of the 6 links of the 3 versions.

**Comment by zoeyyang1** [comment]
Thanks for your question. We will look into this. What is the email address that you used to register?

**Comment by ptoews** [comment]
I've tried a different address now as well without success. I can PM the addresses to someone if necessary.

**Comment by zoeyyang1** [comment]
Hi, feel free to email the address to open-dataset@waymo.com.

**Comment by dschoerk** [comment]
same issue for me. sent an email as well.

**Comment by ptoews** [comment]
In my case this was caused because I registered without filling the optional fields, which seemed to work because I got access to the links, but only when I filled the optional fields as well I got a confirmation mail and (after a processing delay of a day or so) access to the bucket. Maybe this helps you as well @dschoerk, otherwise you can reopen this.

**Comment by dschoerk** [comment]
> 
> 
> In my case this was caused because I registered without filling the optional fields, which seemed to work because I got access to the links, but only when I filled the optional fields as well I got a confirmation mail and (after a processing delay of a day or so) access to the bucket. Maybe this helps you as well @dschoerk, otherwise you can reopen this.

thanks! somehow the fields didn't show up at first for me. after switching to a different browser where i wasnt logged in before they showed up.

**Comment by Ambiwlans** [comment]
Which optional fields? I also cannot get access and see only 4 fields (all required), no e-mail sent. Tested on multiple browsers. I only tried an hour ago though, so maybe just delay.

**Comment by ptoews** [comment]
Yes, it seems like they changed it. Should be 4 fields as you said

**Comment by zoeyyang1** [comment]
Hi all, this is just to confirm that all 4 fields in the licensing terms are required, and you should not be running into the issue that ptoews experienced. 
If your registration is successful, you should receive a confirmation email from Waymo shortly and have access to the bucket. If you received the registration confirmation email, but do not have access to the bucket, please reach out to open-dataset@waymo.com.
