### ISSUE TITLE
Change Metadata about a Test Set Submission

### ISSUE THREAD

**Issue by tianweiy** [waymo-research/waymo-open-dataset#244]
Hi,

I want to change the metadata about one of my submissions to 3d detection leaderboard. The id is CenterPoint. Basically, I used two frames but forgot to change the field in the info file. Could you help me fix this or refer me to anyone that can fix this?

**Comment by peisun1115** [comment]
Hi,
   I usually do not mutate users' data. It is easier if you submit a new version and i can delete your last version.

Pei

**Comment by tianweiy** [comment]
Thanks! Could you delete my old submission then?

**Comment by peisun1115** [comment]
Deleted.
