### ISSUE TITLE
Point cloud mismatch on the side-camera images.

### ISSUE THREAD

**Issue by vink01** [waymo-research/waymo-open-dataset#248]
Hi,

I understand that it's easier to synchronize the point clouds on the front and back cameras since the view will not change a lot while the vehicle is moving. But I feel that the case for the side camera is different since the camera/lidar view keeps changing rapidly while the vehicle is moving. I'm curious that how do you solve the mismatch issue for the side camera point cloud projection? Even if you are using the rolling shutter camera, but the lidar spin speed is different with the rolling shutter exposure speed, I guess you can never get the exact same view for camera and lidar for the same time? 
Looking forward to your response. Thanks!

ps. Not sure if this is still an issue if you are using a global shutter camera.

**Comment by peisun1115** [comment]
Thanks for your question. If you see any mismatch issue in our dataset, we can take a look. The details (except rolling shutter projection) of achieving a good synchronization is out of the scope of this dataset.
