### ISSUE TITLE
Visualizing Camera Projection

### ISSUE THREAD

**Issue by randcode-generator** [waymo-research/waymo-open-dataset#25]
Hi,
I am trying to visualize camera projection on other images by changing ```images``` index as follows 

```
mask = tf.equal(cp_points_all_tensor[..., 0], images[3].name)
```
Here's a screenshot of the output 
<img width="1149" alt="screen1" src="https://user-images.githubusercontent.com/7875165/64227015-d0d92080-ceaf-11e9-9310-0804c66b3cde.png">

Is this the correct way to do it? Does the screenshot look correct?

**Comment by peisun1115** [comment]
It looks correct to me.
