### ISSUE TITLE
[Rule Clarification] Number of frames allowed in the challenge?

### ISSUE THREAD

**Issue by tianweiy** [waymo-research/waymo-open-dataset#254]
According to the email, it states that " Real-time 3D Detection: Given a single lidar range image and the associated camera images, produce a set of 3D upright boxes for the objects in the scene, with a latency requirement." which means we are only given a single range image.

But on the website https://waymo.com/open/challenges/2021/real-time-3d-prediction/  "Given one or more lidar range images and the associated camera images, produce a set of 3D upright boxes for the objects in the scene. "

Could you clarify which one is correct?

**Comment by peisun1115** [comment]
We allow multiple frames. We are likely to set a limit on the number of frames to be used so that we can evaluate the latency properly. For now, you can assume that multi-frame is allowed.

**Comment by tianweiy** [comment]
thanks for the clarification. Please let me know about the exact number of frames allowed once you have finalized the rule.
