### ISSUE TITLE
Dependency on tensorflow_gpu package vs tensorflow package

### ISSUE THREAD

**Issue by Ianni** [waymo-research/waymo-open-dataset#256]
Hi, 
I want to use your package in an environment where the tensorflow 2.4.0 package is already installed. 
Your package requires tensorflow_gpu which results in an environment with both, tensorflow 2.4.0 and tensorflow_gpu 2.4.0. 
Both packages provide gpu support, and according to the tensorflow installation guide, tensorflow_gpu was only necessary for versions <2.0.0 . 
Can we change the requirement for the package from tensorflow_gpu to tensorflow in the build files, or is there a difference between these packages I am not aware of?

**Comment by peisun1115** [comment]
Thanks for asking. For now, you may build your own pip package which is quite easy. Just change this to [tensorflow](https://github.com/waymo-research/waymo-open-dataset/blob/master/pip_pkg_scripts/build.sh#L42-L47).  We are probably won't be able to release another set of pip packages under the same name.

**Comment by Ianni** [comment]
Thank you for reply and sorry for my very late answer. 
For completeness, I also changed [this](https://github.com/waymo-research/waymo-open-dataset/blob/a19ba044e0ad42c49e95f09298b491db5d8ed05c/pip_pkg_scripts/setup.py.in#L23) to change the requirement of the final package, not just the build environment.
