### ISSUE TITLE
[Rule Clarification] Order of the Lidar Frames

### ISSUE THREAD

**Issue by tianweiy** [waymo-research/waymo-open-dataset#259]
Another rule related question. 

For the detection challenge, could we assume that we will be given lidar frames in a sequence? (frame 0, frame 1, frame 2, etc..). This will allow us to do some temporal fusion by keeping a memory buffer of previous frame's detections.

**Comment by peisun1115** [comment]
We do not support that. Multi-frame model will simply take multi-frame as input. If you have solutions that does support streaming, we'd be interested in knowing  how much improvement you can get!

**Comment by tianweiy** [comment]
thanks for the clarification. We will see if we get something for streaming by the NeurIPS deadline :)
