### ISSUE TITLE
Cannot  pip install waymo-open-dataset --user

### ISSUE THREAD

**Issue by nan0755** [waymo-research/waymo-open-dataset#26]
When I want to install  `waymo-open-dataset` in my system, it went wrong as below:
```sh
Collecting waymo-open-dataset
  Could not find a version that satisfies the requirement waymo-open-dataset (from versions: )
No matching distribution found for waymo-open-dataset
```

**Comment by peisun1115** [comment]
it seems that multiple people have complained this. Are you able to pip install tensorflow=1.14.0?

If it works for you, you can build the pip package by yourself by using
https://github.com/waymo-research/waymo-open-dataset/blob/master/pip_pkg_scripts/build_pip_pkg.sh

**Comment by peisun1115** [comment]
Did it work for you?

**Comment by peisun1115** [comment]
You can also do

python3 -m pip install --upgrade pip

That should work. 

This is because:
manylinux2010 was introduced in pip 19.+

**Comment by nan0755** [comment]
I didn't install this package in my system, and I use it as a self-build package in my project.

**Comment by xuanzhangyang** [comment]
https://pypi.org/search/?q=waymo-open-dataset      
Find the version corresponding to tensorflow, then click on  "Download files" button, check if the version of python in the environment matches "Download files"
