### ISSUE TITLE
How to request multiple Lidar Frame?

### ISSUE THREAD

**Issue by tianweiy** [waymo-research/waymo-open-dataset#260]
Could you link to an example? Here 

https://github.com/waymo-research/waymo-open-dataset/blob/7c67158744aa2ed84ac81697d3c3d93890bb7d6f/waymo_open_dataset/latency/examples/pytorch/from_saved_model/submission/lib/wod_latency_submission/__init__.py#L36

it seems to only support the current frame. 

Additionally, here https://github.com/waymo-research/waymo-open-dataset/blob/7c67158744aa2ed84ac81697d3c3d93890bb7d6f/waymo_open_dataset/latency/examples/pytorch/from_saved_model/submission/lib/wod_latency_submission/__init__.py#L81

the code basically concatenates five point clouds together. Could I assume that the point for the other Lidar(e.g. SIDE_LEFT) has already been transformed to top LIDAR's coordinate?

**Comment by peisun1115** [comment]
Yes, we will add an example. @sabeekpradhan

**Comment by tianweiy** [comment]
actually no need for a full example. Could you just let me know how can I get a value of a specific frame? For instance, I want the top lidar of the previous frame? What name should I put in DATA_FIELDS?

**Comment by sabeekpradhan** [comment]
We'll update the README soon, but for now, you can just add _1 to the end of a field name (e.g. TOP_RANGE_IMAGE_FIRST_RETURN_1) to get the value of that field from one frame earlier, and add _2 to the end of a field name (e.g. TOP_RANGE_IMAGE_FIRST_RETURN_2) to get the value of that field from two frames earlier.

Also, to follow up on a dangling question from your original post, the x, y, and z channels in a range image are all in vehicle frame, and thus they are in the same coordinate frame for all the lidars in a given frame (but will be in a different coordinate frame in frame 1 vs frame 2).
