### ISSUE TITLE
KeyError: 'traffic_light_state/current/id'

### ISSUE THREAD

**Issue by luis2r** [waymo-research/waymo-open-dataset#265]
I am trying to get the lane ID controlled by each traffic signal. 
`trl_id =   decoded_example['traffic_light_state/current/id']
`
But I am getting the following error:
`KeyError: 'traffic_light_state/current/id'`

**Comment by May-821** [comment]
Hi,

I encounter the similar error:
`KeyError: 'state/past/x'`

could you please tell me how you resolved it?

Thanks!
