### ISSUE TITLE
PyTorch Dataloader for motion dataset?

### ISSUE THREAD

**Issue by zqh0253** [waymo-research/waymo-open-dataset#268]
Hi, I am wondering if there is a PyTorch Dataloader class supporting motion dataset? 

I notice that there is one wonderful dataset loader [simple-waymo-open-dataset-reader](https://github.com/gdlg/simple-waymo-open-dataset-reader), but that is for perception track.

**Comment by yasser-h-khalil** [comment]
Hi,

Have you found anything yet?

Thanks.

**Comment by xushilin1** [comment]
Hi, @zqh0253. Did you find or implement a PyTorch Dataloader to support waymo motion dataset?

**Comment by EloiZ** [comment]
Hello @zqh0253 @yasser-h-khalil @zqh0253 ,
did you find anything ?
Best,
