### ISSUE TITLE
Can't follow the ''Build and test'' step

### ISSUE THREAD

**Issue by sjtuherisson** [waymo-research/waymo-open-dataset#27]
Hello,
When I follow the "Build and test" step described in the Tutorial[https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/r1.0/tutorial/tutorial.ipynb#scrollTo=-pVhOfzLx9us](url), I can't build it successfully. 

This is the log :

In file included from bazel-out/k8-opt/bin/external/local_config_tf/include/tensorflow/core/framework/tensor_shape.h:22:0,
                 from bazel-out/k8-opt/bin/external/local_config_tf/include/tensorflow/core/framework/tensor.h:23,
                 from ./waymo_open_dataset/metrics/ops/utils.h:23,
                 from waymo_open_dataset/metrics/ops/utils.cc:16:
bazel-out/k8-opt/bin/external/local_config_tf/include/tensorflow/core/framework/types.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
bazel-out/k8-opt/bin/external/local_config_tf/include/tensorflow/core/framework/types.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
bazel-out/k8-opt/bin/external/local_config_tf/include/tensorflow/core/framework/types.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.

I find the types.pb.h and it says "#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION"
But I'm pretty sure that my bazel version is 0.28.0 and the protoc version is 3.6.1.

What should I do ? Please help me, thank you !

**Comment by randcode-generator** [comment]
What is your tensorflow version?

**Comment by peisun1115** [comment]
As Eric pointed out, this is because of a mismatch of tensorflow version. Different tensorflow version has different protobuf version. 

We officially support tf 1.14.0. if you use other versions, you can try to do something similar as r1.0-tf1.15 branch which works for tf.1.15 (the upcoming tf release).

If there is another popular tf version, i can add support for that too

**Comment by sjtuherisson** [comment]
、

> As Eric pointed out, this is because of a mismatch of tensorflow version. Different tensorflow version has different protobuf version.
> 
> We officially support tf 1.14.0. if you use other versions, you can try to do something similar as r1.0-tf1.15 branch which works for tf.1.15 (the upcoming tf release).
> 
> If there is another popular tf version, i can add support for that too

Hmmm, I notice that the quick_start.md says " * TensorFlow 1.14.0 or higher. ",
and mine is exactly1.14.0.

I try to conda create a new env, and ensure all the dependencies version right.

This time 0 errors, 8 warnings. 

BTW, how can I extract frames from the .tfrecord files in the dataset ? 
It seems that the general method of decoding .tfrecod (tf.train.Example etc.) is useless.

**Comment by randcode-generator** [comment]
There's a [tutorial](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_local.ipynb) on how to extract information from tfrecords.

**Comment by sjtuherisson** [comment]
> What is your tensorflow version?

Mine is 1.14.0. 
I establish a new environment and successfully build.
Thank you all the same.

**Comment by sjtuherisson** [comment]
> There's a [tutorial](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_local.ipynb) on how to extract information from tfrecords.

As the tutorial says，
“## Read one frame
Each file in the dataset is a sequence of frames ordered by frame start timestamps. We have extracted two frames from the dataset to demonstrate the dataset format.”

And due to the dataset.proto, each frame contains 4 images : [FRONT, FRONT_LEFT, FRONT_RIGHT, SIDE_LEFT, SIDE_RIGHT]. 

The tutorial uses the FRAME file not the .tfrecord file, I think the frames should be extracted first.

Sorry I'm a newbie if any radicular comprehension, and nobody can give me instruction in my lab.

**Comment by randcode-generator** [comment]
The FRAME file in tutorial folder is a .tfrecord

Replace FRAME file with another tfrecord from Waymo and it should still work

**Comment by peisun1115** [comment]
I think Eric has answered all the questions. I am closing this issue. Feel free to reopen if you see other problems.
