### ISSUE TITLE
Question about multi frame timestamp in latency inference

### ISSUE THREAD

**Issue by lhcalibur** [waymo-research/waymo-open-dataset#276]
Just a question. Will Waymo provide timestamp/timelag in latency inference? I can't find it in https://github.com/waymo-research/waymo-open-dataset/tree/master/waymo_open_dataset/latency. Thanks

**Comment by sabeekpradhan** [comment]
For now we haven't provided it. As an approximation, you can assume that the lag is roughly 100 ms between subsequent frames. However, if you need more detail, we can try to add the timestamp values themselves to the dataset.

**Comment by lhcalibur** [comment]
> For now we haven't provided it. As an approximation, you can assume that the lag is roughly 100 ms between subsequent frames. However, if you need more detail, we can try to add the timestamp values themselves to the dataset.

It's OK, just a question, thanks!
