### ISSUE TITLE
Size/dimensions of scenario map

### ISSUE THREAD

**Issue by pmlakner** [waymo-research/waymo-open-dataset#277]
The coordinates for map features are all arbitrary, is there a way to get the origin for each scenario and is there a standard size for each?

**Comment by scott-ettinger** [comment]
There is not a standard size for each scenario.  Each scenario includes map data for a fixed radius around the path of the autonomous vehicle's path.  The total map extent can vary depending on the travel of the autonomous vehicle that collected the data. Can you describe what you mean by an "origin for each scenario?".

**Comment by pmlakner** [comment]
By origin I meant the extent of the map in the scenario. The coordinates of the smallest x, y and largest x, y values in each scenario

**Comment by scott-ettinger** [comment]
We do not provide the min and max extents of the map features.  Hopefully these are straightforward to compute if you need them.
