### ISSUE TITLE
3D tracking challenge submission

### ISSUE THREAD

**Issue by goktugyildirim** [waymo-research/waymo-open-dataset#281]
My aim is to evaluate my 3D tracker. I know that I can inference my tracker through validation set and test set in order to submit my predictions. At this point, I could not see any data type which indicates the segment of the dataset in the proto file. In sum, how Waymo determine which segment I used? Maybe timestamp info is enough. Can I use any segment I wish?

**Comment by peisun1115** [comment]
[These two fields](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/metrics.proto#L43-L46) uniquely identify a frame.

**Comment by goktugyildirim** [comment]
@peisun1115 thanks for your reply. I have two questions about 3D tracking validation. I'm trying to use create_prediction_file_example.py in order to generate a prediction file, and it requires the object type but I guess it's redundant for 3D tracking tasks. Am I right? My second question is about submission.txtpb file. It contains those instance:number_past_frames_exclude_current,number_future_frames_exclude_current. I couldn't understand what those parameters are. If you express them, I'll be very appreciated
