### ISSUE TITLE
20000 dimension is not enough for all `roadgraph_samples`.

### ISSUE THREAD

**Issue by YaxuanDai** [waymo-research/waymo-open-dataset#282]
Hi, I tried to visualize the `roadgraph_samples` components in `tf_example` folder, while 20000 points seems is not large enough to contain all semantic elements, especially when the road graph is complex. 
(Good and bad samples are posted behind.)

Is there any way to access all road markers around the ADV?

good case:
![good case](https://user-images.githubusercontent.com/25880787/115992797-19ec6400-a602-11eb-8e1f-fff2f01dd431.png)

bad case:
![badcase](https://user-images.githubusercontent.com/25880787/115992807-240e6280-a602-11eb-8dd5-74e88de29ee7.png)

**Comment by scott-ettinger** [comment]
Your visualization very nice!  It is true that in some scenarios, not all road features are represented within the 20,000 points within the tensors. A tensor size of 20000 points was selected for the tf.Examples to trade off between model size and representation as the tensors must be a fixed size.  The Scenario protocol buffer version of the dataset contains all of the map features within a radius of the autonomous vehicle.  There is not a way to recover all of the features from the tf.Example data.

**Comment by troylhy1991** [comment]
@YaxuanDai hi, your visualization looks very good! may I ask what kind of tools you used to achieve that ;)

**Comment by YaxuanDai** [comment]
@scott-ettinger Thanks! using scenario solved the problem. 
By the way, would you release the feature extractor from scenario to tf_example as further explanation?

**Comment by YaxuanDai** [comment]
@troylhy1991 Please try matplotlib.

**Comment by troylhy1991** [comment]
good to know matplotlib can be this good

btw, lane info can be decoded as below, which seems not a fixed length list; not sure how much a larger tensor size (> 20000) will help with the prediction though
dataset = tf.data.TFRecordDataset(FILENAME_IN_SCENARIO_FOLDER, compression_type='')
for data in dataset:
    scenario = scenario_pb2.Scenario()
    scenario.ParseFromString(bytearray(data.numpy()))
    break
    
scenario.map_features()
