### ISSUE TITLE
Ground Truth Labels for Each Point in Point Cloud

### ISSUE THREAD

**Issue by xiongyiheng** [waymo-research/waymo-open-dataset#285]
I am doing segmentation tasks on one frame using point cloud and extracting ground truth labels for each point by calling the method "is_within_bounding_box". I am wondering whether there is a more efficient way to extract ground truth segmentation labels for each point. Thanks in advance!

**Comment by peisun1115** [comment]
No better way for now. What you have described doesn't look very inefficient.

**Comment by xiongyiheng** [comment]
Thanks for your reply.
