### ISSUE TITLE
Submission for Validation and Testing Set

### ISSUE THREAD

**Issue by thptai** [waymo-research/waymo-open-dataset#289]
HI,

I am currently trying to submit to the validation set.
Everything was fine 3 days ago. But right now, I can not see any detail of my submissions (on both validation and testing sets).
I have not changed any thing in my process.
Even the old results that I can read now is empty.

![image](https://user-images.githubusercontent.com/8033997/116857843-6c4c0700-ac38-11eb-9688-4ce9cde0de45.png)

![image](https://user-images.githubusercontent.com/8033997/116857902-84238b00-ac38-11eb-9d07-5cbe03328ac2.png)

I hope to receive your answers soon. Thank you.

**Comment by peisun1115** [comment]
We will get back to you soon. This is likely related to recent changes to the server for the motion dataset.

**Comment by peisun1115** [comment]
This is resolved. Let us know if you see more issues.

**Comment by thptai** [comment]
Thank you, the problem has been resolved.
