### ISSUE TITLE
[Question] Waymo LSTM baseline availability

### ISSUE THREAD

**Issue by manolotis** [waymo-research/waymo-open-dataset#292]
Is the trained baseline model publicly available somewhere? I found a description of the basic architecture in the recently released [whitepaper](https://arxiv.org/pdf/2104.10133.pdf), but if possible I would like to explore this model's predictions without having to implement and train it. 

Thank you in advance!

**Comment by scott-ettinger** [comment]
Unfortunately we do not currently have an open source version of this model.  This model is the simplest of the baselines which uses an LSTM with only the agent past states to encode the input and uses an MLP to predict multiple trajectories as described in the white paper you referenced.  We will consider this request for an open source baseline model.  We appreciate your feedback.
