### ISSUE TITLE
question on "compute_detection_metrics_main.cc"

### ISSUE THREAD

**Issue by ritaiask** [waymo-research/waymo-open-dataset#293]
In line 40~58 in https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc, almost every mAP and mAPH is larger than 0 ,
 but when i ran  " cd waymo-od && bazel-bin/waymo_open_dataset/metrics/tools/compute_detection_metrics_main waymo_open_dataset/metrics/tools/fake_predictions.bin  waymo_open_dataset/metrics/tools/fake_ground_truths.bin ", followed 
 by the steps in QUICK START,   i got :
4 examples found.
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [mAP 0] [mAPH 0]
....
every mAP is 0, and every mAPH is also 0.

**Comment by peisun1115** [comment]
it is because [this](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L130) is not populated in the fake gt/pd as they were created before the field was introduced.

**Comment by ritaiask** [comment]
> it is because [this](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L130) is not populated in the fake gt/pd as they were created before the field was introduced.

Thank you , it's  been solved now .
