### ISSUE TITLE
Submission in 3D real-time detection validation

### ISSUE THREAD

**Issue by lihao0374** [waymo-research/waymo-open-dataset#297]
Hi,  I have submitted the file with the docker link. But i can not find the latency feedback on the page. Could you help me to check out what error happens?  The docker link is 'gs://waymo_lv/sub.tar.gz'.  Thanks!

**Comment by nntrongnghia** [comment]
Hello, I have the same question about the latency. Could you show me where can I find my latency result ?

**Comment by peisun1115** [comment]
You can send an email to open-dataset@waymo.com with your submission page link. Very likely, your docker is can not run successfully
