### ISSUE TITLE
mAP  0  using  your gt.bin [3D detection]

### ISSUE THREAD

**Issue by shmpwk** [waymo-research/waymo-open-dataset#298]
Following #121 and other issue, but mAP are always 0. 

[What I tried]
I downloaded gs://waymo_open_dataset_v_1_2_0/validation/validation_0000.tar
Using those dataset, I make a prediction file called tmp.bin. See the last code.
Then I downloaded gs://waymo_open_dataset_v_1_2_0/validation/ground_truth_objects/gt.bin , which is validation_ground_truth_objects_gt.bin

The result is that all mAP and mAPH are 0.
```
$ bazel-bin/waymo_open_dataset/metrics/tools/compute_detection_metrics_main /tmp/tmp.bin ~/Downloads/validation_ground_truth_objects_gt.bin
39951 examples found.

OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_SIGN_LEVEL_1: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_SIGN_LEVEL_2: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_SIGN_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_SIGN_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_SIGN_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_SIGN_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_SIGN_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_SIGN_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
```

~~Here is the way to make a prediction file.~~ **THIS IS WRONG** . See below.
```
def _create_pd_file(frame): 
    o_list = []

    for camera_labels in frame.camera_labels:
        for gt_label in camera_labels.labels:
            o = metrics_pb2.Object()
            o.context_name = frame.context.name
            o.frame_timestamp_micros = frame.timestamp_micros
            o.camera_name = camera_labels.name

            box = label_pb2.Label.Box()
            box.center_x = gt_label.box.center_x
            box.center_y = gt_label.box.center_y
            box.center_z = gt_label.box.center_z
            box.length =   gt_label.box.length
            box.width =    gt_label.box.width
            box.heading =  gt_label.box.heading
            o.object.box.CopyFrom(box)
            o.score = 0.9
            o.object.type = gt_label.type
            o.object.num_lidar_points_in_box = 100
            o_list.append(o)

    return o_list


def create_bin(dataset_path):
    dataset = tf.data.TFRecordDataset([str(x.absolute()) for x in Path(dataset_path).rglob('*.tfrecord')])
    objects = metrics_pb2.Objects()
    for data in tqdm.tqdm(dataset):
        frame = dataset_pb2.Frame()
        frame.ParseFromString(bytearray(data.numpy()))
        o_list = _create_pd_file(frame)
        for o in o_list:
            objects.objects.append(o)

    f = open("/tmp/tmp.bin", 'wb')
    f.write(objects.SerializeToString())
    f.close()


def main():
    dataset_path = sys.argv[1]
    create_bin(dataset_path)

if __name__ == '__main__':
  main()
```

I also tried to submit the leader board and the result was 0.

**Comment by peisun1115** [comment]
I ma not sure as i do not know what you have in tmp.bin. you can try to feed the tool with both gt and pd as the downloaded ground truth file. It should give you 1.0 AP.

**Comment by shmpwk** [comment]
@peisun1115 
Thank you for your reply.
>  you can try to feed the tool with both gt and pd as the downloaded ground truth file. It should give you 1.0 AP.
Yes I confirmed it.

tmp.bin is made from gs://waymo_open_dataset_v_1_2_0/validation/validation_0000.tar

**Comment by TimGor1997** [comment]
> Following #121 and other issue, but mAP are always 0.
> 
> [What I tried]
> I downloaded gs://waymo_open_dataset_v_1_2_0/validation/validation_0000.tar
> Using those dataset, I make a prediction file called tmp.bin. See the last code.
> Then I downloaded gs://waymo_open_dataset_v_1_2_0/validation/ground_truth_objects/gt.bin , which is validation_ground_truth_objects_gt.bin
> 
> The result is that all mAP and mAPH are 0.
> 
> ```
> $ bazel-bin/waymo_open_dataset/metrics/tools/compute_detection_metrics_main /tmp/tmp.bin ~/Downloads/validation_ground_truth_objects_gt.bin
> 39951 examples found.
> 
> OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_SIGN_LEVEL_1: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_SIGN_LEVEL_2: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1: [mAP 0] [mAPH 0]
> OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_SIGN_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_1: [mAP 0] [mAPH 0]
> RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]
> ```
> 
> Here is the way to make a prediction file.
> 
> ```
> def _create_pd_file(frame):
>     o_list = []
> 
>     for camera_labels in frame.camera_labels:
>         for gt_label in camera_labels.labels:
>             o = metrics_pb2.Object()
>             o.context_name = frame.context.name
>             o.frame_timestamp_micros = frame.timestamp_micros
>             o.camera_name = camera_labels.name
> 
>             box = label_pb2.Label.Box()
>             box.center_x = gt_label.box.center_x
>             box.center_y = gt_label.box.center_y
>             box.center_z = gt_label.box.center_z
>             box.length =   gt_label.box.length
>             box.width =    gt_label.box.width
>             box.heading =  gt_label.box.heading
>             o.object.box.CopyFrom(box)
>             o.score = 0.9
>             o.object.type = gt_label.type
>             o.object.num_lidar_points_in_box = 100
>             o_list.append(o)
> 
>     return o_list
> 
> 
> def create_bin(dataset_path):
>     dataset = tf.data.TFRecordDataset([str(x.absolute()) for x in Path(dataset_path).rglob('*.tfrecord')])
>     objects = metrics_pb2.Objects()
>     for data in tqdm.tqdm(dataset):
>         frame = dataset_pb2.Frame()
>         frame.ParseFromString(bytearray(data.numpy()))
>         o_list = _create_pd_file(frame)
>         for o in o_list:
>             objects.objects.append(o)
> 
>     f = open("/tmp/tmp.bin", 'wb')
>     f.write(objects.SerializeToString())
>     f.close()
> 
> 
> def main():
>     dataset_path = sys.argv[1]
>     create_bin(dataset_path)
> 
> if __name__ == '__main__':
>   main()
> ```
> 
> I also tried to submit the leader board and the result was 0.

could you tell me how to create the .bin of your train? I have no way to create it

**Comment by shmpwk** [comment]
@TimGor1997 I just use distributed waymo dataset in gs://waymo_open_dataset_v_1_2_0/validation/, which including detected bounding box.

**Comment by shmpwk** [comment]
I found my prediction file is wrong. I try 3D detection, but I use 2D bounding box generated from camera lable. 
I also found that num_lidar_points_in_box is not needed for prediction file. ([source](https://github.com/waymo-research/waymo-open-dataset/issues/193#issuecomment-641469592))
Here is how to make the edited predict file.
```
def _create_pd_file(frame):
    o_list = []

    for laser_label in frame.laser_labels:
        o = metrics_pb2.Object()
        o.context_name = frame.context.name
        o.frame_timestamp_micros = frame.timestamp_micros
   
        box = label_pb2.Label.Box()
        box.center_x = laser_label.box.center_x
        box.center_y = laser_label.box.center_y
        box.center_z = laser_label.box.center_z
        box.length =   laser_label.box.length
        box.width =   laser_label.box.width
        box.heading =  laser_label.box.heading
        o.object.box.CopyFrom(box)
        o.score = 0.9
        o.object.type = laser_label.type
        o_list.append(o)
    return o_list


def create_bin(dataset_path):
    dataset = tf.data.TFRecordDataset([str(x.absolute()) for x in Path(dataset_path).rglob('*.tfrecord')])
    objects = metrics_pb2.Objects()
    for data in tqdm.tqdm(dataset):
        frame = dataset_pb2.Frame()
        frame.ParseFromString(bytearray(data.numpy()))
        o_list = _create_pd_file(frame)
        for o in o_list:
            objects.objects.append(o)

    f = open("/tmp/tmp.bin", 'wb')
    f.write(objects.SerializeToString())
    f.close()


def main():
    dataset_path = sys.argv[1]
    create_bin(dataset_path)

if __name__ == '__main__':
  main()
```

**Comment by shmpwk** [comment]
But still all my mAP and mAPH are 0.

Here is one example data of gs://waymo_open_dataset_v_1_2_0/validation/ground_truth_objects/gt.bin 
```
object {
  box {
    center_x: 65.22030601071856
    center_y: -7.655075827020482
    center_z: 1.6157043360668126
    width: 0.8015234565892257
    length: 0.10298852562100518
    height: 0.75
    heading: 3.1279403552168805
  }
  metadata {
    speed_x: 1.0134273703051424e-27
    speed_y: 1.0134273703051424e-27
    accel_x: -1.126030292131695e-27
    accel_y: -1.126030292131695e-27
  }
  type: TYPE_SIGN
  id: "PAdUT_ypaJoIpZV6rIIQBA"
  num_lidar_points_in_box: 19
}
score: 0.5
context_name: "11048712972908676520_545_000_565_000"
frame_timestamp_micros: 1522684691238230
```
and 

gs://waymo_open_dataset_v_1_2_0/validation/validation_0000.tar
```
object {
  box {
    center_x: 65.22030601071856
    center_y: -7.655075827020482
    center_z: 1.6157043360668126
    width: 0.8015234565892257
    length: 0.10298852562100518
    height: 0.75
    heading: 3.1279403552168805
  }
  type: TYPE_SIGN
  id: "PAdUT_ypaJoIpZV6rIIQBA"
}
score: 0.8999999761581421
context_name: "11048712972908676520_545_000_565_000"
frame_timestamp_micros: 1522684691238230
```

I extract this data with the same frame_timestamp_micros, context_name and object type. There are plenty of data corresponds like this. 
Is there any reason why the evaluation matrix is zero?

**Comment by shmpwk** [comment]
Solved. My program is correct. The reason the evaluation matrix is zero is just my trivial typo, and I get
```
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1: [mAP 0.122955] [mAPH 0.122955]
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [mAP 0.106505] [mAPH 0.106505]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1: [mAP 0.0730361] [mAPH 0.0730361]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2: [mAP 0.0609821] [mAPH 0.0609821]
OBJECT_TYPE_TYPE_SIGN_LEVEL_1: [mAP 0.146516] [mAPH 0.146516]
OBJECT_TYPE_TYPE_SIGN_LEVEL_2: [mAP 0.107961] [mAPH 0.107961]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1: [mAP 0.11942] [mAPH 0.11942]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2: [mAP 0.115577] [mAPH 0.115577]
RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_1: [mAP 0.117056] [mAPH 0.117056]
RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_2: [mAP 0.114264] [mAPH 0.114264]
RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_1: [mAP 0.131743] [mAPH 0.131743]
RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_2: [mAP 0.116452] [mAPH 0.116452]
RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_1: [mAP 0.122999] [mAPH 0.122999]
RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_2: [mAP 0.0922284] [mAPH 0.0922284]
RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_1: [mAP 0.0635076] [mAPH 0.0635076]
RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_2: [mAP 0.0568148] [mAPH 0.0568148]
RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_1: [mAP 0.0732648] [mAPH 0.0732648]
RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_2: [mAP 0.0628176] [mAPH 0.0628176]
RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_1: [mAP 0.0922832] [mAPH 0.0922832]
RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_2: [mAP 0.0661743] [mAPH 0.0661743]
RANGE_TYPE_SIGN_[0, 30)_LEVEL_1: [mAP 0.141538] [mAPH 0.141538]
RANGE_TYPE_SIGN_[0, 30)_LEVEL_2: [mAP 0.117953] [mAPH 0.117953]
RANGE_TYPE_SIGN_[30, 50)_LEVEL_1: [mAP 0.143339] [mAPH 0.143339]
RANGE_TYPE_SIGN_[30, 50)_LEVEL_2: [mAP 0.108104] [mAPH 0.108104]
RANGE_TYPE_SIGN_[50, +inf)_LEVEL_1: [mAP 0.160412] [mAPH 0.160412]
RANGE_TYPE_SIGN_[50, +inf)_LEVEL_2: [mAP 0.0972204] [mAPH 0.0972204]
RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_1: [mAP 0.103695] [mAPH 0.103695]
RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_2: [mAP 0.103045] [mAPH 0.103045]
RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_1: [mAP 0.155176] [mAPH 0.155176]
RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_2: [mAP 0.147241] [mAPH 0.147241]
RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_1: [mAP 0.109806] [mAPH 0.109806]
RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_2: [mAP 0.103671] [mAPH 0.103671]
```

**Comment by Loong789** [comment]
Hello, I also encountered the same issue. May I ask what method you used to resolve it?

**Comment by jingluo-lan** [comment]
Hello, I also encountered the same issue. May I ask what method you used to resolve it?

**Comment by jingluo-lan** [comment]
07/17 16:26:56 - mmengine - INFO - Epoch(test) [198/198]    Waymo metric/Vehicle/L1 mAP: 0.0000  Waymo metric/Vehicle/L1 mAPH: 0.0000  Waymo metric/Vehicle/L2 mAP: 0.0000  Waymo metric/Vehicle/L2 mAPH: 0.0000  Waymo metric/Pedestrian/L1 mAP: 0.0000  Waymo metric/Pedestrian/L1 mAPH: 0.0000  Waymo metric/Pedestrian/L2 mAP: 0.0000  Waymo metric/Pedestrian/L2 mAPH: 0.0000  Waymo metric/Sign/L1 mAP: 0.0000  Waymo metric/Sign/L1 mAPH: 0.0000  Waymo metric/Sign/L2 mAP: 0.0000  Waymo metric/Sign/L2 mAPH: 0.0000  Waymo metric/Cyclist/L1 mAP: 0.0000  Waymo metric/Cyclist/L1 mAPH: 0.0000  Waymo metric/Cyclist/L2 mAP: 0.0000  Waymo metric/Cyclist/L2 mAPH: 0.0000  Waymo metric/Overall/L1 mAP: 0.0000  Waymo metric/Overall/L1 mAPH: 0.0000  Waymo metric/Overall/L2 mAP: 0.0000  Waymo metric/Overall/L2 mAPH: 0.0000  data_time: 0.0028  time: 0.1130
