### ISSUE TITLE
bazel build error with gcc-5 and gcc-7

### ISSUE THREAD

**Issue by gongmeteor** [waymo-research/waymo-open-dataset#3]
**firstly I compiled with gcc-5 and get error log as:**
WARNING: /home/chris/.cache/bazel/_bazel_chris/b2fd8959c85968b8f97fc8dbb85c5c52/external/local_config_tf/BUILD:3823:1: target 'libtensorflow_framework.so' is both a rule and a file; please choose another name for the rule
INFO: Analyzed 62 targets (0 packages loaded, 0 targets configured).
INFO: Found 62 targets...
ERROR: /home/chris/work/waymo-od/waymo_open_dataset/math/BUILD:58:1: C++ compilation of rule '//waymo_open_dataset/math:polygon2d' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 46 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
waymo_open_dataset/math/polygon2d.cc: In static member function 'static std::string waymo::open_dataset::Polygon2d::PrintPointsToString(const std::vector<waymo::open_dataset::Vec2d>&, bool)':
waymo_open_dataset/math/polygon2d.cc:484:59: error: 'DECIMAL_DIG' was not declared in this scope
       ::absl::StrAppendFormat(&result, "{%.*e, %.*e},\n", DECIMAL_DIG,
                                                           ^
INFO: Elapsed time: 1.334s, Critical Path: 1.25s
INFO: 3 processes: 3 linux-sandbox.
FAILED: Build did NOT complete successfully

**then I upgrade gcc to v7, the compile still cannot pass:** 
WARNING: /home/chris/.cache/bazel/_bazel_chris/b2fd8959c85968b8f97fc8dbb85c5c52/external/local_config_tf/BUILD:3823:1: target 'libtensorflow_framework.so' is both a rule and a file; please choose another name for the rule
INFO: Analyzed 62 targets (0 packages loaded, 0 targets configured).
INFO: Found 62 targets...
ERROR: /home/chris/work/waymo-od/waymo_open_dataset/math/BUILD:76:1: undeclared inclusion(s) in rule '//waymo_open_dataset/math:segment2d':
this rule is missing dependency declarations for the following files included by 'waymo_open_dataset/math/segment2d.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/syslimits.h'
INFO: Elapsed time: 1.341s, Critical Path: 1.25s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by amrit110** [comment]
don't think it has anything to do with gcc, DECIMAL_DIG is simply not defined. i just set it to some desired precision value and it builds fine. https://abseil.io/docs/cpp/guides/format

**Comment by peisun1115** [comment]
1. I have fixed the build failure for gcc-5 in https://github.com/waymo-research/waymo-open-dataset/commit/9c663111bb63a9520d7037bd1cb878b0210f7a1d

2. Your build failure for gcc-7 does not seem to be related to our code. It seems that you cannot find header files from standard libs. We were not able to reproduce it in gcc-7. Try 'bazel clean'? If that does not work, do you think you can use our dockerfile and give it a try? It will be great if we can reproduce it in a docker.

**Comment by Okkband** [comment]
> 1. I have fixed the build failure for gcc-5 in [9c66311](https://github.com/waymo-research/waymo-open-dataset/commit/9c663111bb63a9520d7037bd1cb878b0210f7a1d)
> 2. Your build failure for gcc-7 does not seem to be related to our code. It seems that you cannot find header files from standard libs. We were not able to reproduce it in gcc-7. Try 'bazel clean'? If that does not work, do you think you can use our dockerfile and give it a try? It will be great if we can reproduce it in a docker.

Thanks, gcc5.4 build is ok after I checkout the branch. But gcc-7 still has some problems, so I change the gcc version to 5.4 at last. Thank you.

**Comment by peisun1115** [comment]
Glad to hear that it is working for you.
