### ISSUE TITLE
The label.box.heading is not correct as visulizing in Open3D GUI.

### ISSUE THREAD

**Issue by nan0755** [waymo-research/waymo-open-dataset#30]
I extracted out only the LiDAR label bounding box and visualized in Open3D GUI. It looks like as follow, but all the bboxes heading angle are verticle to their correct direction. 
![Screenshot from 2019-09-09 10-38-11](https://user-images.githubusercontent.com/29373801/64500041-35e8a800-d2ee-11e9-9ddc-231812822ce6.png)
Thus, I add pi/2 to each heading, and it sames to be coorect, but I still don't know why.
![Screenshot from 2019-09-09 10-44-51](https://user-images.githubusercontent.com/29373801/64500228-ebb3f680-d2ee-11e9-8a64-724e55295db4.png)

**Comment by peisun1115** [comment]
I do not know what Open3D GUI expects.  The heading we provide is the angle required to rotate +x (vehicle frame) to the surface normal of the front face of the labeled box.

**Comment by nan0755** [comment]
I mistake the order of `length` and `width`. Width is at position 4 and length position 5. 
Thanks a lot!
