### ISSUE TITLE
bug in frame utils?

### ISSUE THREAD

**Issue by tianweiy** [waymo-research/waymo-open-dataset#304]
https://github.com/waymo-research/waymo-open-dataset/blob/a19ba044e0ad42c49e95f09298b491db5d8ed05c/waymo_open_dataset/utils/frame_utils.py#L318

this should be rolling_shutter_direction ?

**Comment by sabeekpradhan** [comment]
Yes, thank you for pointing this out. We will fix soon and update the validation server accordingly. For now, you can act as though that field reads "ROLLING_SHUTTER_DIRECTION" instead.

**Comment by tianweiy** [comment]
@sabeekpradhan thanks! Could you also fix 
#305 otherwise the camera projection module is still not usable

**Comment by sabeekpradhan** [comment]
Yes they will be in the same PR.

**Comment by sabeekpradhan** [comment]
Fixed in https://github.com/waymo-research/waymo-open-dataset/commit/1f7525229e2b2853b94a92ce44a7961cddf9aa71
