### ISSUE TITLE
Latency Evaluation Target Request

### ISSUE THREAD

**Issue by tianweiy** [waymo-research/waymo-open-dataset#305]
Hi, I would like to do an image to global transformation using the image_to_world function. 

However, currently two metadata are missing for the function inputs. Namely, ```camera_trigger_time``` and ```camera_readout_done_time```. Could you add this to the evaluation server?

**Comment by sabeekpradhan** [comment]
Fixed in https://github.com/waymo-research/waymo-open-dataset/commit/1f7525229e2b2853b94a92ce44a7961cddf9aa71
