### ISSUE TITLE
Bounding boxes question

### ISSUE THREAD

**Issue by randcode-generator** [waymo-research/waymo-open-dataset#31]
Hi,
There's a bounding box with a vehicle label but it is behind a garage. How are these bounding boxes determined?

![060](https://user-images.githubusercontent.com/7875165/64504723-03fc2500-d29f-11e9-9566-a6dd5d847b9c.jpg)

**Comment by kevinsu628** [comment]
I have encountered similar cases. Probably there is a car parked in the garage, and the lidar detects them. Would be interested to know if there is a way to get rid of these superpower bboxes.

**Comment by randcode-generator** [comment]
Lidar can detect objects through walls?

**Comment by peisun1115** [comment]
Is this lidar projected box? Can you send me the filename (or context.name) so that I can take a look?

**Comment by randcode-generator** [comment]
name: "10075870402459732738_1060_000_1080_000"

**Comment by peisun1115** [comment]
There is an occluded vehicle in that position. If you can tell that by checking a few frames forward.
![image](https://user-images.githubusercontent.com/18294241/64552943-3cc2eb00-d2ed-11e9-81b7-3ec210fb7bd1.png)

The labelers inferred the object by looking at a few frames later. 

Lidar labels do label objects that are occluded.

I will double check with lablers to see whether this is expected and report back.

**Comment by nan0755** [comment]
Laser CANNOT penetrate walls, hhhhh

**Comment by peisun1115** [comment]
The labelers confirmed that the label is activated a few frames earlier. We will fix that.  Thanks a lot for your feedback

**Comment by peisun1115** [comment]
FYI, we will fix this in the next data release or patch release. I will keep you updated. I am closing this issue for now.
