### ISSUE TITLE
INVALID_ARGUMENT: Not enough scenario predictions in submission : 0

### ISSUE THREAD

**Issue by JackWetherell** [waymo-research/waymo-open-dataset#310]
I have written the following code to produce a submission file from the proto buffer (for the motion prediction challenge):
```
import numpy as np
import pandas as pd
import motion_submission_pb2 as proto

# Create submission
submission = proto.MotionChallengeSubmission()
submission.account_name = ACC_NAME
submission.unique_method_name = METHOD_NAME
submission.authors.extend([NAME])
submission.affiliation = AFFILIATION
submission.description = METHOD_DESC
submission.submission_type = 1
for scenario in range(150):
    ypred = np.load('prediction_validation_{0}.npz'.format(str(scenario)))['arr_0']  # load array of prediction in scenario
    meta = pd.read_csv('meta_validation_{0}.csv'.format(str(scenario))).set_index('Unnamed: 0', drop=True)
    scenario_prediction = proto.ChallengeScenarioPredictions()
    scenario_prediction.scenario_id = str(meta.at[0, 'scenario_id'])[2:-1] # scenario_id string
    for object in range(ypred.shape[0]): # all agents in tracks_to_predict = 1
        prediction = proto.SingleObjectPrediction()
        prediction.object_id = int(meta.at[object, 'object_id']) # object_id int
        scored_trajectory = proto.ScoredTrajectory()
        scored_trajectory.trajectory.center_x.extend(list(ypred[object].x))
        scored_trajectory.trajectory.center_y.extend(list(ypred[object].y))
        prediction.trajectories.append(scored_trajectory)
        scenario_prediction.single_predictions.predictions.append(prediction)
        print('scenario_id =', scenario_prediction.scenario_id, 'object_id =', prediction.object_id)
    submission.scenario_predictions.append(scenario_prediction)

# Save submission
f = open('test.bin', 'wb')
f.write(submission.SerializeToString())
f.close()
```

When I run this it prints the following: Which are the correct ids corresponding to the `tracks_to_predict` field.
```
scenario_id = 171ebeba91be9281 object_id = 2667
scenario_id = 171ebeba91be9281 object_id = 2668
scenario_id = 8d0541613ee8f77e object_id = 4631
scenario_id = 8d0541613ee8f77e object_id = 4658
scenario_id = 8d0541613ee8f77e object_id = 4666
scenario_id = 8d0541613ee8f77e object_id = 4674
scenario_id = 8d0541613ee8f77e object_id = 4675
scenario_id = 8d0541613ee8f77e object_id = 4681
scenario_id = 8d0541613ee8f77e object_id = 4959
scenario_id = 8d0541613ee8f77e object_id = 4960
scenario_id = 247b024fb607873 object_id = 343
scenario_id = 247b024fb607873 object_id = 345
...
```

When I upload the produced submission file to the validation submission it shows:
**INVALID_ARGUMENT: Not enough scenario predictions in submission : 0**
But the submission contains exactly 150 scenario predictions (the number of validation scenarios), each with up to 8 objects in each.

How do I find out what has gone wrong?
How do I change the code so it accepts the submission?
How do I proceed to submit my predictions?

Note: I have a feeling its something to do with scenario_id being a hex string? Maybe it needs to be stored as a special data type.

**Comment by scott-ettinger** [comment]
Hi Jack, 
Thanks for the question.  The issue is actually an error in the front end on our website.  Submissions must be archived into either a .tar or .tgz file before submitting.  The error is that the website currently allows you to upload .bin files.  Unfortunately, when .bin files are submitted, the resulting error message is unhelpful.  Please try submitting a .tgz file.  

We will fix the website issue and update the error message for incorrect formatted data. 

The other issue you will run into is that the server requires predictions for all of the scenarios in the validation or test set (with some small tolerance) or you will receive the same error stating that there are not enough predictions in the submission (150 in the case of your current submission).

**Comment by JackWetherell** [comment]
@scott-ettinger Thank you for you help!

I have compressed the file to a tar.gz file and as you predicted I now get the error: 
***INVALID_ARGUMENT: Not enough scenario predictions in submission : 150**

I have 150 scenario predictions, each with up to 8 objects in each. for a total of 3923 total predictions.

Is this not correct? In the [validation dataset](https://console.cloud.google.com/storage/browser/waymo_open_dataset_motion_v_1_0_0/uncompressed/tf_example/validation?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false ) there are 150 segments. Each of these has only 1 scenario_id according to the [data description](https://waymo.com/open/data/motion/tfexample): "scenario/id   ->   A unique string ID for the scenario represented by this example. shape=[1]" 

I don't understand why the correct number of validation scenarios is not 150. Have I missed something?

Thank you.

**Comment by scott-ettinger** [comment]
The validation set has 150 file shards, but each of those shard files contains many scenarios (they are tfRecord files, perhaps you only read the first Scenario proto in the file?). There should be over 40k scenarios in the submission.

**Comment by JackWetherell** [comment]
Ah yes I see, I was only generating from the iterator once in my loop. Thanks for the help!
