### ISSUE TITLE
How to get 3d labels of a specific LIDAR only ?

### ISSUE THREAD

**Issue by SofianeB-03** [waymo-research/waymo-open-dataset#311]
Hello, thank you for your great work ! The command "frame.laser_labels" give all the labels 3D but I want to get the labels of a specific lidar only (for example the TOP). Is there a way to do this ?

Thank you again

**Comment by peisun1115** [comment]
Hello, you can try to filter by num_points_in_box with some threshold where points are from a specific LiDAR.

**Comment by SofianeB-03** [comment]
@peisun1115 , I will follow your solution, thanks!  Also, do you think that is better to train with one lidar only ?or with all the lidar ?

**Comment by peisun1115** [comment]
It depends on your model. Using all LiDARs can potentially get better results.

**Comment by SofianeB-03** [comment]
@peisun1115 Thank you very much for your help !

**Comment by HuangVictorAuto** [comment]
@SofianeB-03 , did you make it work with num_points_in_box threshold to filter only the 3d boxes for TOP lidar? how did you set the threshold?

The background is,  As the new semantic segmentation data set comes out, but only contain the semantic lables for TOP lidar. I want to train a network with object detection together with semantic segmentation. So I want to only use lidar point and labels from TOP lidar.
