### ISSUE TITLE
How to download the Waymo Open Dataset on Ubuntu 20.04?

### ISSUE THREAD

**Issue by CDahmsSpireon** [waymo-research/waymo-open-dataset#313]
I'm not sure if I should post this here or on Ask Ubuntu so I posted both places.

I'm attempting to download the Waymo Open Dataset on Ubuntu 20.04 and I'm running into one problem after another. First I went here:

https://waymo.com/open/download/

Entered my name, etc., then under "Perception Dataset" I choose chose the v1.2 "individual files" link which leads to:

https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_2_0_individual_files

I've used various cloud services before but I have not used Google Cloud Platform before. I checked all the boxes, then choose "Download":

![Screenshot from 2021-05-21 19-22-51](https://user-images.githubusercontent.com/75345949/119212292-44e49f00-ba6c-11eb-81e2-0bf5575e0466.jpg)

A pop-up box appeared instructing to enter this command:

```
gsutil -m cp -r \
  "gs://waymo_open_dataset_v_1_2_0_individual_files/domain_adaptation/" \
  "gs://waymo_open_dataset_v_1_2_0_individual_files/testing/" \
  "gs://waymo_open_dataset_v_1_2_0_individual_files/training/" \
  "gs://waymo_open_dataset_v_1_2_0_individual_files/validation/" \
  .
```

I ran the command, and got an error "gsutil not recognized", so I did:

`sudo apt-get install gsutil`

Then ran the recommended command again, upon which I got this error:

```
Unknown option: m
No command was given.
Choose one of -b, -d, -e, or -r to do something.
```

After some Googling I found this post:

https://stackoverflow.com/questions/61417140/installing-gcloud-gsutil-on-ubuntu-18

so I did:

```
echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

sudo apt-get update

sudo apt-get install google-cloud-sdk
```

Now when I run the recommended command above I get:

```
$ gsutil -m cp -r \
>   "gs://waymo_open_dataset_v_1_2_0_individual_files/domain_adaptation/" \
>   "gs://waymo_open_dataset_v_1_2_0_individual_files/testing/" \
>   "gs://waymo_open_dataset_v_1_2_0_individual_files/training/" \
>   "gs://waymo_open_dataset_v_1_2_0_individual_files/validation/" \
>   .
ServiceException: 401 Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
CommandException: 1 file/object could not be transferred.
```

This dataset is public so a password or equivalent should not be necessary. Has anybody else using Ubuntu gotten this dataset to download successfully?

**Comment by atyshka** [comment]
You need to be authenticated to a google account to use gsutil, there's a cli you can install that will alow you to save your account credentials locally for gsutil to find

**Comment by CDahmsSpireon** [comment]
Are there instructions for how to do that somewhere?

**Comment by m3ht** [comment]
@CDahmsSpireon https://cloud.google.com/sdk/docs/downloads-snap
I'd also recommend using rsync instead of cp with gsutil.
`gsutil -m rsync -r`

**Comment by cdahms123** [comment]
I worked this out and posted instructions in the answer here https://askubuntu.com/questions/1339873/how-to-download-the-waymo-open-dataset-on-ubuntu-20-04
