### ISSUE TITLE
[2D DETECTION] Docker inference

### ISSUE THREAD

**Issue by dereyly** [waymo-research/waymo-open-dataset#316]
Hello,
As I understand it, you need to add a link to the repository with the docker
```
s = submission_pb2.Submission()
s.docker_image_source='gs://dereyly/waymo/dereyly_yolo_front.tar.gz'
````
I push this  to validation and get some score. But not found any time field in my submittion.
Where find speed of my solution? 
How can i see that my docker is coorrect and I done all correct with uploading docker and premission?

PS: Time limit 70/ms per frame. frame is one imge not all 5?

**Comment by peisun1115** [comment]
I hope you have got this resolved. if not, you can send an email to open-dataset@waymo.com with a link to your submission.
