### ISSUE TITLE
Critical submission error in Docker image

### ISSUE THREAD

**Issue by joonjeon** [waymo-research/waymo-open-dataset#319]
Hi!

I tried to submit the detection result on the validation server,
included with the link of the docker image of the deep network model I have used for detection.
However, the submission result page shows "Critical submission error." upon processing the docker image.
![image](https://user-images.githubusercontent.com/29110031/119808691-57088680-bf1f-11eb-94d6-5f5a1fccb3a1.png)

Any ideas on how to fix this issue?
Is it simply because of runtime error while deploying the deep network model from the docker image?
Or is there something else?

Thanks in advance.

**Comment by peisun1115** [comment]
Can you share your submission link? If you want it to be private, send an email to open-dataset@waymo.com with the link

**Comment by joonjeon** [comment]
Ahh, I have just received an email from a Waymo Dataset manager that diagnosed the issue with this error.
It is simply caused by runtime error in my code submission -.-;;

Thanks anyways.
