### ISSUE TITLE
What is the reason behind the shown annotations?

### ISSUE THREAD

**Issue by mariya12290** [waymo-research/waymo-open-dataset#326]
![Screenshot_20210606_104454](https://user-images.githubusercontent.com/64356491/120918350-522c9b00-c6b4-11eb-931f-04f9bb0c2655.png)
Hello @google-admin 

Could you please tell us what might be the reason for doing this kind of annotations?   In just 20k frames, I found around 20% 25% of ground truths are in this way, where even humans can not see objects especially pedestrians. 

Here is an simple example:
![1001063_front](https://user-images.githubusercontent.com/64356491/120918287-feba4d00-c6b3-11eb-82e0-7d2374e84715.jpg)

**Comment by Birdylx** [comment]
@mariya12290 Hi, I'm not sure if you solved the problem, here is a similar issue [here](https://github.com/waymo-research/waymo-open-dataset/issues/531), actually we can filter these invisible bbox
