### ISSUE TITLE
Building Python 3.7 Pip Package

### ISSUE THREAD

**Issue by fcakyon** [waymo-research/waymo-open-dataset#33]
It is not possible to create a python 3.7 linux pip package by editing the docker file in this page, right? https://github.com/waymo-research/waymo-open-dataset/tree/master/pip_pkg_scripts

I tried adding these commands to dockerfile but did not work:
```
RUN apt install python-pip
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get install python3.7
RUN apt-get install python3.7-dev
```
Getitng error "No module named 'apt_pkg'" while adding ppa:deadsnakes/ppa repository.

I can install python 3.7 with above commands using base ubuntu 16.04 image in a docker, but not with your custom-op-ubuntu image..

**Comment by peisun1115** [comment]
Do you think you can  just execute /bin/bash in the docker and then try these commands?

**Comment by fcakyon** [comment]
I am adding these command to https://github.com/waymo-research/waymo-open-dataset/blob/master/pip_pkg_scripts/build.Dockerfile to be able to build a open_dataset_pip image that has python 3.7 installed in it. Since the docker build fails, i cannot execute /bin/bash in the docker. However, I successfully managed to run these  commands on a base ubuntu 16.04 container.

**Comment by peisun1115** [comment]
I tried add-apt-repository ppa:deadsnakes/ppa and it does show the similar problem. I guess it is because of the underlying python3 version it uses? I did not investigate further. I suggest installing python3.7 by following 

https://tecadmin.net/install-python-3-7-on-ubuntu-linuxmint/

I tried it and it worked for me.

**Comment by fcakyon** [comment]
Thanks for your interest
