### ISSUE TITLE
Global frame and vehicle frame not gravity aligned?

### ISSUE THREAD

**Issue by goktugyildirim** [waymo-research/waymo-open-dataset#330]
I'm trying to extract vehicle pose in the global frame in the '10448102132863604198_472_000_492_000' segment of the validation set. In the first frame, the transformation matrix is:

[-0.9978350774312725, 0.06493675995376035, -0.010410353232911333, -338.6209671922976,
 -0.0650491796022436, -0.9978230673552969, 0.010850368046364483, -31.622667749731843, 
-0.009683102849878996, 0.011504062776872355, 0.9998869406382026, 8.353, 0.0, 0.0, 0.0, 1.0]

roll pitch yaw: 0.011504855938255785 0.009683254174888134 -3.0764944553375244
qx qy qz qw: 0.005026163691669122 -0.005591722403987723 -0.9994429805427587 0.03251459615170183

According to the outputs above, the global frame and vehicle frame are not gravity aligned with each other. Is it an expected result or maybe I'm a failure at any point?

**Comment by peisun1115** [comment]
Is gravity aligned referring to zero roll and pitch? They are not perfectly aligned but i think it should be mostly fine if it is approximated as zeros depending on  the usecase. 0.01 = 0.57 degree
