### ISSUE TITLE
[Question] Weather and time of the day in Motion Dataset

### ISSUE THREAD

**Issue by manolotis** [waymo-research/waymo-open-dataset#337]
I see there is some additional context information, including weather (Sunny/Rain) and time of the day (Day, Dawn/Dusk, or Night) in the perception dataset. I am interested in investigating how weather and time of the day could affect the way road users behave. Is there any way of getting this time and weather information for the scenarios of the motion dataset? Or even better, the exact location (e.g. UTM coordinates) and time of the day for each scenario, and then I could retrieve more detailed weather conditions with third party tools.

Thank you in advance!

**Comment by scott-ettinger** [comment]
HI Manuel,
Thank you for this feature request.  We will keep this request in mind for future work.  Unfortunately, there is not currently any way to get weather and time of day for the motion dataset.
