### ISSUE TITLE
pedestrian id

### ISSUE THREAD

**Issue by Guanwh** [waymo-research/waymo-open-dataset#34]
I have obtained the frames and the 2D coordinates of pedestrians in each frame, but how do I know if the pedestrians appearing in different video frames are the same person?

**Comment by peisun1115** [comment]
We have consistent ped IDs for the same video (e.g. FRONT camera), but we do not associate ped IDs for different videos.

**Comment by peisun1115** [comment]
One way to obtain that ID is to infer from 3d object IDs. It can be an interesting project to work on.

**Comment by Guanwh** [comment]
Thanks for your reply! I just want to obtain ped IDs for the same video. In camera labels,what does this "id" mean? Can't I use it as a pedestrian id?
![微信图片_20190912102835](https://user-images.githubusercontent.com/37922698/64749457-514eef80-d548-11e9-8ff8-a062ab86da02.png)

**Comment by peisun1115** [comment]
yes, you can use that.
