### ISSUE TITLE
how to get BEV evaluation results

### ISSUE THREAD

**Issue by Nightmare-n** [waymo-research/waymo-open-dataset#347]
hi, how can we get the BEV evaluation results on 3D Object Detection? The default results are 3D mAP and 3D mAPH, but we want to get BEV mAP and BEV mAPH.

**Comment by peisun1115** [comment]
We do not support these in the server but you can run the metrics on your own if you want to report them.

**Comment by lloveapple** [comment]
> We do not support these in the server but you can run the metrics on your own if you want to report them.

What command or tool can be used to obtain BEV mAP and BEV mAPH? Thank you

**Comment by lloveapple** [comment]
> We do not support these in the server but you can run the metrics on your own if you want to report them.
@peisun1115 
What command or tool can be used to obtain BEV mAP and BEV mAPH? Thank you
