### ISSUE TITLE
Why the submission about the validation set is not processed after six hours ?

### ISSUE THREAD

**Issue by Will-Hui** [waymo-research/waymo-open-dataset#348]
Dear waymo researcher,

Thanks for your open-dataset!  that's great !!!

when I submit my results about the validation set, a problem has happened!

![image](https://user-images.githubusercontent.com/34529740/124275822-a1f86800-db75-11eb-9b55-66039deab53a.png)

7/2/21 2:56 PM - 7/2/21 8:13 PM 
these results are not processed, but 6/29/21 's result was processed after a few minutes. 

![image](https://user-images.githubusercontent.com/34529740/124273725-f817dc00-db72-11eb-9acc-cc70409bce8b.png)

---
another question， I can't view the status in  6/29/21's result, but on 6/29/21, I already got the results

**Comment by scott-ettinger** [comment]
We had a bug in the front end of the server that was not properly showing results.  Could you check again now to see if it is working again?  Sorry for the trouble.

**Comment by Will-Hui** [comment]
> Thank you for the effort, but it still doesn't work. I resubmitted the result and it was not processed.
> 
> We had an issue in the front end of the server that was not properly showing results. Could you check again now to see if it is working again? Sorry for the trouble.

**Comment by scott-ettinger** [comment]
It appears there is still an issue.  Sorry for the trouble. We will get this fixed as soon as we can.

**Comment by scott-ettinger** [comment]
There is a workaround you may be able to use until the server is fixed. The URL is incorrectly formed for the validation result links.  The test set result links work correctly.  If you have a test set submission you can copy the &emailId=\<your email id\> URL parameter from any test set result link and replace the &email= parameter in your validation links.  

If you don't have a test set submission, you can submit your validation submission to the test server to create a test set link.

**Comment by scott-ettinger** [comment]
The server issue is fixed now.

**Comment by Will-Hui** [comment]
Thanks a lot for the great waymo  !!
> The server issue is fixed now.

**Comment by DongfeiJi** [comment]
> The server issue is fixed now.

I just find this problem，i can not view submission after one hour on val dataset
