### ISSUE TITLE
tfexamples contain UTF-8 data 

### ISSUE THREAD

**Issue by jeremiah-dibble** [waymo-research/waymo-open-dataset#350]
Hi, I was wonder how to open the tfexample.tfrecords. The tutorial is for 'frames' and from previous issues I looked at it was explained that "frames" in the tutorial could be replace by "*.tfrecords" but that gives me the following.

![image](https://user-images.githubusercontent.com/69709124/124673577-eafa3600-de6d-11eb-99fa-6809f640ab52.png)

**Comment by pengbo807** [comment]
Hi, I encountered the same problem. Do you remember how you solved it？

**Comment by peisun1115** [comment]
We will take a look. Very likely, something has changed the default way to parse stuff
