### ISSUE TITLE
Data amount

### ISSUE THREAD

**Issue by voa18105** [waymo-research/waymo-open-dataset#352]
Dear authors, thank you for your dataset and your hard work, I have a little silly question for the data of the motion dataset...

In the description it is stated that there are 100k fragments, 20 seconds each... next they are spitted into 9 sec pieces and packed to tfrs... 
so, finally we download 1000 files from you google cloud (train)...

Sorry, but this is 9.000 secs, instead of 2.000.000 secs that were expected. 
where is the rest? am I missing something?

Thank you in advance for any reply!

**Comment by peisun1115** [comment]
Where have you found this '9 sec'?

**Comment by voa18105** [comment]
> Where have you found this '9 sec'?

Here https://waymo.com/open/data/motion/

**Comment by peisun1115** [comment]
When you said 1000 files, i thought you meant perception dataset.  For motion dataset, i will leave it to Scott to answer

**Comment by scott-ettinger** [comment]
The 100k run segments are windowed into 9 second run segments.  The 1000 training files contain about 500,000 individual 9 second scenarios (each file is a tfRecord file containing many scenarios).  These are available as either tf.Example or Scenario protocol buffers.  The full 20 second scenarios are also provided as scenario protocol buffers only.  Please let me know if you need further information.

**Comment by michaelfeil** [comment]
@voa18105 You could use a code similiar to the one below, to iterate through the scenarios. Each file / Scenario protocol buffer has maybe 500 scenarios.
```python
import ...
from waymo_open_dataset.protos import scenario_pb2
# read Tensorflow Dataset Format
dataset = tf.data.TFRecordDataset(tf_record_filename, compression_type="")
# iterate though the 'Scenario' protocol buffers in the TFRecordDataset
for i, data_one_scenario in enumerate(dataset):
    waymo_scenario = scenario_pb2.Scenario()
    waymo_scenario.ParseFromString(bytearray(data_one_scenario.numpy()))
    print(waymo_scenario.scenario_id)
```

**Comment by voa18105** [comment]
Thank you guys for your reply! 
I was hoping that 100k segments mean 100k scenes, not individual trajectories.
I've downloaded 1000 files, its clear, thank you!
