### ISSUE TITLE
About compute detection metric 

### ISSUE THREAD

**Issue by jjeonda** [waymo-research/waymo-open-dataset#36]
Hi.
I want to evaluate with your code "compute_detection_metrics_main.cc", but have a problem.

I tried to test "Fake" ones on Quick Start guid line (below command) and it worked well.
 > bazel-bin/waymo_open_dataset/metrics/tools/compute_detection_metrics_main waymo_open_dataset/metrics/tools/fake_predictions.bin  waymo_open_dataset/metrics/tools/fake_ground_truths.bin

Now i want to test detection metrics on my own results tested by waymo open datset validation set (TYPE_2D). 
But i confused with results file format. 
I found format is following "waymo::open_dataset::Objects proto." , but feel difficulty on making pd_file and gt_file.

SO, may i asking the example of pd_file or gt_file? 
for example, like, 
"image_name center_x center_y length height score"

Thank you.

**Comment by peisun1115** [comment]
The content of the pd/gt file is a serialized string of a "waymo::open_dataset::Objects proto". 
steps to create such files:
1.create and populate  waymo::open_dataset::Objects proto
waymo::open_dataset::Objects objects;
...
2. write objects.SerializedString() to a file

**Comment by peisun1115** [comment]
I assume this is solved. feel free to re-open if there is still a problem

**Comment by jjeonda** [comment]
Hi, Thanks for your answer.

I did build _waymo::open_dataset::Objects objects_ (with include _protos/metrics.pb.h_ ) 
And after tried to serialize it with function _objects.SerializedString(&ofstream)_ ,but it didn't work.

This is error message.
>>> **error: 'class waymo::open_dataset::Objects' has no member named 'SerializedString'** 
I also tried with SerializeToOstream function, but result was same.
>>> **error: 'class waymo::open_dataset::Objects' has no member named 'SerializeToOStream'**

I really confused with writing serialized gt/pd file. Please help me.
For clear, I attach part of my codes.

namespace waymo{
namespace open_dataset{
namespace {

void tt(float center_x, float center_y, float width, float length, Label::Type type, float score, std::string name)
{
  Objects objects;
  Object* obj = objects.add_objects();
  Label* label = obj->mutable_object();
  label->set_allocated_box(BuildAA2dBox(center_x, center_y, width, length));
  label->set_type(type);
  obj->set_score(score);
  obj->set_context_name(name);
  std::fstream output("test_write", std::ios::out | std::ios::trunc | std::ios::binary);
  if (!objects.SerializeToOStream(&output))
  //if (!objects.SerializedString(&output))
  {
    std::cout << "Failed to write"<< std::endl;
  }
}

} // namespace
} // namespace open_dataset
} // namespace waymo

**Comment by peisun1115** [comment]
Use something like:
`
string output;
objects.SerializeToString(&output);

/// Then write output to a file.
`

**Comment by jjeonda** [comment]
Thank you.
