### ISSUE TITLE
Focal length of the cameras?

### ISSUE THREAD

**Issue by zgojcic** [waymo-research/waymo-open-dataset#361]
Hi, 

thank you for the great dataset. I was wondering if the focal length of the cameras (or the pixel size on the projection plane) is known? 

Thank you,

Zan

**Comment by peisun1115** [comment]
You can check the dataset proto. The intrinsics have these info

**Comment by zgojcic** [comment]
thanks for the quick answer. In the intrinsic matrix, the focal length is only given in pixels, and we would need it in the metric unit (or the size of a pixel such that we can convert it).

**Comment by peisun1115** [comment]
I think you can probably read [this code](https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/camera_model.cc#L479).

**Comment by zgojcic** [comment]
Maybe I am missing something, but f_u and f_v are the focal lengths in u and c direction in pixel unit. I would like to convert f_u to f_x in mm unit. For this, we would need either the pixel size in mm or the FOV of the cameras. I have failed to find either of those in the documentation, this repository or in the code that you have linked. 

Thanks again for your help
