### ISSUE TITLE
How to get lidar data in motion dataset？

### ISSUE THREAD

**Issue by WSTao** [waymo-research/waymo-open-dataset#363]

**Comment by scott-ettinger** [comment]
Unfortunately, lidar data is not provided in the motion dataset.  This is mostly due to size restrictions as the lidar data would be on the order of hundreds of terabytes.

**Comment by WSTao** [comment]
> Unfortunately, lidar data is not provided in the motion dataset. This is mostly due to size restrictions as the lidar data would be on the order of hundreds of terabytes.

Got it, Thanks
