### ISSUE TITLE
The lanes controlled by the stop sign in tf.example

### ISSUE THREAD

**Issue by chrisyrniu** [waymo-research/waymo-open-dataset#366]
Is there a way that we can obtain the controlled lanes of a stop sign in the tf.example motion dataset? Thank you!

**Comment by scott-ettinger** [comment]
Unfortunately, there is not currently a direct way to find the lanes controlled by a stop sign.  Proximity to the stop sign is currently the only way to associate with lanes.

**Comment by chrisyrniu** [comment]
Got it. Thank you!

**Comment by chrisyrniu** [comment]
As an extension to the previous question, is it possible that we can obtain the lanes controlled by a stop sign in the scenario proto segment, and then find the corresponding tf.example segment through ''scenario id'', so that we can know the controlled lanes in the tf.example segment?

**Comment by scott-ettinger** [comment]
The scenario proto does not contain the controlled lane information at this time.  It only contains the locations of stop signs.

**Comment by chrisyrniu** [comment]
The stop sign is defined here: https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/map.proto

Here it contains the information "The IDs of lane features controlled by this stop sign." Does this ID indicate the controlled lane?

**Comment by scott-ettinger** [comment]
Sorry, you are correct.  The lane field in the StopSign message indicates the lane that is controlled by the stop sign.  To answer your previous question, I think you could potentially find the corresponding tf.Example for a given scenario to use the controlled lanes in tf.Example data.

**Comment by chrisyrniu** [comment]
That makes sense. Thank you very much!
