### ISSUE TITLE
waymo open dataset installation

### ISSUE THREAD

**Issue by mirtaheri** [waymo-research/waymo-open-dataset#368]
Installation instruction provided [here](https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md) fails. e.g. `pip3 install waymo-open-dataset-tf-2-3-0 --user`

 I tried it on Windows and Linux with different version of python.

> ERROR: Could not find a version that satisfies the requirement waymo-open-dataset-tf-2-3-0 (from versions: none)
> ERROR: No matching distribution found for waymo-open-dataset-tf-2-3-0

Same in [this colab](https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/r1.0/tutorial/tutorial.ipynb#scrollTo=mIMx62ntDaD_). Is this something temporarily blocked or is there any particular requirements?

Thanks in advance.

**Comment by chihchunhsu-dev** [comment]
Same problem here.

**Comment by chihchunhsu-dev** [comment]
Same problem here. Did you find the solution?

Python version: 3.8.8 
Tensorflow version: 2.6.0

**Comment by mirtaheri** [comment]
> Same problem here. Did you find the solution? Thanks!
> 
> Python version: 3.8.8
> Tensorflow version: 2.6.0
> OS: macOS 10.13.6 High Sierra

I only managed to make things working on Linux (Ubuntu 20.04) and didn't find any solution yet for Windows. To my humble opinion There is no way for Windows.

**Comment by peisun1115** [comment]
tf 2.6 is not yet supported. You can contribute to the repo by adding it to the list or wait a few days. we will add it.

**Comment by peisun1115** [comment]
This is resolve. Now you can install with tf 2.6 https://pypi.org/project/waymo-open-dataset-tf-2-6-0/1.4.1/#files

**Comment by mirtaheri** [comment]
> This is resolved. Now you can install with tf 2.6 https://pypi.org/project/waymo-open-dataset-tf-2-6-0/1.4.1/#files

dear @peisun1115 thank you very much. This solution works only for Linux, right? I tried installation with pip in Windows and got same error as before.

**Comment by peisun1115** [comment]
It only works on linux unfortunately . we have never tried it on windows

**Comment by mirtaheri** [comment]
> It only works on linux unfortunately . we have never tried it on windows

Ok perfect, just wanted that for my information. Thanks again!
