### ISSUE TITLE
how do I get the lidar data ?

### ISSUE THREAD

**Issue by WSTao** [waymo-research/waymo-open-dataset#37]
Hi！
In the tutorial, lidar data does not contain intensity，how to get lidar data with intensity and how to get a display like vehicle-3D-labeling-example,thanks

**Comment by peisun1115** [comment]
The lidar data in the tutorial has intensity. It is in the second channel. 

https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L176

**Comment by WSTao** [comment]
Thanks for your answer!!
