### ISSUE TITLE
Motion dataset v1.1 download issue

### ISSUE THREAD

**Issue by manolotis** [waymo-research/waymo-open-dataset#377]
I am trying to download the latest version of the motion dataset using: 
`gsutil -m cp -r "gs://waymo_open_dataset_motion_v_1_1_0/uncompressed/"  .`
but it does not do absolutely anything, not even return an error. I tested the same command for the previous version:
`gsutil -m cp -r "gs://waymo_open_dataset_motion_v_1_0_0/uncompressed/"  .` 
and the download starts without a problem. Any idea what could be happening?

Thank you in advance!

**Comment by manolotis** [comment]
> Please try this command: gsutil -m cp -r gs://waymo_open_dataset_motion_v_1_1_0/uncompressed .
> 
> I am not sure why your original command works for version 1.0.0 but not for version 1.1.0. I will look into what is going on there.

That does the trick, thanks a lot! Indeed it's strange that with the quotes it works with one version and not the other... but at least now I could start the download

**Comment by DapengFeng** [comment]
use rsync instead of cp
`gsutil -m rsync -i -r gs://waymo_open_dataset_motion_v_1_1_0/uncompressed .`

**Comment by cdahms123** [comment]
That's crazy, I had exactly the same problem as the original poster, and running the command with the quotes removed made it work!

`gsutil -m cp -r gs://waymo_open_dataset_motion_v_1_1_0/uncompressed .`

It's a good thing that whoever set up the motion dataset took care to not include any spaces in any of the directory names or this fix wouldn't work!

I'm using Ubuntu 20.04, and I installed the Google Cloud SDK with this command:

`snap install google-cloud-sdk --classic`

Please fix this asap.

**Comment by ParvezAlam123** [comment]
Not able to download waymo open dataset.

command I entered:
gsutil -m cp -r "gs://waymo_open_dataset_motion_v_1_1_0/uncompressed/" .

error:
Unknown option: m
No command was given.

Choose one of -b, -d, -e, or -r to do something.
Try `/usr/bin/gsutil --help' for more information.
