### ISSUE TITLE
What does the value in the generated depth map mean ?

### ISSUE THREAD

**Issue by Cc-Hy** [waymo-research/waymo-open-dataset#379]
For example, values like 2244, 64266, what's the relation with the actual depth in meters?
![image](https://user-images.githubusercontent.com/82150240/137574255-4f8d68ab-a2bc-4471-a734-6753f53ce3ac.png)
![image](https://user-images.githubusercontent.com/82150240/137574269-8219dfe8-212f-46fd-8edb-b41402c510a3.png)

**Comment by gtangg12** [comment]
Hi, do you mind explaining how you got such high-quality dense depth maps? Thanks in advance!

**Comment by marknabil** [comment]
to get distance (measurements in meters) from depth you will need to follow the formula: 

$$
depth = (baseline * focal_length) / disparity)
$$
focal_ length is in the camera calibration file. 
baseline is the distance between the 2 cameras of stereo setup.
