### ISSUE TITLE
Windows installation guide?

### ISSUE THREAD

**Issue by habdolhay** [waymo-research/waymo-open-dataset#38]
Hi,

Do you guys have any tutorials or guides available for windows installation? I cannot seem to find anything and all pip packages seem to be for linux.

Cheers,
Hamid

**Comment by peisun1115** [comment]
We do not have pre-compiled binary for windows. You can try to compile it on your own and see what problems it come up.

**Comment by habdolhay** [comment]
Thanks for the response. I will give it a try
