### ISSUE TITLE
Getting detailed information regarding the results

### ISSUE THREAD

**Issue by shmpwk** [waymo-research/waymo-open-dataset#386]
Thanks to this commit https://github.com/waymo-research/waymo-open-dataset/commit/052f50fa666b62b4f4f3a441d50be74526866880, we expect to get detailed information regarding the results.

To try this, I specify [`include_details_in_measurements=True`](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/metrics.proto#L128) when setting configutation.
For command line example, I added `config.has_include_details_in_measurements();` in [GetConfig function](  https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L80), built and executed it, but the output was the same.
How can I get the detailed information regarding the results?

**Comment by scott-ettinger** [comment]
Hi Shumpei, 
l think you may need to call config.set_include_details_in_measurements(true);  The has_ function returns whether or not the field is set.

**Comment by shmpwk** [comment]
Thank you, soloved.
