### ISSUE TITLE
Coordinate of speed

### ISSUE THREAD

**Issue by zhby99** [waymo-research/waymo-open-dataset#39]
I noticed that speed_x, speed_y, acc_x and acc_y are labeled under the laser labels for objects, can I know which coordinate are these value in, and for curiosity, I found that some of the speed values are 0, while some are numbers like 1e-15(which is also 0...), how do you get these values and why are them not consistent?

**Comment by peisun1115** [comment]
You can assume that they are in global frame. These numbers are computed by (center_x, center_y, center_z) sequences over time.
