### ISSUE TITLE
Is feature `state/current/vel_yaw` stands for angular velocity?

### ISSUE THREAD

**Issue by nnop** [waymo-research/waymo-open-dataset#390]
Is feature `state/current/vel_yaw` stands for angular velocity (yaw rate)?
Didn't find explanation of this feature anywhere.

**Comment by scott-ettinger** [comment]
The vel_yaw field contains the angle of the agent velocity vector.   There is a description of all fields here : https://waymo.com/open/data/motion/tfexample .
