### ISSUE TITLE
Raw sensor data of Waymo Open Motion Dataset

### ISSUE THREAD

**Issue by jiaxiaosong1002** [waymo-research/waymo-open-dataset#393]
Hi guys, thanks for providing this wonderful dataset!

Recently, I am trying to do some end2end work. I am wondering whether it is possible to align the data in the Motion dataset with the Perception dataset. In other words, for given snippets in the Motion dataset with the scene_ID and object_ID, is it possible to find out the cooresponding raw sensor data like images and lidar?

If the answer is no right now, I am wondering could you please release the correspondence file. Right now, there are barely no good public datasets for end2end learning. (nuScenes has large alignments error between Lidar and its image/HD-map.) I believe it would be very helpful for the community if you guys could release the file.

Thank you for your time.

**Comment by scott-ettinger** [comment]
Hi, 
Thanks for your feedback.  At this time there is not a way to get raw sensor data with the motion dataset.  We will keep this request in mind for future releases.  We do understand that end to end research is an important topic.

**Comment by jiaxiaosong1002** [comment]
Thanks for your reply. Look forwarding to the release!
