### ISSUE TITLE
Ego motion of the dataset

### ISSUE THREAD

**Issue by os1a** [waymo-research/waymo-open-dataset#4]
Hi,

Do you provide the ego-motion of the driving car with respect to some reference point in the world coordinate system?

This can be similar to other datasets like nuScenes and Argoverse.

Thanks in advance

**Comment by peisun1115** [comment]
Yes, each frame comes with a pose. https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L281

That pose defines the transform from vehicle frame to global frame (see our coordinate system definition on the website (https://waymo.com/open/data/).

**Comment by jiaxinxie97** [comment]
Hi,
frame.pose is a Transform object, how can I convert it to an array?

**Comment by jiaxinxie97** [comment]
https://github.com/waymo-research/waymo-open-dataset/blob/60df55a1a968a7ccce6c13a0b560a4af086561a7/waymo_open_dataset/utils/frame_utils.py#L108
Thanks, I find the solution.

**Comment by nnsriram97** [comment]
Is it possible to get ego motions in terms of GPS coordinates? is lat,long,h for ENU coordinate frame of reference available?

**Comment by peisun1115** [comment]
Why do you need that?

**Comment by nnsriram97** [comment]
I would like to use map information from OpenStreetMaps. Hence if I can convert these to GPS coordinates it'll be helpful

**Comment by peisun1115** [comment]
Ah, we do not provide map information yet.  We have plans for map but no ETA for now. Stay tuned.

**Comment by KushalBKusram** [comment]
> Ah, we do not provide map information yet. We have plans for map but no ETA for now. Stay tuned.

As of today, have you added map information to the dataset?

**Comment by peisun1115** [comment]
Not yet. But we do have some work in progress. Stay tuned.

**Comment by KushalBKusram** [comment]
> Not yet. But we do have some work in progress. Stay tuned.

Thank you! I am working on a research project and having GPS coordinates of the frame is quite essential. Could you share an expected timeline? It shall help determine if this information will be available anytime before my deadline. Thanks!

**Comment by peisun1115** [comment]
we do not plan to provide GPS coordinates.

**Comment by KushalBKusram** [comment]
> we do not plan to provide GPS coordinates.

I am sorry but I am not familiar with coordinate systems. But is there any way that I could infer the location of the frame using the pose or information that you plan on adding to the dataset soon? If so, an approximate timeline? Thanks!
