### ISSUE TITLE
ValueError: Message waymo.open_dataset.Objects exceeds maximum protobuf size

### ISSUE THREAD

**Issue by kyrie-H** [waymo-research/waymo-open-dataset#404]
When i generated my predict.bin,  I got this:
ValueError: Message waymo.open_dataset.Objects exceeds maximum protobuf size of 2GB: 2477912500
How can I solve it? thaks!

**Comment by peisun1115** [comment]
you can shard it. https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/create_submission.cc#L51

**Comment by kyrie-H** [comment]
> you can shard it. https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/create_submission.cc#L51

I solve it, thanks. Now I meet another problem, When I submit the model on the validation server, the result is all 0. This is my link 
https://waymo.com/open/challenges/entry/?timestamp=1644206607348676&challenge=DETECTION_3D&emailId=399c9f18-4fbf&submissionType=VALIDATION
Could you give a hand?

**Comment by asd291614761** [comment]
> > 您可以对其进行分片。https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/create_submission.cc#L51
> 
> 我解决了，谢谢。现在我遇到了另一个问题，当我在验证服务器上提交模型时，结果都是 0。这是我的链接 https://waymo.com/open/challenges/entry/?timestamp=1644231382119835&challenge=DETECTION_3D&emailId=399c9f18-4fbf&submissionType=VALIDATION 你能帮忙吗？一个示例数据，就像这样，它的格式是否正确？
> 
> 对象 { box { center_x： -33.12730407714844 center_y： -5.9347944259643555 center_z： 0.8840999007225037 宽度： 0.8434931635856628 长度： 0.830409824848175 高度： 1.8874526023864746 标题： 5.449946880340576 } 类型： TYPE_PEDESTRIAN } 分数： 0.1450897604227066 context_name： “6228701001600487900_720_000_740_000”frame_timestamp_micros：1557196123997354

请问你是怎么解决的切片，作者给的网址已经失效了

**Comment by kaimingkuang** [comment]
> > > 您可以对其进行分片。https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/create_submission.cc#L51
> > 
> > 
> > 我解决了，谢谢。现在我遇到了另一个问题，当我在验证服务器上提交模型时，结果都是 0。这是我的链接 https://waymo.com/open/challenges/entry/?timestamp=1644231382119835&challenge=DETECTION_3D&emailId=399c9f18-4fbf&submissionType=VALIDATION 你能帮忙吗？一个示例数据，就像这样，它的格式是否正确？
> > 对象 { box { center_x： -33.12730407714844 center_y： -5.9347944259643555 center_z： 0.8840999007225037 宽度： 0.8434931635856628 长度： 0.830409824848175 高度： 1.8874526023864746 标题： 5.449946880340576 } 类型： TYPE_PEDESTRIAN } 分数： 0.1450897604227066 context_name： “6228701001600487900_720_000_740_000”frame_timestamp_micros：1557196123997354
> 
> 请问你是怎么解决的切片，作者给的网址已经失效了

https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/metrics/tools/create_submission.cc
