### ISSUE TITLE
[Question] Clarifications about uniqueness of scenario and object IDs 

### ISSUE THREAD

**Issue by manolotis** [waymo-research/waymo-open-dataset#406]
The original motion dataset consists of over 100000 20-second segments, which are additionally split into 9 second segments with a sliding window. I see I can download the 20-second scenario protos for the training data, but I am working directly with the 9-second tfExamples since it's more convenient for my purposes. 

I wanted to verify the uniqueness of the scenario/id and state/id attributes. Checking the 1150 files (training and validation) of the 9-second tfExamples, I see that scenario/id is always unique, and state/id is contains more duplicates than I expected. I have a few questions about that:

1. From the tfExamples, can I somehow determine which 9-second scenarios were extracted from the same 20-second scenario/segment?
2. If two objects have the same ID, does that always mean they originated from the same 20-second segment?
3. (Related to the previous question) If the same object is observed in two consecutive (but different) 20-second segments, would it have the same object ID in the 9-second segments?
4. (Again related to question 2) Could it be that two objects have the same ID and are definitely different objects? (e.g. from 20-second segments recorded at different dates and locations). This could happen if the object ID counter is reset at some point. 

Thank you in advance!

**Comment by scott-ettinger** [comment]
Hi,

1.  There is not an easy way to determine which scenarios come from the same 20 second segment.  This was not an intended use case. Can you tell me the application?  Maybe there is another solution.
 
2. IDs are independently assigned per 20 second scenario.  An object in one scenario with the same ID in another scenario does not necessarily correspond to the same object.  If two 9 second scenarios came from the same 20 second scenario, then the object IDs will correspond within these scenarios.

3. No, IDs are independently assigned per 20 second scenario.

4. If the 9 second scenarios are from different 20 second scenarios, then objects with different IDs will be different objects.

Let me know if you have any further questions.

**Comment by manolotis** [comment]
Hi Scott, 

Thank you for the clarifications, everything is clear now! Given the answers for 2 and 3 I suppose in your answer to 4 you meant "...then objects with _the same_ IDs will be different objects". 

Regarding your question in 1: I'm trying to automate the process of extracting a qualitative description of behaviors present in all segments/scenarios (e.g. an aggressive lane change, a pedestrian crossing at a non-designated crossing, etc.), both to check the frequency of each behavior in the dataset, and for a more thorough evaluation of my prediction models for different situations. For convenience, I am working with the 9-second segments, so I was wondering if I would be able to map the behaviors found in these 9-second segments to their original 20-second segment.

If you are aware of any existing approach for this automatic behavior extraction, or you are allowed to share more details regarding the predicates described in section 3.1 of https://arxiv.org/pdf/2104.10133.pdf, I would be really interested. In a way, I am trying to reverse engineer those predicates that were used for selecting the segments, and additionally classify the behaviors of all other road users.
