### ISSUE TITLE
Waymo Detection Results at other IoU thresholds

### ISSUE THREAD

**Issue by abhi1kumar** [waymo-research/waymo-open-dataset#407]
Waymo detection uses a threshold of 0.7 for vehicles and 0.5 for pedestrians and cyclists for detection evaluation based on the [reply](https://github.com/waymo-research/waymo-open-dataset/issues/192#issuecomment-637849103). However, IoU threshold of 0.7 happens to be a strict metric for vehicles as in the KITTI dataset. Hence, recent papers such as [CaDDN](https://openaccess.thecvf.com/content/CVPR2021/papers/Reading_Categorical_Depth_Distribution_Network_for_Monocular_3D_Object_Detection_CVPR_2021_paper.pdf) (See Table 2) and [PCT](https://arxiv.org/pdf/2108.05793.pdf) (See Table 9) also report their Waymo detection results on 0.5 IoU threshold.

Therefore, I am trying to get the Waymo detection results for foreground categories at 0.5 or any other non-standard IoU threshold. It would be great if you could point me how to do this.

**Comment by peisun1115** [comment]
You can update these (https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L93) if you are using our cmd to compute or update the corresponding config field if you are using the tf op wrapper https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/ops/py_metrics_ops.py#L36

**Comment by abhi1kumar** [comment]
> Update the corresponding config field if you are using the tf op wrapper https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/ops/py_metrics_ops.py#L36

@peisun1115 Thank you for your reply. I am using the tf op wrapper in Python and your solution works perfectly. Here is a truncated output with threshold of 0.5

```bash
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/AP: 0.62
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APH: 0.61
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/Recall@0.95: 0.00
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/AP: 0.06
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APH: 0.06
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/Recall@0.95: 0.00
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/AP: 1.00
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APH: 0.97
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/Recall@0.95: 1.00
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/AP: 0.04
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APH: 0.03
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/Recall@0.95: 0.00
```
I had a related follow-up question. I wanted to know whether these AP numbers are fractional (out of 1) or in percentage (out of 100). In other words, I wanted to know what is the max AP possible? Recent papers such as [CaDDN](https://openaccess.thecvf.com/content/CVPR2021/papers/Reading_Categorical_Depth_Distribution_Network_for_Monocular_3D_Object_Detection_CVPR_2021_paper.pdf) (See Table 2) and [PCT](https://arxiv.org/pdf/2108.05793.pdf) (See Table 9) report their Waymo detection results and have numbers greater than one in their tables. AP numbers greater than one means that they report their AP in percentage. (The object detection community reports the AP percentage numbers on the KITTI dataset).

Therefore, I ran a quick oracle experiment as a sanity check and passed the ground truths as predictions, i.e., I ask the tf wrapper to calculate `AP(ground_truth, ground_truth)`. Then, I get the following truncated output:

```bash
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/AP: 1.00
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APH: 1.00
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/Recall@0.95: 1.00
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/AP: 1.00
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APH: 1.00
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/Recall@0.95: 1.00
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/AP: 1.00
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APH: 1.00
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/Recall@0.95: 1.00
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/AP: 1.00
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APH: 1.00
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/Recall@0.95: 1.00
```

The output of 1.00 shows that the tf wrapper reports the fractional AP numbers. Hence, I wanted to double-check that the AP numbers are fractional, i.e., they are out of 1. And these fractional AP numbers would need multiplication by 100 to convert into AP percentage.

**Comment by peisun1115** [comment]
The tool returns fractional value (i.e. ap \in [0, 1]).

but normally people report fraction value * 100 in papers.

**Comment by abhi1kumar** [comment]
> The tool returns fractional value (i.e. ap \in [0, 1]).

Thank you @peisun1115  for the confirmation. I appreciate your quick reply.
