### ISSUE TITLE
Is there any elegant way to load the data from the tfrecords for tracking

### ISSUE THREAD

**Issue by zhby99** [waymo-research/waymo-open-dataset#41]
As reading all the tfrecords together will make it hard to pick consecutive frames for tracking purpose, I can only decode the tfrecords and then save it in the customized format for tracking. Is there any suggestion on how to extract trajectories of objects(from consecutive frames in same segment) directly from the tfrecord files provided?

**Comment by peisun1115** [comment]
I think it is reasonable to run a job on the data to convert it to something fit your model. For example, a tf SequenceExample or a tf Example with desired number of frames you want for your model if you work with tensorflow.
