### ISSUE TITLE
2021 Challenges website is down

### ISSUE THREAD

**Issue by manolotis** [waymo-research/waymo-open-dataset#410]
I went to check the leaderboard of the [2021 motion prediction challenge](https://waymo.com/intl/en_us/open/challenges/2021/motion-prediction/) and I noticed the page gives an error message: "Something went wrong. Sorry, but the page you were looking for could not be found." Is this on purpose? I wonder, since the page for the 2020 challenges works fine.

**Comment by zoeyyang1** [comment]
Looks like if a specific international version is specified, the website shows the error message. 

not working: https://waymo.com/intl/en_us/open/challenges/2021/motion-prediction/
working: https://waymo.com/open/challenges/2021/motion-prediction/

**Comment by manolotis** [comment]
> Looks like if a specific international version is specified, the website shows the error message.
> 
> not working: https://waymo.com/intl/en_us/open/challenges/2021/motion-prediction/ working: https://waymo.com/open/challenges/2021/motion-prediction/

Interesting... Thanks for the help!
