### ISSUE TITLE
Questions regarding the inference speed for Real-Time 2D Challenge

### ISSUE THREAD

**Issue by pangsu0613** [waymo-research/waymo-open-dataset#412]
Hello! Thank you for building this great dataset and hosted the interesting benchmarks! I have a question regarding the inference speed for the real-time 2D challenge.
As stated on the website, for the Real-Time 2D Challege, methods faster than 70 ms/frame on a Nvidia Tesla V100 GPU will be considered valid. There are 5 cameras on the vehicle, so there will be 5 camera images for each timestep. So, my question is, for the 70 ms/frame, what is the 'frame' referes to for the 2D detection situation, is it 70 ms/image (single camera), or 70 ms/5 images (all 5 cameras at a timestep)? Thank you.

**Comment by tianweiy** [comment]
single camera

**Comment by pangsu0613** [comment]
@tianweiy ,thank you.
