### ISSUE TITLE
Motion dataset and Perception dataset

### ISSUE THREAD

**Issue by Arutoria-Alter** [waymo-research/waymo-open-dataset#413]
Hi, Does the Motion dataset contain the same scene as the Perception dataset? Or is Motion dataset converted by Perception dataset

**Comment by scott-ettinger** [comment]
The motion dataset is separate from the perception dataset. They contain different scenes.  The motion dataset contains approximately 100x more scenes than the perception dataset, but it does not contain raw sensor data (lidar, camera).
