### ISSUE TITLE
Details about the correspondence between 2D and 3D labels.

### ISSUE THREAD

**Issue by jihanyang** [waymo-research/waymo-open-dataset#414]
Hello waymo open dataset team,

Thanks for your nice work. I am interesting to the newly updated `correspondence between 2D and 3D labels` in v1.3. However, I cannot find any details or tutorials for it. Could you please provide more information on it?

Best regards

**Comment by alexgorban** [comment]
Hi Jihan,

the correspondence is stored as part of the [`Label`](https://github.com/waymo-research/waymo-open-dataset/blob/1297cdcbcd103d4befb4b498e50a0c030053e6c0/waymo_open_dataset/label.proto#L22) proto in the [`association`](https://github.com/waymo-research/waymo-open-dataset/blob/1297cdcbcd103d4befb4b498e50a0c030053e6c0/waymo_open_dataset/label.proto#L100) field. It is 2D-to-3D association, so a camera label stores object_id of the corresponding lidar label if the objects were associated.

Here is an example how it is used for finding corresponding 2D and 3D key point labels: [`group_object_labels`](https://github.com/waymo-research/waymo-open-dataset/blob/1297cdcbcd103d4befb4b498e50a0c030053e6c0/waymo_open_dataset/utils/keypoint_data.py#L147) .

Note, that at the moment we have the association information only for camera labels of human type objects (pedestrians, cyclists).

Please feel free to re-open the ticket if you need more info.

Regards,
Alexander

**Comment by jihanyang** [comment]
Thank you so much. Your reply is really helpful!
