### ISSUE TITLE
Motion Tutorial

### ISSUE THREAD

**Issue by mosicr** [waymo-research/waymo-open-dataset#415]
Hi, 
I am trying to run Motion Tutorial. 
https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb#scrollTo=B4XX8FN6qgiq&line=18&uniqifier=1

It fails on:
from waymo_open_dataset.protos import motion_metrics_pb2
with error:
ImportError                               Traceback (most recent call last)
[<ipython-input-86-64a63fb9c1f7>](https://localhost:8080/#) in <module>()
     16 from waymo_open_dataset.metrics.ops import py_metrics_ops
     17 from waymo_open_dataset.metrics.python import config_util_py as config_util
---> 18 from waymo_open_dataset.protos import motion_metrics_pb2
     19 
     20 # Example field definition

ImportError: cannot import name 'motion_metrics_pb2' from 'waymo_open_dataset.protos' (/usr/local/lib/python3.7/dist-packages/waymo_open_dataset/protos/__init__.py)

**Comment by scott-ettinger** [comment]
Have you installed the package with pip3?  It looks like the protocol buffer generated files are missing.  Maybe try re-installing?

**Comment by marcusfechner** [comment]
Hey mosicr, I had the same error and just used a newer version of the waymo-open-dataset Python package than specified in the Colab notebook.

Just replace `!pip3 install waymo-open-dataset-tf-2-1-0==1.2.0` with `!pip3 install waymo-open-dataset-tf-2-6-0` and see if it works for you.

**Comment by mosicr** [comment]
Yes it does work, thanks !!

**Comment by parasmech** [comment]
Hey marcusfechner,
I am facing the same problem. 
I tried  " !pip3 install waymo-open-dataset-tf-2-6-0 "
Still not working

**Comment by harsh-tambi** [comment]
How do I access the tfrecord files? I cannot figure out how to use them? Do I download it from the google bucket thing or use api to access it?
