### ISSUE TITLE
In a tfrecord file, it seems that only a few frames are annotated with the point-wise semantic segmentation label.

### ISSUE THREAD

**Issue by jialeli1** [waymo-research/waymo-open-dataset#419]
Hello.

In a tfrecord file, it seems that a few frames are annotated with the point-wise semantic segmentation label.

I downloaded the Waymo V1.3 and installed the latest waymo-open-dataset-tf-2-6-0 V1.4.3. 

When I was converting the tfrecord files, I found that the decoded semantic segmentation labels were incorrect. So I started checking the provided [tutorial_3d_semseg.ipynb](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_3d_semseg.ipynb), and found the follows.

<details>
<summary>Code</summary>

```python
# some tfrecord files from training_0000.tar
# FILENAME = '/path/tfrecord_training/segment-10212406498497081993_5300_000_5320_000_with_camera_labels.tfrecord'
# FILENAME = '/path/tfrecord_training/segment-10023947602400723454_1120_000_1140_000_with_camera_labels.tfrecord'
FILENAME = '/path/tfrecord_training/segment-1005081002024129653_5313_150_5333_150_with_camera_labels.tfrecord'

dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')

for frame_id, data in enumerate(dataset):
    frame = open_dataset.Frame()
    frame.ParseFromString(bytearray(data.numpy()))
    # break
    if frame.lasers[0].ri_return1.segmentation_label_compressed:
      print("==> frame_id: {},    len(lasers[0].ri_return1.segmentation_label_compressed): {}".format(frame_id, len(frame.lasers[0].ri_return1.segmentation_label_compressed)))  
      break
    else:
      # check the segmentation_label_compressed
      print("==> frame_id: {},    len(lasers[0].ri_return1.segmentation_label_compressed): {}".format(frame_id, len(frame.lasers[0].ri_return1.segmentation_label_compressed))) 
```
</details>

<details>
<summary>Output</summary>

```python
==> frame_id: 0,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 1,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 2,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 3,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 4,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 5,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 6,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 7,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 8,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 9,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 10,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 11,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 12,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 13,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 14,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 15,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 16,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 17,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 18,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 19,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 20,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 21,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 22,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 23,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 24,    len(lasers[0].ri_return1.segmentation_label_compressed): 0
==> frame_id: 25,    len(lasers[0].ri_return1.segmentation_label_compressed): 16641
```
</details>

Even for different tfrecord files, only the last frame has len(lasers[0].ri_return1.segmentation_label_compressed) > 0. Is this normal please?

Discussions by anyone are enthusiastically expected.

**Comment by LinaShanghaitech** [comment]
maybe because of its frame sequences, they only sample several frames to annotate for each video segment?

**Comment by jialeli1** [comment]
Yes, you are right. I checked again and found this. I thought the segmentation labels were annotated the same as the box labels, but it's not.

**Comment by Krupal09** [comment]
I am getting error at the line 

> `if frame.lasers[0].ri_return1.segmentation_label_compressed:'` itself.
I too tried multiple files like you did. Some of them are :

**Comment by LinaShanghaitech** [comment]
> I am getting error `AttributeError: segmentation_label_compressed` at the line
> 
> > `if frame.lasers[0].ri_return1.segmentation_label_compressed:'` itself.
> 
> I tried multiple files from `train` and `test` section. Some of them are as below : `segment-5638240639308158118_4220_000_4240_000_with_camera_labels.tfrecord` `segment-10455472356147194054_1560_000_1580_000_with_camera_labels.tfrecord`.
> 
> Instead of opening a new issue, I am reaching out to you people as I feel you managed to get through this. Thank you in advance !
Do you find this situation in the train section?  I guess the testing section should not have the ground truth for segmentation label.

**Comment by jialeli1** [comment]
> I am getting error `AttributeError: segmentation_label_compressed` at the line
> 
> > `if frame.lasers[0].ri_return1.segmentation_label_compressed:'` itself.
> 
> I tried multiple files from `train` and `test` section. Some of them are as below : `segment-5638240639308158118_4220_000_4240_000_with_camera_labels.tfrecord` `segment-10455472356147194054_1560_000_1580_000_with_camera_labels.tfrecord`.
> 
> Instead of opening a new issue, I am reaching out to you people as I feel you managed to get through this. Thank you in advance !

Kindly remind you that it is necessary to properly install the latest waymo-open-dataset higher than V1.4.3 and download the latest Waymo dataset V1.3.

**Comment by LinaShanghaitech** [comment]
Recently, I check the data structure from proto files, and I also find some details. You can see the code block as follows and  it is extracted from the  `message RangeImage`.
<details>
<summary>waymo_open_dataset/dataset.proto</summary>

```java
 // NOTE:
  // 1. Only TOP LiDAR has segmentation labels.
  // 2. Not every frame has segmentation labels. This field is not set if a
  //    frame is not labeled.
  // 3. There can be points missing segmentation labels within a labeled frame.
  //    Their label are set to TYPE_NOT_LABELED when that happens.
  optional bytes segmentation_label_compressed = 6;
```
</details>
So, it may exactly not set the field for some lidar data.

**Comment by naruarjun** [comment]
Hey @jialeli1, are you able to generate correct pointclouds using waymo-open-dataset-tf-2-6-0==1.4.3? My output is as specified in this issue https://github.com/waymo-research/waymo-open-dataset/issues/439 . Any help will be appreciated.
