### ISSUE TITLE
What is the format of the point cloud from convert_range_image_to_point_cloud?

### ISSUE THREAD

**Issue by MikoyChinese** [waymo-research/waymo-open-dataset#42]
Hi,

This is my first time to use this data, I learn it from [Waymo Open Dataset Tutorial](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb).

But when I want to get the point cloud data such like [x, y, z] or depth_data [distance, ](The distance of each pixel.), I failed to understand.

Here is my some code:

```
def load_dataset(filenames):
    dataset = tf.data.TFRecordDataset(filenames=filenames, 
                                      compression_type='')
    frames = []
    for data in dataset:
        frame = open_dataset.Frame()
        frame.ParseFromString(bytearray(data.numpy()))
        frames.append(frame)
    
    return frames

frames = load_dataset(TF_RECORD_FILE)

# Point Cloud

points, cp_points = frame_utils.convert_range_image_to_point_cloud(
    frames[0], 
    range_images, 
    camera_projections, 
    range_image_top_pose)
```

When I print the point cloud data:
```
print(points[0][0])

# Return
[-36.440834    -0.03664176   3.5856297 ]

print(cp_points[0][0])

# Return
[0 0 0 0 0 0]
```

So can you tell me about the data format of every channel? And If I want to use it such like (x, y, z) or (distance, ), how to do?

**Comment by peisun1115** [comment]
They are documented here: https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/utils/frame_utils.py#L99-L101

points is just x, y, z

Each channel of cp_points is documented here:
https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L181-L200

**Comment by yjcaimeow** [comment]
the page is 404.

**Comment by Petros626** [comment]
> the page is 404.

https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/utils/frame_utils.py
