### ISSUE TITLE
Occupancy Flow Tutorial

### ISSUE THREAD

**Issue by mosicr** [waymo-research/waymo-open-dataset#420]
Hi, 
I am trying to run [Occupancy Flow Tutorial](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_occupancy_flow.ipynb)
On Load one example:
inputs = next(it)
I get:
InvalidArgumentError: Feature: roadgraph_samples/dir (data type: float) is required but could not be found.

--
I copied a single tfrecord file as input ( training.tfrecord-00000-of-01000 )
Obviously there's a mismatch in TFRecordDataset and dataset = dataset.map(occupancy_flow_data.parse_tf_example)
Motion TFRecord Example is defined as:
![image](https://user-images.githubusercontent.com/6726953/159169758-805425a0-5646-4dbf-8ae5-c7ff743e06c5.png)
etc.
While occupancy_flow_data.parse_tf_example) is:
def parse_tf_example(tf_example: tf.Tensor) -> Dict[str, tf.Tensor]:
  """Parses a tf.Example into a dict of tensors."""
  features_description = {
      # Scenario ID.
      'scenario/id':
          tf.io.FixedLenFeature([], tf.string, default_value=None),

      # Roadgraph features.
      'roadgraph_samples/dir':
          tf.io.FixedLenFeature([20000, 3], tf.float32, default_value=None),
      'roadgraph_samples/id':
          tf.io.FixedLenFeature([20000, 1], tf.int64, default_value=None),
      '

-----
Seems like there's nothing in a dataset:
filenames = tf.io.matching_files(TRAIN_FILES)
dataset = tf.data.TFRecordDataset(filenames, compression_type='')
dataset = dataset.range(2)
print(list(dataset))
for element in dataset.as_numpy_iterator():
  print(element)
[<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=1>]
0
1

**Comment by w4ngzI** [comment]
Hello,
Have you fixed the issue? 
InvalidArgumentError: Feature: roadgraph_samples/dir (data type: float) is required but could not be found.

I'm also curious about it and don't know how to solve it.

**Comment by rezama** [comment]
Thanks for reporting the issue.  Can you verify that the paths are ok?

What do you get if you just print the filenames?

```
filenames = tf.io.matching_files(TRAIN_FILES)
print(filenames)

```

**Comment by w4ngzI** [comment]
> Thanks for reporting the issue. Can you verify that the paths are ok?
> 
> What do you get if you just print the filenames?
> 
> ```
> filenames = tf.io.matching_files(TRAIN_FILES)
> print(filenames)
> ```

I also use one single file training.tfrecord-00000-of-01000

The printed result is:
tf.Tensor([b'training.tfrecord-00000-of-01000'], shape=(1,), dtype=string)

**Comment by rezama** [comment]
Why are you using

```
dataset = dataset.range(2)
```

in your code?  That is effectively replacing the tfrecord dataset with a dataset containing {0, 1}.

**Comment by mosicr** [comment]
Hi, 
Thank you for replying. 
filenames = tf.io.matching_files(TRAIN_FILES)
print(filenames)
tf.Tensor([b'/content/training.tfrecord-00000-of-01000'], shape=(1,), dtype=string). 
I only copied a single tfrecord to test,

I removed dataset = dataset.range(2) - it was an unsuccessful attempt to dump a raw TFRecord to see what's in there :-); so the code is back to the original:
filenames = tf.io.matching_files(TRAIN_FILES)
print(filenames)
dataset = tf.data.TFRecordDataset(filenames, compression_type='')
dataset = dataset.repeat()
dataset = dataset.map(occupancy_flow_data.parse_tf_example)
dataset = dataset.batch(16)
it = iter(dataset)

**Comment by rezama** [comment]
What is your platform?
Did you install the package with pip3?

Right after
```
dataset = tf.data.TFRecordDataset(filenames)
```
can you test to see if the file paths are ok?

```
for elem in dataset:
  print(elem)
```

**Comment by w4ngzI** [comment]
When I put 
`for elem in dataset:
  print(elem)`
after 
`dataset = tf.data.TFRecordDataset(filenames)`

The output is string like this:
`3?@B"\x08\xd9\x04:\x1d\x12\x1b\t\xfd\xfa\x8a\xdb\x00\x99\xb2\xc0\x11{Z\xfbPboa@\x19\xd2\xe2|j\xb4\xe2>@P\nZ\x04\x08\x01\x10\x00Z\x04\x08\x03\x10\x00Z\x04\x08\x18\x10\x00Z\x04\x08\'\x10\x00Z\x04\x08\x11\x10\x00Z\x04\x08\x1d\x10\x00Z\x04\x08*\x10\x00Z\x04\x08\x1c\x10\x00', shape=(), dtype=string)`

But if I print elem after
`dataset = dataset.map(occupancy_flow_data.parse_tf_example)`
It will raise the error
`InvalidArgumentError: Feature: roadgraph_samples/dir (data type: float) is required but could not be found.`

**Comment by rezama** [comment]
Can you copy that function to the notebook and try to see if it is failing for all features or specific features?  For example you can comment out the roadgraph features and see if it still fails for you.

https://github.com/waymo-research/waymo-open-dataset/blob/1297cdcbcd103d4befb4b498e50a0c030053e6c0/waymo_open_dataset/utils/occupancy_flow_data.py#L54

**Comment by w4ngzI** [comment]
It fails for all features.

**Comment by mosicr** [comment]
Hi, 
The platform is colab tutorial:
https://colab.research.google.com/github/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_occupancy_flow.ipynb#scrollTo=aHBTtPC_NOtw&uniqifier=1
 
Installed with pip3:
!pip3 install "waymo_open_dataset_tf_2_6_0==1.4.3"

for elem in dataset:
  print(elem)
I got a stream of bytes - similar to w4ngzI above ( would take me a while to reproduce as notebook limits output; I am trying to set it up on command line python now ).  

If roadgraph features are commented out it fails on another feature - for example on scenario_id:

InvalidArgumentError: Feature: scenario/id (data type: string) is required but could not be found.
	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]] [Op:IteratorGetNext]

**Comment by mosicr** [comment]
Hi, 
I tried to reproduce in command line python - now inputs = next(it) fails with different error  ( I am running it on free GCP instance - no GPU / Cuda installed, not sure if that matters as per error below):
102Traceback (most recent call last):
103  File "/home/ranko_mosic/.local/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 761, in __next__
104    return self._next_internal()
105  File "/home/ranko_mosic/.local/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 744, in _next_internal
106    ret = gen_dataset_ops.iterator_get_next(
107  File "/home/ranko_mosic/.local/lib/python3.9/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2728, in iterator_get_next
108    _ops.raise_from_not_ok_status(e, name)
109  File "/home/ranko_mosic/.local/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status
110    six.raise_from(core._status_to_exception(e.code, message), None)
111  File "<string>", line 3, in raise_from
112tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNext]
113
114During handling of the above exception, another exception occurred:
115
116Traceback (most recent call last):
117  File "/home/ranko_mosic/Waymo/waymo-od/waymo_open_dataset/occup.py", line 42, in <module>
118    inputs = next(it)
119  File "/home/ranko_mosic/.local/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 763, in __next__
120    raise StopIteration
121StopIteration
122 >

**Comment by rezama** [comment]
Can you run the motion tutorial?  It reads the same data.

https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_motion.ipynb

**Comment by mosicr** [comment]
The motion tutorial fails with:
AlreadyExistsError                        Traceback (most recent call last)
[<ipython-input-17-656000383340>](https://localhost:8080/#) in <module>()
     86 
     87 
---> 88 class SimpleModel(tf.keras.Model):
     89   """A simple one-layer regressor."""
     90 

33 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/monitoring.py](https://localhost:8080/#) in __init__(self, metric_name, metric_methods, label_length, *args)
    133           self._metric_name, len(self._metric_methods)))
    134 
--> 135     self._metric = self._metric_methods[self._label_length].create(*args)
    136 
    137   def __del__(self):

AlreadyExistsError: Another metric with the same name already exists.

**Comment by mosicr** [comment]
The motion tutorial parsing works:
dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')
data = next(dataset.as_numpy_iterator())
parsed = tf.io.parse_single_example(data, features_description)


It displays animation fine.

It is probably irrelevant to our occupancy flow problem, but it fails further down ( last cell ) with:
---> 88 class SimpleModel(tf.keras.Model):
     89   """A simple one-layer regressor."""
     90 

33 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/monitoring.py](https://localhost:8080/#) in __init__(self, metric_name, metric_methods, label_length, *args)
    133           self._metric_name, len(self._metric_methods)))
    134 
--> 135     self._metric = self._metric_methods[self._label_length].create(*args)
    136 
    137   def __del__(self):

AlreadyExistsError: Another metric with the same name already exists.

**Comment by w4ngzI** [comment]
However, it still fails for me when I run the motion tutorial.
The same error when 
`parsed = tf.io.parse_single_example(data, features_description)`

`---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/tmp/ipykernel_6081/1146449495.py in <module>
      1 dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')
      2 data = next(dataset.as_numpy_iterator())
----> 3 parsed = tf.io.parse_single_example(data, features_description)

~/miniconda3/envs/flow/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py in error_handler(*args, **kwargs)
    151     except Exception as e:
    152       filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153       raise e.with_traceback(filtered_tb) from None
    154     finally:
    155       del filtered_tb

~/miniconda3/envs/flow/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

InvalidArgumentError: Feature: roadgraph_samples/dir (data type: float) is required but could not be found. [Op:ParseExampleV2]`

@[rezama](https://github.com/rezama)
Could you please use pipreqs to provide us with the versions of packages you are using? Maybe it's because the versions of tensorflow, waymo dataset and so on.

**Comment by mosicr** [comment]
> 
I think we're way past that point, but I was able to reproduce in command line / Linux environment; just confirming that files are visible and paths are ok ( 
for elem in dataset:
  print(elem) 

225tf.Tensor(b'\t\x00\x00\x00\x00\x00\x00\x00\x00\t\x07\xb6J\xb08\x9c\xb9?\ty\x92t\xcd\xe4\x9b\xc9?\t\xa3\xaf \xcdX4\xd3?\t^K\xc8\x07=\x9b\xd9?\t\xe2X\
   \x17\xb7\xd1\x00\xe0?\t2\x03\x95\xf1\xef3\xe3?\te6\xc8$#g\xe6?\t\x98i\xfbWV\x9a\xe9?\t\xcb\x9c.\x8b\x89\xcd\xec?\tq\xac\x8b\xdbh\x00\xf0?\t\xd1W\x9\
   0f,\x9a\xf1?\tk\xf1)\x00\xc63\xf3?\t\x05\x8b\xc3\x99_\xcd\xf4?\t\x9e$]3\xf9f\xf6?\t\xff\xcfa\xbe\xbc\x00\xf8?\t_{fI\x80\x9a\xf9?\tj\xd9Z_$4\xfb?\t\\

**Comment by mosicr** [comment]
It is data problem.
It works when I plugged in Motion Tutorial data 
( motion_data_one_example.tfrecord )

 364{'roadgraph_samples/dir': <tf.Tensor: shape=(16, 20000, 3), dtype=float32, numpy=
   365array([[[ 0.4319015 ,  0.9018481 , -0.01145135],
   366        [ 0.43158147,  0.90200126, -0.01145135],
   367        [ 0.43126133,  0.9021544 , -0.01145135],
   368        ...,
   369        [ 0.43742135,  0.8992242 , -0.00763833],
   370        [ 0.43694213,  0.8994572 , -0.00763833],
   371        [ 0.4364628 ,  0.8996899 , -0.00763833]],
   372
   373       [[ 0.4319015 ,  0.9018481 , -0.01145135],
   374        [ 0.43158147,  0.90200126, -0.01145135],
   375        [ 0.43126133,  0.9021544 , -0.01145135],
   376        ...,
   377        [ 0.43742135,  0.8992242 , -0.00763833],
   378        [ 0.43694213,  0.8994572 , -0.00763833],

**Comment by rezama** [comment]
Thanks for sharing the results.  Can you run the motion colab with the same data file (`training.tfrecord-00000-of-01000`)?

**Comment by mosicr** [comment]
The motion notebook fails when run on training.tfrecord-00000-of-01000; same error:
---> 3 parsed = tf.io.parse_single_example(data, features_description)

7 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError: Feature: roadgraph_samples/dir (data type: float) is required but could not be found. [Op:ParseExampleV2]

**Comment by rezama** [comment]
I have no idea why it is failing for you.  I have confirmation that it runs for another user.

What is your platform? (linux/windows/mac)?
What is your tensorflow version?

@scott-ettinger

**Comment by YoushaaMurhij** [comment]
@rezama can you please provide environment description to run this notebook with Tensorflow-gpu?
I have tried multiple versions with no success.

**Comment by mosicr** [comment]
I am trying on two platforms:
- Google Colab  ( Motion Tutorial ):
                        - tf 2.6.0 ( as set by pip3 install "waymo_open_dataset_tf_2_6_0==1.4.3"
                        - python 3.7.13 
                       
- GCP free tier Debian ( Occupancy Flow Tutorial ):
                         - tf 2.6.0
                         - python 3.9.2

**Comment by YoushaaMurhij** [comment]
> I am trying on two platforms:
> 
> * Google Colab  ( Motion Tutorial ):
>   - tf 2.6.0 ( as set by pip3 install "waymo_open_dataset_tf_2_6_0==1.4.3"
>   - python 3.7.13
> * GCP free tier Debian ( Occupancy Flow Tutorial ):
>   - tf 2.6.0
>   - python 3.9.2

Thanks for your replay!
Are you using GPU devices? I can not find a working version of tf-gpu with waymo_open_dataset

**Comment by mosicr** [comment]
CPU only for now ( am planning to use TPU later on ). 
Are you able to make it run on gs://waymo_open_dataset_motion_v_1_1_0/uncompressed/tf_example/training/training_tfexample.tfrecord-00000-of-01000 
I tried both v_1_1_0 and v_1_0_0     - no dice. The only file that gets passed parse step is a sample file (  motion_data_one_example.tfrecord ). 
Even that one fails later on in both Motion and Occupancy Flow Tutorials. 

How do you make it run for CPU - on which dataset exactly ?

**Comment by YoushaaMurhij** [comment]
I am using my local cpu with tf 2.6. No problem so far expect that it is very slow (dataloader & inference)

**Comment by YoushaaMurhij** [comment]
But I do not see a point for using cpu for this dataset

**Comment by rezama** [comment]
Looks like you are opening the file with

`gs://waymo_open_dataset_motion_v_1_1_0/uncompressed/tf_example/training/training_tfexample.tfrecord-00000-of-01000`

I'm not sure if that works since only users who have registered with the Open Dataset can access the file and if you are running this code on a generic colab kernel, the colab kernel cannot access that file.

Can you try first downloading the file and then accessing it?

**Comment by rezama** [comment]
@YoushaaMurhij I'm not familiar with the process for obtaining access to colab kernels with GPU support.  But a google search finds this:

https://colab.sandbox.google.com/notebooks/gpu.ipynb

You can also run a local Jupyter kernel with GPU support.

**Comment by mosicr** [comment]
> Looks like you are opening the file with
> 
> `gs://waymo_open_dataset_motion_v_1_1_0/uncompressed/tf_example/training/training_tfexample.tfrecord-00000-of-01000`
> 
> I'm not sure if that works since only users who have registered with the Open Dataset can access the file and if you are running this code on a generic colab kernel, the colab kernel cannot access that file.
> 
> Can you try first downloading the file and then accessing it?

I do download file first, then try to process it ( I put gs://.. reference just so we know what I am trying ).

**Comment by rezama** [comment]
Can you help me replicate your colab setup?  Are you placing the tfrecord next to the ipynb file on google drive when running the motion tutorial?  What exact path are you using to read the tfrecord file?

**Comment by YoushaaMurhij** [comment]
> Can you help me replicate your colab setup? Are you placing the tfrecord next to the ipynb file on google drive when running the motion tutorial? What exact path are you using to read the tfrecord file?

I am not using colab. I am using local conda env with the requirements that are specified in the notebook (tf 2.6 + waymo_open_dataset_2_6_0 + notebook)

**Comment by rezama** [comment]
Thanks for sharing the info.  You are downloading from the `scenario` directory, which contains the scenario protos. Can you try the `tf_example` directory?

**Comment by mosicr** [comment]
Thank you very much for your effort, Reza, it works.

**Comment by Zachs-Playground** [comment]
> 

I am having the same problem. Can you please tell me what I should do for the scenario folder? I am on a Windows machine. I assume that the tf-example folder is just a small portion of the entire dataset, and the scenario folder contains the entire training data, correct?
