### ISSUE TITLE
Motion dataset tf.Example Format:Mapping cars to lanes

### ISSUE THREAD

**Issue by AcNoggano** [waymo-research/waymo-open-dataset#424]
Hi, two questions: 
1. in the motion dataset, is there an attribute in tf.Example proto that maps the vehicle position to the lane id at each time, similar to traffic_ light_ State/current/id, I can't find this information. I think the id of the lane closest to the vehicle location can be regarded as this
2. There are Lane neighbors and boundaries in the scenario proto (https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/lane_neighbors_and_boundaries.md) , does it also have both information in  tf.Example proto

**Comment by scott-ettinger** [comment]
Hello, 
1. There is not any attribute that associates vehicles with lane centers. You would need to compute this.
2. The lane neighbors and boundaries are currently only available in the scenario format data.  We are considering including this data in the tf.Example format data in future releases.
