### ISSUE TITLE
Build pip package locally using docker

### ISSUE THREAD

**Issue by jacobson15p** [waymo-research/waymo-open-dataset#428]
Hello,

I'm trying to build bazel tests locally on my linux machine running Ubuntu 20.04. I tried using docker with the provided Dockerfile and was able to build the container correctly. However, when I tried to run: 

bazel test waymo_open_dataset/metrics:all

inside the container, I get the following error:
ERROR: error loading package '': cannot load '//tf:workspace_tf2_7_0.bzl': no such file
INFO: Elapsed time: 0.096s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by peisun1115** [comment]
we have not added support for tf2.7 which has upgraded c++ version. You are welcome to add its support if you want.  We may add support for it in the future.

**Comment by jacobson15p** [comment]
Understood, thanks!
