### ISSUE TITLE
Any word about submission

### ISSUE THREAD

**Issue by rttariverdi67** [waymo-research/waymo-open-dataset#429]
Dear @charlesq34, @alexgorban, 
Could you kindly give some general guideline about how to submit results on 3D Semantic Segmentation?
there are some info on tutorial_occupancy_flow.ipynb but I still can't find it clear enough.

looking forward to hear from you,
Bests

**Comment by zoeyyang1** [comment]
Hi @rttariverdi67, there are several improvements to the tutorial_3d_semseg.ipynb tutorial. Were you able to get enough info for your submission?
