### ISSUE TITLE
Examples to read TFRecord files of Waymo open dataset

### ISSUE THREAD

**Issue by RalphMao** [waymo-research/waymo-open-dataset#43]
I could not find any doc or example about reading the data/labels from the downloaded tfrecord file. Any suggestion?

**Comment by randcode-generator** [comment]
https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb

**Comment by RalphMao** [comment]
> https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb

Is /content/waymo-od/tutorial/frames in the same format as tfrecord files of the waymo dataset?

**Comment by randcode-generator** [comment]
Yes. Replace the frames file with a tfrecord file that you downloaded from Waymo and it should still work.

**Comment by peisun1115** [comment]
Thanks for helping the community, Eric. I am closing this issue. Feel free to re-open if you have other problems.
