### ISSUE TITLE
traffic light in tf.example proto and scenario proto

### ISSUE THREAD

**Issue by AcNoggano** [waymo-research/waymo-open-dataset#430]
hi, in #421 , I see that the two formats contain slightly different information，does this mean scenario proto records complete traffic light information? I visualize the first training file **tf_example/training/training_tfexample.tfrecord-00000-of-01000** in the tf.example proto, you can see it [here](https://github.com/AcNoggano/traffic-light/blob/main/1.png)(Small black squares represent traffic lights), but I find only one entrance has traffic light information, in the corresponding Scenario proto file (I can't find it. Is there a way to find the same scene in both formats?), are traffic lights recorded at the remaining entrances？

**Comment by scott-ettinger** [comment]
Hi, 
For context, the data only contains data for traffic signals that were visible by the autonomous vehicle at a given time step.  For this reason, not all traffic signals have state data for all time steps.  

The tf.Example format has the same traffic signal information as the scenario data with one restriction.  The tf.Example data has fixed tensors that are limited to 16 traffic signals.  The scenario data may contain more than 16 in some scenarios. This value was chosen to balance the storage size while including all traffic signals for most examples.

If you want the same scene in both formats, you have to find records with corresponding scenario_id fields. The file shards for the two formats do not correspond to the same scenes.

**Comment by AcNoggano** [comment]
thanks, I got it
