### ISSUE TITLE
Inconsistent `tf.Example Format` description

### ISSUE THREAD

**Issue by ShoufaChen** [waymo-research/waymo-open-dataset#431]
Hi,

As listed in  https://waymo.com/open/data/motion/tfexample, 

roadgraph_samples/type | A unique integer for each combination of map feature type and properties. See the table in the Value Range column. | [num_points, 3] | int64 | [0, 19]. LaneCenter-Freeway = 1, LaneCenter-SurfaceStreet = 2, LaneCenter-BikeLane = 3, RoadLine-BrokenSingleWhite = 6, RoadLine-SolidSingleWhite = 7, RoadLine-SolidDoubleWhite = 8, RoadLine-BrokenSingleYellow = 9, RoadLine-BrokenDoubleYellow = 10, Roadline-SolidSingleYellow = 11, Roadline-SolidDoubleYellow=12, RoadLine-PassingDoubleYellow = 13, RoadEdgeBoundary = 15, RoadEdgeMedian = 16, StopSign = 17, Crosswalk = 18, SpeedBump = 19, other values are unknown types and should not be present.
-- | -- | -- | -- | --
roadgraph_samples/valid | A valid flag for each map sample point | [num_points, 3] | int64 | {0, 1}
roadgraph_samples/id | A unique Integer ID for the vector map feature each sample is from. | [num_points, 3] | int64 | Any 64 bit integer value
 

<br class="Apple-interchange-newline">

the `roadgraph_samples/type`, `roadgraph_samples/valid`, and `roadgraph_samples/id` all have shape `[num_points, 3]`. However, this shape is in fact `[num_points, 1]`.

**Comment by scott-ettinger** [comment]
Thank you.  We will update this information.

**Comment by ShoufaChen** [comment]
Thanks for your clarification @scott-ettinger.

You can feel free to close this issue.

**Comment by scott-ettinger** [comment]
These have been updated.

**Comment by ShoufaChen** [comment]
Thanks.
