### ISSUE TITLE
overlapping window size

### ISSUE THREAD

**Issue by ShoufaChen** [waymo-research/waymo-open-dataset#432]
Hello,

From the webpage, https://waymo.com/intl/en_us/open/data/motion/

> The dataset is composed of 103,354 segments each containing 20 seconds of object tracks at 10Hz and map data for the area covered by the segment. These segments are further broken into 9 second windows (1 second of history and 8 seconds of future data) with **5 second** overlap. 

However, in the Appendix.B of paper [Large Scale Interactive Motion Forecasting for Autonomous Driving :
The WAYMO OPEN MOTION DATASET](https://arxiv.org/pdf/2104.10133.pdf):
> The training set contains 9.1 second windows starting at times {0, 2, 4, 5, 6, 8, 10} seconds within the 20 second scenarios. The validation and testing sets contain 9.1 second windows starting at times {0, 5, 10} seconds

I'd like to know what's the overlapping size for the training split. 5 or 2 seconds.

**Comment by scott-ettinger** [comment]
Hello, 
Thank you for pointing this out.  The information in Appendix B of the paper is correct.  The windows are started at the stated times {0, 2, 4, 5, 6, 8, 10} for the training set.
