### ISSUE TITLE
tensorflow.python.framework.errors_impl.DataLossError

### ISSUE THREAD

**Issue by Xiangxu-0103** [waymo-research/waymo-open-dataset#438]
Hi, when I analytical tfrecords using this tool, it may raise an error `tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 478976069 [Op:IteratorGetNext]` for several tfrecords in `validation_0003`

**Comment by scott-ettinger** [comment]
Can you explain further what you are using?  Which tool and which dataset?

**Comment by Xiangxu-0103** [comment]
It seems to be the problem with my data download. I re-download the data and the problem has been solved.

**Comment by vehxianfish** [comment]
> 

Hi, did you re-download all the data or just part of it? I also had this problem, I searched for the corresponding record and then re-downloaded the tar, but it still reported an error, looking forward to your reply.

**Comment by Anonyme415** [comment]
May I ask if your problem has been resolved? I have also encountered the same issue and look forward to your reply.

**Comment by Anonyme415** [comment]
> > 
> 
> @Xiangxu-0103
> 
> 嗨，您是重新下载了所有数据还是仅重新下载了部分数据？我也有这个问题，我搜索了相应的记录，然后重新下载了tar，但它仍然报错，期待你的回复。
May I ask if your problem has been resolved? I have also encountered the same issue and look forward to your reply.
