### ISSUE TITLE
Pointcloud not generated correctly in waymo-open-dataset-tf-2-6-0

### ISSUE THREAD

**Issue by naruarjun** [waymo-research/waymo-open-dataset#439]
Here is a comparison of the pointcloud generated by waymo-open-dataset-tf-2-1-0 and waymo-open-dataset-tf-2-6-0  
![older-api-pointcloud](https://user-images.githubusercontent.com/25205858/162902673-a20d5137-42f4-4dcd-9d09-681e02d4b1af.png)

![newer-api-pointcloud](https://user-images.githubusercontent.com/25205858/162902728-2d52fd8a-7576-4cfe-8e36-9d4d885da0fc.png)

here is the code used to generate this:
```
import os
import imp
import tensorflow.compat.v1 as tf
#import open3d
import time

tf.enable_eager_execution()
import numpy as np
from waymo_open_dataset.utils import range_image_utils
from waymo_open_dataset.utils import transform_utils
from waymo_open_dataset.utils import frame_utils
from waymo_open_dataset.utils import box_utils
from waymo_open_dataset import dataset_pb2 as open_dataset
#from box_utils import vis3DBBox

FILENAME = '/workspace/data/training_data_waymo/segment-10107710434105775874_760_000_780_000_with_camera_labels.tfrecord'
dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')

for id, data in enumerate(dataset):
    print(id)
    frame = open_dataset.Frame()
    frame.ParseFromString(bytearray(data.numpy()))
    
    (range_images, camera_projections,segmentation_labels, range_image_top_pose) = frame_utils.parse_range_image_and_camera_projection(frame) #remove segmentation_labels when using older API
    points, cp_points = frame_utils.convert_range_image_to_point_cloud(frame, range_images, camera_projections,
                                                                        range_image_top_pose)
    top_lidar_point = np.concatenate(points, axis=0)
    np.save("pointcloud3.npy", top_lidar_point)
    break
```

Could someone tell me what I may be doing wrong in the generation.

**Comment by naruarjun** [comment]
Just read the npy file saved and use open3d to visualize
```
import open3d as o3d
xyz = np.load("pointcloud3.npy")
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(xyz)
o3d.visualization.draw_geometries([pcd])
```

**Comment by naruarjun** [comment]
What is the exact version of waymo-open-dataset-tf-2-6-0 you are using?

**Comment by naruarjun** [comment]
Are you using python3.8?

**Comment by joonjeon** [comment]
[naruarjun](https://github.com/naruarjun),
I just found out that enabling the use of GPU can reproduce this issue, while disabling GPU does not reproduce the issue.
I suppose the GPU implementation of some Tensorflow functions involved in point cloud extraction have changed from versions 2.1 to 2.6, thereby causing the issue.

**Comment by naruarjun** [comment]
Thank you so much @joonjeon, you are a lifesaver!

**Comment by friskit-china** [comment]
Hi everyone, I have the same problem. Downgrading the waymo-open-dataset-tf-2-6-0 to waymo-open-dataset-tf-2-1-0 can solve the problem.
