### ISSUE TITLE
Unable to load file '//tf:workspace_tf2_8_0.bzl': file doesn't exist

### ISSUE THREAD

**Issue by alanxuefei** [waymo-research/waymo-open-dataset#453]
The following errors show in the 'Install from source code' of  https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb

```
Loading: 
ERROR: error loading package '': Unable to load file '//tf:workspace_tf2_8_0.bzl': file doesn't exist
ERROR: error loading package '': Unable to load file '//tf:workspace_tf2_8_0.bzl': file doesn't exist
INFO: Elapsed time: 0.475s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by xiaoxiaoheimei** [comment]
They don't provide the file for TensorFlow 2.8, I walk around this by downgrading my TensorFlow to 2.6.

**Comment by jayhsu0627** [comment]
> They don't provide the file for TensorFlow 2.8, I walk around this by downgrading my TensorFlow to 2.6.

I downgrade by
```
!pip3 install --upgrade tensorflow==2.6
!pip3 show tensorflow
```
