### ISSUE TITLE
Fov-Up and FOV-Down for Range-View LiDAR Projection

### ISSUE THREAD

**Issue by ldkong1205** [waymo-research/waymo-open-dataset#456]
Thank you for your contribution to the AV community.

I am writing a function to project points (x, y, z) to the range-view image (h, w). I use the FOV parameters as fov_up = 10.0 and fov_down = -2.0. But it seems that the projected images are not placed in a suitable view. Could you provide the official fov_up and fov_down for the range-view LiDAR projection? Thanks!

![WechatIMG195](https://user-images.githubusercontent.com/44147391/164217169-b52d09e0-2b74-41a8-89bf-f2bcf8705ab0.jpeg)

**Comment by sxfduter** [comment]
@ldkong1205 have you got right fov for the range-view LiDAR projection?
