### ISSUE TITLE
Are road-edges supposed to be impassable?

### ISSUE THREAD

**Issue by eugenevinitsky** [waymo-research/waymo-open-dataset#459]
Hi, I've made the following visualization of a scene from the dataset where I've colored the objects the protobuf labeled as road edges in green. As you can see, one of the moving agents crosses the road edge along its trajectory (the vehicle in light green). I haven't yet had a chance to visualize the scene from the corresponding perception dataset but I'm curious if there's any way to tell when a road is crossable. 

Thank you for any help you can provide!

https://user-images.githubusercontent.com/7660397/164724270-ea135d70-a8a9-49b1-b5fc-301b0b7b961a.mp4

**Comment by scott-ettinger** [comment]
Hi Eugene, 
Thanks for this question. It is a good point. The road edges are continuous but in some areas there are driveways or entrances to parking lots that unfortunately are not included in the map at this time.  In these areas vehicles may cross the road edges, but there is currently not a way to indicate where this occurs.  We are working on releasing the driveway data in future releases.

**Comment by eugenevinitsky** [comment]
Hi Scott,

Thanks so much! This helps clarify things a lot, we were wondering if we were just making some huge mistake.
