### ISSUE TITLE
some annotation typos in the homepage

### ISSUE THREAD

**Issue by ShoufaChen** [waymo-research/waymo-open-dataset#460]
https://waymo.com/open/data/motion/tfexample

For `traffic_light_state/past/*`, the `num_steps` should be 10 rather than 1.

**Comment by scott-ettinger** [comment]
Thank you for pointing this out!  It looks like the traffic_light_state/future/* may have the incorrect number of steps as well. We will update this.

**Comment by scott-ettinger** [comment]
This has been updated on the website.  Thanks for the feedback.
