### ISSUE TITLE
Possible inconsistency in the camera velocity convention

### ISSUE THREAD

**Issue by zgojcic** [waymo-research/waymo-open-dataset#462]
Hi, 

in the [dataset proto](https://github.com/waymo-research/waymo-open-dataset/blob/520c34a2090460d7498078fa9033e011e28e86b0/waymo_open_dataset/dataset.proto#L285) it is stated that the `velocity` field in `CameraImage` holds the velocity in the global reference frame.

However, in the [camera model](https://github.com/waymo-research/waymo-open-dataset/blob/520c34a2090460d7498078fa9033e011e28e86b0/third_party/camera/camera_model.cc#L297) the velocity is then indeed treated as if it is provided in the global reference frame, but the angular velocity appears to be given in the SDC coordinate system:

```
  const Eigen::Vector3d vehicle_omega_vehicle =
      Eigen::Vector3d{velocity.w_x(), velocity.w_y(), velocity.w_z()};
  const Eigen::Vector3d n_omega_vehicle =
      n_tfm_vehicle0.rotation() * vehicle_omega_vehicle;
```

can we assume that the velocity is given in global coordinate system, but the angular velocitty is in SDC coordinate system? Or is there maybe a bug in the camera model code?

Thank you for your help
Zan

**Comment by hfslyc** [comment]
Hi Zan,

The following line indeed transforms the angular velocity from the vehicle frame to the global reference frame (represented by `n_*`)
```
const Eigen::Vector3d n_omega_vehicle =
      n_tfm_vehicle0.rotation() * vehicle_omega_vehicle;
```
If this does not answer your question, could you clarify more? Thanks!


Best,
Wayne, on behalf of the Waymo Open Dataset Team

**Comment by zgojcic** [comment]
Thank you for the response, Wayne. It does answer my question, but the inconstant description is still there in the proto. In the proto the description says that the "velocities are given in a global reference frame", but in fact it seems that the normal velocity is indeed in global frame but the angular is given in the vehicle frame (and we need to transform it to the global frame as above).

Feel free to decide if this should be updated, I will close the issue for now.

Thank you
Zan
