### ISSUE TITLE
How to read the sync camera labels?

### ISSUE THREAD

**Issue by Cc-Hy** [waymo-research/waymo-open-dataset#465]
Hello, can you please upload a new pip package supporting the latest dataset with sync camera labels?

**Comment by Cc-Hy** [comment]
I also tried to compile by myself, but meet the error:
![image](https://user-images.githubusercontent.com/82150240/164955387-0c430125-48d2-4311-bda5-fa68105b635b.png)

**Comment by ritaiask** [comment]
> 

you can use  `std::min(1.0, std::max(  gt_dot_pd / gt_range / pd_range , 0.0)) `   to replace std::clamp()

**Comment by Cc-Hy** [comment]
> > 
> 
> you can use `std::min(1.0, std::max( gt_dot_pd / gt_range / pd_range , 0.0)) ` to replace std::clamp()

Thank you, but I meet other errors after I fix this one.
I think it is not the way to fix the problem one by one. It should be caused by the different compilation environment.

**Comment by zoeyyang1** [comment]
Please install the latest pip package (pip version 1.4.5), and see if that fixes this issue.

**Comment by alanxuefei** [comment]
please change c++ version to 17
