### ISSUE TITLE
Do I need to donwload all the segments of v1.3.1 if I alread have v1.3.0 ?

### ISSUE THREAD

**Issue by fangjin-cool** [waymo-research/waymo-open-dataset#467]
If I already have dataset v1.3.0 (about 1TB), do I need to download the whole dataset v1.3.1 to participate in the camera-only detection challenge?  I know that the test split is new, but the information shows "This version includes a new test set with 80 segments and additional fields for training and validation", it seems that the annotation information for training and validation is updated but the data (images and LiDAR frames) is unchanged.

If so, would you provide the updated part of the dataset instead of the whole dataset? If only the annotation information is updated in every version, perhaps it will be better to only provide the new labels.

**Comment by xyaochen** [comment]
same question

**Comment by fangjin-cool** [comment]
> same question

I was told that Waymo does not support downloading only the new labels without the sensor data. So we have to download all the segments.
