### ISSUE TITLE
Waymo detetction metrics attribute errro

### ISSUE THREAD

**Issue by menayl123** [waymo-research/waymo-open-dataset#468]
I want to use the detetction metrics from the waymo package. I have installed package using pip install Waymo open dataset. But I am getting following error. 

ap, ap_ha, pr, pr_ha, _ = py_metrics_ops.detection_metrics(
  File "/usr/local/lib/python3.8/dist-packages/waymo_open_dataset/metrics/ops/py_metrics_ops.py", line 43, in detection_metrics
    return metrics_module.detection_metrics(
AttributeError: module '012ff3e36e3c24aefc4a3a7b68a03fedd1e7a7e1' has no attribute 'detection_metrics'

I am using TF 2.6. Looking forward to possible solution.

**Comment by zhiqi-li** [comment]
I also got the same error.

**Comment by hfslyc** [comment]
Hi,

This issue should be addressed now with pip 1.4.6. Please let us know if there is more issue.

Thanks,
Wayne, on behalf of the Waymo Open Dataset team.
