### ISSUE TITLE
Large speed fluctuations

### ISSUE THREAD

**Issue by eugenevinitsky** [waymo-research/waymo-open-dataset#474]
Hello,

I've been doing some processing of the velocity x and y components for the motion dataset. For a given vehicle between 0.1 second time-steps the norm of the velocity vector can vary by more than 2 which seems like a lot and seems like it would correspond to a non-physical acceleration. Is this probably labeling noise or is it some other source? I definitely understand that some preprocessing of the data is probably needed but in case you have any ideas for how to understand this we really appreciate any help.

Thanks!

**Comment by scott-ettinger** [comment]
Could you send me a particular example?  My guess is that it is due to changes in the object dimensions due to occlusion.

**Comment by eugenevinitsky** [comment]
Yeah let me hunt it down, what's the easiest way to describe it to you? I can tell you that it's the 75th object in the first shard in tfrecord-00300-of-01000 at 4 time-steps in at position (-7096.321, 12572.3710) where the speed transitions from [-0.595703125, -0.01953125]  to [-.5810546875, .80078125]. That particular trajectory has a lot of fluctuations like that. If that's not helping for finding it let me know, I can also send you a parsed json version of it.

Thank you so much for your help!

**Comment by scott-ettinger** [comment]
I'll see if I can find that object and visualize what is going on.

**Comment by scott-ettinger** [comment]
I forgot to ask, for the file you referenced, is it the scenario format or the tf.Example format?

**Comment by eugenevinitsky** [comment]
It is the scenario format! I've also provided a quick visualization in case it is helpful. Still working on getting the appropriate vehicle colored so that you can see which one it is but I figured better to send over something than nothing

https://user-images.githubusercontent.com/7660397/166510373-4c6b8a13-fbd2-48d2-b227-532433fa146c.mp4

:

**Comment by eugenevinitsky** [comment]
Thank you so much! It is from the training set. Let me know if there's anything in particular that might be helpful, otherwise I'll just work on getting the visualization above with a tracker on the appropriate agent.

**Comment by scott-ettinger** [comment]
Do you have the object ID of the track you are looking at?

**Comment by eugenevinitsky** [comment]
Sorry, would you mind clarifying what an object ID is?

**Comment by scott-ettinger** [comment]
Sure, I mean the id field in the track object you are looking at in the scenario proto (i.e. scenario.tracks[index].id) .

**Comment by eugenevinitsky** [comment]
I believe it's 5121

**Comment by eugenevinitsky** [comment]
I think it's 5028

**Comment by scott-ettinger** [comment]
I took a look at the visualization of the scene.  The object is a pedestrian that is partially occluded behind a row of parked cars.  The changes in velocity are due to noise in the perception measurements of the object.  This can happen in cases where the object is occluded or is far from the autonomous vehicle where laser measurements are sparse.  Attached is a visualization of the scene. The orange arrow points to the object in question.  The visualizations is provided here under the Waymo Dataset License Agreement for Non-Commercial Use.
![example_image](https://user-images.githubusercontent.com/82909755/166523576-58a3b8ca-17ef-4a1b-9743-f2ef2d92d9ae.png)

**Comment by eugenevinitsky** [comment]
Wow, thank you so much for going above and beyond to help us. This clarifies a lot.
