### ISSUE TITLE
Compiling errors.

### ISSUE THREAD

**Issue by Cc-Hy** [waymo-research/waymo-open-dataset#476]
Hello, when I'm using bazel to compile the files, I always meet errors like this:
![image](https://user-images.githubusercontent.com/82150240/165950180-2f79681b-d80e-4064-83c2-8fbb60abae85.png)
![image](https://user-images.githubusercontent.com/82150240/165950303-6d329588-91d5-41a9-9469-f9d51b2d15ed.png)
How can I fix it?

**Comment by alexgorban** [comment]
Hi, sorry for the long overdue response. It looks like it could be related to missing a declaration for the int64 type.
This specific issue was fixed in #071b5add2d0d8. I'm closing this issue for now, but please feel free to reopen if syncing with the master branch didn't fixed this error.
