### ISSUE TITLE
[motion predict] About Metrics

### ISSUE THREAD

**Issue by ares89** [waymo-research/waymo-open-dataset#478]
Hi,
About metrics, this page [Motion Prediction](https://waymo.com/open/challenges/2022/motion-prediction/) says:

> All metrics described below are computed by first bucketing all objects into object type. The metrics are then computed per type. The metrics for each object type (ADE, FDE, Miss Rate, Overlap rate, and mAP) are all computed at 3, 5, and 8 second timestamps. 

does it means, the result we submitted has 16 position samples each corresponding to the future 8 seconds sampled at 2 Hz, but only the (x,y)s at 3,5,8 second timestamps are used in the metrics, the left 13 (x,y) values are ignored?

**Comment by scott-ettinger** [comment]
Hi, 
The minADE and overlap metrics use all 16 of the prediction points.   Both of these metrics are computed separately using all of the data points up to 3, 5, and 8 seconds.  The FDE, miss rate, and mAP metrics only use the points at the 3, 5, and 8 second time steps.  Please let me know if you have further questions.
