### ISSUE TITLE
It seems that Python API does not support to calculate LET-3D-APL.

### ISSUE THREAD

**Issue by zhiqi-li** [waymo-research/waymo-open-dataset#480]
Can I only use the compiled `compute_detection_let_metrics_main` to get the LET-3D-APL for camera-only 3D detection? It seems this Python API [py_metrics_ops.detection_metrics](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/ops/py_metrics_ops.py#L27) can only calculate LET-3D-AP and LET-3D-APH.

**Comment by hfslyc** [comment]
Hi, we are currently working on that update. For now, please use the provided tool.
