### ISSUE TITLE
Motion dataset - lane center division

### ISSUE THREAD

**Issue by rdbch** [waymo-research/waymo-open-dataset#481]
Hi, 

In am working in the context of the motion prediction task, and I have a question regarding how lane centers are divided. In some cases, what would appear to be a continous lane, is split in half. Please see the picture below with cases A1 and A2 highlighted as positive samples (each road center has a different color). Could you please share if there is any reason/heuristic that applies to such cases?

![image](https://user-images.githubusercontent.com/24796252/167269986-f06653b1-10c4-4106-aecf-693ed40c1825.png)

**Comment by rdbch** [comment]
Yes, for the provided sample, what could be a longer straight "LaneCenter" (plotted with dot-dash lines) is sometimes divided into 2 smaller segments. 

![image](https://user-images.githubusercontent.com/24796252/167500939-55393dd4-3bac-4914-aa95-0783af01fbd8.png)

**Comment by scott-ettinger** [comment]
Hi, this is a valid question. In some cases, lane segments must change to a new map feature if the speed limit changes.  In other cases, however, map features can be arbitrarily split as lanes do not have a well defined start and end point.  Sorry I don't have a better answer for you.  Does this cause an issue for your application?  If so, let me know and we can try to find a workaround.

**Comment by rdbch** [comment]
No, it does not cause any issues, I just did not know if I was missing something. Your answer clarified this for me. Thank you very much. 

However, do you know if this issue will be addressed in the feature (i.e make the LaneCenter division more predictible)?

**Comment by scott-ettinger** [comment]
Thanks for the feedback on this. We will consider consolidating lanes that do not have any property changes for future releases.

**Comment by rdbch** [comment]
Thank you.
