### ISSUE TITLE
range_image_flow_compressed seems to be empty

### ISSUE THREAD

**Issue by turboxin** [waymo-research/waymo-open-dataset#482]
range_image_flow_compressed field seems to be empty in v1.3.0 dataset，is that right？Is it provided in other version of WOD dataset? 
Thanks a lot!

https://github.com/waymo-research/waymo-open-dataset/blob/071b5add2d0d809be2f18cec7922147c48c2efdf/waymo_open_dataset/dataset.proto#L245

**Comment by hfslyc** [comment]
For future reference, the scene flow data is provided in a separate [bucket](https://console.cloud.google.com/storage/browser/waymo_open_dataset_scene_flow).
