### ISSUE TITLE
what is new fields added in v1.3.2 for camera-only-challege?

### ISSUE THREAD

**Issue by xyaochen** [waymo-research/waymo-open-dataset#483]
What are the differences between v1.3.2 and v1.3.1 for camera-only-challenge?
Do I need to download all v1.3.2 to participate camera-only-challenge?

**Comment by hfslyc** [comment]
For 1.3.2, we add a new field [num_top_lidar_points_in_box](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/label.proto#L89) so that users can filter out occluded boxes more accurately during training.

Best,
Wayne, on behalf of the Waymo Open Dataset team
