### ISSUE TITLE
Laser keypoints are empty

### ISSUE THREAD

**Issue by gfgy786** [waymo-research/waymo-open-dataset#488]
Hello, 

I want to use the human keypoints annotations of this wonderful dataset. I played with the tutorial_keypoints.ipynb and tried to load different training tfrecord files of dataset V1.3.0, however, I canot find any lables about laser keypoints. So, I'm wondering whether the laser keypoints only appear on some specific sequence? Or I loaded the label incorrectly?

Thanks in advance!

Here is my code to get label:
```
import tensorflow as tf

dataset = tf.data.TFRecordDataset(frame_path, compression_type='')
for data in dataset:
  frame = dataset_pb2.Frame()
  frame.ParseFromString(bytearray(data.numpy()))
  break

labels = keypoint_data.group_object_labels(frame)
print(labels)
```

Here is a piece of sample output:
```
'-jVlA9prN22MmriJjSr34Q': ObjectLabel(laser=LaserLabel(object_type=2, box=center_x: -66.10604325782333
center_y: -6.65979958061871
center_z: 1.3565303728270521
width: 0.8678895761445033
length: 0.9078659635753055
height: 1.7159014649426219
heading: -0.022219865456174492
, keypoints=), camera=None),
```

**Comment by alexgorban** [comment]
Hi, thanks for your interest to the dataset!

Yes, both laser and camera keypoints are published only for some objects on some frames. There are ~10K object/frames with laser keypoints and ~200K object/frames with camera keypoints.

Please use the v1.3.2 - it has fixes for issues with SIDE_RIGHT cameras (see #458 for details)
