### ISSUE TITLE
train the dataset from v1.3.1 or v1.3.0 and get the 2D segmentation results

### ISSUE THREAD

**Issue by WEIYI2021** [waymo-research/waymo-open-dataset#489]
How can I use my downloaded v.1.3.1 or v1.3.0 dataset for training process and then get the 2D segmentation results ?

**Comment by zoeyyang1** [comment]
Currently the Waymo Open Dataset does not contain any 2D segmentation labels, but if you are looking for 3D segmentation  tutorial, you can find it here: https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_3d_semseg.ipynb
