### ISSUE TITLE
 module 'tensorflow' has no attribute 'unsorted_segment_max'

### ISSUE THREAD

**Issue by Xiangwang-Hu** [waymo-research/waymo-open-dataset#49]
This error comes from ' from waymo_open_dataset.utils import range_image_utils'
The version of tensorflow is 2.0.0
Full error message:
Traceback (most recent call last):
  File "waymo_data_preprocess.py", line 12, in <module>
    from waymo_open_dataset.utils import range_image_utils
  File "/home/shawn/.local/lib/python3.6/site-packages/waymo_open_dataset/utils/range_image_utils.py", line 59, in <module>
    pool_method=tf.unsorted_segment_max):
AttributeError: module 'tensorflow' has no attribute 'unsorted_segment_max'

Hope anyone can help. Thank you

**Comment by peisun1115** [comment]
This is because of tf 2.0. 

We have not updated the default tf version to 2.0 in 1.0.1 pip packages. The code has been updated in https://github.com/waymo-research/waymo-open-dataset/tree/r1.0-tf2.0

Try  this package built from that branch: https://pypi.org/project/waymo-od-tf2-0/

**Comment by Xiangwang-Hu** [comment]
@peisun1115 Thanks a lot for that. Your advice solve my problem.

**Comment by atyshka** [comment]
Can the Colab notebook be updated for this?
