### ISSUE TITLE
World coordinate is not really the case.

### ISSUE THREAD

**Issue by Akamel01** [waymo-research/waymo-open-dataset#490]
Hi. Thanks for the opportunity to work with a processed AVs data. 

When the trajectories are plotted using the "world coordinates" - as defined in the description - I realized that not all files share the same origin. Kindly check the snaps below to see how the trajectories from different files don't share the same origin (because of the unreasonable overlap).

Is there a plan in the near future to publish trajectories with the same global world coordinates with the same origin? 

Am I missing something resulted in having this issue? 

Thanks,
AK

![image](https://user-images.githubusercontent.com/100009525/168940801-4935f4e6-1103-43c2-8b1a-e1cb3c93f9ac.png)
![image](https://user-images.githubusercontent.com/100009525/168940913-3b64c39b-5f39-4b80-826c-c84d7fcf770b.png)

**Comment by scott-ettinger** [comment]
Hi, 
You are correct that each scenario has a separate coordinate frame origin.  The global coordinates are not consistent across scenarios. We are not able to release large areas of continuous map data at this time.  Part of the reason for this is that scenarios come from different cities that are far apart and a single Z-up coordinate system cannot consistently represent all scenarios together.  Could you let me know how this limits your application?

**Comment by Akamel01** [comment]
Thanks for confirming it. 
I am a roadway safety researcher at UBC and we are developing a network-level safety analysis framework. Typically we prove our hypothesis based on simulated vehicle-vehicle interactions. However, with such AVs dataset, we can produce novel work for adopting real-world data to verify the hypothesis practically and show the potential application as well. We cited Lyft dataset as it was the basis for our previous novel work (currently under revision). Although, Waymo dataset has much bigger potential for its geo-spatial coverage.

Please let me know if you are planning to reveal the data with a unified origin. 

Thanks

**Comment by scott-ettinger** [comment]
We do not have plans to release this kind of data at this time. I think we would need to break the dataset up into regions that can be approximated by a plane.  We will consider this based on user feedback.

**Comment by miladsasha** [comment]
the origin of scenarios are not consistent, however, I wonder if it is possible to locate the segment of each scenario in the world?
I mean I want to find the location of each segment however, I don't have the global coordinates. is there any function to extract that?
