### ISSUE TITLE
Issues with Monocular 3D Object Detection Leaderboard Submission

### ISSUE THREAD

**Issue by towardsautonomy** [waymo-research/waymo-open-dataset#491]
Hello,

I am trying to submit results to the monocular 3d object detection leaderboard test server, however, I received all zeros within the metrics table. The exact same method worked with validation submission and I received reasonable performance metrics.

The only changes between the two submissions were:
1. For validation submission, I set `object.num_lidar_points_in_box=100`, because I wanted to be able to do local evaluation as well. I do not think it is necessary for test submission?
2. For test submission, I set `metrics_pb2.Object().camera_name` to correspond to the camera sensor that the image came from.

Could the above two have caused the said issue? I do not want to lose another opportunity (we only get 3 attempts) trying out these changes, so if someone could help me out here it would be really appreciated.

Thanks,
Shubham

**Comment by wangbo-zhao** [comment]
Hello. When did you submit and get the results? I submitted it yesterday but I still do not get any results.

**Comment by towardsautonomy** [comment]
> 

You should get the results back within minutes. Unfortunately they don’t show you the error messages (at least I have not seen one) if the submission file has issues.

**Comment by hfslyc** [comment]
Hi,

Could you share the code on how to generate your submission? In the mean time, I'm checking your submission. The points you mentioned shouldn't affect the evaluation.

**Comment by Cc-Hy** [comment]
> Hi,
> 
> Could you share the code on how to generate your submission? In the mean time, I'm checking your submission. The points you mentioned shouldn't affect the evaluation.

@hfslyc

Hello, for the camera-only 3d task, it doesn't matter if I don't modify the "id" field in the submission file because I don't do the tracking task, is that right?

**Comment by towardsautonomy** [comment]
> Hi,
> 
> Could you share the code on how to generate your submission? In the mean time, I'm checking your submission. The points you mentioned shouldn't affect the evaluation.

Hi @hfslyc, here is the snippet I am using to save predictions to a `.bin` file. Following which, I use `bazel-bin/waymo_open_dataset/metrics/tools/create_submission` to create the submission and submit the `gunzipped` version to Waymo server.
 
```python

import sys
import os

import glob
from PIL import Image
from io import BytesIO
from src.models import *
from src.utils import *
import matplotlib.pyplot as plt
from matplotlib import patches

try:
    from waymo_open_dataset import dataset_pb2
    from waymo_open_dataset.protos import metrics_pb2
    from waymo_open_dataset import label_pb2
    from waymo_open_dataset.protos import metrics_pb2
    from waymo_open_dataset.protos import submission_pb2


except ImportError:
    raise ImportError(
        'Please run "pip install waymo-open-dataset-tf-2-6-0 --user" '
        'to install the official devkit first.')

from glob import glob
import numpy as np
import tensorflow as tf

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' # FATAL

# 3x3 Rotation matrix to euler angles
def rotationMatrixToEulerAngles(R):
    sy = math.sqrt(R[0,0] * R[0,0] +  R[1,0] * R[1,0])
    singular = sy < 1e-6
    if  not singular :
        x = math.atan2(R[2,1] , R[2,2])
        y = math.atan2(-R[2,0], sy)
        z = math.atan2(R[1,0], R[0,0])
    else :
        x = math.atan2(-R[1,2], R[1,1])
        y = math.atan2(-R[2,0], sy)
        z = 0
    return np.array([x, y, z])

class WaymoDataset(object):
    def __init__(self,
                 load_dir,
                 workers=4,):
        self.load_dir = load_dir
        self.workers = workers
        self.filter_empty_3dboxes = True
        self.filter_no_label_zone_points = True

        self.selected_waymo_classes = ['VEHICLE', 'PEDESTRIAN', 'CYCLIST']
        self.selected_waymo_locations = None
        self.save_track_id = False

        # turn on eager execution for older tensorflow versions
        if int(tf.__version__.split('.')[0]) < 2:
            tf.enable_eager_execution()

        self.lidar_list = [
            '_FRONT', '_FRONT_RIGHT', '_FRONT_LEFT', '_SIDE_RIGHT',
            '_SIDE_LEFT'
        ]
        self.type_list = [
            'UNKNOWN', 'VEHICLE', 'PEDESTRIAN', 'SIGN', 'CYCLIST'
        ]
        self.camera_id_to_name = {
            1: 'FRONT',
            2: 'FRONT_LEFT',
            3: 'FRONT_RIGHT',
            4: 'SIDE_LEFT',
            5: 'SIDE_RIGHT'
        }
        self.camera_name_to_id = {
            'FRONT': 1,
            'FRONT_LEFT': 2,
            'FRONT_RIGHT': 3,
            'SIDE_LEFT': 4,
            'SIDE_RIGHT': 5
        }

        self.k2w_cls_map = {
            'Car': label_pb2.Label.TYPE_VEHICLE,
            'Pedestrian': label_pb2.Label.TYPE_PEDESTRIAN,
            'Sign': label_pb2.Label.TYPE_SIGN,
            'Cyclist': label_pb2.Label.TYPE_CYCLIST,
        }

        self.T_ref_to_front_cam = np.array([[0.0, 0.0, 1.0, 0.0],
                                            [-1.0, 0.0, 0.0, 0.0],
                                            [0.0, -1.0, 0.0, 0.0],
                                            [0.0, 0.0, 0.0, 1.0]])

        self.load_dir = load_dir

        self.tfrecord_pathnames = sorted(
            glob(os.path.join(self.load_dir, '*.tfrecord')))

        self.cur_dataset_idx = 0
        self.cur_frame_index = 0
        self.n_frames_this_frame = -1

    def get_dataset(self, dataset_idx):
        pathname = self.tfrecord_pathnames[dataset_idx]
        dataset = tf.data.TFRecordDataset(pathname, compression_type='', num_parallel_reads=self.workers)
        return dataset

    def get_next_frame(self,):
        """Get frame from dataset."""
        n_datasets = len(self.tfrecord_pathnames)
        if self.n_frames_this_frame != -1 and \
           self.cur_frame_index >= self.n_frames_this_frame:
            self.cur_dataset_idx += 1
            self.cur_frame_index = 0
        if self.cur_dataset_idx >= n_datasets:
            print('No more data in the dataset.')
            return None
        if self.cur_frame_index == 0:
            print('Loading Dataset: {}/{}'.format(self.cur_dataset_idx+1, n_datasets))
            self.dataset = self.get_dataset(self.cur_dataset_idx)
            self.n_frames_this_frame = len(list(self.dataset.as_numpy_iterator()))

        for i, data in enumerate(self.dataset):
            if i == self.cur_frame_index:
                frame = dataset_pb2.Frame()
                frame.ParseFromString(bytearray(data.numpy()))
                self.cur_frame_index += 1
                return frame

# main function
if __name__ == "__main__":
    
    # parse arguments                
    args = parse_args()
    
    # define model
    model = ObjectDetector( args )

    # load weights
    model = load_pretrained_weights(model, args)

    # load dataset
    dataset = WaymoDataset(load_dir=args.dataroot)
    out_dir = os.path.join('results', args.exp_id)
    if not os.path.exists(out_dir):
        os.makedirs(out_dir)

    print('Number of tfrecords: {}'.format(len(dataset.tfrecord_pathnames)))
    
    global_frame_counter = 1
    gt_objects = metrics_pb2.Objects()
    prediction_objects = metrics_pb2.Objects()
    frame = dataset.get_next_frame()
    while frame is not None:
        print('Dataset: {} | Frame: {} | Global Frame: {}'.format(
            dataset.cur_dataset_idx+1, dataset.cur_frame_index, global_frame_counter))

        context_name = frame.context.name
        frame_timestamp_micros = frame.timestamp_micros

        segment_name = dataset.tfrecord_pathnames[dataset.cur_dataset_idx].split('/')[-1].split('.')[0]
        objects = metrics_pb2.Objects()
        for i, image in enumerate(frame.images):
            camera_id = image.name
            # Fetch matching camera calibration.
            calibration = next(cc for cc in frame.context.camera_calibrations
                                if cc.name == camera_id)
            K = np.zeros((3, 4))
            K[0, 0] = calibration.intrinsic[0]
            K[1, 1] = calibration.intrinsic[1]
            K[0, 2] = calibration.intrinsic[2]
            K[1, 2] = calibration.intrinsic[3]
            K[2, 2] = 1
            img = np.array(Image.open(BytesIO(image.image)))

            T_cam_to_vehicle = np.array(
                        calibration.extrinsic.transform).reshape(4, 4)
            T_cam2lidar = T_cam_to_vehicle @ dataset.T_ref_to_front_cam
            
            pred_label_dict = model.predict(img, K, conf_thres=0.7, nms=True)

            # add to waymo metrics object
            for obj in pred_label_dict:
                box = label_pb2.Label.Box()
                pose4x4 = np.hstack((roty(obj['global_yaw']), np.array([obj['x'], obj['y'], obj['z']]).reshape(3, 1)))
                pose4x4 = np.vstack((pose4x4, np.array([0, 0, 0, 1])))
                pose_lidar = T_cam2lidar @ pose4x4
                box.center_x = pose_lidar[0, 3]
                box.center_y = pose_lidar[1, 3]
                box.center_z = pose_lidar[2, 3]
                box.length = obj['l']
                box.width = obj['w']
                box.height = obj['h']
                rpy = rotationMatrixToEulerAngles(pose_lidar[0:3, 0:3])
                box.heading = rpy[2]
                if box.heading < -np.pi:
                    box.heading += 2*np.pi
                elif box.heading > np.pi:
                    box.heading -= 2*np.pi
                

                o = metrics_pb2.Object()
                o.object.box.CopyFrom(box)
                o.object.type = dataset.k2w_cls_map[obj['class']]
                o.score = obj['conf']
                o.context_name = context_name
                o.frame_timestamp_micros = frame_timestamp_micros
                o.camera_name = camera_id
                prediction_objects.objects.append(o)

        frame = dataset.get_next_frame()
        global_frame_counter += 1

    # save to file
    predictions_filename = os.path.join(out_dir, 'predictions.bin')
    with tf.io.gfile.GFile( predictions_filename, 'wb' ) as f:
        f.write(prediction_objects.SerializeToString())
    print('Predictions saved to {}'.format(predictions_filename))
```

**Comment by yinzp-simple** [comment]
Same question as you. Validation submission can get scores, but Test submission are all zeros. I visualize my predictions on test datasets and it looks fine. Can you help me to check my submission at 5/20/22 11:36 AM?@hfslyc
Thanks!

**Comment by wangbo-zhao** [comment]
@yinzp-simple Hello. Can I ask you how do you generate the submission file? I follow the official tutortial but I still can not get any results from the website.

**Comment by yinzp-simple** [comment]
> @yinzp-simple Hello. Can I ask you how do you generate the submission file? I follow the official tutortial but I still can not get any results from the website.

Just follow the official tutorial. Maybe you can visualize your predictions to have a check?

**Comment by hfslyc** [comment]
@towardsautonomy 

The bug is actually because of setting `camera_name`. Please leave them empty when submitting. I've cleared your submissions and you still have 3 quota. Please submit again and let me know it works for you.

Best,
Wayne

**Comment by wangbo-zhao** [comment]
I use the official tool to eval my validation submission and I get
reasonable results. But when I submit it to the website,  I can not get any
results from the website.

yinzp-simple ***@***.***> 于2022年5月20日周五 15:40写道：

**Comment by wangbo-zhao** [comment]
@hfslyc Hello. I have tried several times to submit my val predictions to the website but it can not return any results. Everything goes well when I eval it on my computer with your evaluation tool.  
![middle_img_v2_4ef86fba-2fae-46cf-98fb-fbb5cabba7bg](https://user-images.githubusercontent.com/56866854/169480547-a251a77e-117c-4d23-8d19-a7b35f96cfb6.jpg)

**Comment by hfslyc** [comment]
@yinzp-simple you are submitting the results for the `testing` set. We have a new test set in `testing_3d_camera_only_detection`.

Best,
Wayne

**Comment by hfslyc** [comment]
@wangbo-zhao what's your submission email?

**Comment by hfslyc** [comment]
> > Hi,
> > Could you share the code on how to generate your submission? In the mean time, I'm checking your submission. The points you mentioned shouldn't affect the evaluation.
> 
> @hfslyc
> 
> Hello, for the camera-only 3d task, it doesn't matter if I don't modify the "id" field in the submission file because I don't do the tracking task, is that right?

Yes, the id field does not matter.

**Comment by wangbo-zhao** [comment]
Thanks for your reply. I use ***@***.*** to submit to the
validation sever to learn how to submit.

Wayne Hung ***@***.***> 于2022年5月20日周五 15:57写道：

**Comment by wangbo-zhao** [comment]
@hfslyc  caixvkun999@gmail.com

**Comment by hfslyc** [comment]
@wangbo-zhao "error_message": "The account name acc@domain.com is different from the registered email caixvkun999@gmail.com."

The front end currently has a problem to display error messages. Therefore, if you see a submission which doesn't have results out in 30 mins, please let me know and I can check the error message for you.

Best,
Wayne

**Comment by wangbo-zhao** [comment]
Thank you very much. I will try it later..

Wayne Hung ***@***.***> 于2022年5月20日周五 16:06写道：

**Comment by yinzp-simple** [comment]
> @yinzp-simple you are submitting the results for the `testing` set. We have a new test set in `testing_3d_camera_only_detection`.
> 
> Best, Wayne

Thank you for your reply! I did use the wrong testing set : (
Could you please help me to  clear my wrong submission(submitted by yinzphnu@gmail.com at 5/20/22 11:36 AM). It would be so hard for me to have only two chances last! @hfslyc 
Thanks a lot!

**Comment by hfslyc** [comment]
@yinzp-simple We've answered you question through gmail. Thanks!

**Comment by zhiqi-li** [comment]
@hfslyc I submitted to the test leaderboard, but no results were shown. I wonder what is the problem. The email is "denghanmig@gmail.com"

**Comment by towardsautonomy** [comment]
Thanks for all the help. I have resolved the issues following @hfslyc's comments.
