### ISSUE TITLE
How to get the evaluation results of camera-only 3D detection?

### ISSUE THREAD

**Issue by wangbo-zhao** [waymo-research/waymo-open-dataset#495]
I try to submit my prediction results of validation set following https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md/ to the website. But there are still not any results can be found. What should I do?
![middle_img_v2_4ef86fba-2fae-46cf-98fb-fbb5cabba7bg](https://user-images.githubusercontent.com/56866854/169445090-b4be69bd-045c-46d1-bf91-93477567852b.jpg)

**Comment by hfslyc** [comment]
What's your submission email?

**Comment by hfslyc** [comment]
Addressed in #491. Please close this issue, Thanks!
