### ISSUE TITLE
2D bounding box

### ISSUE THREAD

**Issue by giladdiv** [waymo-research/waymo-open-dataset#5]
Where can I find the information of the 2D bounding boxes in the scene?

**Comment by dtransposed** [comment]
I have the same problem as you do. There is a header file "aabox2d.h" in waymo_open_dataset/math. I guess it could be used somehow  to transform the cuboids into bounding boxes.

**Comment by peisun1115** [comment]
There are 2D bounding boxes defined in dataset.proto.

See these
https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L285-L295
