### ISSUE TITLE
Can we find ego poses in motion dataset?

### ISSUE THREAD

**Issue by ruixuanz** [waymo-research/waymo-open-dataset#508]
Having read the website and tutorials of the latest released Motion Dataset, I can obtain the state information of other tracking objects. However, I didn't find any Field storing the pose of ego vehicle, which is quite important to my usage. Can someone tell me if it is available or not? Thanks!

Fixed. Use <scenario>.tracks[<scenario>.sdc_track_index], where <scenario> is your own scenario instance.

**Comment by ruixuanisuzu** [comment]
Fixed. Use <scenario>.tracks[<scenario>.sdc_track_index].

**Comment by scott-ettinger** [comment]
Sorry for the late reply.  As mentioned now in the original post, the sdc_track_index field in the Scenario proto indicates which object is the ego vehicle.  If you are using the tf.Example format data the 'state/is_sdc' is a mask that indicates which object is the ego vehicle.  See also: https://waymo.com/open/data/motion/tfexample.
