### ISSUE TITLE
No permission to download dataset.

### ISSUE THREAD

**Issue by sillybirrrd** [waymo-research/waymo-open-dataset#512]
![IMG_1350](https://user-images.githubusercontent.com/71678608/173750914-20a4a673-ce7c-44f8-8eb2-b395109899c9.jpeg)
Hi, I have no idea why I cant access the dataset. Could you please help me? Thanks!

**Comment by niraj-bhujel** [comment]
I am having the same issue. The worse part is  get I get internal server error when I got to  click the Download tab. 
![image](https://user-images.githubusercontent.com/17889007/174704606-7c597ae1-7cb6-4db3-aefa-923131a2ba03.png)

**Comment by zoeyyang1** [comment]
Hi, I'm closing this old issue as dataset access was updated/fixed in June. Please feel free to post a new issue if you run into any problems.

**Comment by jayabrata97** [comment]
I am still having the same issue.
