### ISSUE TITLE
How to generate bin files for evaluation?

### ISSUE THREAD

**Issue by DianCh** [waymo-research/waymo-open-dataset#52]
Hi! I'm using Waymo Open Dataset for my own academic research. I'm still vague about how to use the provided tools to do evaluation on the results. Specifically, how to generate the bin files of my own results and the ground truths (for both detection and tracking)? And, is tracking evaluation tool ready for use now?

I really appreciate the effort you've put in producing this high-quality dataset. Thank you!

**Comment by peisun1115** [comment]
yes, the eval tool is ready. 

We provide 2 ways to eval your model:
1. Eval in TensorFlow. You metrics will show up in tensorboard. Call this API. https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/python/detection_metrics.py

2. Eval in commandline tool. 
Detection: https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc
Tracking: https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_tracking_metrics_main.cc

The format is https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/metrics.proto#L38

I suggest reading the two commandline tool source code which itself is a good demo on the format of the file.
