### ISSUE TITLE
Hi I wanna know how many recall positions the AP is in official tool 

### ISSUE THREAD

**Issue by Ultra11nstinct** [waymo-research/waymo-open-dataset#528]
Thanks for your great contribution！

 I want to know how many recall positions of AP calculation in official tool, 40recall or 11recall positions？

**Comment by hfslyc** [comment]
Hi, we use 100 score cutoff points in evaluation. Please refer to https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L116-L119

**Comment by Ultra11nstinct** [comment]
> Hi, we use 100 score cutoff points in evaluation. Please refer to https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L116-L119

Got it, thank you and have a good day!
