### ISSUE TITLE
does all image already be dedistorted?

### ISSUE THREAD

**Issue by yzl96** [waymo-research/waymo-open-dataset#53]
Hi, does all image already be dedistorted, or I should according to camera calibration dedistort the image by myself?

**Comment by peisun1115** [comment]
@yzl96 

All images are distorted. We have documented our distortion model in https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L89-L100

You can also take a look at
https://github.com/waymo-research/waymo-open-dataset/issues/24#issuecomment-535794541
