### ISSUE TITLE
how to transform tfrecord files into images in training set

### ISSUE THREAD

**Issue by WEIYI2021** [waymo-research/waymo-open-dataset#530]
I have written the for loop code for converting tfrecord files into images in training set, but finally from training folder 000 to training folder 031, throughout the conversion process, I finally only got 3990 images. But I guess for training set, we may get more than 100k images actually. Is there any advise how I can resolve this issue in order to arrive at the accurate number of images in training ?

**Comment by hfslyc** [comment]
Hi,

Could you provide your main for loop for reading the images from open datasets?
