### ISSUE TITLE
Waymo open motion dataset can't convert roadgraph_samples/type=18 to a crosswalk polygon, just some short lines

### ISSUE THREAD

**Issue by lwx422** [waymo-research/waymo-open-dataset#539]
I use the fellowing method to convert data:
roadgraph_xyz = decoded_example['roadgraph_samples/xyz'].numpy()
roadgraph_dir = decoded_example['roadgraph_samples/dir'].numpy()
roadgraph_valid = decoded_example['roadgraph_samples/valid'].numpy()
roadgraph_valid_xyz = roadgraph_xyz[np.squeeze(roadgraph_valid>0, axis=-1)]
roadgraph_valid_dir = roadgraph_dir[np.squeeze(roadgraph_valid>0, axis=-1)]
roadgraph_valid_start_xyz = roadgraph_valid_xyz
roadgraph_valid_end_xyz = roadgraph_valid_xyz + 0.5 * roadgraph_valid_dir
<img width="1064" alt="infoflow 2022-08-10 14-30-10" src="https://user-images.githubusercontent.com/110963935/183831507-aa92d75d-3dc5-4653-b0a9-fa1d5dd46d5f.png">

than I plot. roadgraph_valid_start_xyz to roadgraph_valid_end_xyz,  this method works for polyline objects such as lanecenter or laneboundary, but for crosswalk, there are just some short lines, not a polygon. not as described.

**Comment by lwx422** [comment]
solve it, thanks very much

**Comment by BulbasaurG** [comment]
> solve it, thanks very much

Hi,

Can I ask how do you solve it? In my case, the polygons are not closed... After checking the directions for the last point of the polygon, they are zeros...

**Comment by lwx422** [comment]
> > solve it, thanks very much
> 
> Hi,
> 
> Can I ask how do you solve it? In my case, the polygons are not closed... After checking the directions for the last point of the polygon, they are zeros...

just use id to gather points from same polygon and connect the last point with the first one, is will be closed.

**Comment by BulbasaurG** [comment]
>Thanks so much!
