### ISSUE TITLE
Cannot access waymo_open_dataset_motion_v_1_1_0

### ISSUE THREAD

**Issue by jayabrata97** [waymo-research/waymo-open-dataset#540]
I am getting the error: `Additional permissions required to list objects in this bucket. Ask a bucket owner to grant you 'storage.objects.list' permission` same as #450 . Can anyone help me?

**Comment by scott-ettinger** [comment]
Could you try registering (or re-registering) at https://waymo.com/open/licensing/   This process should grant you access to the dataset files.
