### ISSUE TITLE
what is the sensor(camera and the lidar) type ?

### ISSUE THREAD

**Issue by credoxfromcqut** [waymo-research/waymo-open-dataset#544]
would you mind tell us the centain device  so i can look for more sensor intrinsic parameter and information in detail ?i didnt see in your paper and the web site(waymo/open)

**Comment by VincentCa** [comment]
Hi,

Thanks for your question. Unfortunately, the details of our sensors are confidential and I can only refer you to what we have released with the dataset. On the camera side, we do provide quite a bit of information, including intrinsics, extrinsics and rolling shutter information for each image.

Best,
Vincent

**Comment by credoxfromcqut** [comment]
> Hi,
> 
> Thanks for your question. Unfortunately, the details of our sensors are confidential and I can only refer you to what we have released with the dataset and/or paper. On the camera side, we already do provide quite a bit of information, such as intrinsics, extrinsics and rolling shutter information for each image.
> 
> Best, Vincent

thank you vincent, i still want to consult you the things i want to know directly.
![image](https://user-images.githubusercontent.com/56586981/184464067-fdf8a65b-2ee5-4a5a-8029-3e04b74c80df.png)

i noticed the shutter time is 1 col time to exposure,the diff time(computed) is the total time, diff/shutter is almost the total col, and the col i computed is 5.42. but the image must be more col (resolution 1920*1280, means 1920 cols), if this col mentioned in the dataset.proto is consist of many cols(1920 / 5.42, i named it BIG col)  in images(1920 cols), and the cols in the BIG col were exposured at the same time? 

whats more ,we know that the exposure time is not fixed, so the shutter time recored in the dataset (all the same in one frame)is the average valure in one frame or in all frame?(shutter time  = exposure time / BIG col or tested in a certain scene before install)   ,  i prefer the second case because i checked almost five fames, or every record day waymo will recheck the shutter time ?

**Comment by VincentCa** [comment]
Hi!

> i noticed the shutter time is 1 col time to exposure,the diff time(computed) is the total time, diff/shutter is almost the total col, and the col i computed is 5.42. but the image must be more col (resolution 1920*1280, means 1920 cols at least cuz the crop operation), if this col mentioned in the dataset.proto is consist of many cols(1920 / 5.42, i named it BIG col) in images(1920 cols), and the cols in the BIG col were exposured at the same time?

You are right that the shutter time is the time it takes to expose a single image column and this is done from left to right or right to left (depending on [RollingShutterReadOutDirection](https://source.corp.google.com/piper///depot/google3/third_party/waymo_open_dataset/dataset.proto;l=132?q=dataset.proto)). The primary reason why you can not simply recover the number of image columns by computing $\frac{readoutdonetime - cameratriggertime}{shutter}$ is that the exposure timeframes overlap heavily, it is not a sequential process at all. We tried to illustrate this in our comment [here](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L329-L339).

> whats more ,we know that the exposure time is not fixed, so how to get the camera_center_time for sychronizating data with lidar(shown in paper)

You can still get an approximate center time as $\frac{1}{2}(cameratriggertime+readoutdonetime)$. You can also consider using [pose_timestamp](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L324) which is near the center.

> and the shutter time recored in the dataset (all the same in one frame)is the average valure in one frame or in all frame?(shutter time = exposure time / BIG col or tested in a certain scene before install) , i prefer the second case because i checked almost five fames, or every record day waymo will recheck the shutter time ?

The shutter time is a property of `CameraImage`, as such it varies not only by frame but really every individual camera image taken. The exposure depends on the environmental conditions.

**Comment by credoxfromcqut** [comment]
> Hi!
> 
> > i noticed the shutter time is 1 col time to exposure,the diff time(computed) is the total time, diff/shutter is almost the total col, and the col i computed is 5.42. but the image must be more col (resolution 1920*1280, means 1920 cols at least cuz the crop operation), if this col mentioned in the dataset.proto is consist of many cols(1920 / 5.42, i named it BIG col) in images(1920 cols), and the cols in the BIG col were exposured at the same time?
> 
> You are right that the shutter time is the time it takes to expose a single image column and this is done from left to right or right to left (depending on [RollingShutterReadOutDirection](https://source.corp.google.com/piper///depot/google3/third_party/waymo_open_dataset/dataset.proto;l=132?q=dataset.proto)). The primary reason why you can not simply recover the number of image columns by computing readoutdonetime−cameratriggertimeshutter is that the exposure timeframes overlap heavily, it is not a sequential process at all. We tried to illustrate this in our comment [here](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L329-L339).
> 
> > whats more ,we know that the exposure time is not fixed, so how to get the camera_center_time for sychronizating data with lidar(shown in paper)
> 
> You can still get an approximate center time as 12(cameratriggertime+readoutdonetime). You can also consider using [pose_timestamp](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L324) which is near the center.
> 
> > and the shutter time recored in the dataset (all the same in one frame)is the average valure in one frame or in all frame?(shutter time = exposure time / BIG col or tested in a certain scene before install) , i prefer the second case because i checked almost five fames, or every record day waymo will recheck the shutter time ?
> 
> The shutter time is a property of `CameraImage`, as such it varies not only by frame but really every individual camera image taken. The exposure depends on the environmental conditions.

great thanks to you for your patient reply.Vincent
best wishes
