### ISSUE TITLE
Post-processing of Intensity profile

### ISSUE THREAD

**Issue by ShengyuH** [waymo-research/waymo-open-dataset#546]
hi the team,

Thanks for this great contribution to the filed. I have one question regarding the post-processing of LiDAR Intensity profile. 

From this paper titled "LiDAR Snowfall Simulation for Robust 3D Object Detection" we know that LiDAR raw intensity roughly follows a Lambertian model which has dependence on the range squared and cosine incidence angle (see below). I tried to correct these dependence to obtain surface properties like reflectance but find that: it seems Waymo dataset has already done some post-processing to remove range and incidence angle dependence. My question is: Has the team done some post-processing as I mentioned above? If yes, do we have a reference for these detailed operations? 
 
<img width="393" alt="image" src="https://user-images.githubusercontent.com/28732721/184900684-f898bb3f-2a50-473a-a99d-fc67bb431e82.png">

Thanks and look forward to your reply.

Best,
Shengyu

**Comment by VincentCa** [comment]
Hi Shengyu,

Thanks for your question - unfortunately, due to IP reasons, we are unable to provide details on the LiDAR data processing.

Please don't hesitate to reach out if you have any other questions.

Thanks!

**Comment by ShengyuH** [comment]
hi,

I have another question regarding two returns of the LiDAR sensor data. I am wondering how exactly these two returns are organised. I find for pixels with both returns: 1). the intensity difference could be both negative and positive, so it's not organised as strongest + second strongest;  2). the range difference could also be both negative and positive, though only around 0.1% of pixels having the first return with bigger range than the second return, so they are also not strictly organised as closest peak + second closest peak. I am wondering are there any strict physical properties between the two returns. Thanks for your attention.

Best,
Shengyu

**Comment by ShengyuH** [comment]
thanks
