### ISSUE TITLE
Get all zeros in 3D camera-only detection submission

### ISSUE THREAD

**Issue by githubfragments** [waymo-research/waymo-open-dataset#547]
I submitt results to the3d object detection leaderboard test server, however, I received all zeros within the metrics table. But validation submission is right. And there is no difference between the formats of test and validation submission. 
I have tried twice, but cannot figure out the reason.  Is there any wrong? 

Some results is shown as follow (ignore the '?' ):

task: CAMERA_ONLY_DETECTION_3D
unique_method_name: "?"
authors: "?"
affiliation: "?"
description: ""
method_link: ""
number_past_frames_exclude_current: 0
inference_results {
  objects {
    object {
      box {
        center_x: 27.504085540771484
        center_y: 23.97313690185547
        center_z: -0.3927741050720215
        width: 2.378368854522705
        length: 5.738202095031738
        height: 2.2326509952545166
        heading: 1.5803601741790771
      }
      type: TYPE_VEHICLE
      id: "1_0"
    }
    score: 0.9823976159095764
    context_name: "10084636266401282188_1120_000_1140_000"
    frame_timestamp_micros: 1558407840397346
  }
  objects {
    object {
      box {
        center_x: 28.629989624023438
        center_y: 31.43358612060547
        center_z: -1.3385446071624756
        width: 2.0027835369110107
        length: 4.433125019073486
        height: 1.7841345071792603
        heading: 1.5825525522232056
      }
      type: TYPE_VEHICLE
      id: "1_4"
    }
    score: 0.9672803282737732
    context_name: "10084636266401282188_1120_000_1140_000"
    frame_timestamp_micros: 1558407840397346
  }
  objects {
    object {
      box {
        center_x: 11.986915588378906
        center_y: 0.20557403564453125
        center_z: 1.005812168121338
        width: 0.9609906673431396
        length: 1.1536551713943481
        height: 1.8216203451156616
        heading: -1.4168647527694702
      }
      type: TYPE_PEDESTRIAN
      id: "2_8"
    }
    score: 0.9593930840492249
    context_name: "10084636266401282188_1120_000_1140_000"
    frame_timestamp_micros: 1558407840397346
  }
}
sensor_type: CAMERA_ALL
account_name: "???@???"
object_types: TYPE_VEHICLE
object_types: TYPE_PEDESTRIAN
object_types: TYPE_CYCLIST

**Comment by githubfragments** [comment]
I have checked #491 , and I found the wrong test set is used. I should use testing_3d_camera_only_detection. The new datasets have 15879 frames. Is the number right?

**Comment by hfslyc** [comment]
Hi, the camera-only test set consist of 80 segments where each segment contains close to 200 frames. I think you are reading the right data.

**Comment by githubfragments** [comment]
> Hi, the camera-only test set consist of 80 segments where each segment contains close to 200 frames. I think you are reading the right data.

Ok，Thank you.
