### ISSUE TITLE
Support for tensorflow 2.7?

### ISSUE THREAD

**Issue by Rtakaha** [waymo-research/waymo-open-dataset#548]
Hi, thank you very much for your great work!

I have one quick question, do you plan to support tensorflow 2.7?

I tried creating `tf/workspace_tf2_7_0.bzl` by changing the version of `absl` following [this](https://github.com/tensorflow/tensorflow/blob/v2.7.0/third_party/absl/workspace.bzl), but didn't work.

```console
waymo_open_dataset/protos/metrics.proto:21:1: warning: Import waymo_open_dataset/protos/scenario.proto but not used.                         
ERROR: /tmp/repo/waymo_open_dataset/metrics/ops/BUILD:39:10: Compiling waymo_open_dataset/metrics/ops/metrics_ops.cc failed: (Exit 1): crosst
ool_wrapper_driver_is_not_gcc failed: error executing command third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0/c
lang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 78 arguments skipped) 
```

Could you tell me what else do I need to create `tf/workspace_tf2_7_0.bzl`?

**Comment by Ianni** [comment]
[tf27py39.txt](https://github.com/waymo-research/waymo-open-dataset/files/9506716/tf27py39.txt)

This is my patch file to build the package using the provided docker build environment with support for python3.9 and all tf 2.7.x releases.
I hope it will work for you too.

**Comment by Rtakaha** [comment]
Hi @Ianni , thank you very much for your advice :)

It worked!!!
Let me share some actions I needed to do in addition to applying the patch file.

- After applying your patch, `bazel build` was successfully completed but `bazel test` failed. The following output came out, which says `tensorflow_graphics` is not installed.
```console
==================== Test output for //waymo_open_dataset/utils:occupancy_flow_metrics_test:
2022-09-08 01:24:37.071496: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open share
d object file: No such file or directory       
2022-09-08 01:24:37.071532: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/9e9b22f1cb0d873507139f227aa7d4e2/sandbox/processwrapper-sandbox/1468/execroot/__main__/bazel-out/k8-opt/bin/waymo_open_dataset/utils/occupancy_flow_me
trics_test.runfiles/__main__/waymo_open_dataset/utils/occupancy_flow_metrics_test.py", line 21, in <module>
    from waymo_open_dataset.utils import occupancy_flow_metrics
  File "/root/.cache/bazel/_bazel_root/9e9b22f1cb0d873507139f227aa7d4e2/sandbox/processwrapper-sandbox/1468/execroot/__main__/bazel-out/k8-opt/bin/waymo_open_dataset/utils/occupancy_flow_me
trics_test.runfiles/__main__/waymo_open_dataset/utils/occupancy_flow_metrics.py", line 20, in <module>
    import tensorflow_graphics.image.transformer as tfg_transformer
ModuleNotFoundError: No module named 'tensorflow_graphics'
================================================================================
[27 / 35] 26 / 37 tests, 1 failed; Testing //waymo_open_dataset/utils:occupancy_flow_renderer_test; 17s processwrapper-sandbox ... (8 actions running)
```
- So I tried to install `tensorflow_graphics` in the container, but the command below didn't work due to some problems in `OpenEXR`.
```
python3 -m pip install tensorflow_graphics
```

- I installed tensorflow_graphics from source, with removing `OpenEXR` from the requirements. The wheel files are finally in `/tmp/artifacts`!!

Thank you again @Ianni for your tips! I am closing this issue.
It will be cool if the official `waymo-open-dataset` supports tf2.7 as well :)

**Comment by Ianni** [comment]
I do not think that you have to compile tensorflow_graphics on your own. 
At the moment, openexr fails to build and install its wheel, simply skipping the latest version and using `OpenEXR==1.3.8 `in the dockerfile solved it for me. 
Some months ago when i built the package this was not necessary.

**Comment by Hiusam** [comment]
Hi, is there a waymo-open-dataset-tf-2-7-0? tf2.6 only supports numpy 1.19, it's really terrible.

**Comment by ShaneXiangH** [comment]
Hi @lanni, to build versions tf2.11, as you mentioned, we need to change gcc7 to gcc9. Could you give me any suggestions on how to change it? I have seen in the `configure.sh` there are lines:
```
write_to_bazelrc "build:manylinux2010 --crosstool_top=//third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0:toolchain"

if [[ "$PIP_MANYLINUX2010" == "1" ]]; then
  write_to_bazelrc "build --config=manylinux2010"
  write_to_bazelrc "test --config=manylinux2010"
fi
```
I guess we need change these lines. They use the files in: `/third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0`. Where could we get the appropriated files for gcc9, as well as the corresponding cuda and ubuntu version? (Something like`/third_party/toolchains/preconfig/ubuntu18.06/gcc9_manylinux2010-nvcc-cuda14.3:toolchain`)?

Thank you so much!

> > Hi, is there a waymo-open-dataset-tf-2-7-0? tf2.6 only supports numpy 1.19, it's really terrible.
> 
> I have built versions for tf2.7 and now 2.11 privately, but I am unsure if I should "distribute" these packages as I am not involved in this project and made quite a lot of (for me) necessary changes to the build environment (e.g. tf2.11 now uses gcc9). Also Dockerfiles that worked some weeks ago now don't (see the openexr issue or that the deadsnakes python repo no longer supports ubuntu 16.04 that is used here originally).
> 
> you can follow the outlined changes in this thread to build your version, or wait for a new official release (I think there was someone working on a PR for tf2.10)

**Comment by Ianni** [comment]
I just switched to the `FROM tensorflow/build:2.11-python3.9` docker image as build environment.
Then you have to adjust some bazel pipelines, update your bazl configs, fix the OpenEXR version (if the build error discusses earlier is not fixed yet), switch MANYLINUX2010 target with MANYLINUX 2.17 and add the new tensorflow version in some places.

I am hesitant to create a PR as I changed a lot of things I am not really an expert in. And the only thing I can guarantee is that it worked for my use-case some months ago. And the new build environment breaks the build of the original supported versions.
Also, there is a pending PR from someone else that for some reason does not get merged.

**Comment by ShaneXiangH** [comment]
Thank you @Ianni! Following your guidance and some online resource, I succeed to build the waymo-open-datset-tf-2.9 package now. Yeah, we have to change several configs in bazel config, configure.sh and build.sh. 

But I cannot use the built package. When I import and use the package, it show the error: 
```
tensorflow.python.framework.errors_impl.NotFoundError: user/lib/python3.9/site-packages/waymo_open_dataset/metrics/ops/metrics_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
```

I built the package in linux x86_64 system. It seems like a Application Binary Interface (ABI) issue. I did not switch MANYLINUX2010 target with MANYLINUX 2.17.  Could that problem occurs due to this? 

I do not know how to switch MANYLINUX2010 target with MANYLINUX 2.17. In the `configure.sh` these line: 
```
write_to_bazelrc "build:manylinux2010 --crosstool_top=//third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0:toolchain"
```
They use this manylinux2010 package that is already written. So should we modify these files or should we create some new files for MANYLINUX 2.17?

**Comment by ShaneXiangH** [comment]
Oh I figure out this problem now! Just need to follow the [TF Release Tags](https://github.com/tensorflow/tensorflow/tags) descriptions ok.

Specifically in my case, for tf2.9, I need to set `_GLIBCXX_USE_CXX11_ABI=1` and let `--cxxopt="-std=c++14"`

**Comment by akshaaayyy** [comment]
> metrics/ops/metrics_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

Hey, I also faced a similar error, ...metrics/ops/metrics_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

I have tensorflow 2.12.0 (Running is WSL2) , Could you explain what you did here  (I need to set _GLIBCXX_USE_CXX11_ABI=1 and let --cxxopt="-std=c++14")

**Comment by ShaneXiangH** [comment]
I used tf2.9, so need I set `_GLIBCXX_USE_CXX11_ABI=1` and `--cxxopt="-std=c++14"`. You can check for the [TF Release Tags](https://github.com/tensorflow/tensorflow/tags) descriptions for the description about tf2.12 to see if you need to set it.   If you need, you could set them in `YOUR_PATH/lingvo/pip_package/build.sh`
