### ISSUE TITLE
How to get ego vehicle's position and velocity in global frame ?

### ISSUE THREAD

**Issue by Xiangwang-Hu** [waymo-research/waymo-open-dataset#55]
As I am reading the format file dataset.proto, I can not directly find the ego vehicle's position and velocity in global frame. 
However, in "message CameraImage" I find the attirbute Velocity. I wonder what this velocity refers to? Why is velocity related to CameraImage ?
Also, in this message, I can not understand what is SDC pose and velocity. I never saw SDC anywhere else. What is the the full name ?
It's many questions here probably because I don't learn CS...
Anyway, hope anyone can give me a more detailed explanation. Thanks in advance.

**Comment by peisun1115** [comment]
@Xiangwang-Hu 

The vehicle (SDC, self driving car)'s position is set in https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L281

We do not provide SDC's velocity. You can infer that by looking consecutive poses. Alternatively, you can look at the one in CameraImage as you have found.

The SDC pose and SDC velocity in each CameraImage is to specify where the SDC is and what it is its speed at the camera center time (the time at which the center of the image is captured). This is used to project 3d points to camera image precisely by compensating for rolling shutter effect.

**Comment by Xiangwang-Hu** [comment]
@peisun1115 
Thanks for your detailed reply. Now I understand poses.

I tried to calculate the SDC's velocity in global frame using the global positions in the poses (Velocity A). And I found it was slightly different from the velocitiy in the CameraImage (Velocity B). In CameraImage, it's said that the velocity is calculated in vehicle's frame. If this is true,  I suppose Velocity A and Velocity B should be largely different due to different coordinate systems. But why there is no major differences? In addition the velocity in each CameraImage is also slightly different. 

So what velocity should I use in order to get the most precise SDC's velocity in global frame?

Besides, In issue 39 [https://github.com/waymo-research/waymo-open-dataset/issues/39](url), the speed and acceleration of laser labels are calculated by (center_x, center_y, center_z) in vehicle's frame, why can we can we assume they are in global frame ?

 How can I get the most precise velocities for laser labels in global frame?

**Comment by peisun1115** [comment]
I somehow forgot to answer this.

1. The velocity is the CameraImage is in vehicle frame.
2. You can transform your velocity calculated from the global poses to vehicle frame by applying a rotation to see whether it is different.
3. The velocity for each label is in global frame as they were computed in global frame. We should have probably documented this more clearly or transformed that to vehicle frame to make it clearer. but that is what we have now.

**Comment by Xiangwang-Hu** [comment]
Thanks a lot for the detailed explanation.
