### ISSUE TITLE
any way to speed up the eval process

### ISSUE THREAD

**Issue by lcc815** [waymo-research/waymo-open-dataset#550]
when i eval my detection result by running following-like code, it will take so long time to get the result(one hour i guess). is there any way i can do to speed up this slow process? thanks.
 ```
bazel-bin/waymo_open_dataset/metrics/tools/compute_detection_metrics_main
waymo_open_dataset/metrics/tools/fake_predictions.bin
waymo_open_dataset/metrics/tools/fake_ground_truths.bin
```

**Comment by hfslyc** [comment]
Hi,

Since the dataset is large, please consider submit your validation results to the evaluation server, where we use distributed computation to obtain result efficiently.

**Comment by lcc815** [comment]
One could further build the multi-thread Waymo evaluation tool ([link](https://github.com/Abyssaledge/waymo-open-dataset-master)) for faster evaluation.
