### ISSUE TITLE
How to convert our own OpenDrive or Lanelet2 map to rasterized images? 

### ISSUE THREAD

**Issue by ggosjw** [waymo-research/waymo-open-dataset#554]
Hi, **much appreciated for your amazing and wonderful open data set**. We are currently training a planning algorithm on your motion data set. We are keen on deploying the algorithm on the real vehicle.

Therefore we have an issue that how we could convert our own OpenDrive or Lanelet2 map to rasterized images. 

Could you provide us any suggestions, like which API could realize that.

Thank you for your kind help!

**Comment by scott-ettinger** [comment]
Hi.  I'm not sure I fully understand the question.  Our motion dataset does not contain any rasterized images.  Is there a specific format you are trying to convert maps into?
