### ISSUE TITLE
Unable to parse `.tfrecord` with `dataset_pb2.Frame()`

### ISSUE THREAD

**Issue by jonathanloganmoran** [waymo-research/waymo-open-dataset#556]
Hello,

I am running into issues attempting to read in a `.tfrecord` using the `dataset_pb2.Frame()` method (i.e., the script under "Read one frame" in your [`tutorial.ipynb`](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb) notebook):
```
example_set = tf.data.TFRecordDataset(FILE_PATHS_LIST, compression_type=''):
for i, data in enumerate(example_set):
    frame = waymo_open_dataset.dataset_pb2.Frame()
    frame.ParseFromString(bytearray(data.numpy()))
    break
```
The resulting output of `frame` is:
```
context {
  name: "\n\026image/object/bbox/xmin\022\342\001\022\337\001\n\334\001x\212g?|w\314=\333\267\010?\323\0008?|wL?\305\252\337<9L,>^\031\371>\003\tO?\365\201\010?s\360\t>p\217\t?)1\222>\033\3339?,\270H?\352\020\246=\"\363\006?\207\026X?\265\242\344>\000\000\000\000V\373!?Y)O>\036\240\373=\327\227\320>\304\204!>5)/>-\270P?\303\262J?\350>\317>/\320\031?)w\204>\361^\213>\300A\360>\320\257\021>\316\227H>\313\214\224=\336lp?;\353\257>\360Y\341=\261a\030?\220\325\227>\256dY?\000\000\000\000\000\000\000\000\022\3331=B\177\007?\000\000\000\000\373\204Q>\n\273u>=\235R?\203\177?>\031\006\036?+Gv?.\021b?\007<&>"
}
```

I believe this is related to the specific `.tfrecord` files I am using; I assume that some of their fields have been intentionally omitted (e.g., LiDAR data) from their original Waymo `segment` record counterparts.

I bring this to your attention to ask for further information on the `dataset_pb2.py` file (can't find it here), the `Frame()` method and to raise awareness that its functionality appears to be broken when using `.tfrecord` files with incomplete attribute fields.

This issue is also cross-referenced [here](https://github.com/jonathanloganmoran/ND0013-Self-Driving-Car-Engineer/issues/21). Thank you.

**Comment by jonathanloganmoran** [comment]
Hi Vincent — thanks for clarifying this issue. Can you point me to the proto config file you are referring to?

**Comment by VincentCa** [comment]
I'm specifically referring to the Frame proto definition in https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto. Alternatively, you may be able to download the corresponding run segment from our page directly, and that should be valid.

**Comment by jonathanloganmoran** [comment]
Thanks for that, @VincentCa. Just to note, I do not experience any issues with parsing the segments that have been fetched directly from the Waymo GCS bucket — only with the presumably modified records from Udacity.
