### ISSUE TITLE
PVPS dataset: Remapping instance_id on validation data may cause overflow for panoptic_label of uint16

### ISSUE THREAD

**Issue by npurson** [waymo-research/waymo-open-dataset#557]
Hi, I was referring to `tutorial/tutorial_2d_pvps.ipynb` for implementing the data loading process, and calling `camera_segmentation_utils.decode_multi_frame_panoptic_labels_from_protos(segmentation_protos_flat, remap_values=True)` to produce consistent IDs between cameras and frames. I found that concealed overflow may be encountered for `panoptic_label` when doing so.

In `waymo_open_dataset/utils/camera_segmentation_utils.py: line 233`, the `panoptic_label_divisor` may be rather large (in my case, 2939) after remapping, and for those pixels of `semantic_label` > 23, an overflow may be encountered when encoding semantic and instance labels back to panoptic_labels because `23 * 2939 > 65535`, which will represent the incorrect categories and instance ids.

I believe this can be easily reproduced for most of the validation data. And this problem becomes even more imperceptible because this may only be encountered in validation/testing data (since there is fewer frames for training sequences, leading to fewer instances and smaller `panoptic_label_divisor`), and there do seem to be some negligible erroneous annotations where pixels with the same instance_id may belong to multiple categories, which has similar appearance of this problem.

**Comment by alexzzhu** [comment]
Thanks for bringing this to our attention. You're right that `encode_semantic_and_instance_labels_to_panoptic_label` could cause overflow if the inputs are a smaller datatype. We will fix this by explicitly casting the semantic and instance labels to uint32 before combining into a panoptic label. Hopefully we don't run into overflow issues in that case.
