### ISSUE TITLE
[Question] minADE calculation 

### ISSUE THREAD

**Issue by manolotis** [waymo-research/waymo-open-dataset#559]
I have a question regarding minADE calculation: When you state something like "The metrics for each object type (ADE, FDE, Miss Rate, Overlap rate, and mAP) are all computed at 3, 5, and 8 second timestamps" (e.g. in the motion prediction challenge), and given the definition of minADE in [https://arxiv.org/pdf/2104.10133v1.pdf](url), do you
1.  pick the kth best prediction that minimizes ADE over the entire prediction horizon (8 seconds), and then report the ADE of that prediction at times 3,5,8 seconds? Or
2. pick the kth best prediction that minimizes ADE at each separate timestep (3,5,8 seconds)? Which would allow 

So, in the simplified image below, which one would be the result of the computation?:

1. Pick prediction 2 because it is closest at 8 seconds, and report the ADE of prediction 2 at times 3, 5 and 8, even though at time 5 it is not the best prediction.
2. Report the ADE of prediction 2 at t=3, the ADE of prediction 1 at t=5, and the ADE of prediction 2 at t=8

I suppose it's is the second option, but I got a bit confused and would like to make sure I got it right. Thank you in advance!

![image](https://user-images.githubusercontent.com/12627289/196459732-45399dd6-a679-4860-8221-7a66bd25d652.png)

**Comment by scott-ettinger** [comment]
Hi. Apologies for the late reply. You are correct. It will be computed as you have described in option 2.  Please let me know if you have further questions.
