### ISSUE TITLE
About the distortation of Camera image

### ISSUE THREAD

**Issue by RicardoWUlei** [waymo-research/waymo-open-dataset#56]
Is the camera image provided in this dataset distorted or undistorted?

**Comment by peisun1115** [comment]
yes. see my reply here: https://github.com/waymo-research/waymo-open-dataset/issues/53

**Comment by RicardoWUlei** [comment]
Thank you for that!

**Comment by peisun1115** [comment]
we have camera model released in third_party/camera directory. You can see an example usage at

https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/ops/camera_model_ops_test.py

C++ interface is at https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/camera_model.h
