### ISSUE TITLE
How to extract the waymo datasets in a right form

### ISSUE THREAD

**Issue by XiaoyanQian** [waymo-research/waymo-open-dataset#569]
Hello. I downloaded your dataset in the form of tar files in different folders. 
how could I unzip the tar files, does the "ls *.tar.gz | xargs -n1 tar xzvf" work? Do I need to go to each folder and run this Linux code? Are there any better ways to extract the datasets? 
Dose the layout should be training/validation/testing folders of tf. files?
Thank you so much.

**Comment by VincentCa** [comment]
Hi, thanks for your question! If you chose to download the tar representation of the dataset, then you will find the regular directory structure (`training`, `validation`, `testing`, `testing_3d_camera_only_detection`, `domain_adaptation` for the current release) and each folder contains sharded tar files with its contents. GNU tar should be able to handle it just normally. After unpacking, yes, you should be left with tfrecord files - one for each driving segment.

**Comment by KoapT** [comment]
> Hi, thanks for your question! If you chose to download the tar representation of the dataset, then you will find the regular directory structure (`training`, `validation`, `testing`, `testing_3d_camera_only_detection`, `domain_adaptation` for the current release) and each folder contains sharded tar files with its contents. GNU tar should be able to handle it just normally. After unpacking, yes, you should be left with tfrecord files - one for each driving segment.

every time I unpacking the .tar file with  "tar -xvf xxx.tar", the following will show:
```
tar: This does not look like a tar archive
tar: Skipping to next header
./segment-9568394837328971633_466_365_486_365_with_camera_labels.tfrecord
./segment-9653249092275997647_980_000_1000_000_with_camera_labels.tfrecord
...
tar: Exiting with failure status due to previous errors
```
Is this right ?

**Comment by KoapT** [comment]
> Hi, thanks for your question! If you chose to download the tar representation of the dataset, then you will find the regular directory structure (`training`, `validation`, `testing`, `testing_3d_camera_only_detection`, `domain_adaptation` for the current release) and each folder contains sharded tar files with its contents. GNU tar should be able to handle it just normally. After unpacking, yes, you should be left with tfrecord files - one for each driving segment.

Should I  download all the .tar files before unpacking?

**Comment by william-ngvn** [comment]
@KoapT Hi,
Did you resolve your unpacking .tar file problems? If done. Can you tell me how to unpack it right a way?
Thank you so much.

**Comment by KoapT** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已收到您的邮件，会在阅读之后尽快给您回复。

**Comment by RealHaoyeChen** [comment]
> [@KoapT](https://github.com/KoapT) Hi, Did you resolve your unpacking .tar file problems? If done. Can you tell me how to unpack it right a way? Thank you so much.

hi, I also encountered this when unpacking v1.43 tar file

**Comment by KoapT** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已收到您的邮件，会在阅读之后尽快给您回复。

**Comment by KoapT** [comment]
> > [@KoapT](https://github.com/KoapT) Hi, Did you resolve your unpacking .tar file problems? If done. Can you tell me how to unpack it right a way? Thank you so much.
> 
> hi, I also encountered this when unpacking v1.43 tar file
> 
> 

download all that shit before unpacking
(You must notice that all the tar files have the same size, since they are packed segmently)
