### ISSUE TITLE
Question about 3D labels' information

### ISSUE THREAD

**Issue by Ov3RCoM3** [waymo-research/waymo-open-dataset#572]
Hi,thanks for your work on the Waymo Open Dataset. I got a problem when I attempt to show the lidar points number of each labeled object: **some of them are of 0 points number**, like this:
**the id of this obj: wI7NZ_HA9-u78UF8M9B3pg
the points number of this obj: 0
the top lidar points number of this obj: 0**
Here is my code:
**for label in frame.laser_labels:
    _id = label.id
    num_pts = label.num_lidar_points_in_box
    top_pts =label.num_top_lidar_points_in_box
    print(f'the id of this obj: {_id}')
    print(f'the points number of this obj: {num_pts}')
    print(f'the top lidar points number of this obj: {top_pts}')**
Is this **label.num_lidar_points_in_box**  represents the number that this 3D label contains? If so, I am confused about why a zero numbered object can be detected and labeled?

**Comment by VincentCa** [comment]
Hi, thanks for your question! I can't get into details as to how to the labeling is performed, but it is not unexpected to find some objects with no points. For example, a label may be created based on other sensor types that perceive it. A label may also be interpolated between visible frames while the object of interest is temporarily fully occluded. That's for the labeling part - note that we obviously do not expect LiDAR-based methods to detect these cases, so they are ignored during evaluation, and you may want to handle this accordingly when developing a model. Hope this helps!

Best,
Vincent, on behalf of the Waymo Open Dataset team

**Comment by Ov3RCoM3** [comment]
Thank you very much for your response! @VincentCa   
Now I understand some of the laser_labels are labeled by cameras.
Thank you again for your helps! I am closing this issue.
