### ISSUE TITLE
Motion dataset: point order of polylines

### ISSUE THREAD

**Issue by ZikangZhou** [waymo-research/waymo-open-dataset#574]
Hi Waymo Team,

I wonder how the points in polylines are arranged since I can't find any document talking about this. 

Polylines exist in LaneCenter, RoadEdge, and RoadLine features. For polylines in LaneCenter, I guess the direction of polyline[i+1] - polyline[i] is the same as the driving direction of the lane (correct me if I'm wrong). But how about the point order in road edges and road lines? Does the direction of polyline[i+1] - polyline[i] follow any specific pattern (e.g., the coordinates being oriented counter-clockwise if the road edge is a part of the drivable area's exterior)?

**Comment by scott-ettinger** [comment]
Sorry for the late reply, 
The direction of road edges is defined such that the road area is always to the left of the boundary.  For road lines there cannot be a specific direction ordering as lines that divide opposing lanes can be defined in either direction. 

Please let me know if you have further questions.

**Comment by ZikangZhou** [comment]
Thanks for the clarification! It makes sense.
