### ISSUE TITLE
Questions regarding the motion prediction leaderboard submission

### ISSUE THREAD

**Issue by ggosjw** [waymo-research/waymo-open-dataset#578]
Hi, thank you for open-sourcing your great work.

I have a question regarding my submission for the motion prediction leaderboard.

When I uploaded the validation submission, I encountered the following error information:
![image](https://user-images.githubusercontent.com/87901530/205914777-598655a2-11cd-4bd9-abde-1103a10f2758.png)
However, when I check the scenario: 4e3b488f1d96ea29, using code:
![image](https://user-images.githubusercontent.com/87901530/205915185-47e0db78-dd1a-4b40-8b0c-03fcd109f553.png)

I found that 
![image](https://user-images.githubusercontent.com/87901530/205916015-3a6ca516-7171-4c36-845d-62ee8920619f.png)
This is contradicting the error information. And the total number of tracks is 148, much smaller than 600.

So, could you give me some intuitive suggestions regarding this error?

I really appreciate any help you can provide.

**Comment by scott-ettinger** [comment]
Sorry you are having this issue. We will look into it.

**Comment by scott-ettinger** [comment]
Can you tell me the e-mail address you registered with to submit the file?  Your tracks to predict do look correct.

**Comment by ggosjw** [comment]
Thanks! My email is :ggosjw@gmail.com.

I have submitted it several times.  For the scenario ID:4e3b488f1d96ea29, c4f2c870eb898747, 2656048c83c55d02, 472a72a2e92e8371, 453e4638ab0fac3f, I confront the same error bug. At first, I think there might not be so many error scenarios, so I used the following code to manually change the index for tracks_to_predict.
![image](https://user-images.githubusercontent.com/87901530/206626975-3db228fa-c2b5-452f-87b8-6f4ae00fb6ae.png)

You may check my first submission where I didn't do any changes to the index for tracks_to_predict. Submission time is: "12/6/22 11:59 AM" 
![image](https://user-images.githubusercontent.com/87901530/206627478-df7f71c6-4a56-4ce9-a81c-8612e4fe6206.png)

Thank you for you help! Much appreciation.

**Comment by ZikangZhou** [comment]
@ggosjw,

Are you using the track index in your submission? I think it should be track id instead of track index.

**Comment by ggosjw** [comment]
Oh! Thank you very much!
