### ISSUE TITLE
UNAVAILABLE: Server is not responding

### ISSUE THREAD

**Issue by shawnding** [waymo-research/waymo-open-dataset#580]
Hi,

I submitted my result to the WOD 3D detection (validation set), and got an error:

```
UNAVAILABLE: Server is not responding [type.googleapis.com/util.ErrorSpacePayload='RPC::UNREACHABLE']
```
The submission link is https://waymo.com/open/challenges/entry/?timestamp=1670570006503294&challenge=DETECTION_3D&emailId=7ecd31ca-5930&submissionType=VALIDATION

It's been >4h since I submitted the result. What caused this issue and how should I solve it? Thanks!

**Comment by hfslyc** [comment]
Hi, 

Thanks for reporting the outage. The eval servers should be back online. Please try again and let us know if there is any more issue.

Thanks,
Wayne

**Comment by smpotdar** [comment]
I am trying to upload a submission for the validation dataset. I am getting the same issue. Is the eval server still on?

`UNAVAILABLE: server(s) are not responding [type.googleapis.com/util.ErrorSpacePayload='RPC::UNREACHABLE']`
