### ISSUE TITLE
Data visualization script for motion prediction

### ISSUE THREAD

**Issue by BJHYZJ** [waymo-research/waymo-open-dataset#582]
Dear author, do you have a  data visualization script for motion prediction dataset? I did not find it in the program. I really hope that you could provide it or tell me the location of the script. Thank you very much.

**Comment by scott-ettinger** [comment]
Hi, 

We don't currently have a comprehensive visualization for the motion dataset.  We plan to include this in a future release. There is a very simple visualization in the [motion tutorial](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_motion.ipynb).
