### ISSUE TITLE
provide lidar segment map

### ISSUE THREAD

**Issue by waveleaf27** [waymo-research/waymo-open-dataset#586]
Hi, 
When parsing LiDAR semantic labels using tutorial/tutorial_3d_semseg.ipynb, the labels shape is [N,2], and the unique labels are:
     [-1,  0,  1,  8, 10, 14, 15, 16, 17, 18, 19, 20, 21, 22, 28, 29, 30, 31, 33, 34, 35, 36, 37, 40, 45, 48, 52],
and the official documentation says there are 23 semantics classes in total:
      Car, Truck, Bus, Motorcyclist, Bicyclist, Pedestrian, Sign, Traffic Light, Pole, Construction Cone, Bicycle, Motorcycle, Building, Vegetation, Tree Trunk, Curb, Road, Lane Marker, Walkable, Sidewalk, Other Ground, Other Vehicle, Undefined

Is there a map that maps ids to categories ? Thanks

**Comment by Kin-Zhang** [comment]
I think the unqiue label is 0-22... If you try the tutorial book here:
https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_3d_semseg.ipynb

But the lidar data looks really weird... I mean when they convert to point, and I directly view with open3d
```python
# vis points_all in o3d with color
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points_all)
o3d.visualization.draw_geometries([pcd])
```
Didn't look like correct points
