### ISSUE TITLE
issue of parsing range images

### ISSUE THREAD

**Issue by waveleaf27** [waymo-research/waymo-open-dataset#587]
the point clounds of TOP-LiDAR  are not correct,  
results:
![image](https://user-images.githubusercontent.com/107839110/211202904-246a1b47-ebbc-49d3-9f2f-7f7e74d115e8.png)

Infos:
    dataset waymo_v1.4.0

envs:
    tensorboard                 2.11.0
    tensorboard-data-server     0.6.1
    tensorboard-plugin-wit      1.8.1
    tensorflow                  2.6.0
    tensorflow-estimator        2.11.0
    tensorrt                    8.0.1.6
    waymo-open-dataset-tf-2-6-0 1.4.9
    Werkzeug                    2.2.2
    wheel                       0.37.1
    wrapt                       1.12.1
    zipp                        3.11.0

data:
FILENAME = segment-9415086857375798767_4760_000_4780_000_with_camera_labels.tfrecord

code:(offical code in tutorial/tutorial_3d_semseg.ipynb)

**Comment by waveleaf27** [comment]
import os
import matplotlib.pyplot as plt
import tensorflow.compat.v1 as tf
import numpy as np

tf.enable_eager_execution()

from waymo_open_dataset.utils import  frame_utils
from waymo_open_dataset import dataset_pb2 as open_dataset
from waymo_open_dataset.protos import segmentation_metrics_pb2
from waymo_open_dataset.protos import segmentation_submission_pb2

dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')

def convert_range_image_to_point_cloud_labels(frame,
                                              range_images,
                                              segmentation_labels,
                                              ri_index=0):
  """Convert segmentation labels from range images to point clouds.

  Args:
    frame: open dataset frame
    range_images: A dict of {laser_name, [range_image_first_return,
       range_image_second_return]}.
    segmentation_labels: A dict of {laser_name, [range_image_first_return,
       range_image_second_return]}.
    ri_index: 0 for the first return, 1 for the second return.

  Returns:
    point_labels: {[N, 2]} list of 3d lidar points's segmentation labels. 0 for
      points that are not labeled.
  """
  calibrations = sorted(frame.context.laser_calibrations, key=lambda c: c.name)
  point_labels = []
  for c in calibrations:
    range_image = range_images[c.name][ri_index]
    range_image_tensor = tf.reshape(
        tf.convert_to_tensor(range_image.data), range_image.shape.dims)
    range_image_mask = range_image_tensor[..., 0] > 0

    if c.name in segmentation_labels:
      sl = segmentation_labels[c.name][ri_index]
      sl_tensor = tf.reshape(tf.convert_to_tensor(sl.data), sl.shape.dims)
      sl_points_tensor = tf.gather_nd(sl_tensor, tf.where(range_image_mask))
    else:
      num_valid_point = tf.math.reduce_sum(tf.cast(range_image_mask, tf.int32))
      sl_points_tensor = tf.zeros([num_valid_point, 2], dtype=tf.int32)
      
    point_labels.append(sl_points_tensor.numpy())
  return point_labels


for data in dataset:
    frame = open_dataset.Frame()
    frame.ParseFromString(bytearray(data.numpy()))
    frame.lasers.sort(key=lambda laser: laser.name)
    if frame.lasers[0].ri_return1.segmentation_label_compressed:
      print(frame.context.name)
      print(frame.context.stats)

      (range_images, camera_projections, segmentation_labels,
      range_image_top_pose) = frame_utils.parse_range_image_and_camera_projection(
          frame)

      points, cp_points = frame_utils.convert_range_image_to_point_cloud(
          frame, range_images, camera_projections, range_image_top_pose)
      points_ri2, cp_points_ri2 = frame_utils.convert_range_image_to_point_cloud(
          frame, range_images, camera_projections, range_image_top_pose, ri_index=1)

      point_labels = convert_range_image_to_point_cloud_labels(
          frame, range_images, segmentation_labels)
      point_labels_ri2 = convert_range_image_to_point_cloud_labels(
          frame, range_images, segmentation_labels, ri_index=1)

      # 3d points in vehicle frame.
      points_all = np.concatenate(points, axis=0)
      points_all_ri2 = np.concatenate(points_ri2, axis=0)
      # point labels.
      point_labels_all = np.concatenate(point_labels, axis=0)
      point_labels_all_ri2 = np.concatenate(point_labels_ri2, axis=0)
      # camera projection corresponding to each point.
      cp_points_all = np.concatenate(cp_points, axis=0)
      cp_points_all_ri2 = np.concatenate(cp_points_ri2, axis=0)

      points = np.concatenate([points_all, points_all_ri2], axis=0)
      labels = np.concatenate([point_labels_all, point_labels_all_ri2], axis=0)
      pts_color = np.zeros((points.shape[0], 3))

      # vis points and segment label

**Comment by VincentCa** [comment]
Hi! I've manually checked this run segment, and can not reproduce the issue. While I haven't had the chance to verify your custom code, running `tutorial_3d_semseg.ipynb` and adding a simple 3D visualization of `points_all` and `points_all_ri2` doesn't reveal such discretization artifacts. I would suggest checking whether this issue persists for other run segments, and maybe double-checking your code modifications/visualization code. Feel free to report back what you find here, thanks!

**Comment by waveleaf27** [comment]
Thanks for reply, I will double-check code and update this session.
