### ISSUE TITLE
question about the methods to obtain intensity of the corresponding point cloud

### ISSUE THREAD

**Issue by Gus-Guo** [waymo-research/waymo-open-dataset#59]
Hi, I want to use the waymo_open_dataset/utils/frame_utils.py file to produce the corresponding intensity, and the codes are like this:
range_image_intensity = range_image_tensor[..., 1]
range_image_mask = range_image_tensor[..., 0] > 0
points_intensity_tensor = tf.gather_nd(range_image_intensity, tf.compat.v1.where(range_image_mask))

But the obtained intensity values of some points are above 1 and even up to 49664. Are there problems with my codes? Thank you very much.

**Comment by peisun1115** [comment]
intensity is float number. It is expected.
