### ISSUE TITLE
There is something wrong with the website.

### ISSUE THREAD

**Issue by Longzhong-Lin** [waymo-research/waymo-open-dataset#596]
The website "https://waymo.com/open/" does not function rightly, when I log in the Challenges. The "submit" button turns into "working" and cannot be click on, as in the figure.
![image](https://user-images.githubusercontent.com/81036197/221389967-186f5462-4b3b-45f5-896a-87d41f0d8717.png)

**Comment by scott-ettinger** [comment]
Could you try this again?  It should be working now.  Thank you for flagging this.

**Comment by Longzhong-Lin** [comment]
Yes, it works!

**Comment by Longzhong-Lin** [comment]
In "Download" and "Challenges", after I fill out the form and read terms to the bottom, I still can not click the check boxes. I have tried cleaning the cookies and it did not work.
