### ISSUE TITLE
The height of the camera center

### ISSUE THREAD

**Issue by ZLTJohn** [waymo-research/waymo-open-dataset#597]
Hi, I'm very interesting in different camera settings in different datasets.
Recently I'm observing the differences of object distribution across different datasets like Waymo Open and NuScenes. My question is that, what are the height of the cameras from the ground?
I can use camera extrinsics to recover the heights from ego center to the cameras, but I can not get the exact height of the camera from the ground. I can't infer it by the transformations, since I have no idea about the properties of the global origin or ego center.

To be specific, could you please tell me what is the height of the five camera optical centers of Waymo Perception Dataset, relative to the ground? I mean the ground that vehicle is driving on. Or, maybe there is any method to recover this property from the existing open dataset?
![image](https://user-images.githubusercontent.com/67246790/221401598-ca57af20-75c0-429c-8511-cd6fc532cc29.png)

**Comment by VincentCa** [comment]
Hi, great question! The vehicle frame origin (ego center) is located on the ground, so you can read the height from the camera extrinsics directly.

**Comment by ZLTJohn** [comment]
Here is one of the camera pose I get in the dataset：
CAM_FRONT (front camera to ego)
 [[-0.    0.    1.    1.54]
 [-1.   -0.02 -0.   -0.02]
 [ 0.02 -1.    0.    2.12]
 [ 0.    0.    0.    1.  ]]
So the height is approximately 2.12 meters?

**Comment by VincentCa** [comment]
Yes, that's correct. Remember that Waymo has more than one ride-hailing vehicle type, including [Jaguar I-PACE](https://blog.waymo.com/2019/08/meet-our-newest-self-driving-vehicle.html) and [Chrysler Pacifica](https://medium.com/waymo/a-first-look-at-our-waymo-fully-self-driving-chrysler-pacifica-hybrid-minivans-5677e5e67750) vehicles. The Waymo Open Dataset was collected entirely on Chrysler Pacifica Minivans.

**Comment by ZLTJohn** [comment]
Thank you! It helps a lot.
