### ISSUE TITLE
Something go wrong in submission website.

### ISSUE THREAD

**Issue by Abyssaledge** [waymo-research/waymo-open-dataset#598]
Every time I open the 3D detection submission website, the submission button disappears and it shows "working" all the time, as the attached image shows.
![image](https://user-images.githubusercontent.com/21312704/221410281-24e43e4a-7526-4d8c-bcd6-1ba7c8eab227.png)

**Comment by scott-ettinger** [comment]
Could you try this again?  It should be working now.  Thank you for flagging this.

**Comment by Abyssaledge** [comment]
Thanks, it works now.
