### ISSUE TITLE
Cannot Register to Access Open Dataset

### ISSUE THREAD

**Issue by danmartinez78** [waymo-research/waymo-open-dataset#599]
I am attempting to sign up and agree to the license terms.

I sign in with a google account, complete the form, check the agreement box, and click Agree and Register.

The page only refreshes.

I have tried:

- using a different google account
- incognito mode
- different browser
- different device
- different network

All have yielded same result.

**Comment by ies0411** [comment]
me too....how to access dataset????

**Comment by juanluishortelano** [comment]
same here

**Comment by TheLastFrame** [comment]
+1

**Comment by shengchao-y** [comment]
same problem

**Comment by scott-ettinger** [comment]
Could you try this again? It should be working now.  Thank you for flagging this issue.

**Comment by TheLastFrame** [comment]
Just tested works again, thanks!

**Comment by danmartinez78** [comment]
Verified that sign up is now working correctly. Closing issue.
