### ISSUE TITLE
Problematic fake bin files to test evaluation tools

### ISSUE THREAD

**Issue by DianCh** [waymo-research/waymo-open-dataset#60]
Hi! I've encountered problems regarding the **detection & tracking** evaluation tools.

I've built the metrics computation tool for tracking using the most recent repository (i.e. directly clone from the repo without changing the branch). However, I can't get the expected results on the two fake pd/gt binary files provided, as documented at the beginning of the source code.

All I get is the following error:

`WARNING: Logging before InitGoogleLogging() is written to STDERR`
`F1028 14:25:46.491297 32399 mot.cc:60] Duplicate ground truths found for tracking ID 3S1Jzdq9a6Jqyhdf8cuKzA.`
`*** Check failure stack trace: ***`
`Aborted (core dumped)`

The bazel build spits no error and finished building. How can I test the validity of the compiled **tracking evaluation tool** ?

As for the **detection evaluation tool**, the binary tool took those two bin pd/gt files and produced some results, except that the results are different from the values suggested in the comments in compute_detection_metrics_main.cc:

Evaluation on my machine:

OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [mAP 0.0693958] [mAPH 0.0588563]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2: [mAP 0.103343] [mAPH 0.043977]
OBJECT_TYPE_TYPE_SIGN_LEVEL_2: [mAP 0.0455449] [mAPH 0.0333994]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_2: [mAP 0.0716681] [mAPH 0.0651036]
RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_2: [mAP 0.129427] [mAPH 0.0956238]
RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_2: [mAP 0.0490004] [mAPH 0.0422815]
RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_2: [mAP 0.0458333] [mAPH 2.20291e-09]
RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_2: [mAP 0.0954545] [mAPH 0.0442826]
RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_2: [mAP 0.141667] [mAPH 0.0699209]
RANGE_TYPE_SIGN_[0, 30)_LEVEL_2: [mAP 0.112251] [mAPH 0.0871696]
RANGE_TYPE_SIGN_[30, 50)_LEVEL_2: [mAP 0.0326389] [mAPH 0.0153958]
RANGE_TYPE_SIGN_[50, +inf)_LEVEL_2: [mAP 0.015625] [mAPH 0.0146571]
RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]

Evaluation suggested in the code comments:

OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [mAP 0.0650757] [mAPH 0.055601]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2: [mAP 0.101786] [mAPH 0.0473937]
OBJECT_TYPE_TYPE_SIGN_LEVEL_2: [mAP 0.0500082] [mAPH 0.0366725]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_2: [mAP 0.0784186] [mAPH 0.0709105]
RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_2: [mAP 0.133955] [mAPH 0.103888]
RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_2: [mAP 0.0522752] [mAPH 0.0460845]
RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_2: [mAP 0.0458333] [mAPH 2.20291e-09]
RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_2: [mAP 0.110526] [mAPH 0.0512746]
RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_2: [mAP 0.15] [mAPH 0.074034]
RANGE_TYPE_SIGN_[0, 30)_LEVEL_2: [mAP 0.128993] [mAPH 0.100171]
RANGE_TYPE_SIGN_[30, 50)_LEVEL_2: [mAP 0.0354839] [mAPH 0.0171309]
RANGE_TYPE_SIGN_[50, +inf)_LEVEL_2: [mAP 0.0164904] [mAPH 0.01548]
RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_2: [mAP 0] [mAPH 0]
RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_2: [mAP 0] [mAPH 0]

There are significant differences in the values between the two. Could you please help me verify if my compilation is working correctly?

Thank you!

**Comment by bairdzhang** [comment]
Hi DianCh, I suspect you get the incorrect order when passing prediction and ground-truth files. It should be `/path/to/compute_detection_metrics_main pd_filename gt_filename`.

**Comment by DianCh** [comment]
> Hi DianCh, I suspect you get the incorrect order when passing prediction and ground-truth files. It should be `/path/to/compute_detection_metrics_main pd_filename gt_filename`.

Hi bairdzhang, thank you very much for pointing that out! I fixed the mismatch problem, but the problem in tracking evaluation still remains.

**Comment by bairdzhang** [comment]
For tracking, it is also `pd_file gt_file`. I was not able to reproduce the error after fixing the order.

**Comment by DianCh** [comment]
What does your tracking evaluation output look like? Mine now looks like:

...(many similar lines)
W1028 18:08:14.108418 33698 mot.cc:48] Duplicate predictions found for tracking ID hcKLopO8tYQKXJxXtNo9tA (subset id 2).
W1028 18:08:14.108427 33698 mot.cc:48] Duplicate predictions found for tracking ID hcKLopO8tYQKXJxXtNo9tA (subset id 1).
W1028 18:08:14.108440 33698 mot.cc:48] Duplicate predictions found for tracking ID hcKLopO8tYQKXJxXtNo9tA (subset id 2).
W1028 18:08:14.108456 33698 mot.cc:48] Duplicate predictions found for tracking ID hcKLopO8tYQKXJxXtNo9tA (subset id 1).
W1028 18:08:14.108470 33698 mot.cc:48] Duplicate predictions found for tracking ID hcKLopO8tYQKXJxXtNo9tA (subset id 2).

OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
OBJECT_TYPE_TYPE_SIGN_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
OBJECT_TYPE_TYPE_SIGN_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_1: [MOTA 0.145455] [MOTP 0.13926] [Miss 0.636364] [Mismatch 0] [FP 0.218182]
RANGE_TYPE_VEHICLE_[0, 30)_LEVEL_2: [MOTA 0.145455] [MOTP 0.13926] [Miss 0.636364] [Mismatch 0] [FP 0.218182]
RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_1: [MOTA 0.21875] [MOTP 0.15987] [Miss 0.59375] [Mismatch 0] [FP 0.1875]
RANGE_TYPE_VEHICLE_[30, 50)_LEVEL_2: [MOTA 0.21875] [MOTP 0.15987] [Miss 0.59375] [Mismatch 0] [FP 0.1875]
RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_VEHICLE_[50, +inf)_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_PEDESTRIAN_[0, 30)_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_1: [MOTA 0.25] [MOTP 0.0845365] [Miss 0.5] [Mismatch 0] [FP 0.25]
RANGE_TYPE_PEDESTRIAN_[30, 50)_LEVEL_2: [MOTA 0.25] [MOTP 0.0845365] [Miss 0.5] [Mismatch 0] [FP 0.25]
RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_PEDESTRIAN_[50, +inf)_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_SIGN_[0, 30)_LEVEL_1: [MOTA 0.227273] [MOTP 0.151606] [Miss 0.545455] [Mismatch 0] [FP 0.227273]
RANGE_TYPE_SIGN_[0, 30)_LEVEL_2: [MOTA 0.227273] [MOTP 0.151606] [Miss 0.545455] [Mismatch 0] [FP 0.227273]
RANGE_TYPE_SIGN_[30, 50)_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_SIGN_[30, 50)_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_SIGN_[50, +inf)_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_SIGN_[50, +inf)_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_CYCLIST_[0, 30)_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_CYCLIST_[30, 50)_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_1: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]
RANGE_TYPE_CYCLIST_[50, +inf)_LEVEL_2: [MOTA 0] [MOTP 0] [Miss 0] [Mismatch 0] [FP 0]

**Comment by peisun1115** [comment]
Not sure what is the question for tracking.  Warnings like 'Duplicate predictions found for tracking' is fine. It is because the the fake pd file is generated by a tool which has duplicate  detections.

**Comment by DianCh** [comment]
Ok, this clears my doubts. Thank you so much!
