### ISSUE TITLE
Error of submission to 3D Segmentation: INVALID_ARGUMENT: Prediction and Groudtruth length do not match

### ISSUE THREAD

**Issue by foolhard** [waymo-research/waymo-open-dataset#600]
Hi, 

I got some issues when I try to submit results to 3D segmentation evaluation server. 

**1. **The entries of validation set and test set may be oppisite:****

I use _tutorial_3d_semseg.ipynb_ to generate a dummy validation set file and try to submit to server. I got the error as following:

_**INVALID_ARGUMENT: Prediction and Groudtruth length do not match**_

Then I try to submit the val set file to test set leaderboard that has button "Publish to leaderboard". Then I got the result which are all zeros.  
It seems to be very strange. So I try to submit dummy test set file and got the similar error. 

**2. The results of the dummy file are zero. Is this corrct?**

Best regards

**Comment by foolhard** [comment]
Fixed.

**Comment by ppbangKGT** [comment]
> So I try to submit dummy test set file and got the similar error.

Hi, I met the same problem. The entries of validation set and test set seem to be oppisite. How did you fix this problem?
Thanks for your time.
