### ISSUE TITLE
ERROR: No matching distribution found for waymo_open_dataset_tf_2_6_0==1.5.0

### ISSUE THREAD

**Issue by alexgorban** [waymo-research/waymo-open-dataset#603]
Heads up the PIP package `waymo_open_dataset_tf_2_6_0==1.5.0` is not available yet. Please be advised that we are currently addressing the build issues, and we expect to have them resolved by March 20th.

**Comment by hanfeng-wu** [comment]
same here

**Comment by kylevedder** [comment]
Do you have a timeline on fixing the build issues? I would like to use the new map API.

**Comment by alexgorban** [comment]
The new codebase is no longer compatible with TensorFlow 2.6.
The new package was just released, but only for TensorFlow 2.11. Please give it a try:
```
pip install waymo-open-dataset-tf-2.11.0==1.5.0
```

**Comment by jayhsu0627** [comment]
please update this tutorial https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_v2.ipynb
