### ISSUE TITLE
map_feature.WhichOneof("feature_data") returns None (Motion Dataset v1.2.0)

### ISSUE THREAD

**Issue by BenQLange** [waymo-research/waymo-open-dataset#604]
Hi, 

When processing map features `map_pb2.MapFeature` from the motion dataset v.1.2.0, some data samples have feature type None (`map_feature.WhichOneof("feature_data") returns None`). Is it expected or is some data missing?

My setup:
```
Tested on validation.tfrecord-00134-of-00150
Motion dataset = 1.2.0
waymo-open-dataset-tf-2-4-0 = 1.4.1
tensorflow = 2.4.0
```

**Comment by scott-ettinger** [comment]
It is possible that a very small number of scenarios do not have map data.  If you have an example of this could you send the scenario_id (the contents of the scenario_id field) ?

**Comment by BenQLange** [comment]
I noticed that it occurs in the majority of scenes. I think the issue is not that the scenario has no map, but some objects in protobuf.map_features are of type `None`. It looks like some type of padding to me. When I skip those map_features and visualize the scenario it looks complete to me but maybe I'm missing something. 

```
sample = validation.tfrecord-00134-of-00150
scenario_id = 2abd7cb0c29d14d0
```

Content of map_pb2.MapFeature feature with None type:
```  
id: 250
```

**Comment by scott-ettinger** [comment]
It looks like the issue is that we are missing an update in the pip package and the Scenario proto has changed to add a new map feature type. This causes the missing feature type you are seeing.  We should be updating the pip package today. Sorry for the delay on this.  Please check late today or tomorrow to see if the pip package is updated.

**Comment by alexgorban** [comment]
New pip package was just released. Please feel free to reopen the issue if something is not working 
```
pip install waymo-open-dataset-tf-2.11.0==1.5.0
```
