### ISSUE TITLE
Question: Is it possible to retrieve the location where a sample was recorded?

### ISSUE THREAD

**Issue by mh0797** [waymo-research/waymo-open-dataset#607]
Hi,

I am wondering if it is possible to retrieve the location where a sample was recorded (San Francisco, Phoenix, Mountain View, Los Angeles, Detroit, or Seattle).
Is there a key in the tensorflow records from which this can be infered?
Or is there a list with a mapping of sample ids and locations?

**Comment by alexgorban** [comment]
Hi,

in the v1.4.6 human readable location (e.g. CHD, SF) of the run segment is stored in [`Frame.context.location` field](https://github.com/waymo-research/waymo-open-dataset/blob/9d0be7c4aeed2ef5e11f2e739537bf2d27cec65b/src/waymo_open_dataset/dataset.proto#L156). In the v2 dataset format it is in the `[StatsComponent].location` column of the StatsComponent table (see [tutorial for details](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_v2.ipynb)).

**Comment by mh0797** [comment]
Hi,
thanks for the reply. My question referred to the motion dataset (v1.1).
I am using the tf.Example proto files containing [these](https://waymo.com/open/data/motion/tfexample) entries.

my code looks as follows:
```
import os
import tensorflow as tf

path_to_dataset = "/path/to/dataset/uncompressed/tf_example/training"
descriptor = "scenario/id"

dataset = tf.data.TFRecordDataset(
        [os.path.join(datapath, f) for f in files], num_parallel_reads=1
)
for data in tqdm(dataset.as_numpy_iterator()):
    data = tf.io.parse_single_example(data, generate_features_description())
    print(data[descriptor]) 
```

is there a value that I can use for `descriptor` to obtain the location where this scenario was recorded?

If not, how can I extract the location from the tf.Example ?

**Comment by miladsasha** [comment]
> Hi,
> 
> in the v1.4.6 human readable location (e.g. CHD, SF) of the run segment is stored in [`Frame.context.location` field](https://github.com/waymo-research/waymo-open-dataset/blob/9d0be7c4aeed2ef5e11f2e739537bf2d27cec65b/src/waymo_open_dataset/dataset.proto#L156). In the v2 dataset format it is in the `[StatsComponent].location` column of the StatsComponent table (see [tutorial for details](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_v2.ipynb)).

 This can help you narrow down the geographic area, but not pinpoint exact coordinates. how can I find more precise location coordiantes?
