### ISSUE TITLE
waymo-open-dataset compilation problem

### ISSUE THREAD

**Issue by atanasko** [waymo-research/waymo-open-dataset#609]
Hi,

I try to compile waymo-open-dataset with the following system setup:

- Debian GNU/Linux bookworm (from testing repository)
- Python3.11
- bazel 3.1.0
- TensorFlow 2.11.1

I change TF_VERSION in ~/waymo-od/pip_pkg_scripts/build.sh

`export TF_VERSION="${TF_VERSION:-2.11.1}"`

afterwards execute

`./congigure.sh`

and when I try 

`bazel test waymo_open_dataset/metrics:all`

I have the following error 

`
ERROR: /home/atanasko/.cache/bazel/_bazel_atanasko/96edba5dee387bb50ea4a7ae9b2351ec/external/com_google_absl/absl/BUILD.bazel:100:1: unexpected keyword 'visibility' in call to _config_setting_group(name, match_any = [], match_all = [])
ERROR: Analysis of target '//waymo_open_dataset/metrics:iou' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.093s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 2 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 2 targets configured)
`

Any advice what the problem can be? I do not have much experience with using bazel.

**Comment by alexgorban** [comment]
Hi, with the v1.5.0 release we are using a new build configuration, which no longer has `./configure.sh`. Please pull the most recent version of the code and refer to https://github.com/waymo-research/waymo-open-dataset/tree/master/src/waymo_open_dataset/pip_pkg_scripts for instructions how to build the package. Please feel free to reopen the issue if you experience build issues with the new build config.

**Comment by atanasko** [comment]
@alexgorban thanks! I compile successfully now.
