### ISSUE TITLE
Questions regarding tracking evaluation

### ISSUE THREAD

**Issue by DianCh** [waymo-research/waymo-open-dataset#61]
Hi all, I have a few questions regarding the usage of tracking evaluation tool:

1. As for now, it seems that the tool only supports 3D tracking evaluation, because when I used 2D labels to pack the ground truth and tested, the output suggested "W1028 17:04:39.338112 32869 iou.cc:134] Tiny box dim seen, return 0.0 IOU." Just want to confirm if that's the case. And if so, would you consider supporting 2D tracking evaluation, or I'll have to work on my own?

2. To produce the prediction Objects message, how do we determine the difficulty level for each predicted box?

Thank you for any clarification!

**Comment by bairdzhang** [comment]
I haven't played with the tracking evaluation code so am not quite sure. But for the first question, maybe you can try to modify https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_tracking_metrics_main.cc#L115. For the second question, I guess we do not need to specify difficult_level for pd_objects, instead,  we need to specify for gt_objects. Please correct me if I misunderstand anything. Thanks!

**Comment by peisun1115** [comment]
This is correct.

Slight more details for Q 2: In the 1.0 data release, we did not populate human labeled difficulty. We will add that in the next data release.

**Comment by DianCh** [comment]
Ok, just to confirm these things so I can work on implementing the 2D evaluator.

As for the difficulty level, so for now we can just leave the field empty/default?

**Comment by peisun1115** [comment]
Yes, you can do that (or just set them to 1 which is level_1). We will update the data with human labeled difficulty soon.
