### ISSUE TITLE
TypeError when running sim agent tutorial

### ISSUE THREAD

**Issue by jchengai** [waymo-research/waymo-open-dataset#610]
I encounter numerous TypeErrors while working with the sim agent tutorial, predominantly associated with protobuf and TensorFlow typing issues...

For example, in

https://github.com/waymo-research/waymo-open-dataset/blob/9d0be7c4aeed2ef5e11f2e739537bf2d27cec65b/src/waymo_open_dataset/utils/sim_agents/converters.py#L63-L72

the TypeError can be fixed by converting everthing to numpy
```python
  for idx in range(trajectories.object_id.shape[0]):
    simulated_trajectories.append(sim_agents_submission_pb2.SimulatedTrajectory(
        center_x=trajectories.x[idx].numpy(),
        center_y=trajectories.y[idx].numpy(),
        center_z=trajectories.z[idx].numpy(),
        heading=trajectories.heading[idx].numpy(),
        object_id=trajectories.object_id[idx].numpy(),
    ))
  return sim_agents_submission_pb2.JointScene(
      simulated_trajectories=simulated_trajectories)
```

Similarly, I don't get why some entries are not converted to numpy.

https://github.com/waymo-research/waymo-open-dataset/blob/9d0be7c4aeed2ef5e11f2e739537bf2d27cec65b/src/waymo_open_dataset/wdl_limited/sim_agents_metrics/metrics.py#L174-L188

fixed by
```python
  return sim_agents_metrics_pb2.SimAgentMetrics(
      scenario_id=scenario.scenario_id,
      metametric=metametric.numpy(),
      average_displacement_error=average_displacement_error.numpy(),
      min_average_displacement_error=min_average_displacement_error.numpy(),
      linear_speed_likelihood=linear_speed_likelihood.numpy(),
      linear_acceleration_likelihood=linear_accel_likelihood.numpy(),
      angular_speed_likelihood=angular_speed_likelihood.numpy(),
      angular_acceleration_likelihood=angular_accel_likelihood.numpy(),
      distance_to_nearest_object_likelihood=distance_to_obj_likelihood.numpy(),
      collision_indication_likelihood=collision_likelihood.numpy(),
      time_to_collision_likelihood=ttc_likelihood.numpy(),
      distance_to_road_edge_likelihood=distance_to_road_edge_likelihood.numpy(),
      offroad_indication_likelihood=offroad_likelihood.numpy(),
  )
```

**Comment by nicomon24** [comment]
Hi @jchengai, could you please provide me some more info on where and how this if failing? 
1. What version of the repo did you install? Could you check the TF version and protobuf versions?
2. Which cell of the notebook is failing specifically? 

I tried running the tutorial with the libraries packaged by pip and it's working correctly. If you could help me reproduce locally I'll update the code (casting to numpy is probably less error prone anyway).
Thanks!

**Comment by jchengai** [comment]
Hi @nicomon24, thanks for your kind response.  It's strange that I cannot reproduce the typing error in a clean docker environment.  

However, I can confirm that another issue continues to occur.

![image](https://user-images.githubusercontent.com/86758357/228445758-8d0da74b-5587-4fb8-b2fc-aab54f8a4b7b.png)

The Dockerfile to reproduce:

```dockerfile
FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y git python3 python3-pip libopenexr-dev

WORKDIR /home
RUN git clone https://github.com/waymo-research/waymo-open-dataset
RUN pip install waymo-open-dataset-tf-2.11.0==1.5.0 ipykernel
``` 

I'll what caused the typing error in my env. Thanks.

**Comment by jchengai** [comment]
It's an internal problem of the vscode notebook, sorry.
