### ISSUE TITLE
ModuleNotFoundError: No module named 'waymo_open_dataset.wdl_limited'

### ISSUE THREAD

**Issue by imhuaweizhu** [waymo-research/waymo-open-dataset#611]
I followed [](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_sim_agents.ipynb), but when I run this cell in Colab, I got _ModuleNotFoundError: No module named 'waymo_open_dataset.wdl_limited'_
```
# Imports
import os
import tarfile
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import tqdm

from waymo_open_dataset.wdl_limited.sim_agents_metrics import metric_features
from waymo_open_dataset.wdl_limited.sim_agents_metrics import metrics

from waymo_open_dataset.protos import scenario_pb2
from waymo_open_dataset.protos import sim_agents_submission_pb2

from waymo_open_dataset.utils.sim_agents import submission_specs
from waymo_open_dataset.utils.sim_agents import test_utils as sim_agents_test_utils
from waymo_open_dataset.utils.sim_agents import visualizations
from waymo_open_dataset.utils import trajectory_utils

# Set matplotlib to jshtml so animations work with colab.
from matplotlib import rc
rc('animation', html='jshtml')
```

**Comment by alexgorban** [comment]
Did you install the new pip package?

```
!pip install waymo-open-dataset-tf-2.11.0==1.5.0
```

**Comment by imhuaweizhu** [comment]
yes

**Comment by imhuaweizhu** [comment]
!rm -rf waymo-od > /dev/null
!git clone https://github.com/waymo-research/waymo-open-dataset.git waymo-od
!cd waymo-od && git branch -a
!cd waymo-od && git checkout remotes/origin/master
!pip3 install --upgrade pip
# install packagges
!pip3 install waymo-open-dataset-tf-2.11.0
!pip3 install tqdm

**Comment by imhuaweizhu** [comment]
This is what I have installed.

**Comment by imhuaweizhu** [comment]
I'm running this on Google Colab

**Comment by imhuaweizhu** [comment]
It's working now. I think you need to update [](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial.ipynb) . Because in that page, it says `!pip3 install waymo-open-dataset-tf-2.6.0`, not `!pip3 install waymo-open-dataset-tf-2.11.0`

**Comment by alexgorban** [comment]
The tutorial was updated.
