### ISSUE TITLE
after run `pip install waymo-open-dataset-tf-2.11.0==1.5.0` , bug still: ImportError: cannot import name 'dataset_pb2' from 'waymo_open_dataset' (unknown location)

### ISSUE THREAD

**Issue by Wu-Xiang123** [waymo-research/waymo-open-dataset#613]
I build a new conda env, then successfully run `pip install waymo-open-dataset-tf-2.11.0==1.5.0`, but when I use `from waymo_open_dataset import v2`, bug happen:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 14
     12 import sys
     13 sys.path.append(".[./utils](https://vscode-remote+ssh-002dremote-002bs1.vscode-resource.vscode-cdn.net/mnt/gt-data/wuxiang/projects/waymo-open-dataset/notebooks/utils)")
---> 14 from waymo_open_dataset import v2
     15 from ossutil import OssUtil, oss
     16 from quick_pool import quick_pool

File [/mnt/gt-data/wuxiang/anaconda3/envs/waymo/lib/python3.9/site-packages/waymo_open_dataset/v2/__init__.py:29](https://vscode-remote+ssh-002dremote-002bs1.vscode-resource.vscode-cdn.net/mnt/gt-data/wuxiang/anaconda3/envs/waymo/lib/python3.9/site-packages/waymo_open_dataset/v2/__init__.py:29)
     27 from waymo_open_dataset.v2.perception import pose as _pose
     28 from waymo_open_dataset.v2.perception import segmentation as _segmentation
---> 29 from waymo_open_dataset.v2.perception.utils import lidar_utils as _lidar_utils
     31 # Supported components.
     32 CameraBoxComponent = _box.CameraBoxComponent

File [/mnt/gt-data/wuxiang/anaconda3/envs/waymo/lib/python3.9/site-packages/waymo_open_dataset/v2/perception/utils/lidar_utils.py:21](https://vscode-remote+ssh-002dremote-002bs1.vscode-resource.vscode-cdn.net/mnt/gt-data/wuxiang/anaconda3/envs/waymo/lib/python3.9/site-packages/waymo_open_dataset/v2/perception/utils/lidar_utils.py:21)
     17 from typing import Optional, TypeVar
     19 import tensorflow as tf
---> 21 from waymo_open_dataset import dataset_pb2 as _v1_dataset_pb2
     22 from waymo_open_dataset.utils import range_image_utils
     23 from waymo_open_dataset.utils import transform_utils

ImportError: cannot import name 'dataset_pb2' from 'waymo_open_dataset' (unknown location)

**Comment by alexgorban** [comment]
I've tried to reproduce the issue in a clean conda environment and in the colab.research.google.com, but in both cases the `from waymo_open_dataset import v2` statement executed without any issues. 

From the Traceback log you provided it looks like this import was executed from some other script and apparently there are `sys.path` manipulations right before the call, which may affect the way python imports modules. Can you please try to execute this line before the sys.path manipulations or in an empty python prompt? If the issue still persists, please share all commands you used to create the conda environment.

**Comment by aryaman-patel** [comment]
I would suggest to try one of the following:
1. [Building your pip packages locally](https://github.com/waymo-research/waymo-open-dataset/tree/master/src/waymo_open_dataset/pip_pkg_scripts)  
2. Use the waymo-open-dataset from the `src` files:
    - To do so you can copy the dependencies from `waymo-open-dataset/src/waym_open_dataset/requirements.in` in a `requirements.txt` file and run `cat requirements.txt | xargs -n 1 pip install` ([source](https://stackoverflow.com/questions/22250483/stop-pip-from-failing-on-single-package-when-installing-with-requirements-txt)) in your python env.
   - (And this step to solve the specific problem you mentioned) To import the protoc files: 
   `protoc ./waymo_open_dataset/protos/*.proto -- python_out=.`
   `protoc ./waymo_open_dataset/dataset.proto --python_out=.`
   `protoc ./waymo_open_dataset/label.proto --python_out=.`
   - To import the `waymo_open_dataset` from `src`: 
```
    import sys
    sys.path.insert(0, '/home/<your_path_here>/waymo-open-dataset/src')
```

**Comment by Wu-Xiang123** [comment]
> I've tried to reproduce the issue in a clean conda environment and in the colab.research.google.com, but in both cases the `from waymo_open_dataset import v2` statement executed without any issues.
> 
> From the Traceback log you provided it looks like this import was executed from some other script and apparently there are `sys.path` manipulations right before the call, which may affect the way python imports modules. Can you please try to execute this line before the sys.path manipulations or in an empty python prompt? If the issue still persists, please share all commands you used to create the conda environment.

Thanks for your reply! It finally turned out to be the problem @aryaman-patel pointed out. After run protoc commands, it works now.

**Comment by Wu-Xiang123** [comment]
> I would suggest to try one of the following:
> 
> 1. [Building your pip packages locally](https://github.com/waymo-research/waymo-open-dataset/tree/master/src/waymo_open_dataset/pip_pkg_scripts)
> 2. Use the waymo-open-dataset from the `src` files:
>    
>    * To do so you can copy the dependencies from `waymo-open-dataset/src/waym_open_dataset/requirements.in` in a `requirements.txt` file and run `cat requirements.txt | xargs -n 1 pip install` ([source](https://stackoverflow.com/questions/22250483/stop-pip-from-failing-on-single-package-when-installing-with-requirements-txt)) in your python env.
>    * (And this step to solve the specific problem you mentioned) To import the protoc files:
>      `protoc ./waymo_open_dataset/protos/*.proto -- python_out=.`
>      `protoc ./waymo_open_dataset/dataset.proto --python_out=.`
>      `protoc ./waymo_open_dataset/label.proto --python_out=.`
>    * To import the `waymo_open_dataset` from `src`:
> 
> ```
>     import sys
>     sys.path.insert(0, '/home/<your_path_here>/waymo-open-dataset/src')
> ```

Thanks a lot, `protoc` commands just works for me! By the way, it is also the only way works for me, even if i install waymo by pip, proto files still does not exist in the site-packeges, I have to generate them by myself.
