### ISSUE TITLE
GPS coordinates associated with sensor measurements.

### ISSUE THREAD

**Issue by SubMishMar** [waymo-research/waymo-open-dataset#614]
Hi,
Thanks for this amazing dataset. Do you provide or plan to provide GPS coordinates associated with each sensor (lidar/camera) measurement? I see that the newest version has some map information, but does it have GPS?

**Comment by alexgorban** [comment]
Hi, there are no plans to release GPS coordinates, but there is 3D location information in a local coordinate frame associated with each segment.
