### ISSUE TITLE
how to remap instance_id to global in v2

### ISSUE THREAD

**Issue by Wu-Xiang123** [waymo-research/waymo-open-dataset#615]
can you update tutorial_2d_pvps.ipynb for dataset v2, 2023?

**Comment by alexzzhu** [comment]
Working on this now, will push it in the next code update.

**Comment by alexgorban** [comment]
The [tutorial_2d_pvps](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_2d_pvps.ipynb) was updated, see "Read 2D panoptic segmentation labels from v2 components" section.
