### ISSUE TITLE
Questions about BuildSubsets

### ISSUE THREAD

**Issue by DianCh** [waymo-research/waymo-open-dataset#62]
Hi all, I'm trying to modify the tracking evaluation tool to support 2D evaluation. I have some questions while following the codes. Specifically, could you help explain what a "shard" is in each frame? And what's the simple logic of objects into shards and what to do with shards after that?

And, it seems that the Config protobuf message has some fields to be deprecated, which I don't quite understand the meanings and usage. Could you please explain how "score_cutoffs" and "num_desired_score_cutoffs" are used?

Thank you so much! I really appreciate the contribution to this dataset from you guys all.

**Comment by peisun1115** [comment]
1. To support 2D, you only need to change https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_tracking_metrics_main.cc#L115 to other types such TYPE_2D or TYPE_AA2D( https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/label.proto#L41-L45)

2. Shard a way to split a set of objects (a set of ground truths or predictions). The logic to shard object is defined by each BreakdownGenerator. It is a way to get breakdown metrics (e.g. range based breakdown).

3.  score_cutoffs is used and num_desired_score_cutoffs is deprecated. I will remove num_desired_score_cutoffs from code to make it clearer.  score_cutoffs specifies ways to sample P/R curve (in detection metrics) or ways to sample MOTA (each MOTA needs to specify a score cutoff to select predictions for each frame).
