### ISSUE TITLE
ModuleNotFoundError: No module named 'deeplab2'

### ISSUE THREAD

**Issue by taerkk** [waymo-research/waymo-open-dataset#620]
When running the panoptic segmentation tutorial, I get an error:
`ModuleNotFoundError: No module named 'deeplab2'` 
when executing the following:
`from waymo_open_dataset.wdl_limited.camera_segmentation import camera_segmentation_metrics`
I installed the latest Waymo open dataset package:
`!pip install waymo-open-dataset-tf-2.11.0==1.5.0`
Would it be possible to get a package with DeepLab2 integrated? Thanks.

**Comment by alexzzhu** [comment]
Hi, we have made some improvements that should be packaged in our next update to the code base within the next few days. With the changes, you'll still have to clone the deeplab2 repo, but that should be it. I'll double back once the changes are pushed.

**Comment by alexgorban** [comment]
Just updated [Waymo Open Dataset 2D Panoramic Video Panoptic Segmentation Tutorial](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_2d_pvps.ipynb):
- updated pip package version to v1.5.1
- added a cell to download required deeplab2 modules, build and install a minimal pip package for it:

```
!pip3 install waymo-open-dataset-tf-2-11-0==1.5.1
!wget https://raw.githubusercontent.com/waymo-research/waymo-open-dataset/master/src/waymo_open_dataset/pip_pkg_scripts/install_deeplab2.sh -O - | bash
```

Please feel free to re-open the ticket if you still experience the issue.

**Comment by taerkk** [comment]
Thank you @alexzzhu & @alexgorban for fixing the issues!
