### ISSUE TITLE
Can't find  driveway in the data?

### ISSUE THREAD

**Issue by pengzhenghao** [waymo-research/waymo-open-dataset#625]
Hi,

When I am reading a map_feature, I find that `map_feature.HasField("driveway")` will raise error and I hardly see any tfrecord contains the driveway information (probably because I haven't tried all trfrecord yet.)

I am reading tfrecords from training_20s in waymo open dataset 1.2.0, which is supposed to be updated with "driveway" and "entrances". Could you elaborate more on these two newly introduced data? Thank!

**Comment by scott-ettinger** [comment]
Hi.  Here is a brief code snippet you can try in colab (you will have to replace the path to the data files): 

```
import tensorflow as tf
from waymo_open_dataset.protos import scenario_pb2

def load_tfrecord(filename: str, proto_type: Any, index: int):
  """Loads a single record from a tfrecord file."""

  dataset = tf.data.TFRecordDataset(filename, compression_type='')

  count = 0
  for data in dataset:
    proto_str = bytearray(data.numpy())
    if count == index:
      break
    count += 1

  proto = proto_type.FromString(proto_str)
  del dataset
  return proto


filename = '<your_path_to_data_files>/training_20s.tfrecord-00015-of-01000'
scenario = load_tfrecord(filename, scenario_pb2.Scenario, 0)

count = 0
num_points = 0
for map_feature in scenario.map_features:
  if map_feature.HasField('driveway'):
    count += 1
    num_points += len(map_feature.driveway.polygon)

print(f'Number of driveway features: {count}')
print(f'Number of total driveway points: {num_points}')
```

For me this prints the following when run:
Number of driveway features: 34
Number of total driveway points: 136

Please let me know if you have further questions.

**Comment by pengzhenghao** [comment]
That’s great! Thank you so much! For those have similar issue, also remember to setup latest Waymo toolkit so it will contain the latest proto description files!Best,ZhenghaoOn Apr 10, 2023, at 12:28, Scott ***@***.***> wrote:﻿
Hi.  Here is a brief code snippet you can try in colab (you will have to replace the path to the data files):
import tensorflow as tf
from waymo_open_dataset.protos import scenario_pb2

def load_tfrecord(filename: str, proto_type: Any, index: int):
  """Loads a single record from a tfrecord file."""

  dataset = tf.data.TFRecordDataset(filename, compression_type='')

  count = 0
  for data in dataset:
    proto_str = bytearray(data.numpy())
    if count == index:
      break
    count += 1

  proto = proto_type.FromString(proto_str)
  del dataset
  return proto


filename = '<your_path_to_data_files>/training_20s.tfrecord-00015-of-01000'
scenario = load_tfrecord(filename, scenario_pb2.Scenario, 0)

count = 0
num_points = 0
for map_feature in scenario.map_features:
  if map_feature.HasField('driveway'):
    count += 1
    num_points += len(map_feature.driveway.polygon)

print(f'Number of driveway features: {count}')
print(f'Number of total driveway points: {num_points}')

For me this prints the following when run:
Number of driveway features: 34
Number of total driveway points: 136
Please let me know if you have further questions.
