### ISSUE TITLE
Is there anyway we can use the v2 for the v1 tfrecord to associate the LiDAR and camera object?

### ISSUE THREAD

**Issue by jayhsu0627** [waymo-research/waymo-open-dataset#628]
Hi guys,

Thanks for providing a comprehensive tutorial for v2, and I'm interested in the usage of `camera_to_lidar_box_association ` for the older version so that it could solve these questions [[1](https://github.com/waymo-research/waymo-open-dataset/issues/212) and [2](https://github.com/waymo-research/waymo-open-dataset/issues/477)].

The application environment I used is `waymo_open_dataset_v_1_3_2` with `waymo-open-dataset-tf-2-6-0`. Therefore, I came up with two solutions:
1. Find a way to install two separate `waymo_open_dataset` packages to include both `tf-2-6-0` and `tf-2.11.0`, therefore, I can call the `v2` whenever I need in the `v1` loop. But it seems impossible to rename the installation(`tf` and `waymo_open_dataset`).
2. Using your v2 tutorial to parse all the segments in the datasets, save the association relationship as a dictionary/table.

Is there anyway easier?

**Comment by JingweiJ** [comment]
Hi, thank you for your question and interests in using the v2!

At the moment, v2 is not supported for older versions. I think your 2nd solution is practical, and the association relationship should be light-weighted in terms of file size.

Best,
Jingwei, on behalf of the Waymo Open Dataset team

**Comment by alexgorban** [comment]
Hi, camera to lidar box association information is also available in the v1 dataset format - [Label.association](https://github.com/waymo-research/waymo-open-dataset/blob/576f63526281cf403be2b6720a0d3acb4d18f41d/src/waymo_open_dataset/label.proto#L104). You can refer to [keypoint_data.group_object_labels](https://github.com/waymo-research/waymo-open-dataset/blob/576f63526281cf403be2b6720a0d3acb4d18f41d/src/waymo_open_dataset/utils/keypoint_data.py#L149) as an example how to use it.

**Comment by jayhsu0627** [comment]
Thank you so much Alex,
I remember the association only works for pedestrian class in the older version, did you extend it to the car and other vehicle types? Which version should I use?

**Comment by jayhsu0627** [comment]
I've tested the association, and it only has the pedestrian class. I'll use the parquet instead.

**Comment by jayhsu0627** [comment]
I've tested the `camera_to_lidar_box_association ` in the parquet format, the association labels only work for ['PEDESTRIAN'] class not for ['UNKNOWN', 'VEHICLE', 'PEDESTRIAN', 'SIGN', 'CYCLIST'].

v2 in parquet format
```Found 11 objects on lidar.key.segment_context_name='1146261869236413282_1680_000_1700_000' lidar.key.frame_timestamp_micros=1558401135447667
	laser_object_id='pa4NYCGwiXJWNFGAAMv9pQ' camera_object_id='38fe1c07-02f4-442c-9165-b41275110e85' camera_name=1
	laser_object_id='pa4NYCGwiXJWNFGAAMv9pQ' camera_object_id='4e1e658d-0986-4e60-91d5-c4049104f82e' camera_name=2
	laser_object_id='kSQDm6ajZq78yeljVpclyA' camera_object_id='5980453d-b4ec-402c-9ebb-b024313deca5' camera_name=1
	laser_object_id='kSQDm6ajZq78yeljVpclyA' camera_object_id='3ede0ba0-a0ce-48e8-bede-4b5d594f046c' camera_name=2
	laser_object_id='AZeZM70JmH_UrQWVoU03eA' camera_object_id='a2a20869-7abb-4647-8cd4-b38cf4920e35' camera_name=1
	laser_object_id='AZeZM70JmH_UrQWVoU03eA' camera_object_id='155eeb3d-e319-4f76-9557-a6b3818f3c9e' camera_name=2
	laser_object_id='vnWKafUb3A5PKA1KwHPJsw' camera_object_id='ddc1f8d8-513c-40ba-8d60-caa9e4bef0c2' camera_name=1
	laser_object_id='vnWKafUb3A5PKA1KwHPJsw' camera_object_id='964a6c46-b3a1-4992-b478-515f341c7975' camera_name=2
	laser_object_id='vL0YA_hU34G_5cSxEUqF5w' camera_object_id='31e27500-cdba-4b21-b14f-e333732554bf' camera_name=2
	laser_object_id='FzfrREfgdu03_WMH6uk4vw' camera_object_id='6574404a-8b6f-48d6-a292-7e1f89885923' camera_name=4
	laser_object_id='exDOBs_pata3nBb8E_IyFA' camera_object_id='c35c5c4b-ee8f-4443-8217-f8869c379a77' camera_name=4
```
visualization of v1 in `tfrecord` format
![v1_camera_lidar](https://user-images.githubusercontent.com/31528202/231230103-24149baf-9879-4a42-99f4-03597f36e589.png)

**Comment by alexgorban** [comment]
Both formats have the same data. Association labels are available only for pedestrians at the moment.
