### ISSUE TITLE
pip install is not working on Windows

### ISSUE THREAD

**Issue by pengzhenghao** [waymo-research/waymo-open-dataset#630]
Can't do this:

```
pip install waymo-open-dataset-tf-2-11-0==1.5.1
```

on Windows.

**Comment by alexgorban** [comment]
that is right, we support only manylinux2014 as the target platform. On Windows users can try to build a pip package from the source:

1. Install [bazelisk](https://github.com/bazelbuild/bazelisk#installation)
2. Build the wheel

```
bazelisk test -c opt //waymo_open_dataset/... --test_output=all
bazelisk build -c opt //waymo_open_dataset/pip_pkg_scripts:wheel
```
