### ISSUE TITLE
how do we kown which classes are things in 2d panoptic task?

### ISSUE THREAD

**Issue by Wu-Xiang123** [waymo-research/waymo-open-dataset#631]
I failed to find informaion about this, it's not a good idea to traverse all labels and induct the answer...

**Comment by alexzzhu** [comment]
Hi, that's a good question. The instance classes are outlined in our paper here: https://arxiv.org/pdf/2206.07704.pdf (Figure 2), but it's a good idea to embed it here. I'll work on adding this. For your convenience, the classes are:
```
"car", "truck", "bus", "other_large_vehicle", "trailer", "pedestrian", "cyclist", "motorcyclist"
```

**Comment by Wu-Xiang123** [comment]
> Hi, that's a good question. The instance classes are outlined in our paper here: https://arxiv.org/pdf/2206.07704.pdf (Figure 2), but it's a good idea to embed it here. I'll work on adding this. For your convenience, the classes are:
> 
> ```
> "car", "truck", "bus", "other_large_vehicle", "trailer", "pedestrian", "cyclist", "motorcyclist"
> ```

Thanks a lot! This is what I need. More,  in dataset v2, I notice that there is a new class called ego-vehicle, does it belong to  thing classes?

**Comment by Wu-Xiang123** [comment]
> Hi sorry missed this reply. Could you clarify where the ego-vehicle class name is coming up in the v2 dataset? This should correspond to the 'sdc' class, which is the Waymo vehicle which collected the dataset. It may show up in the images from time to time.

I saw it in the proto file: https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/protos/camera_segmentation.proto#:~:text=The%20Waymo%20vehicle.-,TYPE_EGO_VEHICLE,-%3D%201%3B .

**Comment by alexzzhu** [comment]
Ah I see, I thought there was a new class spec for v2 only. This proto should be consistent for both v1 and v2, and the ego_vehicle class refers to the Waymo vehicle as described above.

**Comment by Wu-Xiang123** [comment]
> Ah I see, I thought there was a new class spec for v2 only. This proto should be consistent for both v1 and v2, and the ego_vehicle class refers to the Waymo vehicle as described above.

emmm... sorry, what does "sdc" mean, so is ego-vehicle a thing class and shoud be tracked?

**Comment by alexzzhu** [comment]
Ah sdc == ego-vehicle here. SDC is just the name used in the deeplab2 library but the two are equivalent. It's not a thing class, only semantic.
