### ISSUE TITLE
Tracks split by different range-based shards?

### ISSUE THREAD

**Issue by DianCh** [waymo-research/waymo-open-dataset#64]
Hi, from the tracking evaluation code it seems that some shards are based on distance range. I wonder if a car's track goes from beyond 50m to below 30m (very likely to happen for cars that come towards us), is its track considered as 3 separate tracks, since you would first split indices according to shards and then match? 

Thanks for any clarification!

**Comment by peisun1115** [comment]
I think you are talking about the tracking metrics breakdown.

In the ground truth, they will share the same tracking ID. Similarly for predictions. So it is fine.

**Comment by DianCh** [comment]
Yes the ground truths share the same tracking ID. But what if two different identities are matched to the same gt object, but in different shards? Since the evaluation seems to first decompose both predictions/gt's into different shards (talking about range-based shards) by indices, and matching runs independently, it's possible that object A in shard A matched to G, and object B in shard B matched to G.

Could you help explain more? Or am I misunderstanding anything here?
Thank you very much!

**Comment by peisun1115** [comment]
if two objects match to the same object, we pick the one that has higher IoU. If one of them goes out of the shard, then this can cause a mismatch. but this is 3d detection, most algorithms should not output 2 predictions that have so much overlap. In that case, it will be fine.

**Comment by peisun1115** [comment]
I assume this is resolved. Reopen if you have more questions.
