### ISSUE TITLE
Configuring doesn't find tensorflow-gpu

### ISSUE THREAD

**Issue by gdicker1** [waymo-research/waymo-open-dataset#65]
Line 56 of `configure.sh` only checks for tensorflow and tf-nightly installs, but doesn't check for tensorflow-gpu install. Causes configure to state no tensorflow is installed when one actually is.

**Comment by peisun1115** [comment]
Good catch. For now you can probably update it on your own or use our pre-built pip libs or send a fix. We will fix it later

**Comment by peisun1115** [comment]
Fixed now.
