### ISSUE TITLE
How to extract the depth images from the frames?

### ISSUE THREAD

**Issue by minz27** [waymo-research/waymo-open-dataset#650]
I searched for previous issues in this repository, checked the documentation, as well as checked the internet and could not find how to properly use the build_camera_depth_image() funtion. I have written the following code, but I believe it is faulty as the extracted depth images are black for all the cameras except the front one, and depth image from the front camera only has a few points. Can anyone let me know where I am going wrong please?

Thanks a lot
```

def` extract_depth_maps(datadirs:List[str], saving_dir:str):
    for file_num,file in enumerate(datadirs):
        file_name = file.split('/')[-1].split('.')[0]
        if not os.path.isdir(os.path.join(saving_dir,file_name, 'depth_images')):   os.mkdir(os.path.join(saving_dir,file_name, 'depth_images'))
        print("Procesing %s"%file_name)
        dataset = tf.data.TFRecordDataset(file, compression_type='')
        for f_num, data in enumerate(tqdm(dataset)):
            frame = open_dataset.Frame()
            frame.ParseFromString(bytearray(data.numpy()))
            (range_images, camera_projections, range_image_top_pose) = \
                frame_utils.parse_range_image_and_camera_projection(frame)
            range_image_cartesian = frame_utils.convert_range_image_to_cartesian(frame,
                                     range_images,
                                     range_image_top_pose,
                                     ri_index=0,
                                     keep_polar_features=False)                             
            for im in frame.images:
                camera_name = open_dataset.CameraName.Name.Name(im.name)
                depth_path = os.path.join(saving_dir,file_name, 'depth_images','%03d_%s.png'%(f_num,camera_name))
                extrinsic = np.reshape(frame.context.camera_calibrations[im.name-1].extrinsic.transform, [1,4,4]).astype(np.float32)
                camera_image_size = (frame.context.camera_calibrations[im.name-1].height, frame.context.camera_calibrations[im.name-1].width)                
                ric_shape = range_image_cartesian[im.name].shape
                ric = np.reshape(range_image_cartesian[im.name], [1, ric_shape[0], ric_shape[1], ric_shape[2]])
                cp = camera_projections[im.name][0]
                cp_tensor = tf.reshape(tf.convert_to_tensor(value=cp.data), cp.shape.dims)
                cp_shape = cp_tensor.shape
                cp_tensor = np.reshape(cp_tensor, [1, cp_shape[0], cp_shape[1], cp_shape[2]])
                depth_image = range_image_utils.build_camera_depth_image(ric,
                             extrinsic,
                             cp_tensor,
                             camera_image_size,
                             im.name)
                depth_shape = depth_image.shape
                depth_image = np.reshape(depth_image, [depth_shape[1], depth_shape[2]])
                depth_image = normalize8(depth_image) 
                        
                imageio.imwrite(depth_path, depth_image, compress_level=3)
```

**Comment by xcyan** [comment]
Hi @minz27, thanks for your interest! May I know the data version you have been using?

**Comment by minz27** [comment]
@xcyan Hi, I am using waymo_open_dataset_v_1_3_1, and working with the validation files directly. In particular, I am looking at validation_0000.tar available at this link to signed in users [here](https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_3_1/validation?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)

**Comment by minz27** [comment]
Closing this issue as the code I have written above seems to be correct - back-projecting the depth images gives me the expected point clouds.

**Comment by DongyangHuLi** [comment]
@minz27 Hi~, could you show me the depth map after visualization?

**Comment by minz27** [comment]
Sure. I have a bit of skew while backprojecting which I need to fix, but it seems to work otherwise. Note: The depth maps extracted using the code above are extremely sparse.

![image](https://github.com/waymo-research/waymo-open-dataset/assets/20521847/04fed67d-dee3-4fe5-b189-8006a5e0750f)

![image](https://github.com/waymo-research/waymo-open-dataset/assets/20521847/4d31d3bf-79aa-4673-a64b-de7fc553e4c5)

**Comment by Gilgamesh666666** [comment]
> I searched for previous issues in this repository, checked the documentation, as well as checked the internet and could not find how to properly use the build_camera_depth_image() funtion. I have written the following code, but I believe it is faulty as the extracted depth images are black for all the cameras except the front one, and depth image from the front camera only has a few points. Can anyone let me know where I am going wrong please?
> 
> Thanks a lot
> 
> ```
> 
> def` extract_depth_maps(datadirs:List[str], saving_dir:str):
>     for file_num,file in enumerate(datadirs):
>         file_name = file.split('/')[-1].split('.')[0]
>         if not os.path.isdir(os.path.join(saving_dir,file_name, 'depth_images')):   os.mkdir(os.path.join(saving_dir,file_name, 'depth_images'))
>         print("Procesing %s"%file_name)
>         dataset = tf.data.TFRecordDataset(file, compression_type='')
>         for f_num, data in enumerate(tqdm(dataset)):
>             frame = open_dataset.Frame()
>             frame.ParseFromString(bytearray(data.numpy()))
>             (range_images, camera_projections, range_image_top_pose) = \
>                 frame_utils.parse_range_image_and_camera_projection(frame)
>             range_image_cartesian = frame_utils.convert_range_image_to_cartesian(frame,
>                                      range_images,
>                                      range_image_top_pose,
>                                      ri_index=0,
>                                      keep_polar_features=False)                             
>             for im in frame.images:
>                 camera_name = open_dataset.CameraName.Name.Name(im.name)
>                 depth_path = os.path.join(saving_dir,file_name, 'depth_images','%03d_%s.png'%(f_num,camera_name))
>                 extrinsic = np.reshape(frame.context.camera_calibrations[im.name-1].extrinsic.transform, [1,4,4]).astype(np.float32)
>                 camera_image_size = (frame.context.camera_calibrations[im.name-1].height, frame.context.camera_calibrations[im.name-1].width)                
>                 ric_shape = range_image_cartesian[im.name].shape
>                 ric = np.reshape(range_image_cartesian[im.name], [1, ric_shape[0], ric_shape[1], ric_shape[2]])
>                 cp = camera_projections[im.name][0]
>                 cp_tensor = tf.reshape(tf.convert_to_tensor(value=cp.data), cp.shape.dims)
>                 cp_shape = cp_tensor.shape
>                 cp_tensor = np.reshape(cp_tensor, [1, cp_shape[0], cp_shape[1], cp_shape[2]])
>                 depth_image = range_image_utils.build_camera_depth_image(ric,
>                              extrinsic,
>                              cp_tensor,
>                              camera_image_size,
>                              im.name)
>                 depth_shape = depth_image.shape
>                 depth_image = np.reshape(depth_image, [depth_shape[1], depth_shape[2]])
>                 depth_image = normalize8(depth_image) 
>                         
>                 imageio.imwrite(depth_path, depth_image, compress_level=3)
> ```

Hi,

Thank you for sharing your code, i am trying to get depth map too but i am not very familiar with this dataset. May i know what those four functions in our code are?
`range_image_utils.build_camera_depth_image`, `frame_utils.parse_range_image_and_camera_projection`, `frame_utils.convert_range_image_to_cartesian` and `normalize8`. I will be very appreciate if you can give me some hint. Thank you very much!

**Comment by Len-Li** [comment]
Check out tutorial/tutorial.ipynb for point cloud project to image
