### ISSUE TITLE
Waymo-open-dataset-tf-2-6-0 does not work

### ISSUE THREAD

**Issue by TommyClemenzaChen** [waymo-research/waymo-open-dataset#654]
I tried installing the waymo-open-dataset-tf-2-6-0, but it resulted in an error, "No matching distribution found". Is there a workaround so I can still use Tensorflow 2.6 because Tensorflow 2.11 causes my code to result in an error?

**Comment by alexgorban** [comment]
Sorry, but Tensorflow 2.6 is no longer supported.
