### ISSUE TITLE
Point Cloud visualization

### ISSUE THREAD

**Issue by atanasko** [waymo-research/waymo-open-dataset#655]
I try to get the point could from range image using 

`
from waymo_open_dataset.v2.perception.utils import lidar_utils as _lidar_utils
`

but I have the following error 

```
  File "~/lidar-sensor/venv/lib/python3.10/site-packages/waymo_open_dataset/v2/perception/utils/lidar_utils.py", line 92, in convert_range_image_to_cartesian
    if calibration.beam_inclination.values:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

changing

`
 if calibration.beam_inclination.values:
`
to 
`
 if calibration.beam_inclination.values.any:
`

return the point cloud and I'm able to visualize it using open3d. Is this a bug or something with my environment?

I use

`
Python 3.10.10
`

**Comment by JingweiJ** [comment]
Hi @atanasko ,

Thank you for flagging this issue. Depending on how `calibration` is initialized, `calibration.beam_inclination.values` can be None, list or numpy array. When it's a numpy array, this error shows up. A hot fix you may also use is changing [this line](https://github.com/waymo-research/waymo-open-dataset/blob/1eabddad78858a74b18152f61b89868a6c4ecc59/src/waymo_open_dataset/v2/perception/utils/lidar_utils.py#L92) into
`  if calibration.beam_inclination.values is not None:` to cover all cases.
We'll fix it in the next commit.

**Comment by atanasko** [comment]
hi @Jingwei,

Thank you! I'll use local fix for the moment and try changes after committed.
