### ISSUE TITLE
INVALID_ARGUMENT: Duplicate prediction scenario ID found

### ISSUE THREAD

**Issue by yixin-c** [waymo-research/waymo-open-dataset#659]
Hello, I've submitted my results for the validation set, but I keep encountering an `INVALID_ARGUMENT: Duplicate prediction scenario ID found: xxxxxxxxxxxxxxxx` error. The ID mentioned in the error is consistently the last scenario ID in my predictions. But I'm sure that's the only scenario I submitted. How can I resolve this issue? I generated my submission similar to the code shared in [https://github.com/waymo-research/waymo-open-dataset/issues/310](url).

Also, Could you share a complete scenario_id list for the validation set for me to double check? 

Thank you very much for your help!

**Comment by nicomon24** [comment]
Hi @yixin-c, could you please confirm to which of the challenges you are referring to? The issue refers to the motion prediction challenge.

**Comment by yixin-c** [comment]
I was referring to the motion prediction challenge, but I figure out the issue by myself. Thanks!

**Comment by yixin-c** [comment]
I was referring to the motion prediction challenge, but I figure out the issue by myself. Thanks!

**Comment by 786739982** [comment]
> 您好，我已经提交了验证集的结果，但一直遇到错误。错误中提到的 ID 始终是我的预测中的最后一个方案 ID。但我确信这是我提交的唯一场景。如何解决此问题？我生成的提交类似于 [https://github.com/waymo-research/waymo-open-dataset/issues/310](url) 中共享的代码。`INVALID_ARGUMENT: Duplicate prediction scenario ID found: xxxxxxxxxxxxxxxx`
> 
> 另外，您能否分享一个完整的scenario_id列表供我仔细检查验证集？
> 
> 非常感谢您的帮助！

**Comment by 786739982** [comment]
> 您好，我已经提交了验证集的结果，但一直遇到错误。错误中提到的 ID 始终是我的预测中的最后一个方案 ID。但我确信这是我提交的唯一场景。如何解决此问题？我生成的提交类似于 [https://github.com/waymo-research/waymo-open-dataset/issues/310](url) 中共享的代码。`INVALID_ARGUMENT: Duplicate prediction scenario ID found: xxxxxxxxxxxxxxxx`
> 
> 另外，您能否分享一个完整的scenario_id列表供我仔细检查验证集？
> 
> 非常感谢您的帮助！

**Comment by 786739982** [comment]
Hello, I have encountered the same problem. May I ask how you resolved it？
Thank you very for your help！

**Comment by yixin-c** [comment]
> Hello, I have encountered the same problem. May I ask how you resolved it？ Thank you very for your help！

It was actually a mistake in my code. I think I messed up when I tried to append trajectories to predictions in my `for` loop. I don't remember exactly what it was since it's a while ago. 

There could be many reasons that lead to this error. I don't think yours will be exactly the same as mine.  But I suggest you double check your code when you are appending trajectories and when you are appending predictions.

**Comment by 786739982** [comment]
OK！thank you very much for your help !!!

**Comment by 786739982** [comment]
scenario_id: "529df7de8ca4721e"
single_predictions {
  predictions {
    object_id: 30
    trajectories {
      trajectory {
        center_x: -260.480712890625
        center_x: -259.3681335449219
        center_x: -258.28277587890625
        center_x: -257.2763671875
        center_x: -256.3489074707031
        center_x: -255.47012329101562
        center_x: -254.56021118164062
        center_x: -253.5795135498047
        center_x: -252.50900268554688
        center_x: -251.3688201904297
        center_x: -250.255615234375
        center_x: -249.20736694335938
        center_x: -248.34292602539062
        center_x: -247.69454956054688
        center_x: -247.27206420898438
        center_x: -247.0102996826172
        center_y: 2920.763916015625
        center_y: 2920.806640625
        center_y: 2920.84619140625
        center_y: 2920.859375
        center_y: 2920.845947265625
        center_y: 2920.78564453125
        center_y: 2920.643798828125
        center_y: 2920.40869140625
        center_y: 2920.0068359375
        center_y: 2919.3662109375
        center_y: 2918.46240234375
        center_y: 2917.27099609375
        center_y: 2915.82470703125
        center_y: 2914.145751953125
        center_y: 2912.276123046875
        center_y: 2910.160888671875
      }
      confidence: 0.35986119508743286
    }
    trajectories {
      trajectory {
        center_x: -260.4786376953125
        center_x: -259.3855285644531
        center_x: -258.4195556640625
。。。。。。。。。。。。。。。。。。。。

**Comment by 786739982** [comment]
Sorry, I have been working all day today and still haven't solved this problem, so I still want to consult you about this issue. The one I sent above is my current data format. Could you please take a look where the problem occurred and where modifications are needed?

Thank you very much for your help!!!
