### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by DongyangHuLi** [waymo-research/waymo-open-dataset#660]
Hi, thank you for your contributions.
Could you tell me how can I download data about a particular time of day or weather？

**Comment by alexgorban** [comment]
Hi, you can use the v2 dataset format to get a list of segments, for a specific time of the day or weather:

Here is an example how to do it in https://colab.research.google.com/

```python
from google.colab import auth
import gcsfs
import google.auth
auth.authenticate_user()
import dask.dataframe as dd
import io

credentials, project_id = google.auth.default()
fs = gcsfs.GCSFileSystem(project=project_id, token=credentials)

wod_v2_bucket = 'waymo_open_dataset_v_2_0_0'
subset = 'training'
component = 'stats'

# Details about the dataset format
# https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_v2.ipynb
stats_paths = fs.glob(f'{wod_v2_bucket}/{subset}/{component}/*.parquet')

# To read parquet you can also use pyarrow, dask or tensorflow_io
stats_df = dd.read_parquet(stats_paths, filesystem=fs).compute()

# Define your selection
time_of_day = "Day" #@param ["Day", "Dawn/Dusk", "Night"]
weather = "sunny" #@param ["sunny", "rain"]
select = (stats_df['[StatsComponent].time_of_day'] == time_of_day) & (stats_df['[StatsComponent].weather'] == weather)
context_names = stats_df[select]['key.segment_context_name'].unique()
print(f'Found {len(context_names)} segments with {time_of_day=} and {weather=}, e.g.:')
print(context_names[:10])
```

With the list of `context_names` you can generate a list of parquet files for a download manager of your choice.

**Comment by DongyangHuLi** [comment]
> Hi, you can use the v2 dataset format to get a list of segments, for a specific time of the day or weather:
> 
> Here is an example how to do it in https://colab.research.google.com/
> 
> ```python
> from google.colab import auth
> import gcsfs
> import google.auth
> auth.authenticate_user()
> import dask.dataframe as dd
> import io
> 
> credentials, project_id = google.auth.default()
> fs = gcsfs.GCSFileSystem(project=project_id, token=credentials)
> 
> wod_v2_bucket = 'waymo_open_dataset_v_2_0_0'
> subset = 'training'
> component = 'stats'
> 
> # Details about the dataset format
> # https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_v2.ipynb
> stats_paths = fs.glob(f'{wod_v2_bucket}/{subset}/{component}/*.parquet')
> 
> # To read parquet you can also use pyarrow, dask or tensorflow_io
> stats_df = dd.read_parquet(stats_paths, filesystem=fs).compute()
> 
> # Define your selection
> time_of_day = "Day" #@param ["Day", "Dawn/Dusk", "Night"]
> weather = "sunny" #@param ["sunny", "rain"]
> select = (stats_df['[StatsComponent].time_of_day'] == time_of_day) & (stats_df['[StatsComponent].weather'] == weather)
> context_names = stats_df[select]['key.segment_context_name'].unique()
> print(f'Found {len(context_names)} segments with {time_of_day=} and {weather=}, e.g.:')
> print(context_names[:10])
> ```
> 
> With the list of `context_names` you can generate a list of parquet files for a download manager of your choice.

Thank you so much！It helps me a lot.
