### ISSUE TITLE
Is it possible to extend the deadline for Sim Agents Challenge

### ISSUE THREAD

**Issue by ZikangZhou** [waymo-research/waymo-open-dataset#666]
Hi @nicomon24,

Thanks for bringing this great challenge to the research community!

I'm asking this because it really takes time to figure out tons of details of this relatively new task. And, it is very time-consuming to train a model that generates 32 simulations for all agents per scene...

**Comment by nicomon24** [comment]
Hi @ZikangZhou,
thanks for your interest in the competition! 
For the deadline we are quite constrained by the CVPR workshop dates, so I don't think we can push it back (maybe we can push it by a week if we see a lot users struggling near the deadline).
I wanted to also mention that, while the challenge itself has a deadline, we will leave the evaluation and leaderboard live after that moment too, so you're still able to submit and publish on the leaderboard. 

Good luck and let me know if you need any help!

**Comment by ZikangZhou** [comment]
OK, thanks! I'll try to submit some initial results recently.
