### ISSUE TITLE
How to append the names and email information of team members？

### ISSUE THREAD

**Issue by QC625** [waymo-research/waymo-open-dataset#669]
If I have a team, how can I fill in the names and email information of team members during packaging?
![image](https://github.com/waymo-research/waymo-open-dataset/assets/94269942/4a6ee58a-6dd9-4e31-a2a8-8f8d9d2f302c)

**Comment by QC625** [comment]
Can this account_name  be modified into a list？

**Comment by alexzzhu** [comment]
The authors field is intended to be used for team members (pass them in as a list of names). For the emails, you can just provide the email of the primary contact (person doing the submission) under account_name.

**Comment by QC625** [comment]
Thank you for your reply, but I still have one confusion：If only the names of team members are filled in, how can the official judge that team members have not participated in multiple teams, such as duplicate names.
