### ISSUE TITLE
Challenge dataset version for website motion prediction eval/test set

### ISSUE THREAD

**Issue by icefall7** [waymo-research/waymo-open-dataset#670]
For the motion forecasting competition this year. I would like to consult about version the open dataset version used on the official validation/test engine. Since we found significant differences between our offline validation result and submitted validation result . The version we used is waymo-open-dataset-tf-2.11.0==1.5.0. Also, would like to confirm that eval set and test set on the website are regenerated from motion dataset v1.2. thanks

**Comment by scott-ettinger** [comment]
I have verified that the data used on the evaluation servers are identical to the validation data in the published dataset.  Could you explain further how you are running the offline evaluation and how different the results are?
