### ISSUE TITLE
occupancy_flow_vis

### ISSUE THREAD

**Issue by UestcJay** [waymo-research/waymo-open-dataset#673]
many thanks for your great work! I wonder  how to plot the image?  Is there vis code in the repo? 
![微信截图_20230517103419](https://github.com/waymo-research/waymo-open-dataset/assets/37372259/e2952ee7-be6f-4dad-a829-8da9e69af94c)

**Comment by rezama** [comment]
This notebook demonstrates how to visualize the outputs: https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_occupancy_flow.ipynb
