### ISSUE TITLE
Sim Agents Challenge: X, Y, Z values of the origin of the scene

### ISSUE THREAD

**Issue by Chidvilas-Karpenahalli-Ramakrishna** [waymo-research/waymo-open-dataset#674]
Hello,

I wish to obtain the X, Y, and Z values of the origin of the scene (using the scenario_id for ex.). I want these values to normalize the X, Y, and Z trajectory points of each agent in a scenario. Is this possible?

Thanks and regards,
Chid

**Comment by nicomon24** [comment]
Hi @Chidvilas-Karpenahalli-Ramakrishna.

Just to confirm, you are referring to a normalised X/Y/Z **across** scenarios? (Basically, global coordinates?). Otherwise all the agents X/Y/Z are already normalised to some fixed point per-scenario.
If you're referring to the global coordinates, I don't think we have released that data for now, and I feel like this will not be the case for the remaining part of the challenge. @scott-ettinger could you please confirm? 

Meanwhile, I get while this information might be valuable for the sim agents challenge, so I'll check internally if it's possible to release this data in further releases of the open dataset.

Hope this helps! Let me know if you need further help

Nico

**Comment by Chidvilas-Karpenahalli-Ramakrishna** [comment]
Hi @nicomon24 and @scott-ettinger,
Thank you for the quick response. I am aware of the fact that all points are with respect to the global coordinate system. I wish to get the coordinates of agents normalized to each scenario. For example, if I get a BEV image of a scenario, the BEV comes with an origin. I wish to get the {X, Y, Z} points of that origin so that I can normalize each agent's {X, Y, Z} with respect to that origin. After playing around, I was able to get the X and Y of the BEV origin (basically the scenario origin) from the map information. But, since the BEV is 2D, I cannot get the Z value of the origin.

My use case is as follows. I wish to pass the scenario BEV with all agents as one input and the state information = {X, Y, Z, heading, velocity_x, velocity_y, length, width, height} of traffic agents as a second input to my model. Here, you can already see the problem as {X, Y, Z} are not normalized to the scene/BEV but are in the global coordinate system. I think my model can learn better if I normalize the values.

**Comment by scott-ettinger** [comment]
Hi, I'm not sure I understand how you are defining the origin for a BEV image of a scenario.  Is this something like the centroid of  all of the map points? Can you explain this further?

**Comment by Chidvilas-Karpenahalli-Ramakrishna** [comment]
Hi @scott-ettinger, Sorry if I was not clear with the description of my problem. Let me try to rephrase it. I have attached an image of a BEV image that I can obtain from the `add_map()` method. I can access the axis X-limits and Y-limits to get the (X, Y) origin. I want to use these points to normalize the (X, Y) points of all agents in this scene. I want to perform the same normalization along Z. But, I cannot do that using this method. So, I was wondering if there is some other way of accessing the Z-origin.

<img width="503" alt="2023-05-21 10-29-35_notebook_bev ipynb · main · mohana _ waymo_sim_agent · GitLab — Mozilla Firefox" src="https://github.com/waymo-research/waymo-open-dataset/assets/57722826/b8307301-1147-4bba-b9f0-072341e18a26">

**Comment by scott-ettinger** [comment]
Hi, 
It looks like you want to choose the origin to be whatever your plot library is using for its axes?  Under the hood the plot library appears to take the minimum of the X and Y values and maybe adding some arbitrary offset for padding. In a similar way, you could choose to use the minimum Z value over all map features to be the Z value for the origin?  Depending on how you plan to process the coordinates, this seems like a reasonable choice.

**Comment by Chidvilas-Karpenahalli-Ramakrishna** [comment]
Hi @scott-ettinger,
We decided to go ahead with the same technique. Thanks for the suggestions and quick responses 🙂👍🏼
