### ISSUE TITLE
Sim Agents Challenge: The submitted file takes up too much memory

### ISSUE THREAD

**Issue by Guozhiming-art** [waymo-research/waymo-open-dataset#679]
I am participating in the Sim Agents competition and conducting experiments using the scenario dataset. I generated the final submission file 'submission.binproto-00000-of-00150' using the official script 'tutorial_sim_agents.ipynb'. However, the file size of the final submission exceeds 60G, I observed that you mentioned the validation set test results submitted were about 30GB, and I would like to know what is causing my submitted file to occupy more memory. Additionally, after submitting yesterday, it has been 8 hours and currently displays "This submission could not be found. If it was recently uploaded, it may still be processing. Check back in about 6 hours. Please avoid resubmitting if a submission is still processing, as it might overload the server." May I know the reason for this? Is there an issue with the documents I submitted? My submission information is shown below:
![图片](https://github.com/waymo-research/waymo-open-dataset/assets/76396377/f74c3095-6627-4ef4-921e-823884979ad0)
![图片](https://github.com/waymo-research/waymo-open-dataset/assets/76396377/889c1fcb-a596-42d9-b9a5-13238bc5d203)

**Comment by nicomon24** [comment]
Hi @Guozhiming-art,

Regarding the submission size, could you confirm:
- Are you referring to the tar.gz archive size? Or to the sharded binprotos before compression?
- Do you have all the 150 shards? 

Regarding the server: can you check back now? We are getting a lot more submissions now so the wait time for the last day might be a bit higher, but right now we have no pending submission to be evaluated. 
Can you provide your email and submission ID if this is not the case so I can check manually?

**Comment by Guozhiming-art** [comment]
I am participating in the Sim Agents competition and conducting experiments using the scenario dataset. I generated the final submission file 'submission.binproto-00000-of-00150' using the official script 'tutorial_sim_agents.ipynb'.

Hello, I am participating in the Sim Agents competition and conducting experiments using the scenario dataset. the previous problem has been solved, thank you for your reply.However, the test results of the test set I submitted on June 4, Beijing time, have passed 30 hours and still show that it is being processed. I want to know why.My waymo account is ***@***.***, my submission information and the current result display are as follows:













At 2023-05-23 15:58:58, "Nico Montali" ***@***.***> wrote:

Hi @Guozhiming-art,

Regarding the submission size, could you confirm:

Are you referring to the tar.gz archive size? Or to the sharded binprotos before compression?
Do you have all the 150 shards?

Regarding the server: can you check back now? We are getting a lot more submissions now so the wait time for the last day might be a bit higher, but right now we have no pending submission to be evaluated.
Can you provide your email and submission ID if this is not the case so I can check manually?

**Comment by nicomon24** [comment]
@Guozhiming-art I received a message about your submission being stuck in evaluation. It was an error on our server side, I'll restart that for you.

**Comment by Guozhiming-art** [comment]
Thank you sincerely for taking the time to respond and offer your assistance!













At 2023-06-05 18:31:57, "Nico Montali" ***@***.***> wrote:

@Guozhiming-art I received a message about your submission being stuck in evaluation. It was an error on our server side, I'll restart that for you.

**Comment by Guozhiming-art** [comment]
Hello there, my Waymo account ID is ***@***.*** Unfortunately, my submission ID is not being displayed on the submission interface at the moment. However, I can provide you with the exact time of my submission in Beijing time, which is as follows:

















At 2023-06-05 18:31:57, "Nico Montali" ***@***.***> wrote:

@Guozhiming-art I received a message about your submission being stuck in evaluation. It was an error on our server side, I'll restart that for you.

**Comment by Guozhiming-art** [comment]
> 



> @Guozhiming-art I received a message about your submission being stuck in evaluation. Could you please provide more info here? I couldn't read the email address and submission ID.
Hello there, my Waymo account ID is hu15645090213@gmail.com. Unfortunately, my submission ID is not being displayed on the submission interface at the moment. However, I can provide you with the exact time of my submission in Beijing time, which is as follows:
![图片](https://github.com/waymo-research/waymo-open-dataset/assets/76396377/8caed7b6-459b-4f0c-97dd-935610da7815)

**Comment by nicomon24** [comment]
@Guozhiming-art If you look at your submission now it should be visible!
