### ISSUE TITLE
I am getting the following error  on running ./pip_pkg_scripts/build.sh in mac

### ISSUE THREAD

**Issue by saching13** [waymo-research/waymo-open-dataset#68]
INFO: Starting clean.
+ bazel build ...
INFO: Writing tracer profile to '/private/var/tmp/_bazel_blackbird/6d9f59d76a8f7d25e77907807c48d1de/command.profile.gz'
WARNING: /private/var/tmp/_bazel_blackbird/6d9f59d76a8f7d25e77907807c48d1de/external/local_config_tf/BUILD:2445:1: target 'libtensorflow_framework.so' is both a rule and a file; please choose another name for the rule
INFO: Analyzed 77 targets (58 packages loaded, 1829 targets configured).
INFO: Found 77 targets...
ERROR: /Users/blackbird/Desktop/python_codes/waymo-od/waymo-od/waymo_open_dataset/protos/BUILD:23:1: Linking of rule '//waymo_open_dataset/protos:breakdown_cc_proto' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -lc++ -fobjc-link-runtime -shared -o bazel-out/darwin-opt/bin/waymo_open_dataset/protos/libbreakdown_cc_proto.so ... (remaining 7 argument(s) skipped)

I am new at this. Can I get some help ?

**Comment by peisun1115** [comment]
the build files might need some tweaks to make it work for mac. 

Do you think you can just try our docker?

https://github.com/waymo-research/waymo-open-dataset/tree/master/pip_pkg_scripts

Try the following command:
(assuming docker is installed on mac)

1. docker build --tag=open_dataset_pip -f pip_pkg_scripts/build.Dockerfile .
2. sudo docker run -it --entrypoint=/bin/bash -e "GITHUB_BRANCH=master" -e "PYTHON_VERSION=3" -e "PYTHON_MINOR_VERSION=5" -e "PIP_MANYLINUX2010=1" -e "TF_VERSION=1.15.0" open_dataset_pip
(you can change env if you like)

**Comment by saching13** [comment]
yeah. that would be an work around but I would prefer local installation

**Comment by saching13** [comment]
> the build files might need some tweaks to make it work for mac.
> 
> Do you think you can just try our docker?
> 
> https://github.com/waymo-research/waymo-open-dataset/tree/master/pip_pkg_scripts
> 
> Try the following command:
> (assuming docker is installed on mac)
> 
> 1. docker build --tag=open_dataset_pip -f pip_pkg_scripts/build.Dockerfile .
> 2. sudo docker run -it --entrypoint=/bin/bash -e "GITHUB_BRANCH=master" -e "PYTHON_VERSION=3" -e "PYTHON_MINOR_VERSION=5" -e "PIP_MANYLINUX2010=1" -e "TF_VERSION=1.15.0" open_dataset_pip
>    (you can change env if you like)

Hey, once I have built using docker how do I add those files to the local python library ?

**Comment by saching13** [comment]
> the build files might need some tweaks to make it work for mac.
> 
> Do you think you can just try our docker?
> 
> https://github.com/waymo-research/waymo-open-dataset/tree/master/pip_pkg_scripts
> 
> Try the following command:
> (assuming docker is installed on mac)
> 
> 1. docker build --tag=open_dataset_pip -f pip_pkg_scripts/build.Dockerfile .
> 2. sudo docker run -it --entrypoint=/bin/bash -e "GITHUB_BRANCH=master" -e "PYTHON_VERSION=3" -e "PYTHON_MINOR_VERSION=5" -e "PIP_MANYLINUX2010=1" -e "TF_VERSION=1.15.0" open_dataset_pip
>    (you can change env if you like)

I Tired the below command after building it using docker but I ended up getting an error. it says it doesn't support my os. how to build that for mac ?
 pip3 install /tmp/pip_pkg_build/waymo_open_dataset_tf_1_15_0-1.0.1-cp35-cp35m-linux_x86_64.whl 


ERROR: waymo_open_dataset_tf_1_15_0-1.0.1-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.
