### ISSUE TITLE
LiDAR based 3D detection submission problem

### ISSUE THREAD

**Issue by douya1121** [waymo-research/waymo-open-dataset#680]
I am trying to submit LiDAR 3D detection results on WOD website (valset), but the reply is: "Sorry, there was a problem submitting the form. Please try again" .
I used create_submission to generate target file, and I got the same error even if I using the fake_predictions.bin you provided. Any advice on this situation?

**Comment by VincentCa** [comment]
Hi! We've recently received one similar report. Could you verify the following?

- Could it be that you're on a protected network that denies uploads?
- There is a signing process based on the filename (so we can upload securely). It is possible that non-ASCII characters could generate some problems there, could you check whether any may be present in your filepath? 

Best,
Vincent

**Comment by douya1121** [comment]
@VincentCa  It's my network problem .Thank you so much!
