### ISSUE TITLE
For all data under the /tf_example/Training folder of Motion Dataset V1.2

### ISSUE THREAD

**Issue by YUQIJLU** [waymo-research/waymo-open-dataset#686]
Can I find the Value Range of state/{current,past,future}/xx data in all tfrecord format files under the Training folder? For example, after parsing a certain tfrecord file, I can get the range of state/past/x as (335.9037, 343.2258), and the range of state/past/y as (156.4488, 162.3615)...and I want to know the (min, max) of each of them after all tfrecord files have been parsed.

**Comment by scott-ettinger** [comment]
We don't have any utility for this.  The position data in the motion dataset has a different arbitrary origin for each scenario. The coordinates are not a single global coordinate system. Finding the overall min/max would also be an arbitrary range.  The scenarios are from multiple cities and there is no single 2D cartesian coordinate system that can cover all scenarios.  If you still need this range, unfortunately we do not have this data. You would need to run a task over the dataset to compute it.
