### ISSUE TITLE
Questions about the Waymo Motion data

### ISSUE THREAD

**Issue by xwenAR** [waymo-research/waymo-open-dataset#687]
Hello,

Thanks so much for sharing this data!

Currently I am using the motion part of Waymo Open Dataset to understand the effects of AVs on real-world traffic. I just have one question: in your paper titled "Large Scale Interactive Motion Forecasting for Autonomous Driving : The WAYMO OPEN MOTION DATASET". It is indicated that the motion part contains more than 570 hours of unique data. I am wondering if the AV control algorithm was updated during the data collection period.

Hope to hear from you.

Thanks.

**Comment by scott-ettinger** [comment]
Unfortunately, we are not able to provide any data about the autonomy algorithm or the state of the autonomous vehicle in the dataset at this time.  The dataset may contain both autonomous and human driven segments.

**Comment by xwenAR** [comment]
Thanks for your reply! Do you mean that the “AVs” in the motion part could be controlled by either the autonomy algorithms or human drivers and the control type was not disclosed in the data?

**Comment by scott-ettinger** [comment]
That is correct.  Some fraction of the data may be driven by human drivers. Unfortunately we are not able to release any data on which Scenarios were driven autonomously and which are manually driven, or any information about the autonomous software versions.  Sorry for any confusion on this. I will look into updating our website to clarify this.
