### ISSUE TITLE
Something goes wrong on the submission website.

### ISSUE THREAD

**Issue by Longzhong-Lin** [waymo-research/waymo-open-dataset#689]
The website "https://waymo.com/open/" does not function rightly, when I submit results.tar.gz of the Challenges. The page always shows that "Sorry, there was a problem submitting the form. Please try again.",  even when I submit the correct file submitted before to validation split.
![image](https://github.com/waymo-research/waymo-open-dataset/assets/81036197/4fde60e1-6e17-4d66-a3e4-6906af1ef28a)

**Comment by scott-ettinger** [comment]
It looks like this is for the motion challenge?  I tested uploading to the validation server this morning and it was working for me.  Could you try refreshing the page at waymo.com/open to refresh the login and then try re-submitting?  If it is still not working, please let me know and we will look further into it.

**Comment by Longzhong-Lin** [comment]
Oh relogin works for me, thx!
