### ISSUE TITLE
Mismatch in id (unique object track id) between camera labels and laser labels

### ISSUE THREAD

**Issue by geoseb94** [waymo-research/waymo-open-dataset#69]
There is mismatch in id (unique object track id) between objects mentioned in camera labels and laser labels. The string length is also different in both. How to map objects in both labels?

**Comment by peisun1115** [comment]
We do not use the same track ID between camera images images and lidar labels. It is interesting project to associate them. The naive way is to associate them by matching 2d image labels and 2d lidar  projected labels.

**Comment by peisun1115** [comment]
I assume this is fixed. Closing now.
