### ISSUE TITLE
Camera Segmentation testing part is empty

### ISSUE THREAD

**Issue by bshelkhonov** [waymo-research/waymo-open-dataset#690]
Hello. I downloaded 2.0.0 WOD and found out that segmentation testing is empty.
Is it okay situation?

**Comment by alexzzhu** [comment]
Hi yes, we do not provide the labels for the test set and the camera segmentation dataset does not provide any new data. If you plan on using the eval server, we do provide the frames for which we have labels in tutorial/2d_pvps_test_frames.txt.

**Comment by bshelkhonov** [comment]
Ok, thank you
