### ISSUE TITLE
why can not submit to motion prediction leaderboard?

### ISSUE THREAD

**Issue by ggosjw** [waymo-research/waymo-open-dataset#693]
![image](https://github.com/waymo-research/waymo-open-dataset/assets/87901530/2050878d-c4e5-40ed-86e1-546c767dd00f)
Hi, when I submit to the motion prediction leaderboard, it shows this error.
Could you give me some advice regarding this issue?
Thank you very much!

**Comment by scott-ettinger** [comment]
We will look into this issue. Sorry for the trouble.

**Comment by ggosjw** [comment]
> We will look into this issue. Sorry for the trouble.

Thank you for your kind help!

**Comment by scott-ettinger** [comment]
Could you try again?  I tested this morning and it worked for me.  Also, are you using the validation or test server?

**Comment by Longzhong-Lin** [comment]
> Could you try again? I tested this morning and it worked for me. Also, are you using the validation or test server?

I encountered the same problem when evaluating my results for both validation & test server.

**Comment by ggosjw** [comment]
> Could you try again? I tested this morning and it worked for me. Also, are you using the validation or test server?

Remains the same. Not solved.

**Comment by scott-ettinger** [comment]
We are looking into this. Just to confirm are your submission files similar in size and content to submissions that have worked successfully before?

**Comment by scott-ettinger** [comment]
Could you please try your submissions again?  I believe we have resolved the issue.

**Comment by ggosjw** [comment]
> Could you please try your submissions again? I believe we have resolved the issue.

Solved! Thank you for your help!
