### ISSUE TITLE
Panoramic Image

### ISSUE THREAD

**Issue by gogojjh** [waymo-research/waymo-open-dataset#7]
Hi,
a short question that how can I obtain the panoramic image (combining image from all cameras) from the dataset?
By the way, I am curious about the specific types of the lidars, and regarding the properties, what are the major differences between mid-range and short-range lidars?
Thanks.

**Comment by peisun1115** [comment]
1.  You can write your own code to combine all the 5 images in each frame in the dataset generate panoramic image.  We do not have code to do that in this repo.
2. You can try out our tutorial and explore mid-range/short-range lidars. In short, they have different ranges.

**Comment by xmyqsh** [comment]
@gogojjh 
How is going on you Panoramic Image reconstruction?
Indeed, this dataset is suitable for Panoramic Image reconstruction.

**Comment by juanluishortelano** [comment]
Hi, is it still the case that there are no full panoramic images in the dataset?
