### ISSUE TITLE
How do you obtain the pose of ego vehicle?

### ISSUE THREAD

**Issue by RicardoWUlei** [waymo-research/waymo-open-dataset#70]
Could you tell me how did you get the pose of ego vehicle? Is it from INS or anything else?
Cheers!

**Comment by peisun1115** [comment]
Pose is specified in the proto:
https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L281

**Comment by RicardoWUlei** [comment]
Thank you, I know where to find the pose data. My question is how the pose is collected?

**Comment by peisun1115** [comment]
The pose represents an integrated coordinate the car is at certain time. For every data frame, we set the pose to be the vehicle location (globally integrated) at the time corresponding the middle of the TOP lidar spin.
