### ISSUE TITLE
Unable to submit testing: "missing ground truth"

### ISSUE THREAD

**Issue by georgeliu233** [waymo-research/waymo-open-dataset#708]
Hi,

When I have submitted the testing zip file of Occupancy flow prediction, it popped out the following error:
![image](https://github.com/waymo-research/waymo-open-dataset/assets/46886579/41000961-eb5a-44f2-941a-7196745723e7)

**Comment by scott-ettinger** [comment]
Sorry for the delay I'll find the right person to take a look at this.

**Comment by alexgorban** [comment]
Hi, sorry that you experienced the difficulty evaluating your results and delayed response.

Your submission failed because it contained a scenario is `775e81a9d9f70276`, which is not in the test subset. Please filter out all non-testing scenarios from your submission and try again.
