### ISSUE TITLE
Is it possible to obtain laser label's pose in global frame?

### ISSUE THREAD

**Issue by Xiangwang-Hu** [waymo-research/waymo-open-dataset#71]
I tried to visualize all the laser label and ego vehicle in 2D plane (top view) in global frame. But I found the heading of laser label is not right (the ego vehicle's heading is always right).
I realize that the ego vehicle's pose is given in global frame. However, for the pose of laser label, only heading (in vehicle frame ) is give. If we don't know the pose of laser label, we then can't calculate the  laser label's heading in global frame ?

**Comment by peisun1115** [comment]
i think you are talking about vehicle frame instead of global frame?

the heading of the laser label is specified in vehicle frame. Make sure you don't switch the order of length/width. A common problem people encounter

**Comment by Xiangwang-Hu** [comment]
Thanks for your instant reply.
I think my problem is not from the order of length/width. Perhaps it's because I'm doing the visualization in 2D plane?
I think label's heading is actually the yaw angle in vehicle frame (without roll and pitch)?
So it's not possible to get the full pose of label ?
My final intention is to obtain the yaw angle of label in global frame, just like the pose of ego vehicle.

**Comment by peisun1115** [comment]
Heading in global frame = heading_in_vehicle_frame + vehicle_pose_yaw (find it from vehicle pose)

No need the full pose (yaw,pitch, row) for this though it is better to have. but without it, it still works. 


** I don't know why you need to viz things in global frame. I guess you want to viz multiple frames of data. Just convert everything into one vehicle frame (for example, the first one).

**Comment by Xiangwang-Hu** [comment]
Actually, I have tried the formula you provided and that's the best result I can get. In some segments everything looks great. But in some other segments where ego vehicle is turning or changing is heading, the parked vehicle at street side also rotates and moving vehicle is not heading right. I just can't figure out why is that. So I guess the error is possibly from pitch or row. I also check the data and calculate the headings ( in global frame ) for a parked vehicle using the formula, but the values are not constant.
I do want to viz multiple frames. Thanks for your advice, I'll try everything into one vehicle frame.

**Comment by peisun1115** [comment]
It might be related to the way you viz.  Try it in a vehicle frame is easier to viz

**Comment by Xiangwang-Hu** [comment]
Thanks a lot. I'll double check everything.

**Comment by zhangpur** [comment]
Hi, @peisun1115 

Is it correct to calculate the heading in global frame as:

pose=np.reshape(np.array(frame.pose.transform), [4, 4])
heading_global=box.heading - Quaternion(matrix=pos[:3,:3]).yaw_pitch_roll[0]

Thanks.

**Comment by peisun1115** [comment]
@zhangpur  I think it is '+' instead  of '-' . But it is probably more reliable by testing it with two frames and a moving object.

Alternatively, you can use [this](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/utils/box_utils.py#L198) function by setting 'to_frame_pose' to eye(4) and 'from_frame_pose' to the pose in the current frame.
