### ISSUE TITLE
Cannot download dataset

### ISSUE THREAD

**Issue by jjeong19** [waymo-research/waymo-open-dataset#721]
Hi, First of all thank you for providing the open dataset!
While trying to access the open dataset, it seems even after registering at waymo.com/open/licensing several times I wasn't able to get access to the dataset. 
![image](https://github.com/waymo-research/waymo-open-dataset/assets/42210420/8b41bba5-7ed1-4da3-af74-1aae96ddb1d7)

I thought it could have been due to some error with how I listed my school email address on my initial licensing form, so I tried registering under my personal gmail, but could never get the permission issue resolved. Could you help look into this? 

Sincerely,
Jason

**Comment by scott-ettinger** [comment]
Can you tell me the email address you are using to try to register?

**Comment by jjeong19** [comment]
@scott-ettinger I was able to get in touch with Alex and was able to get my email manually added to the list. Thank you!
