### ISSUE TITLE
Results not returned for about one week of the Sim Agent Channel

### ISSUE THREAD

**Issue by william-gx** [waymo-research/waymo-open-dataset#722]
Hi, 

The results have not been returned since submission on Sep. 15 in the Sim Agent Channel.  Could you help to find whether there is a problem?  The account is gxyssy@163.com.
<img width="940" alt="截屏2023-09-21 上午11 05 16" src="https://github.com/waymo-research/waymo-open-dataset/assets/33149255/a4430495-f4ae-48a2-b164-ba1e5ae629fd">

<img width="1106" alt="截屏2023-09-21 上午11 05 29" src="https://github.com/waymo-research/waymo-open-dataset/assets/33149255/fe137e13-c0e9-446a-bae1-49264c2a4f7c">

**Comment by alexgorban** [comment]
Hi, your submission from 2023-09-14 has been processed and results should be ready to view.
Sorry for the transient issue.
