### ISSUE TITLE
Segment numbers are changed

### ISSUE THREAD

**Issue by timegate** [waymo-research/waymo-open-dataset#723]
It seems that there had been segments named
segment-1172406780360799916_1660_000_1680_000_with_camera_labels
segment-4058410353286511411_3980_000_4000_000_with_camera_labels
in waymo_open_dataset_v_1_4_2 google cloud.

But now there are different segments in waymo_open_dataset_v_1_4_2 google cloud.
(I can't find segment-40... in even other folders (test, valid), even other versions (v_2_0, v_1_3, etc..))

Could anyone please explain what happened to this?

**Comment by timegate** [comment]
There was my mistake. I'm sorry to bothering you if anyone read this.

**Comment by LiuXuan66** [comment]
> There was my mistake. I'm sorry to bothering you if anyone read this.

same question. So why?
