### ISSUE TITLE
Does the TOP LiDAR use Phase Lock?

### ISSUE THREAD

**Issue by ly3106** [waymo-research/waymo-open-dataset#726]
Dear @peisun1115

The picture first picture was generated using the following Python code and LiDAR's extrinsic matrix. However, the coordinate frame of the TOP LiDAR is different from what is shown in the [official paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Sun_Scalability_in_Perception_for_Autonomous_Driving_Waymo_Open_Dataset_CVPR_2020_paper.pdf), as depicted in the last picture. So, I assume that the picture in the paper illustrates the sensor's coordinate frame, while the extrinsic matrix represents the actual point cloud frames (i.e. TOP LiDAR uses Phase Lock). Furthermore, the Phase Lock angle is equal to the azimuth correction. Is my understanding correct? 

```
# draw extrinsic matrixs
vis = o3d.visualization.Visualizer()
vis.create_window()
extrinsic_O = np.eye(4)  # 例如，创建一个单位矩阵表示原点坐标系
coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame()  # 创建坐标系帧
coord_frame.transform(extrinsic_O)  # 应用外部矩阵
vis.add_geometry(coord_frame)  # 添加到可视化窗口
for c in frame.context.laser_calibrations:
    extrinsic = np.reshape(np.array(c.extrinsic.transform), [4, 4])
    extrinsic = tf.linalg.inv(extrinsic).numpy()
    coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame()  # 创建坐标系帧
    coord_frame.transform(extrinsic)  # 应用外部矩阵
    vis.add_geometry(coord_frame)  # 添加到可视化窗口
vis.run()
vis.destroy_window()
```

and

Item|Version|
--|--
WOD|v1.3.1
WOD lib| -tf-2-6-0 v1.4.9

![ScreenCapture_2023-10-08-14-22-55](https://github.com/waymo-research/waymo-open-dataset/assets/42125674/1219b360-925f-472f-8c6d-94aab11bbd13)
------
![图片1](https://github.com/waymo-research/waymo-open-dataset/assets/42125674/47f29197-5bad-4794-a944-c186896ae971)

**Comment by peisun1115** [comment]
yeah, the top_lidar's exact sensor frame is determined by the extrinsic. It is not aligned with vehicle frame.

our code handle it like this https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/utils/range_image_utils.py#L286

**Comment by xcyan** [comment]
@ly3106 Thanks for your interest! Can we close this issue now?
