### ISSUE TITLE
An error occurred when submitted the Waymo benchmark for testing.

### ISSUE THREAD

**Issue by lunhengsheng** [waymo-research/waymo-open-dataset#734]
I trained and inferred the network locally, then submitted the detection results to the Waymo benchmark. However, I did not receive any detection results and encountered the following error message.

UNAVAILABLE: server(s) are not responding [type.googleapis.com/util.ErrorSpacePayload='RPC::UNREACHABLE']

![WX20231027-162658@2x](https://github.com/waymo-research/waymo-open-dataset/assets/75060618/47c2ef8c-016d-4c1f-8a79-992f9cfa2cd7)

How can this problem be solved?

**Comment by lunhengsheng** [comment]
@scott-ettinger

**Comment by scott-ettinger** [comment]
We will look into this issue.

**Comment by scott-ettinger** [comment]
Which challenge did you submit to?

**Comment by lunhengsheng** [comment]
> Which challenge did you submit to?

3D detection

**Comment by lunhengsheng** [comment]
> We will look into this issue.

May I ask when this issue can be resolved?

**Comment by scott-ettinger** [comment]
Sorry for the delay.  We are trying to reproduce the issue now.

**Comment by sankin97** [comment]
Hello, has the issue that occurred when submitting the Waymo benchmark for testing been resolved?

**Comment by scott-ettinger** [comment]
Sorry for the delay. Engineers are looking into this.

**Comment by scott-ettinger** [comment]
Could you please try your submissions again?  The problem should be resolved. Please let us know if you are still having trouble.

**Comment by sankin97** [comment]
It's normal now, and thank you for your help!

**Comment by lunhengsheng** [comment]
> Could you please try your submissions again? The problem should be resolved. Please let us know if you are still having trouble.

Thanks to your help, have been able to submit tests and get proper results!
