### ISSUE TITLE
Visualization of  `tutorial/frames` point cloud is not correct.

### ISSUE THREAD

**Issue by nan0755** [waymo-research/waymo-open-dataset#74]
top-down view
![image](https://user-images.githubusercontent.com/29373801/69305284-6a69d000-0c5e-11ea-92db-33e7c39b03b6.png)
side view
![image](https://user-images.githubusercontent.com/29373801/69305295-781f5580-0c5e-11ea-9e90-be3b6b4bac69.png)

Just as visulization above, the points which height between [0.0, ~1.X] is missing, and also the upper poinc cloud should be near the lower point cloud.

Here is my code script, I use Open3D for visualization.
```python
import os
import imp
import tensorflow as tf
import open3d
import time

tf.enable_eager_execution()

from waymo_open_dataset.utils import range_image_utils
from waymo_open_dataset.utils import transform_utils
from waymo_open_dataset.utils import frame_utils
from waymo_open_dataset.utils import box_utils
from waymo_open_dataset import dataset_pb2 as open_dataset
from box_utils import vis3DBBox

dataset = tf.data.TFRecordDataset("tutorial/frames", compression_type='')

for id, data in enumerate(dataset):
      frame = open_dataset.Frame()
      frame.ParseFromString(bytearray(data.numpy()))

    (range_images, camera_projections, range_image_top_pose) = frame_utils.parse_range_image_and_camera_projection(frame)
        points, cp_points = frame_utils.convert_range_image_to_point_cloud(frame, range_images, camera_projections,
                                                                            range_image_top_pose)

        # store points to protobuf
        top_lidar_point = points[0]
        point_cloud = open3d.geometry.PointCloud()
        point_cloud.points = open3d.utility.Vector3dVector(top_lidar_point)
        open3d.visualization.draw_geometries([point_cloud])

```

**Comment by nan0755** [comment]
Also if I visualize all lidars' point cloud, the blind zone lidar's point cloud coordinates are not compatible with the top lidar:
![image](https://user-images.githubusercontent.com/29373801/69397445-2be91980-0d21-11ea-8636-329d90dd708d.png)

**Comment by Weijiang-Xiong** [comment]
hello, I also experienced the same issue
the colab tutorial works just fine, but when I downloaded the tutorial to my machine, the point cloud just look like what you post here.
I think the problem may lay in frame_utils.convert_range_image_to_point_cloud, but I do not know how to fix it. 
would you mind sharing you solution to this? many thanks

**Comment by huyhung411991** [comment]
We had the same problem when extracting the lidar data using waymo-open-dataset-tf-2-0-0 on tensorflow-gpu 2.0 installed with pip. However, when we use waymo-open-dataset-tf-2-1-0 on tensorflow-gpu 2.1 install with conda, everything works fine. Maybe try that and see if it helps.
