### ISSUE TITLE
Whether all imaging configurations of the three front-facing cameras are identical, aside from the shutter time？

### ISSUE THREAD

**Issue by yifanlu0227** [waymo-research/waymo-open-dataset#742]
Hi!

I wish to reconstruct Waymo's autonomous driving scene, taking into account the exposure time of each camera. I first want to ascertain whether the RollingShutterParams.shutter parameter corresponds to the duration each pixel is exposed to light? For example, in the scene `segment-11379226583756500423_6230_810_6250_810_with_camera_labels`, the first camera's shutter time is about 0.0005

 Beyond this, in the imaging process of the three forward-facing cameras, is shutter time the only differing factor, with other parameters such as aperture and focal length remaining identical? 

I find your answer in #544  @VincentCa , that's useful. Would you mind answering this question? Thanks a lot!

**Comment by VincentCa** [comment]
Hi! 

> I first want to ascertain whether the RollingShutterParams.shutter parameter corresponds to the duration each pixel is exposed to light?
Yes, more specifically it represents the exposure time for the whole image column. Just a reminder that the cameras have a horizontal rolling shutter, and that exposure times heavily overlap.

> Beyond this, in the imaging process of the three forward-facing cameras, is shutter time the only differing factor, with other parameters such as aperture and focal length remaining identical?
Yes to the things you mentioned, however the three forward-facing cameras trigger sequentially as they are synchronized with the LiDAR spin. For each camera image, you can find a unique `camera\_trigger\_time` and `readout\_done\_time`. If you are looking to obtain more accurate camera pose in world coordinates, this will need to be considered as the ego vehicle may have moved.

**Comment by yifanlu0227** [comment]
Thank you !!!
