### ISSUE TITLE
Is there a way to associate the motion data to the perception data in a one to one manner?

### ISSUE THREAD

**Issue by wisleythewise** [waymo-research/waymo-open-dataset#743]

**Comment by ZiliangMiao** [comment]
Same question. I want to use all lidar scans of Motion dataset,  instead of "the first 1 second of each of the 9-second windows".
https://github.com/waymo-research/waymo-open-dataset/issues/740

**Comment by scott-ettinger** [comment]
The perception data and the motion data are distinct datasets.  They do not contain the same data.

Thanks for the feedback about the desire for the full 9 seconds of lidar data.  We are not able to provide the full 9 seconds at this time but we will consider this for future releases.

**Comment by wisleythewise** [comment]
Thank you for the clarification!

Op vr 10 nov. 2023 om 03:33 schreef Scott ***@***.***>
