### ISSUE TITLE
[Motion Mertics - mAP] why bin right u-turns with right turns?

### ISSUE THREAD

**Issue by SEU-zxj** [waymo-research/waymo-open-dataset#754]
Hi! I am new to here and recently I read your paper "Large Scale Interactive Motion Forecasting for Autonomous Driving: The Waymo Open Motion Dataset". 
In the last few pages of the paper, you visualize 7 types (i.e. Stationary, Straight, Straight-Left, Straight-Right, .etc) of trajectories' P-R curve with different pridict trajectory number K=3,6,12,24. I cut off the picture below.
![image](https://github.com/waymo-research/waymo-open-dataset/assets/73421144/dd78b9fc-0817-4417-b8f1-e56367d61310)

I'm confusing about the types you provide in the picture, I mean, why the PR-curve of Right-U-Turn is not shown in the picture......

I read the source code of waymo-open-dataset/motion_metrics.cc, and at line 684, I find the code that can explain the reason why right u-turn is not appear in picture above.
```
  // Bin right u-turns with right turns.
  if (type == TrajectoryType::RIGHT_U_TURN) {
    type = TrajectoryType::RIGHT_TURN;
  }
```
I do not know the reason why bin right u-turns with right turns......
can someone help me explain?
Thanks~

**Comment by scott-ettinger** [comment]
The reason is that for areas that drive on the right side of the road, right U turns do not really exist.  There is not a way to turn right to get back onto the same road. The motion dataset is exclusively from areas that drive on the right side of the road. If we left right U-turns as its own bin, only trajectories that are incorrectly classified as right U-turns (there should be none) would be in that bin and this would skew the results with noise.

**Comment by SEU-zxj** [comment]
@scott-ettinger Thanks for your reply, I think I got it!
Thanks again~❤

**Comment by SEU-zxj** [comment]
@scott-ettinger Hi, I have some new questions. It is true that for vehicles, there should not appear a right-u-turn trajectory. However, I think it make no sense for pedestrian and cyclist? Based on your paper's cluster gragh (I provided below), I think there exist some pedestrain and cyclist trajectories should by classfied as right-u-turn. And the code in line 684 in waymo-open-dataset/motion_metrics.cc seems to conduct "bin switch" for all three types of agent.
```
  // Bin right u-turns with right turns.
  if (type == TrajectoryType::RIGHT_U_TURN) {
    type = TrajectoryType::RIGHT_TURN;
  }
```

Sorry, it seem that the network is something wrong here, I will provide the graph later......

**Comment by scott-ettinger** [comment]
It is true that all agent types get binned in the same way.  This is a design choice.  Because vehicles cannot have a right U turn bin, we combine the bins together for all 3 agent types and we don't use the right U turn bin.  All agent types need to have the same number of bins to be able to compute the average across bins for all agents. Please let me know if you have further questions or concerns.

**Comment by SEU-zxj** [comment]
Oh, Thanks for your explanation❤. I am late, here is the image that I mentioned above.
<img width="229" alt="cluster figure" src="https://github.com/waymo-research/waymo-open-dataset/assets/73421144/e9edfe39-a74f-42e9-85bc-097caf093c43">

**Comment by SEU-zxj** [comment]
@scott-ettinger , Hi. I think the current design choice (i.e. combining the bins together for all 3 agent types) may classify some pedestrians' trajectories into right-turn, but they should be classified as right-u-turn. This is my concern, and you have just explained your design choice, Thanks!

And I look up your code just now, I think maybe we can just do the "bin switch" for the vehicle but not pedestrian or cyclist. Below are my reasons:
1. You designed 8 trajectory types, but in the current design choice, "right-u-turn" is not used. The reason is just as you explained to me at first (The motion dataset is exclusively from areas that drive on the right side of the road).
2. In waymo-open-dataset/motion_metrics.cc, at line 995, the function ComputeMapMetric is used to compute the mAP.
```
double ComputeMapMetric(MeanAveragePrecisionStats* stats) {
  double total = 0;
  int count = 0;
  for (auto& bucket : stats->pr_buckets) {
    if (!bucket.samples.empty()) {
      total += ComputeMeanAveragePrecision(&bucket);
      ++count;
    }
  }
  if (count == 0) {
    return 0.0;
  }
  return total / count;
}
```
the if statement in the for loop indicates that the empty bin is not considered in the final result (we do not count the empty bin). I mention this as this shows that whether or not we conduct the "bin switch" action, we will obtain a reasonable mAP result.

Based on my concern, what I want to do is simply add an if statement before we do the "bin switch" action. And I think it is reasonable as we just change the variable ```count``` in the above function (i.e. for the vehicle, count = 7, for pedestrian and cyclist, count = 8), the final mAP result is the AP average of all non-empty bins.
```
// [Add] Only do "bin switch" for vehicle
if(object_type == TYPE_VEHICLE){
  // Bin right u-turns with right turns.
  if (type == TrajectoryType::RIGHT_U_TURN) {
    type = TrajectoryType::RIGHT_TURN;
  }
}
```

However, there is also a question:
In the function domain, object_type is not defined. 

The function invoke chain to compute mAP from the beginning is:
```ComputeImpl(...)``` in ```motion_metrics_ops.cc``` =>
```ComputeMetricsStats(...)``` in ```motion_metrics.cc``` =>
```ComputeAllMetrics(...)``` in ```motion_metrics.cc``` =>
```ComputeMeanAveragePrecision()``` in ```motion_metrics.cc```
and skip later functions.
I find that in function ```ComputeAllMetrics(...)```'s domain, ```object_type``` is defined. So, adding a parameter to the function ```ComputeMeanAveragePrecision``` may solve this problem.

What do you think about it?
