### ISSUE TITLE
The potential bug in the mAP direction classification method.

### ISSUE THREAD

**Issue by BJHYZJ** [waymo-research/waymo-open-dataset#755]
Hello, thank you for your contributions to the WOMD dataset. I am a data user who has been researching mAP and soft mAP for some time. I am inquisitive about the trajectory classification interface in the API and I have noticed a potential bug. The processing of angles in the classification of trajectories may lead to inaccurate classification. In the original data, the vehicle's angle is represented in radians, ranging from (-pi, pi). However, I believe this angle value can be adjusted using the modulus operation to restrict it within the range of (0, 2*pi), to prevent potential errors in directional classification.

The method path in: https://github.com/waymo-research/waymo-open-dataset/blob/c9bf4d829bdf10f48a0dec2ef0ef2e5e05a8a0db/src/waymo_open_dataset/metrics/motion_metrics_utils.cc#L28

**Comment by scott-ettinger** [comment]
Thanks for raising this.  Could you say more how changing to range (0, 2pi) would help the issue?  It does look like there could potentially be a missing angle normalization.

**Comment by BJHYZJ** [comment]
`def GetStandardAngle(angle):
    while angle < 0 or angle >= 2 * math.pi:
        if angle < 0:
            angle += 2 * math.pi
        else:
            angle -= 2 * math.pi
    return angle

def GetStandardHeadingDiff(angle):
    if abs(angle) > math.pi:
        # return -(2 * math.pi - abs(angle))
        if angle < 0:
            return 2 * math.pi - abs(angle)
        else:
            return -(2 * math.pi - abs(angle))
    else:
        return angle

def ClassifyTrack(track):
    # Constants for classification
    kMaxSpeedForStationary = 2.0  # m/s
    kMaxDisplacementForStationary = 5.0  # m
    kMaxLateralDisplacementForStraight = 5.0  # m
    kMinLongitudinalDisplacementForUTurn = -5.0  # m
    kMaxAbsHeadingDiffForStraight = math.pi / 6.0  # rad

    # Extract valid states
    valid_states = [state for state in track if state[9]]  # state[9] is the valid bit

    if not valid_states:
        return "Invalid"

    # Start and end state
    start_state = valid_states[0]
    end_state = valid_states[-1]

    # Compute deltas and displacements
    x_delta = end_state[0] - start_state[0]  # cx
    y_delta = end_state[1] - start_state[1]  # cy
    final_displacement = math.hypot(x_delta, y_delta)
    heading_diff = GetStandardAngle(end_state[6]) - GetStandardAngle(start_state[6])  # heading
    heading_diff = GetStandardHeadingDiff(heading_diff)

    # Normalized deltas
    dx = x_delta * math.cos(-start_state[6]) - y_delta * math.sin(-start_state[6])
    dy = x_delta * math.sin(-start_state[6]) + y_delta * math.cos(-start_state[6])

    # Speed calculations
    start_speed = math.hypot(start_state[7], start_state[8])  # vel_x, vel_y
    end_speed = math.hypot(end_state[7], end_state[8])  # vel_x, vel_y
    max_speed = max(start_speed, end_speed)

    # Trajectory type classification
    if max_speed < kMaxSpeedForStationary and final_displacement < kMaxDisplacementForStationary:
        return "STATIONARY"
    if abs(heading_diff) < kMaxAbsHeadingDiffForStraight:
        if abs(dy) < kMaxLateralDisplacementForStraight:
            return "STRAIGHT"
        return "STRAIGHT_RIGHT" if dy < 0 else "STRAIGHT_LEFT"
    if heading_diff < -kMaxAbsHeadingDiffForStraight and dy < 0:
        return "RIGHT_U_TURN" if dx < kMinLongitudinalDisplacementForUTurn else "RIGHT_TURN"
    if dx < kMinLongitudinalDisplacementForUTurn:
        return "LEFT_U_TURN"

    return "LEFT_TURN"
`

Maybe like this.

**Comment by BJHYZJ** [comment]
`def GetStandardAngle(angle):
    while angle < 0 or angle >= 2 * math.pi:
        if angle < 0:
            angle += 2 * math.pi
        else:
            angle -= 2 * math.pi
    return angle

def GetStandardHeadingDiff(angle):
    if abs(angle) > math.pi:
        # return -(2 * math.pi - abs(angle))
        if angle < 0:
            return 2 * math.pi - abs(angle)
        else:
            return -(2 * math.pi - abs(angle))
    else:
        return angle

def ClassifyTrack(track):
    # Constants for classification
    kMaxSpeedForStationary = 2.0  # m/s
    kMaxDisplacementForStationary = 5.0  # m
    kMaxLateralDisplacementForStraight = 5.0  # m
    kMinLongitudinalDisplacementForUTurn = -5.0  # m
    kMaxAbsHeadingDiffForStraight = math.pi / 6.0  # rad

    # Extract valid states
    valid_states = [state for state in track if state[9]]  # state[9] is the valid bit

    if not valid_states:
        return "Invalid"

    # Start and end state
    start_state = valid_states[0]
    end_state = valid_states[-1]

    # Compute deltas and displacements
    x_delta = end_state[0] - start_state[0]  # cx
    y_delta = end_state[1] - start_state[1]  # cy
    final_displacement = math.hypot(x_delta, y_delta)
    heading_diff = GetStandardAngle(end_state[6]) - GetStandardAngle(start_state[6])  # heading
    heading_diff = GetStandardHeadingDiff(heading_diff)

    # Normalized deltas
    dx = x_delta * math.cos(-start_state[6]) - y_delta * math.sin(-start_state[6])
    dy = x_delta * math.sin(-start_state[6]) + y_delta * math.cos(-start_state[6])

    # Speed calculations
    start_speed = math.hypot(start_state[7], start_state[8])  # vel_x, vel_y
    end_speed = math.hypot(end_state[7], end_state[8])  # vel_x, vel_y
    max_speed = max(start_speed, end_speed)

    # Trajectory type classification
    if max_speed < kMaxSpeedForStationary and final_displacement < kMaxDisplacementForStationary:
        return "STATIONARY"
    if abs(heading_diff) < kMaxAbsHeadingDiffForStraight:
        if abs(dy) < kMaxLateralDisplacementForStraight:
            return "STRAIGHT"
        return "STRAIGHT_RIGHT" if dy < 0 else "STRAIGHT_LEFT"
    if heading_diff < -kMaxAbsHeadingDiffForStraight and dy < 0:
        return "RIGHT_U_TURN" if dx < kMinLongitudinalDisplacementForUTurn else "RIGHT_TURN"
    if dx < kMinLongitudinalDisplacementForUTurn:
        return "LEFT_U_TURN"

    return "LEFT_TURN"
`

**Comment by BJHYZJ** [comment]
```
def GetStandardAngle(angle):
    while angle < 0 or angle >= 2 * math.pi:
        if angle < 0:
            angle += 2 * math.pi
        else:
            angle -= 2 * math.pi
    return angle

def GetStandardHeadingDiff(angle):
    if abs(angle) > math.pi:
        # return -(2 * math.pi - abs(angle))
        if angle < 0:
            return 2 * math.pi - abs(angle)
        else:
            return -(2 * math.pi - abs(angle))
    else:
        return angle

def ClassifyTrack(track):
    # Constants for classification
    kMaxSpeedForStationary = 2.0  # m/s
    kMaxDisplacementForStationary = 5.0  # m
    kMaxLateralDisplacementForStraight = 5.0  # m
    kMinLongitudinalDisplacementForUTurn = -5.0  # m
    kMaxAbsHeadingDiffForStraight = math.pi / 6.0  # rad

    # Extract valid states
    valid_states = [state for state in track if state[9]]  # state[9] is the valid bit

    if not valid_states:
        return "Invalid"

    # Start and end state
    start_state = valid_states[0]
    end_state = valid_states[-1]

    # Compute deltas and displacements
    x_delta = end_state[0] - start_state[0]  # cx
    y_delta = end_state[1] - start_state[1]  # cy
    final_displacement = math.hypot(x_delta, y_delta)
    heading_diff = GetStandardAngle(end_state[6]) - GetStandardAngle(start_state[6])  # heading
    heading_diff = GetStandardHeadingDiff(heading_diff)

    # Normalized deltas
    dx = x_delta * math.cos(-start_state[6]) - y_delta * math.sin(-start_state[6])
    dy = x_delta * math.sin(-start_state[6]) + y_delta * math.cos(-start_state[6])

    # Speed calculations
    start_speed = math.hypot(start_state[7], start_state[8])  # vel_x, vel_y
    end_speed = math.hypot(end_state[7], end_state[8])  # vel_x, vel_y
    max_speed = max(start_speed, end_speed)

    # Trajectory type classification
    if max_speed < kMaxSpeedForStationary and final_displacement < kMaxDisplacementForStationary:
        return "STATIONARY"
    if abs(heading_diff) < kMaxAbsHeadingDiffForStraight:
        if abs(dy) < kMaxLateralDisplacementForStraight:
            return "STRAIGHT"
        return "STRAIGHT_RIGHT" if dy < 0 else "STRAIGHT_LEFT"
    if heading_diff < -kMaxAbsHeadingDiffForStraight and dy < 0:
        return "RIGHT_U_TURN" if dx < kMinLongitudinalDisplacementForUTurn else "RIGHT_TURN"
    if dx < kMinLongitudinalDisplacementForUTurn:
        return "LEFT_U_TURN"

    return "LEFT_TURN"


```

**Comment by BJHYZJ** [comment]
```def GetStandardAngle(angle):
    while angle < 0 or angle >= 2 * math.pi:
        if angle < 0:
            angle += 2 * math.pi
        else:
            angle -= 2 * math.pi
    return angle

def GetStandardHeadingDiff(angle):
    if abs(angle) > math.pi:
        # return -(2 * math.pi - abs(angle))
        if angle < 0:
            return 2 * math.pi - abs(angle)
        else:
            return -(2 * math.pi - abs(angle))
    else:
        return angle

def ClassifyTrack(track):
    # Constants for classification
    kMaxSpeedForStationary = 2.0  # m/s
    kMaxDisplacementForStationary = 5.0  # m
    kMaxLateralDisplacementForStraight = 5.0  # m
    kMinLongitudinalDisplacementForUTurn = -5.0  # m
    kMaxAbsHeadingDiffForStraight = math.pi / 6.0  # rad

    # Extract valid states
    valid_states = [state for state in track if state[9]]  # state[9] is the valid bit

    if not valid_states:
        return "Invalid"

    # Start and end state
    start_state = valid_states[0]
    end_state = valid_states[-1]

    # Compute deltas and displacements
    x_delta = end_state[0] - start_state[0]  # cx
    y_delta = end_state[1] - start_state[1]  # cy
    final_displacement = math.hypot(x_delta, y_delta)
    heading_diff = GetStandardAngle(end_state[6]) - GetStandardAngle(start_state[6])  # heading
    heading_diff = GetStandardHeadingDiff(heading_diff)

    # Normalized deltas
    dx = x_delta * math.cos(-start_state[6]) - y_delta * math.sin(-start_state[6])
    dy = x_delta * math.sin(-start_state[6]) + y_delta * math.cos(-start_state[6])

    # Speed calculations
    start_speed = math.hypot(start_state[7], start_state[8])  # vel_x, vel_y
    end_speed = math.hypot(end_state[7], end_state[8])  # vel_x, vel_y
    max_speed = max(start_speed, end_speed)

    # Trajectory type classification
    if max_speed < kMaxSpeedForStationary and final_displacement < kMaxDisplacementForStationary:
        return "STATIONARY"
    if abs(heading_diff) < kMaxAbsHeadingDiffForStraight:
        if abs(dy) < kMaxLateralDisplacementForStraight:
            return "STRAIGHT"
        return "STRAIGHT_RIGHT" if dy < 0 else "STRAIGHT_LEFT"
    if heading_diff < -kMaxAbsHeadingDiffForStraight and dy < 0:
        return "RIGHT_U_TURN" if dx < kMinLongitudinalDisplacementForUTurn else "RIGHT_TURN"
    if dx < kMinLongitudinalDisplacementForUTurn:
        return "LEFT_U_TURN"

    return "LEFT_TURN"
```

This is the python version I'm using.

**Comment by pengzhenghao** [comment]
So does this mean that when doing local evaluation, we need to prepare the GT trajectory with heading copy from the original data but manually change it's range to [0, 2pi]?
