### ISSUE TITLE
Sim Agents leaderboard numbers have changed

### ISSUE THREAD

**Issue by jonahthelion** [waymo-research/waymo-open-dataset#758]
Hello,

Something seems to have changed very recently in how the meta metric, interaction metrics, and map metrics are reported for the sim agents benchmark, resulting in a significant reranking of all the submissions. The kinematic metrics and minADE are still the same, and it seems all of the component-level metrics (e.g. time to collision, off-road likelihood etc.) are still the same, so it's unclear why the meta metric values changed. Have the organizers changed how the meta metric is calculated?

**Comment by nicomon24** [comment]
@jonahthelion See https://waymo.com/open/challenges/2023/sim-agents-v0 for more references to the why this happened.
The code on github is also up to date now (as promised offline, took a bit more than planned :) )
