### ISSUE TITLE
failed to download motion dataset

### ISSUE THREAD

**Issue by SenZh1234** [waymo-research/waymo-open-dataset#771]
Hi,
I am trying to download the latest version of the motion dataset using:
gsutil -m cp -r "gs://waymo_open_dataset_motion_v_1_1_0/uncompressed/  . 

But I got the error:

NotFoundException: 404 gs://waymo_open_dataset_motion_v_1_1_0/uncompressed/tf_example/training/training_tfexample.tfrecord-00153-of-01000 does not exist.
CommandException: Some components of ./uncompressed/tf_example/training/training_tfexample.tfrecord-00153-of-01000 were not downloaded successfully. Please retry this download.

Could you tell me how can I resolve this issue?

Thanks,
Sen

**Comment by nicomon24** [comment]
Hi @SenZh1234,

I've checked manually and that specific file is in the bucket. Are you able to download the rest of the dataset?

**Comment by SenZh1234** [comment]
Thanks for your reply. @nicomon24 
It seems to be a problem with my network. I've got the dataset from someone else.
