### ISSUE TITLE
2+ hour wait time for test set results

### ISSUE THREAD

**Issue by jlidard** [waymo-research/waymo-open-dataset#777]
Hi all,

Many thanks for providing a great dataset and maintaining the public leaderboard. I just submitted results to the Interactive Challenge test set, but I am left with the message "This submission could not be found. If it was recently uploaded, it may still be processing. Check back in a few minutes" for the past few hours. Is it possible there is an issue with our submission, or possible with the server? I saw on #266 the server could give a similar message when it is down. 

Submission timestamp: 2/11/24 11:56 PM

Many thanks for any help you can provide!

**Comment by scott-ettinger** [comment]
I believe we discussed this on e-mail. Hopefully this has been resolved. Please let us know if you have any further issues.

**Comment by jlidard** [comment]
Yes, everything has been resolved! Thanks again.
