### ISSUE TITLE
lidar range different in paper and website?

### ISSUE THREAD

**Issue by AndyYuan96** [waymo-research/waymo-open-dataset#78]
Hi, I see in the waymo dataset website's Data Lidar, it says Range of the mid-range lidar truncated to a maximum of 75 meters, but in paper Scalability in Perception for Autonomous Driving： An Open Dataset Benchmark,  Baselines for Object Detection, it says For vehicles and pedestrians we set the voxel size to 0.33m, the grid range to [−85m; 85m] along the X and Y axes, and [−3m; 3m] along the Z axis.
why you set grid range to [-85,85], and the data range is [-75,75]?

**Comment by peisun1115** [comment]
75m is the range of lidar points in sensor frame. 

there can be objects partially outside 75m in vehicle frame. 85 is just an upper obund.

**Comment by AndyYuan96** [comment]
if a object is  outside 75m, can lidar see it ? , or camera can see the object.

**Comment by peisun1115** [comment]
If part of the object is within 75m radius, the truncated LiDAR can still see part of it.
