### ISSUE TITLE
The Test Set Submission of the Interaction Prediction Benchmark is Always Pending

### ISSUE THREAD

**Issue by ZikangZhou** [waymo-research/waymo-open-dataset#783]
Hi @scott-ettinger,

It seems that the server for the interaction prediction benchmark cannot process my test set submission normally. However, the submission of validation set results can be processed in less than 20 minutes. Can you check what's wrong with the server or what's wrong with my submission?

Here is my submission:

https://waymo.com/intl/en_us/open/challenges/entry/?timestamp=1709049556019437&challenge=INTERACTION_PREDICTION&emailId=5b7ac16e-1c97

**Comment by scott-ettinger** [comment]
Thanks for flagging this. We will take a look.

**Comment by scott-ettinger** [comment]
This has been resolved. It looks like your submission has been processed.  Sorry for the trouble.

**Comment by ZikangZhou** [comment]
Thanks a lot!
