### ISSUE TITLE
waymo 2022 Occupancy and Flow Prediction challenge server no response

### ISSUE THREAD

**Issue by zhyj-going** [waymo-research/waymo-open-dataset#785]
When I uploaded validataion result, https://waymo.com/open/challenges/2022/occupancy-flow-prediction-challenge/ everything seems , it always return the message like "This submission could not be found. If it was recently uploaded, it may still be processing. Check back in a few minutes.", even after one day.

I wanna know if the server is down or it's something wrong in my results.

**Comment by rezama** [comment]
Thanks for sharing this issue.  The evaluation server is down at the moment.  We are working on bringing it back up.  Once that happens, it should automatically process your submission.

**Comment by zhyj-going** [comment]
> Thanks for sharing this issue. The evaluation server is down at the moment. We are working on bringing it back up. Once that happens, it should automatically process your submission.

Thanks for the replay. When will the evaluation serve be up?

**Comment by nicomon24** [comment]
Hi @zhyj-going,
the server should be now up and running again, and all the past evaluations you submitted should be done. Let me know if you need further help.
