### ISSUE TITLE
How to calculate relative pose?

### ISSUE THREAD

**Issue by LucasSloan** [waymo-research/waymo-open-dataset#79]
How would I calculate the relative pose between 2 frames in the frame of a given camera?  Ie from frame 1 to 2, camera 1 moved 1 meter forwards, .05 meters left, .001 meters up (and the associated pitch yaw and roll)?

**Comment by xmyqsh** [comment]
Forward F:      1(m)
Left L:        0.05(m)
Up  U:      0.001(m)
pitch2 = pitch1 + arcsin(U, sqrt(F^2 + L^2 + U^2))
yaw2 = yaw1 + arctan2(L, F)
roll2 = roll1

**Comment by LucasSloan** [comment]
Sure, but the delta isn't a primitive in the dataset.  The closest thing available is the [velocity data](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L240), but that's in the global frame, not the vehicle frame.

I think you should somehow be able to combine the transform to from the [global frame to vehicle frame](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L229)  with the transforms from [vehicle frame to camera frame](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L102) to do the thing I want, but the dataset utils don't offer that.

**Comment by peisun1115** [comment]
@LucasSloan 

Global <-> vehicle frame transforms are determined by [poses](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L229). 

We also provide per LiDAR [point pose](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L217) if you want more advanced transforms. 

Global <-> Camera frames: Use [camera extrincs](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L102).

Camera <-> Image frame: Use camera intrinsics and our provided [camera model](https://github.com/waymo-research/waymo-open-dataset/tree/master/third_party/camera) to compensate for image distortion and rolling shutter effect.

**Comment by xmyqsh** [comment]
@LucasSloan 
That's easy. The velocity is in the global frame, including both linear velocity and angular velocity.
You can get the realtime vehicle pose at time `t` by:
```
  r(t) = CameraImage.pose.reshape(-1, 4)[:,3] + dr/dt * (t - CameraImage.pose_timestamp) where dr/dt = v_{x,y,z}.
  R(t) = CameraImage.pose.reshape(-1, 4)[:,:3] * SkewSymmetric(w_{x,y,z})*dt
```

**Comment by xmyqsh** [comment]
@peisun1115 
I create a PR to fix the comment of rotation calculation from angular velocity.
https://github.com/waymo-research/waymo-open-dataset/pull/80

**Comment by xmyqsh** [comment]
@LucasSloan @peisun1115 
A new PR #82 , please have a double check

**Comment by xmyqsh** [comment]
@peisun1115 
The [camera model](https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/camera_model.cc) is wonderful!
I have run out of my mind on it...
I have noticed the brief description of it in your paper. Is there a detailed technical report on the rolling shutter compensation algorithm?

One doubt on this formula:
```
307   const Eigen::Vector3d vehicle_omega_vehicle =
308       Eigen::Vector3d{velocity.w_x(), velocity.w_y(), velocity.w_z()};
312   const Eigen::Vector3d cam_omega_cam0 =
313       vehicle_tfm_cam.rotation().transpose() * vehicle_omega_vehicle;
```
Should it be:
```
307   const Eigen::Vector3d vehicle_omega_vehicle =
308       Eigen::Vector3d{velocity.w_x(), velocity.w_y(), velocity.w_z()};
312   const Eigen::Vector3d cam_omega_cam0 =
313       vehicle_tfm_cam.rotation().transpose() * vehicle_omega_vehicle
                                           * vehicle_tfm_cam.rotation();
```

Also, I cannot hold the velocity lever arm effect compensation total. It almost runs out of my mind...
```
rolling_shutter_state_->n_vel_cam0 =
                  n_vel_vehicle + SkewSymmetric(n_omega_vehicle) *
                                             n_tfm_vehicle0.rotation() *
                                             vehicle_tfm_cam.translation();
```
```
vehicle_tfm_cam.translation():  translation from cam to vehicle under vehicle coordinate
n_tfm_vehicle0.rotation() * vehicle_tfm_cam.translation(): trans from cam to veh under world coord
n_omega_vehicle: vehicle angular velocity under world coordinate
SkewSymmetric(n_omega_vehicle) * n_tfm_vehicle0.rotation() * vehicle_tfm_cam.translation()
= angular velocity of vehicle under world coordinate   *   trans from cam to veh under world coord
= relative velocity caused by level arm from camera to vehicle and angular velocity of vehicle under world coordinate
```
It is best for you to update the relevant comment on this topic. 

@LucasSloan 
You can get all of the things you want by calling 
```
from third_party.camera.ops.py_camera_model_ops import image_to_world, world_to_image
```

**Comment by xmyqsh** [comment]
> Sure, but the delta isn't a primitive in the dataset. The closest thing available is the [velocity data](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L240), but that's in the global frame, not the vehicle frame.
> 
> I think you should somehow be able to combine the transform to from the [global frame to vehicle frame](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L229) with the transforms from [vehicle frame to camera frame](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L102) to do the thing I want, but the dataset utils don't offer that.

@LucasSloan Nothing hears from you.
Have you solved your problem? You can solve it with P2P1^(-1). 
The material you have given above is mainly for solving the roll shutter problem. And the comment
[https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L232-L239](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L232-L239)  is misleading us. And @peisun1115 said he will update these comments which should coincide to [rolling shutter version camera model](https://github.com/waymo-research/waymo-open-dataset/blob/master/third_party/camera/camera_model.cc). I'm afraid I cannot describe this part precisely.

**Comment by LucasSloan** [comment]
I tried to import the ops you suggested and got this error:

Traceback (most recent call last):
  File "extract_waymo.py", line 5, in <module>
    from third_party.camera.ops.py_camera_model_ops import image_to_world, world_to_image
ModuleNotFoundError: No module named 'third_party'

waymo_open_dataset.third_party.camera.ops.py_camera_model_ops

and

waymo_open_dataset.camera.ops.py_camera_model_ops

also failed.

**Comment by LucasSloan** [comment]
Also I'm unsure about how to use those functions to solve my problem - they seem to be about finding coordinates of pixels in an image (?).  Whereas I'm trying to compute the distance between the camera at time t and t+1?

**Comment by xmyqsh** [comment]
@LucasSloan 
`waymo_open_dataset.camera.ops.py_camera_model_ops` is no need for you.
```
distance = norm(camera_image2.pose() - camera_image1.pose())
           === norm(camera_image2.pose() * calibration2.extrinsic()
                          - camera_image1.pose() * calibration1.extrinsic())
```

**Comment by LucasSloan** [comment]
Sure, but I want the distance vector and the euler angle delta, not just the scalar distance.

**Comment by xmyqsh** [comment]
@LucasSloan 
```
camera_image2.pose() = T_21 * camera_image1.pose()
distance vector = T_21.translation()
euler angle delta = rot_to_euler(T_21.rotation())
```

**Comment by LucasSloan** [comment]
Thanks!

I tried to implement that, but I'm getting values that don't agree with the velocity values that are given:

```python
    for i, data in enumerate(tf.data.TFRecordDataset(segment)):
        frame = open_dataset.Frame()
        frame.ParseFromString(bytearray(data.numpy()))

        image = frame.images[0]

        pose = np.array(image.pose.transform)
        pose = np.reshape(pose, (4, 4))

        if prev_pose is not None:
            rel_pose = np.matmul(pose, np.linalg.inv(prev_pose))
            speed1 = np.linalg.norm([image.velocity.v_x, image.velocity.v_y, image.velocity.v_z])
            speed2 = 10 * np.linalg.norm([rel_pose[0][3], rel_pose[1][3], rel_pose[2][3]])
            print(speed1, speed2)
        
        prev_pose = pose

        if i == 10:
            break
```

```
0.10803824049617468 133.9695143288111
0.1766319603489769 277.9366488390983
0.08566226429807572 128.08119288837347
0.10040338047241715 423.72370715580496
0.029014475459645406 30.534458026751366
0.1668031442568409 263.8516617054407
0.04438401779787703 141.20204275434259
0.24167411555415558 199.90540724269005
0.09369013701304411 225.99734677246494
0.16777656301224034 120.67921714435141
```

Any idea where I might have gone wrong?

**Comment by xmyqsh** [comment]
> Thanks!
> 
> I tried to implement that, but I'm getting values that don't agree with the velocity values that are given:
> 
> ```python
>     for i, data in enumerate(tf.data.TFRecordDataset(segment)):
>         frame = open_dataset.Frame()
>         frame.ParseFromString(bytearray(data.numpy()))
> 
>         image = frame.images[0]
> 
>         pose = np.array(image.pose.transform)
>         pose = np.reshape(pose, (4, 4))
> 
>         if prev_pose is not None:
>             rel_pose = np.matmul(pose, np.linalg.inv(prev_pose))
>             speed1 = np.linalg.norm([image.velocity.v_x, image.velocity.v_y, image.velocity.v_z])
>             speed2 = 10 * np.linalg.norm([rel_pose[0][3], rel_pose[1][3], rel_pose[2][3]])
>             print(speed1, speed2)
>         
>         prev_pose = pose
> 
>         if i == 10:
>             break
> ```
> 
> ```
> 0.10803824049617468 133.9695143288111
> 0.1766319603489769 277.9366488390983
> 0.08566226429807572 128.08119288837347
> 0.10040338047241715 423.72370715580496
> 0.029014475459645406 30.534458026751366
> 0.1668031442568409 263.8516617054407
> 0.04438401779787703 141.20204275434259
> 0.24167411555415558 199.90540724269005
> 0.09369013701304411 225.99734677246494
> 0.16777656301224034 120.67921714435141
> ```
> 
> Any idea where I might have gone wrong?

@LucasSloan
Everything looks well for me.
@peisun1115 
Do you have any idea?

**Comment by peisun1115** [comment]
Replace 
rel_pose = np.matmul(pose, np.linalg.inv(prev_pose))

with
rel_pose = np.matmul(np.linalg.inv(prev_pose), pose)

**Comment by xmyqsh** [comment]
> Replace
> rel_pose = np.matmul(pose, np.linalg.inv(prev_pose))
> 
> with
> rel_pose = np.matmul(np.linalg.inv(prev_pose), pose)

@peisun1115 Are you sure?
@LucasSloan Does this works for you?

**Comment by xmyqsh** [comment]
Hum, it depends on the definition of the pose, pose or pose.T.

**Comment by LucasSloan** [comment]
Yes, I tried that, and it seems to work.  Over the whole segment I'm testing with, the speed calculated that way correlates .999 with the speed calculated with the velocity labels.

Thanks!
