### ISSUE TITLE
Availability of v1.6.2 via pip?

### ISSUE THREAD

**Issue by twkillian** [waymo-research/waymo-open-dataset#791]
I am interested in updating my install of this library as soon as possible but realize that the package has not been yet been provided/built to pypi. 

When can we expect to have pip installation compatibility of the newest version of this library?

**Comment by nicomon24** [comment]
Hi @twkillian,

I just finished uploading the package to pypi https://pypi.org/project/waymo-open-dataset-tf-2-12-0/1.6.2/

Let me know if you have any issues.

Note: we still need to update the tutorials with the new version number.
