### ISSUE TITLE
How to get San Francisco mission bay dataset?

### ISSUE THREAD

**Issue by kalelpark** [waymo-research/waymo-open-dataset#793]
Hello, I'm wondering how to download the San Francisco Mission Bay Dataset.
What I mean is that I couldn't download this [Block-NeRF site](https://waymo.com/research/block-nerf/).
<img width="1294" alt="image" src="https://github.com/waymo-research/waymo-open-dataset/assets/86551201/eeb52bdb-1db0-4c9f-9b5f-1a48fb01a197">

Could you provide information on where the dataset can be download?
I would appreciate if someone could tell me.
Thank you for good research.

**Comment by VincentCa** [comment]
Hi,

Thank you for reporting this issue! We have updated the website to fix this issue.

If the issue persists, please reopen and report back here.

Thank you!
Vincent
