### ISSUE TITLE
Mapping the 3D bounding box location to the 2D image location

### ISSUE THREAD

**Issue by lunasdejavu** [waymo-research/waymo-open-dataset#8]
I am researching on ["BoxCars: Improving Fine-Grained Recognition of Vehicles using 3D Bounding Boxes in Traffic Surveillance"](https://arxiv.org/pdf/1703.00686.pdf) 
Is there any code or hint( like the distance between the 2d camera and LIDAR) to convert the 3D bounding box location in LIDAR to 2D IMAGE?
Thanks!

**Comment by henrikkretzschmar** [comment]
The dataset contains one or more 2D camera bounding boxes for each 3D lidar bounding box:
https://github.com/waymo-research/waymo-open-dataset/blob/9c663111bb63a9520d7037bd1cb878b0210f7a1d/waymo_open_dataset/dataset.proto#L285-L290

In addition to these projected lidar bounding boxes, the dataset also contains 2D camera bounding boxes that were directly labeled in the camera images, which also capture objects that are outside of the lidar field of view:
https://github.com/waymo-research/waymo-open-dataset/blob/9c663111bb63a9520d7037bd1cb878b0210f7a1d/waymo_open_dataset/dataset.proto#L291-L295
