### ISSUE TITLE
pip install waymo-open-dataset-tf-2-11-0==1.6.1

### ISSUE THREAD

**Issue by kawasaki94year** [waymo-research/waymo-open-dataset#804]
Hello, everyone.
   I have a question about the command pip install waymo-open-dataset-tf-2-11-0==1.6.1. When I enter this code in the Anaconda terminal, it shows two errors:
       ERROR: Could not find a version that satisfies the requirement waymo-open-dataset-tf-2-11-0==1.6.1 (from versions: none)
       ERROR: No matching distribution found for waymo-open-dataset-tf-2-11-0==1.6.1.
However, I have already installed TensorFlow 2.10.0 and Python 3.11.7 on Anaconda. How can I resolve this issue?
![image](https://github.com/waymo-research/waymo-open-dataset/assets/104112142/bec5e98d-d152-4915-86b4-95ce016b9a03)

**Comment by jamesheatonrdm** [comment]
I think python 3.11 is incompatible. It works for me with anaconda and python 3.10

**Comment by kawasaki94year** [comment]
> I think python 3.11 is incompatible. It works for me with anaconda and python 3.10
However, I have tried switching Python versions and encountered the same error. However, this error occurred on a **Windows 11** system. When I switched to a **Linux system** and used pip to install, it was installed successfully. Does this mean the waymo-open-dataset-tf library cannot be installed on Windows systems?

**Comment by nicomon24** [comment]
Hi @kawasaki94year, could you try install the new version? https://pypi.org/project/waymo-open-dataset-tf-2-12-0/1.6.2/ 
(I still need to update tutorials)

**Comment by kawasaki94year** [comment]
> Hi @kawasaki94year, could you try install the new version? https://pypi.org/project/waymo-open-dataset-tf-2-12-0/1.6.2/ 
> (I still need to update tutorials)

@nicomon24 
Thank you for your help. I installed Anaconda on Windows 11, and all the operations were done on Windows. So I tried to install the new version following your instructions, but encountered the same error. However, when I switched to a Linux system, I was able to install it successfully. Does this mean that the package cannot be installed on a Windows system?

**Comment by sashamilad** [comment]
I have the same issue, please some one help

**Comment by haynaou** [comment]
I had the same error on M2 Macbook until I used Linux (Ubuntu).

I was getting this error:
```
No matching distribution found for waymo-open-dataset-tf-2-12-0==1.6.4
```

And this how I got it working:

- Setup a new VM using Linux (ubuntu 22.04)
- Install Python 3.10.0 and pip
  ```sh
  sudo apt install Python3.10
  sudo apt-get install python3-pip
  ```
- Clone repo
  ```sh
   git clone https://github.com/waymo-research/waymo-open-dataset.git waymo-od
   cd waymo-od
  ```
- Install packages (this worked for me now)
  ```sh
   python3 -m pip install gcsfs waymo-open-dataset-tf-2-12-0==1.6.4
  ```

**Comment by nicomon24** [comment]
Responding to everyone on the thread: the package I uploaded on pypi specifies linux as the platform (https://github.com/waymo-research/waymo-open-dataset/blob/5f8a1cd42491210e7de629b6f8fc09b65e0cbe99/src/waymo_open_dataset/pip_pkg_scripts/BUILD#L242). 
If you are constrained to use non-linux environments, could you instead git clone and pip install from source?

**Comment by kawasaki94year** [comment]
> I had the same error on M2 Macbook until I used Linux (Ubuntu).
> 
> I was getting this error:
> 
> ```
> No matching distribution found for waymo-open-dataset-tf-2-12-0==1.6.4
> ```
> 
> And this how I got it working:
> 
> * Setup a new VM using Linux (ubuntu 22.04)
> * Install Python 3.10.0 and pip
>   ```shell
>   sudo apt install Python3.10
>   sudo apt-get install python3-pip
>   ```
> * Clone repo
>   ```shell
>    git clone https://github.com/waymo-research/waymo-open-dataset.git waymo-od
>    cd waymo-od
>   ```
> * Install packages (this worked for me now)
>   ```shell
>    python3 -m pip install gcsfs waymo-open-dataset-tf-2-12-0==1.6.4
>   ```

@haynaou Thanks for the help. I also managed to run it successfully on **Linux**. After seeing your steps, it seems like it can only be run on Linux. I guess this problem can only be solved on Linux and this package cannot be successfully run on **Windows**. Have you found any instructions on how to install waymo-open-dataset-tf-2-12-0==1.6.4 on Windows?

**Comment by kawasaki94year** [comment]
> Responding to everyone on the thread: the package I uploaded on pypi specifies linux as the platform (
> 
> https://github.com/waymo-research/waymo-open-dataset/blob/5f8a1cd42491210e7de629b6f8fc09b65e0cbe99/src/waymo_open_dataset/pip_pkg_scripts/BUILD#L242
> 
> ).
> If you are constrained to use non-linux environments, could you instead git clone and pip install from source?

@nicomon24 Thank you for your help. I will try the installation method you provided later.

**Comment by antoinekeller** [comment]
Same problem here
OS : Ubuntu 22.04 Jammy
Python: Python 3.10.12

Then I cloned the repo with:
```
 git clone https://github.com/waymo-research/waymo-open-dataset.git waymo-od
 cd waymo-od
```

```
python3 -m pip install waymo-open-dataset-tf-2-11-0==1.6.1
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement waymo-open-dataset-tf-2-11-0==1.6.1 (from versions: none)
ERROR: No matching distribution found for waymo-open-dataset-tf-2-11-0==1.6.1
```

I have been trying to change the package version but none of them is working.

Any help would be much appreciated !

**Comment by qiyan98** [comment]
Same problem here!

```
pip install waymo-open-dataset-tf-2-12-0
ERROR: Could not find a version that satisfies the requirement waymo-open-dataset-tf-2-12-0 (from versions: none)
ERROR: No matching distribution found for waymo-open-dataset-tf-2-12-0
```

This happens to me in `Python 3.10.14` with anaconda. Can anyone give me a hint?

Thanks.

**Comment by SyedShafiq** [comment]
Did this work for anybody?

**Comment by kawasaki94year** [comment]
> Did this work for anybody?

I have tried many methods to install it on the Windows system but none have worked. However, it works fine on the Ubuntu system. You need to match your Python version with the TensorFlow version.

**Comment by kawasaki94year** [comment]
> TensorFlow 2.10.0 and Python 3.11.7

**Comment by OrangeSodahub** [comment]
@nicomon24 Why you set this platform constraint? I need to use it on Winodws. Could you give some instructioin on how to install if from source on Windows?

**Comment by SoumyajitC-24** [comment]
doing apt update and updating the pip version to latest solved the problem for me.

**Comment by wisamshaheen1** [comment]
is there a way to install the data set if we are constrained with windows and using colab ?

**Comment by tanvi-sama** [comment]
Hi @nicomon24 ! Any updates? I'd like to use the library on an M1 Mac .
