### ISSUE TITLE
cannot import name 'womd_camera_utils' from 'waymo_open_dataset.utils'

### ISSUE THREAD

**Issue by lssiair** [waymo-research/waymo-open-dataset#806]
Hi, everyone,

I want to get the lidar and camera data in motion prediction task.  It shows an import error when I import the script of camera：

from waymo_open_dataset.utils import womd_camera_utils
ImportError: cannot import name 'womd_camera_utils' from 'waymo_open_dataset.utils' (unknown location)

Fortunately, the lidar script (womd_lidar_utils) can be imported normally.

**Comment by lssiair** [comment]
Thanks for your response, @nicomon24 . I install the new version, waymo-open-dataset-tf-2-12-0 == 1.6.2, but the womd_camera_utils still cannot be imported.  Below is my pip-installed list:
  
absl-py                      1.4.0
array-record                 0.5.0
astunparse                   1.6.3
cachetools                   5.3.3
certifi                      2024.2.2
charset-normalizer           3.3.2
click                        8.1.7
cloudpickle                  3.0.0
contourpy                    1.2.0
cycler                       0.12.1
dacite                       1.8.1
dask                         2023.3.1
dataclass_array              1.5.1
decorator                    5.1.1
dm-tree                      0.1.8
einops                       0.7.0
einsum                       0.3.0
etils                        1.7.0
flatbuffers                  24.3.25
fonttools                    4.50.0
fsspec                       2024.3.1
gast                         0.4.0
google-auth                  2.16.2
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
googleapis-common-protos     1.63.0
grpcio                       1.62.1
h5py                         3.10.0
idna                         3.6
imageio                      2.34.0
immutabledict                2.2.0
importlib_resources          6.4.0
jax                          0.4.25
joblib                       1.3.2
keras                        2.12.0
kiwisolver                   1.4.5
lark                         1.1.9
lazy_loader                  0.3
libclang                     18.1.1
locket                       1.0.0
Markdown                     3.6
MarkupSafe                   2.1.5
matplotlib                   3.6.1
ml-dtypes                    0.3.2
networkx                     3.2.1
numpy                        1.23.0
oauthlib                     3.2.2
OpenEXR                      1.3.9
opt-einsum                   3.3.0
packaging                    24.0
pandas                       1.5.3
partd                        1.4.1
Pillow                       9.2.0
pip                          23.3.1
plotly                       5.13.1
promise                      2.3
protobuf                     3.20.3
psutil                       5.9.8
pyarrow                      10.0.0
pyasn1                       0.6.0
pyasn1_modules               0.4.0
pyparsing                    3.1.2
python-dateutil              2.9.0.post0
pytz                         2024.1
PyWavelets                   1.4.1
PyYAML                       6.0.1
requests                     2.31.0
requests-oauthlib            2.0.0
rsa                          4.9
scikit-image                 0.20.0
scikit-learn                 1.2.2
scipy                        1.10.1
setuptools                   67.6.0
six                          1.16.0
tenacity                     8.2.3
tensorboard                  2.12.3
tensorboard-data-server      0.7.2
tensorboard-plugin-wit       1.8.1
tensorflow                   2.12.0
tensorflow-addons            0.23.0
tensorflow-datasets          4.9.0
tensorflow-estimator         2.12.0
tensorflow-graphics          2021.12.3
tensorflow-io-gcs-filesystem 0.36.0
tensorflow-metadata          1.13.0
tensorflow-probability       0.19.0
termcolor                    2.4.0
threadpoolctl                3.4.0
tifffile                     2024.2.12
toml                         0.10.2
toolz                        0.12.1
tqdm                         4.66.2
trimesh                      4.2.2
typeguard                    2.13.3
typing_extensions            4.10.0
urllib3                      2.2.1
visu3d                       1.5.1
waymo-open-dataset-tf-2-12-0 1.6.2
Werkzeug                     3.0.1
wheel                        0.41.2
wrapt                        1.14.1
zipp                         3.18.1

**Comment by nicomon24** [comment]
Hi @lssiair,
thanks for finding this, I was able to reproduce just by running the camera tutorial on colab with the pip package. Let me try to understand what is happening and come back to you asap.

**Comment by nicomon24** [comment]
Hi @lssiair
I can confirm that the error is caused by a missing dependency (basically the camera utils files is not included in what gets packaged on pip). I'm working on a fix, but in the meantime, if you clone the repo and pip install from source it should work.

**Comment by lssiair** [comment]
Hi, @nicomon24 I have imported the camera utils successfully from source. Thanks!
