### ISSUE TITLE
Submission error from WOSAC

### ISSUE THREAD

**Issue by Longzhong-Lin** [waymo-research/waymo-open-dataset#812]
Hi I made a submission to WOSAC validation set, but I got:
```
No shards found in submission_key { user_id: "linlongzhong2000@zju.edu.cn" submission_id: "1712199559748000" } file_path: "/bigstore/waymo_open_dataset_challenge_validation/submission/SIM_AGENTS/linlongzhong2000@zju.edu.cn/1712199559748000/1712199559748000.tar.gz" subset: SUBSET_VALIDATION
```
It's hard to debug what's wrong with my submission given the information. Could you please explain more about this error message? Thanks!

**Comment by manuelvogel12** [comment]
Hello, 

I am running into the same error when trying to submit to the validation set of the E2E Driving Challenge.

Can you share how you solved it?

Thanks

**Comment by vpapareddy** [comment]
@manuelvogel12 @Longzhong-Lin 

Hi, I'm facing the same issue "no shards found in submission_key" when trying to submit to the Waymo E2E challenge. Were any of you able to solve this? 

I've tried various submission formats and checked that I can open the tar file and view contents locally. Others seem to have submitted fine.

Thanks

**Comment by manuelvogel12** [comment]
I did not try it yet, but it seems to be the case that you need to rename the parts, as mentioned here:
https://github.com/waymo-research/waymo-open-dataset/issues/936
