### ISSUE TITLE
The size of submission file for WOSAC

### ISSUE THREAD

**Issue by Longzhong-Lin** [waymo-research/waymo-open-dataset#813]
Hi, I followed your tutorial of `sim agents` and got a complete `tar.gz` submission whose size is about `18GB`, which is surprisingly large.
I found that I could barely upload the file to evaluation server, because the process is too time-consuming.
Hence I wonder whether it is a normal size of a WOSAC submission file? Hope for your timely reply!

**Comment by nicomon24** [comment]
Hi @Longzhong-Lin,
thanks for reaching out. I can confirm that usually WOSAC submissions are pretty large (as we are requiring 10Hz updates for many objects). Depending on how much gzip manages to compress, this can range from 10 to 30GB.

Are you getting time-outs or disconnections? Or simply it would take too much time?

**Comment by Longzhong-Lin** [comment]
Thank you for the response! I now understand that the file size for submission is indeed quite large. However, uploading such large files through a relatively "fragile" web interface often takes a long time, with no visibility into the upload progress. Moreover, possibly due to our location not being in the United States, it's common for the upload to abruptly fail midway with an error message like "something went wrong when uploading." Therefore, for submissions of this magnitude, perhaps there could be a more user-friendly interface and upload method available.

**Comment by nicomon24** [comment]
Thanks for the feedback @Longzhong-Lin. We did look into adding a command-line base upload a while ago, let me revive the conversation and get back to you.
In the meantime, if you want to try uploading your file to a google cloud storage bucket I can try to then upload it for you manually.

**Comment by Longzhong-Lin** [comment]
Understood! The file that I needed to submit has been successfully uploaded after several attempts. Thank you for your assistance! I hope you all make great progress!
