### ISSUE TITLE
Waymo Open Motion Dataset

### ISSUE THREAD

**Issue by lihua12312** [waymo-research/waymo-open-dataset#815]
Hello! Is the 'heading' in the Waymo Open Motion Dataset referring to the angle between the vehicle's heading direction and the x-axis, or the angle between the velocity vector of the vehicle's center of mass and the x-axis?

**Comment by nicomon24** [comment]
Hi @lihua12312, has described in https://github.com/waymo-research/waymo-open-dataset/blob/5f8a1cd42491210e7de629b6f8fc09b65e0cbe99/src/waymo_open_dataset/protos/scenario.proto#L37, you can see that the `heading` refers to the bounding box orientation, so it's not directly tied to the direction of speed.

**Comment by lihua12312** [comment]
Thank you for your kind response!
