### ISSUE TITLE
[WOSAC] 2023 V1 leaderboard == 2024 leaderboard?

### ISSUE THREAD

**Issue by pengzhenghao** [waymo-research/waymo-open-dataset#817]
Hi, I want to double check if the 2023 upgraded v1 version of the WOSAC is the same as the latest 2024 leaderboard. This confuses me cuz I saw MVTE has drastically different result in two leaderboards.

**Comment by nicomon24** [comment]
Hi @pengzhenghao, no this is a new configuration of the metrics as explicitly called out on the website (section "[Update March 2024]" under leaderboard). 
Specifically, you can see that the metrics_config [changed](https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/wdl_limited/sim_agents_metrics/challenge_2024_config.textproto) (which accounts for most of the changes in scores, [old config](https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/wdl_limited/sim_agents_metrics/legacy_configs/challenge_2023_config.textproto))

Sorry about the confusion, the v0->v1 change was prior to the new challenge and with a different naming scheme, hopefully with this year-based one it should be clearer.
