### ISSUE TITLE
Cannot download dataset programmatically

### ISSUE THREAD

**Issue by maxvandenhoven** [waymo-research/waymo-open-dataset#819]
Hello,

I have registered for the dataset using my gmail account, and I can now see the cloud storage console and download files manually, but whenever I try to download files programmatically (e.g., using the requests module or the cloud storage python sdk), I get authentication errors. I already tried to make a service account corresponding to the email I signed up with, but it does not seem to be connected to the dataset's cloud storage. I also tried registering under a different email at https://waymo.com/open/licensing/, but the form appears to be broken, as I cannot check the box to accept the licensing agreement. 

Any help would be greatly appreciated! I am mostly looking for help on how to download select .tfrecord files programmatically using the cloud storage python sdk if possible.

Thank you!

**Comment by maxvandenhoven** [comment]
Hi @nicomon24,

Thank you for the reply, that stackoverflow link is definitely useful! 

I tried getting the blob directly, but I am still getting permission denied errors. I think I may be using the wrong credentials however, as I made a service account to be able to use the Python SDK, but this presumably does not have access to the dataset. Do you have any pointers on how to authenticate with Google cloud using my email, as I assume this is how I am able to access the web console?

If it helps, this is the code snippet I am using:
```
from google.cloud import storage
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file("<path-to-service-account-credentials.json>")

storage_client = storage.Client(project="<project-name-I-made>", credentials=credentials)

bucket = storage_client.bucket("waymo_open_dataset_v_1_4_3")

bucket.get_blob("individual_files/training/segment-10017090168044687777_6380_000_6400_000_with_camera_labels.tfrecord")
```

The final last throws the following exception:
```
Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/waymo_open_dataset_v_1_4_3/o/individual_files%2Ftraining%2Fsegment-10017090168044687777_6380_000_6400_000_with_camera_labels.tfrecord?projection=noAcl&prettyPrint=false: waymo-open-dataset-download@waymo-open-dataset-420120.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).
```

Thanks!

**Comment by nicomon24** [comment]
Related stackoverflow hhttps://stackoverflow.com/questions/44328277/how-to-auth-to-google-cloud-using-service-account-in-python#comment128852228_44329070 
The service account being different from your google account should probably be the issue I guess

**Comment by haoming29** [comment]
I think you'd have to use OAuth to obtain the access token (with your Google account that signed into the Waymo dataset) and use that access token to issue a RESTful request like documented here: https://cloud.google.com/storage/docs/downloading-objects#rest-download-object

I used https://developers.google.com/oauthplayground/ to get myself started without writing a ton of code handling OAuth. This approach requires you to authenticate (like you logged in with your Google account for other websites) every time you want to initialize the batch download, which means you can't use them on servers and run as parallel programs.

**Comment by maxvandenhoven** [comment]
Thanks @nicomon24 and @haoming29 for your input!

What ended up working was installing `google-cloud-sdk` and running `gcloud auth application-default login` to log in with the Google account I used to register for the dataset. This generated the required environment variables to be able to run the following Python code to download and process a .tfrecord file:
```python
import tempfile
from google.cloud import storage

client = storage.Client(project=None)
bucket = client.bucket(bucket_name="waymo_open_dataset_v_1_4_3")

with tempfile.NamedTemporaryFile() as temp_file:
    blob = bucket.get_blob(blob_name="<path to .tfrecord file in bucket>")
    blob.download_to_filename(filename=temp_file.name) 

    # Code to process .tfrecord file now downloaded to temp_file
```

Note: I had to use the `download_to_filename()` method instead of the `.download_to_file()` method, as the latter frequently resulted in incomplete files leading to a TensorFlow `DataLossError`. I didn't investigate further into this issue, as using `.download_to_filename()` fixed the issue.
