### ISSUE TITLE
a new release needed

### ISSUE THREAD

**Issue by ares89** [waymo-research/waymo-open-dataset#822]
> INVALID_ARGUMENT: The uses_lidar_data field in the submission proto is not set. Please set this field and re-submit

Encountered a discrepancy: The test failed because the proto definition seems to have been updated, but the released version used for testing is outdated. A new release containing the latest proto changes is likely necessary.

**Comment by nicomon24** [comment]
Hi @ares89,
we introduced a change last Friday that made these fields required for proper book-keeping of the leaderboard.
This affects all the challenges based on the motion-dataset (motion prediction, occupancy flow, sim agents).

New fields here (for motion): https://github.com/waymo-research/waymo-open-dataset/blob/5f8a1cd42491210e7de629b6f8fc09b65e0cbe99/src/waymo_open_dataset/protos/motion_submission.proto#L157

So new submissions need to include these new fields to be valid.

Note: what do you mean by "released version used for testing"? If you refer to the latest pip package, using version `waymo-open-dataset-tf-2-12-0==1.6.4` (we updated all the tutorials btw) should include the new fields.

**Comment by ares89** [comment]
thank you for reply.

**Comment by pengzhenghao** [comment]
Should update the release page: https://github.com/waymo-research/waymo-open-dataset/releases

**Comment by MPCheng-ZW** [comment]
Sorry to bother you.

Have you encountered and resolved the error "Missing uses_lidar_data field from submission"?

Thank you!

@ares89 @nicomon24 @pengzhenghao @gormanity @rezama

**Comment by pengzhenghao** [comment]
I encountered that and solved that already by adding new fields in the submission. So my submission should not fails because of this error. You should check out what the staff said above about new mandatory fields.Sent from my iPhoneOn Nov 7, 2024, at 05:43, MPCheng ***@***.***> wrote:﻿
Sorry to bother you.
Have you encountered and resolved the error "Missing uses_lidar_data field from submission"?
Thank you!
@ares89 @nicomon24 @pengzhenghao @gormanity @rezama

**Comment by MPCheng-ZW** [comment]
Thanks for your reply.

I am submitting the results for the Occupancy Flow Challenge.

When I install the waymo-open-dataset-tf package, it is shown as follows:
<img width="968" alt="screenshot" src="https://github.com/user-attachments/assets/9e62b1fa-791a-465f-9db7-231ca2a72b0d">

How can I add the new fields to the submission?

Is the issue related to the version of waymo-open-dataset-tf? If so, which version should I install via pip?

Thank you very much!

@pengzhenghao

**Comment by pengzhenghao** [comment]
Please read through the tutorial notebook.Sent from my iPhoneOn Nov 7, 2024, at 17:47, MPCheng ***@***.***> wrote:﻿
Thanks for your reply.
I am submitting the results for the Occupancy Flow Challenge.
When I install the waymo-open-dataset-tf package, it is shown as follows:
screenshot.png (view on web)
How can I add the new fields to the submission?
Is the issue related to the version of waymo-open-dataset-tf? If so, which version should I install via pip?
Thank you very much!
@pengzhenghao

**Comment by MPCheng-ZW** [comment]
> Please read through the tutorial notebook.Sent from my iPhoneOn Nov 7, 2024, at 17:47, MPCheng ***@***.***> wrote:﻿ Thanks for your reply. I am submitting the results for the Occupancy Flow Challenge. When I install the waymo-open-dataset-tf package, it is shown as follows: screenshot.png (view on web) How can I add the new fields to the submission? Is the issue related to the version of waymo-open-dataset-tf? If so, which version should I install via pip? Thank you very much! @pengzhenghao —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

I have solved it, thanks! @pengzhenghao
