### ISSUE TITLE
IMU data

### ISSUE THREAD

**Issue by jeho-lee** [waymo-research/waymo-open-dataset#824]
Hi, I wonder Waymo dataset has the IMU sensor data, just as can_bus data in the NuScenes dataset. Thanks.

**Comment by VincentCa** [comment]
Hi, thanks for your interest in Waymo Open Dataset! Open Dataset includes similar information, such as the vehicle pose at different points in time (at the time of each image capture and at the given center laser spin time) and translational and angular velocity estimates.

For more details, please refer to https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/dataset.proto.

Best,
Vincent

**Comment by jeho-lee** [comment]
Thanks! I'll check the information.

**Comment by unicoco7** [comment]
> Thanks! I'll check the information.谢谢！我去查一下资料。



> NuScenes

Hello, I would like to ask if you already know how to generate can_bus data similar to that in the NuScenes dataset from the Waymo dataset? Could you please share it? Thank you very much.

**Comment by jeho-lee** [comment]
Unfortunately, i ended up using the solution without IMU sensor data for Waymo dataset..
