### ISSUE TITLE
Some questions about the format(tfrecord) of the data

### ISSUE THREAD

**Issue by Jaywxy** [waymo-research/waymo-open-dataset#825]
My task is point cloud semantic segmentation, I only need point cloud data, I want to use the **V2.0.1 dataset**, I get all the data named with lidar, do I need to download other data?Another problem is that the **tutorial_3d_semseg.ipynb** in the tutorial doesn't seem to work, because the prompt needs a **tfrecord** file, but I found that the 2.0.1 version of the data does not have this file, and all are files of another formatWhat should I do? Hope to get some advice, thanks

**Comment by JingweiJ** [comment]
Hi @Jaywxy ,

For point cloud semseg, you'll need `lidar_calibration`, `lidar_segmentation`, `lidar_pose`, `lidar`, vehicle_pose` minimally. You can convert LiDAR range image to 3D point cloud using [this function in v2/perception/utils/lidar_utils.py](https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/v2/perception/utils/lidar_utils.py#L142), and convert the corresponding segmentation labels as in [this answer](https://github.com/waymo-research/waymo-open-dataset/issues/814#issuecomment-2079328255).

**Comment by Jaywxy** [comment]
> Hi @Jaywxy ,
> 
> For point cloud semseg, you'll need `lidar_calibration`, `lidar_segmentation`, `lidar_pose`, `lidar`, `vehicle_pose` minimally. You can convert LiDAR range image to 3D point cloud using [this function in v2/perception/utils/lidar_utils.py](https://github.com/waymo-research/waymo-open-dataset/blob/master/src/waymo_open_dataset/v2/perception/utils/lidar_utils.py#L142) and convert the corresponding segmentation labels as in [this answer](https://github.com/waymo-research/waymo-open-dataset/issues/814#issuecomment-2079328255).

thank you for your reply!
