### ISSUE TITLE
Waymo submission question.

### ISSUE THREAD

**Issue by Osama26-byte** [waymo-research/waymo-open-dataset#831]
I wanted to know for how much return images we need to submit our predictions i.e ri1, ri2 or just for ri1? (3D Semantic Segmentation)

**Comment by zhenpeiyang** [comment]
Hi @Osama26-byte , you are supposed to submit prediction for ri2 as well. The relevant metric code for ri2 is here: https://github.com/waymo-research/waymo-open-dataset/blob/5f8a1cd42491210e7de629b6f8fc09b65e0cbe99/src/waymo_open_dataset/metrics/tools/compute_segmentation_metrics_main.cc#L203

**Comment by Osama26-byte** [comment]
Thanks, another question, How to extract Test dataset as whole dataset is of 29647 items, but major paper indicated only 2982 valid items, how to extract those?

**Comment by zhenpeiyang** [comment]
Hi @Osama26-byte , have you checked out the semseg [tutorial](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_3d_semseg.ipynb)? Specifically you may want to checkout the section `Create a dummy submission file for the testing set`

**Comment by Osama26-byte** [comment]
Ohh, Thanks, I found the 3d_semseg_test_frames file in the repo.
