### ISSUE TITLE
issue about waymo challenge 2024 validation set submission

### ISSUE THREAD

**Issue by WeiXiCZ** [waymo-research/waymo-open-dataset#832]
I participated in the Waymo Challenge 2024 (Occupancy Flow Prediction). I submitted my Test Set Submissions two days ago, but I have yet to receive any test results. Could you please advise on what might be the issue? 

Thank you for your assistance.
![IMG_8241](https://github.com/waymo-research/waymo-open-dataset/assets/86120782/117b96e6-9a70-47f2-a2ca-70bc74face28)
![IMG_8240](https://github.com/waymo-research/waymo-open-dataset/assets/86120782/de540848-8229-47d3-855f-8f7fc9834c65)

**Comment by WeiXiCZ** [comment]
Thank you for your reply! Are you referring to my account ID? Because I didn't see any ID other than my login account ID on the submission interface.
my login account ID is 616275167cz@gmail.com
![1715734861391](https://github.com/waymo-research/waymo-open-dataset/assets/86120782/4da69243-8fdc-441c-aeb3-f449f4c28232)

**Comment by nicomon24** [comment]
@WeiXiCZ Could you check now? Should be done, sorry about the inconvenience!

**Comment by WeiXiCZ** [comment]
Thank you for your assistance. I can now see the results😀
