### ISSUE TITLE
How does the camera_projection_compressed in RangeImage generated?

### ISSUE THREAD

**Issue by xmyqsh** [waymo-research/waymo-open-dataset#85]
`camera_projection_compressed` stores the Lidar point to camera image projections.
We can also use `third_party.camera.ops.py_camera_model_ops.world_to_image` to do the same thing.

Does the `camera_projection_compressed` is generated by `third_party.camera.ops.py_camera_model_ops.world_to_image` ?

Or, we have to use `third_party.camera.ops.py_camera_model_ops.world_to_image` to get rid of the camera rolling shutter problem in the corresponding process between lidar point cloud and camera pixel by ourselves.

Another usage of the powerful camera model should be that predict the image depth first, then, use `third_party.camera.ops.py_camera_model_ops.image_to_world` to get the accurate dense semantic point cloud. Offline dense map construction should benefit from this.

**Comment by peisun1115** [comment]
camera_projection_compressed is generated by third_party.camera.ops.py_camera_model_ops.world_to_image . That is provided because we don't have the code open sourced when we release the data
