### ISSUE TITLE
Perception Dataset V201 Lidar Timestamp Issue

### ISSUE THREAD

**Issue by donceykong** [waymo-research/waymo-open-dataset#851]
I have so far tested the validation and testing directories of V201 of the perception data, and the lidar timestamps seem to be completely non-consecutive. If the timestamps are indeed in microseconds, then I am not only seeing timestamps over multiple days, but over multiple years.

Is this in fact the case? Here are some of examples:

file: 271338158136329280_2541_070_2561_070.parquet
lidar_timestamp: 1508691276351529, date: 2017-10-22 16:54:36.351529

file: 5832416115092350434_60_000_80_000.parquet
lidar_timestamp: 1557873841498507, date: 2019-05-14 22:44:01.498507

file: 15488266120477489949_3162_920_3182_920.parquet
lidar_timestamp: 1508978495599220, date: 2017-10-26 00:41:35.599220

file: 17539775446039009812_440_000_460_000.parquet
lidar_timestamp: 1546906349822720, date: 2019-01-08 00:12:29.822720

file: 4690718861228194910_1980_000_2000_000.parquet
lidar_timestamp: 1552693990049301, date: 2019-03-15 23:53:10.049301

file: 18331704533904883545_1560_000_1580_000.parquet
lidar_timestamp: 1553532178173827, date: 2019-03-25 16:42:58.173827

**Comment by JingweiJ** [comment]
Yes. The Waymo Open Dataset contains data collected over years.

**Comment by Zhenlin-Xu** [comment]
Hi, I am interested in this absolute timestamps. Is it possible for me to access it in the motion dataset? Or is there any way that I can link motion and sensor datasets together so that I can know the exact absoulate timestamp of each trajectory in motion dataset?
