### ISSUE TITLE
Relation between range image and polar coordinates

### ISSUE THREAD

**Issue by VICKY1991** [waymo-research/waymo-open-dataset#86]
Guys,

What is the relation between a range image and point cloud in polar coordinate?
Aren't they conceptually the same thing?
Also, say I have a 3D boxes from a particular frame.
Can I project these into 2D boxes in the range image and vice versa?
Please explain.

**Comment by peisun1115** [comment]
See [this paper](https://arxiv.org/abs/1912.04838) for the range image definition.

In short, range image is a special form of polar coordinates that reflexes LiDAR scanning pattern.  Each pixel is conceptually a LiDAR return. But a generic polar coordinate won't achieve that. You either will have a lot of holes or a lot of collisions depending on the resolution of your polar coordinates quantization.

Yes, you can. Look at range_image_utils.py for libs needed to do such projection
