### ISSUE TITLE
Unkown worng of WOSAC submission

### ISSUE THREAD

**Issue by Longzhong-Lin** [waymo-research/waymo-open-dataset#864]
When I upload a submission to sim agents challenge, I got error but there is not any error information or hint as in figure.
So I come here to ask for your help and solution. 
My account is linlongzhong2000@zju.edu.cn, and the submission link is https://waymo.com/open/challenges/sim-agents/results/5cf88d3f-eece/1722133974548000/ .
Looking forward to your kind reply.
![image](https://github.com/user-attachments/assets/0c254513-58f4-4214-97a6-04ce30e6b34b)

**Comment by nicomon24** [comment]
Hi @Longzhong-Lin,

sorry for the delay. There are some errors that are not correctly propagated in the server. Let me investigate and get back to you.

**Comment by Longzhong-Lin** [comment]
Hi @nicomon24 , is there any update?

**Comment by nicomon24** [comment]
Hey @Longzhong-Lin,

Sorry I responded to the same exact issue via email and I didn't realise these were different submissions. The error seemed to be a transient one on the server, I'm re-evaluating your submission hopefully will let you know something in the next couple of hours! 

Sorry for the delay 
Nico

**Comment by linxuewu** [comment]
hello, @nicomon24 
I encountered the same problem with my submissions. Can you help me re-evaluate them?
https://waymo.com/open/challenges/sim-agents/results/3379d968-4609/1722143929690000/
https://waymo.com/open/challenges/sim-agents/results/3379d968-4609/1722149697960000/

**Comment by nicomon24** [comment]
@Longzhong-Lin your submission should be now visible.
@linxuewu Will update in a couple of hours

**Comment by nicomon24** [comment]
@linxuewu Should be fixed now!

**Comment by linxuewu** [comment]
@nicomon24  Hello, I encountered the same problem. Could you please take a look at it?
https://waymo.com/open/challenges/sim-agents/results/3379d968-4609/1724646061908000/
https://waymo.com/open/challenges/sim-agents/results/3379d968-4609/1724626439963000/

**Comment by nicomon24** [comment]
Hi @linxuewu, all done now

**Comment by linxuewu** [comment]
@nicomon24 Sorry bother you again, the same problem keeps recurring. Could you please help restart this evaluation? https://waymo.com/open/challenges/sim-agents/results/3379d968-4609/1726910365917000/

**Comment by nicomon24** [comment]
Hi @linxuewu,
sorry this keeps happening 😢
I've restarted your eval, should be done in a couple of hours

**Comment by Longzhong-Lin** [comment]
Hi @nicomon24 ,
I wonder if you could help us edit the information of the testing submission, since the submission times are limited.
