### ISSUE TITLE
question about motion prediction submission

### ISSUE THREAD

**Issue by skylineo** [waymo-research/waymo-open-dataset#872]
My code only predicts the future motion of ego vehicle, and store the agent_id like this: 
            scenario_string = scenario.numpy()
            parsed_data = scenario_pb2.Scenario()
            parsed_data.ParseFromString(scenario_string)

            scenario_id = parsed_data.scenario_id
            sdc_id = parsed_data.sdc_track_index

            sdc = parsed_data.tracks[sdc_id]
            ego_id = sdc.id
but i got a error when submit:
ce42b7f3d1aae8c9 required : 1538, 1568, 1855, 1856, predicted : 2235,
did i do something wrong?
my email is: Submissions by renze0130@gmail.com
plz reply as soon as possible, thank you!

**Comment by skylineo** [comment]
and I encountering this issue in multiple scenarios:
CANCELLED: Missing required object prediction for scenario : e730dcfbc801ab04 required : 0, 28, predicted : 39,
CANCELLED: Missing required object prediction for scenario : be52ea4b683868ed required : 1062, 1081, 1108, predicted : 1229,

**Comment by skylineo** [comment]
May I ask, if it is feasible to use one of the cars in predict_tracks as ego-car?

**Comment by skylineo** [comment]
BTW，do I need to test all the testing data (which contains 150 tf.record files) once if I want to submit the results?

**Comment by scott-ettinger** [comment]
The benchmark requires that your submission includes predictions for all agents and for all examples in all 150 files of the validation or test set.  Currently there is not a way to compute metrics for a single vehicle.

**Comment by skylineo** [comment]
Thanks for your reply!
