### ISSUE TITLE
How big is the dataset?

### ISSUE THREAD

**Issue by nam1410** [waymo-research/waymo-open-dataset#873]
Before I proceed downloading your dataset, I want to know the size breakup of the dataset and its subsets so that I can make the necessary storage set-up. Please provide this information. Thank you.

**Comment by jlambert-waymo** [comment]
Hi @nam1410, thanks for your interest in the Waymo Open Datasets.

Is your inquiry about the [Perception Dataset](https://waymo.com/open/data/perception/), or the [Motion Dataset](https://waymo.com/open/data/motion/)?

File sizes are listed in the following two Google Cloud buckets:

Perception Dataset: https://pantheon.corp.google.com/storage/browser/waymo_open_dataset_v_2_0_1;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

Motion Dataset: https://pantheon.corp.google.com/storage/browser/waymo_open_dataset_motion_v_1_2_1;tab=objects?pli=1&prefix=&forceOnObjectsSortingFiltering=false

**Comment by jlambert-waymo** [comment]
Marking as resolved, feel free to re-open if you have further questions.
