### ISSUE TITLE
Incorrect weather in context information

### ISSUE THREAD

**Issue by DianCh** [waymo-research/waymo-open-dataset#88]
Hi, I was trying to extract subsets of data depending on the weather it was collected. However, I noticed that all the "frame.context.stats.weather" fields are populated with "sunny". Would you consider update the dataset with the correct weather annotation?
Thank you!

**Comment by peisun1115** [comment]
Most but not all of the scenes are indeed sunny.  We have plans to expand the dataset with more rainy ones in the future.
