### ISSUE TITLE
What are the dimensions(length, width, height) of self-driving car itself ?

### ISSUE THREAD

**Issue by Xiangwang-Hu** [waymo-research/waymo-open-dataset#92]
The dimensions of other vehicles can be obtained by lidar label.
But I can't find the dimensions of self-driving car itself anywhere (any website)?
If it's not in the data, can you tell me directly ?
Thanks in advance.

**Comment by peisun1115** [comment]
The exact size can be inferred by where the sensors are. The vehicle size before modification is (found on Google):
![image](https://user-images.githubusercontent.com/18294241/72210733-e7ead900-3474-11ea-903f-6acebf1408ba.png)
