### ISSUE TITLE
how to get the right intensity value of lidar data?

### ISSUE THREAD

**Issue by AndyYuan96** [waymo-research/waymo-open-dataset#93]
Hi, thanks for open waymo dataset, how can I convert the intensity channel value to true intensity value, it looks like the lidar data is raw data, don't converted to point cloud format with x,y,z,intensity, can you give me a formula that convert intensity channelvalue to true intensity? I simply normalize with max intensity value, but didn't help.

**Comment by peisun1115** [comment]
The value in the dataset is the raw intensity.  A popular way to normalize the intensity is tanh(raw_value). I am not aware of any theory to back that up. You can try to plot the distribution and come up with other normalization method if tanh does not work well for you

**Comment by callzhang** [comment]
That's a very good answer. Helped a lot. Thanks!
