### ISSUE TITLE
Detection difficulty metrics not recognizing levels

### ISSUE THREAD

**Issue by carranza96** [waymo-research/waymo-open-dataset#94]
Hello,
I am not getting correct results for metrics of objects of LEVEL_1 and LEVEL_2. No matter what level the object is, they are included in both levels to make the calculations.
If I create a toy example in which there is a single ground truth object of LEVEL_1 with a perfect prediction, the output is the following:
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1: [mAP 1] [mAPH 1]
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [mAP 1] [mAPH 1]

I cannot find in the code the place where the objects are separated depending on their level. Is it related to the indices field in BreakdownShardSubset?
Also, in the example fake_gts/predictions, all objects have difficulty LEVEL_0::Unknown, and there are different outcomes for level1 and level2 metrics, but I cannot find why.
Thank you for your help.

**Comment by peisun1115** [comment]
You need to either pre-populate detection_difficulty_level in ground truth or set num_lidar_points_in_box in ground truth. 

Our next patch will will prepopulate these information in the data. for now, you need to set these on your own.

**Comment by carranza96** [comment]
I am populating that field manually when I write the .bin files, but still getting that error. I cannot find the code where objects are separated into two subsets depending on their difficulty level.
Thanks

**Comment by peisun1115** [comment]
what did you populate? Can you copy paste the DebugString of the proto?

code is here https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/detection_metrics.cc#L121

**Comment by carranza96** [comment]
This is the content of the toy .bin files I generate with just one item.

- Ground truths

```
objects {
  object {
    box {
      center_x: 20.0
      center_y: 50.0
      width: 10.0
      length: 10.0
    }
    type: TYPE_VEHICLE
    detection_difficulty_level: LEVEL_2
  }
  score: 1.0
  context_name: "17612470202990834368_2800_000_2820_000"
  frame_timestamp_micros: 1553640777197289
  camera_name: FRONT
}

```

- Predictions

```
objects {
  object {
    box {
      center_x: 20.0
      center_y: 50.0
      width: 10.0
      length: 10.0
    }
    type: TYPE_VEHICLE
  }
  score: 1.0
  context_name: "17612470202990834368_2800_000_2820_000"
  frame_timestamp_micros: 1553640777197289
  camera_name: FRONT
}
```


And the result with compute_detection_metrics_main:

```
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1: [mAP 1] [mAPH 1]
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [mAP 1] [mAPH 1]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_SIGN_LEVEL_1: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_SIGN_LEVEL_2: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1: [mAP 0] [mAPH 0]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2: [mAP 0] [mAPH 0]

```

The same happens if I set the item to Level 1. Both levels have a 1 in the mAP

**Comment by peisun1115** [comment]
@carranza96 
This is working as expected. 
When you compute metrics for level 1, the prediction is not counted as a false positive as it matches a level 2 object. We don't penalize a model when computing level 1 metrics if it can predict objects that are more difficult (level 2). 
(code is in this [file](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/detection_metrics.cc)). The way it is implemented is: when do matching, we ignore difficulty. But when computing false negative, we do [this](https://github.com/waymo-research/waymo-open-dataset/blob/3b13f19d16644c693d45eeacecdd9cedf101eb37/waymo_open_dataset/metrics/metrics_utils.cc#L53).

If you want to see different metrics between level 1/2, simply remove the prediction. The AP for level 1 should be 1 and level 2 should 0. To make it more robust, add another box in your test.

**Comment by carranza96** [comment]
Thanks for your help. I was thinking about the two levels being completely independent sets, which is now clear that is not the case.

**Comment by mathild7** [comment]
> You need to either pre-populate detection_difficulty_level in ground truth or set num_lidar_points_in_box in ground truth.
> 
> Our next patch will will prepopulate these information in the data. for now, you need to set these on your own.
> 
> code is here https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/metrics/tools/compute_detection_metrics_main.cc#L123-L135

Hi,

It appears as though for dataset version 1.2 this difficulty metric is still not prepopulated for the majority of lidar GT labels. Is this known and still expected for the user to pre-populate?
