### ISSUE TITLE
What is the use of enum Type defined in Box in label.proto?

### ISSUE THREAD

**Issue by witignite** [waymo-research/waymo-open-dataset#96]
I see that enum `Type` is defined in [Box](https://github.com/waymo-research/waymo-open-dataset/blob/04152e70f4fe633c2d0d1a7b4b10a6299759faaa/waymo_open_dataset/label.proto#L22) message but there is no field with that type.
What is the use of this enum?

https://github.com/waymo-research/waymo-open-dataset/blob/04152e70f4fe633c2d0d1a7b4b10a6299759faaa/waymo_open_dataset/label.proto#L38-L46

**Comment by peisun1115** [comment]
It is used to pass the metrics computation configuration to tell what is the  type of the boxes you are generating. https://github.com/waymo-research/waymo-open-dataset/blob/04152e70f4fe633c2d0d1a7b4b10a6299759faaa/waymo_open_dataset/protos/metrics.proto#L111

**Comment by witignite** [comment]
You beat me to it; I should have seen this in the first place.
