### ISSUE TITLE
Is it possible to obtain higher-fps dataset?

### ISSUE THREAD

**Issue by RalphMao** [waymo-research/waymo-open-dataset#97]
I noticed that the provided dataset is in 10fps. Is it possible to release the original full fps camera data?

**Comment by peisun1115** [comment]
No, we don't provide that. Why do you need more than 10fps?

**Comment by RalphMao** [comment]
@peisun1115 I am studying the trade-off between object detection latency and computation budget. An example question would be: given higher fps, but lower computation budget for every single frame, will that always reduce the latency to detect objects (of course not) - if not, what fps would be the best choice?

**Comment by peisun1115** [comment]
OK. that is interesting to know. We don't provide data more than 10fps for now.
