### ISSUE TITLE
What is the height of the top lidar from the ground?

### ISSUE THREAD

**Issue by maneekwant** [waymo-research/waymo-open-dataset#99]
I couldn't seem to find the information on the height of the top lidar from ground level. Could you point me to the source or is there any other way I could obtain this information? (The reason I need this information is for ground segmentation of point cloud data) 
Thank you in advance!

**Comment by peisun1115** [comment]
@maneekwant You can find that by reading lidar [extrinsic] (https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto#L128). It is a 4x4 matrix M. M[0:3, 3] tells you where the lidar is within vehicle frame.

**Comment by maneekwant** [comment]
Oh so the vehicle frame's origin is set at ground level? Sorry I wasn't sure where the origin of the vehicle frame is set at with respect to the ground!

**Comment by maneekwant** [comment]
Okay thanks!
